examples/airflow/.env
examples/airflow/docker-compose.yml

Set AIRFLOW_IMAGE to the AIRFLOW_IMAGE_TAG set in `start`, should it be set

Use custom AIRFLOW_IMAGE_TAG in compose file

---

examples/airflow/docker-compose-lite.yml
examples/airflow/start
examples/config/airflowlite.env

@schnie Was discussed on side, but wanted to share full picture of the code changes. If still out of scope just decline and I will resubmit with examples git clone removed.

Add airflowlite example

---

.codeclimate.yml

@ryw This should make the checks run on CC via YAML consistent with the UI.  I think the config change needs to be merged into master before the checks can run using it.

Add Code Climate YAML config

---

docker/platform/airflow/include/clean-airflow-logs
docker/platform/airflow/include/entrypoint
docs/pages/airflow.md

This should bring Code Climate open issue count to 0

More fixes from Code Climate

---

docs/_config.yml
docs/index.md

Replaces http protocol in doc site urls with https.
I also changed the URL on the repo itself.

http → https 2/2

---

docs/_includes/head.html

Add copy buttons

---

docs/index.md

this pr
- was created in response to issue #44 
- clarifies what Astronomer Open is
- guides a user towards the CLI for local development

add clarity around what astronomer open is

---

docker/vendor/grafana/Dockerfile

Note: Untested
Pinning this to be consistent for deterministic builds like with the other images.
Note: This tag is the latest stable but it is from 15 days ago while master was updated today.

Pin Grafana to 5.0.4

---

docker/platform/airflow/Dockerfile

Added upgraded version of pip in Dockerfile.

Upgraded version of pip to 10.0.0

---

docker/platform/commander/Dockerfile
docker/platform/houston-api/Dockerfile

Dockerfiles updated for v0.2.0

Updated Dockerfiles for commander and houston

---

docker/vendor/nginx/Dockerfile

Updated nginx-ingress version

---

docs/ee-metrics.md

update grafana url [skip ci]

---

docs/ee-logging.md

prelim doc, mostly fluentD config info

Ee logging doc

---

docker/platform/houston-api/Dockerfile

This PR refactors the houston image to pull and install houston2.

Refactor houston image to use houston2

---

docker/platform/orbit-ui/include/nginx.conf

```
➜  ~ curl -v localhost:8080
* Rebuilt URL to: localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.14.2
< Date: Tue, 30 Apr 2019 21:03:11 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: no-store, no-cache, must-revalidate
```

Add no-cache for index.html

---

docker/vendor/grafana/include/airflow-overview.json

fix https://github.com/astronomer/astronomer/issues/303

Add filter only pods without dag_id label to exclude from health

---

docker/vendor/curator/Dockerfile
docker/vendor/elasticsearch/Dockerfile
docker/vendor/kibana/Dockerfile

**Upgrade:**
- ElasticSearch to 7.1.1 
- Kibana to 7.1.1
- elasticsearch-curator==5.7.6
fix https://github.com/astronomer/astronomer/issues/309
please DON'T merge without related PR
related PR -> https://github.com/astronomer/helm.astronomer.io/pull/141

Upgrade ElasticSearch and Kibana to 7.1.1

---

docker/vendor/pgbouncer/Dockerfile
docker/vendor/registry/Dockerfile

- Fix `registry:2.6.2/2.7` https://github.com/docker/distribution-library-image/pull/92

fix security issues

---

docker/vendor/elasticsearch/Dockerfile
docker/vendor/kibana/Dockerfile

**Links:**
https://www.elastic.co/blog/kibana-7-3-0-released
https://www.elastic.co/blog/elasticsearch-7-3-0-released
**Security check:**
```
clair-scanner --ip=192.168.1.199 ap-elastisearch:latest
2019/08/02 16:15:39 [INFO] ▶ Start clair-scanner
2019/08/02 16:15:51 [INFO] ▶ Server listening on port 9279
2019/08/02 16:15:51 [INFO] ▶ Analyzing 21ce7dd52e6869f92d3a200a18b1dcca939ca431550d8c40f3581e867c0df177
2019/08/02 16:15:51 [INFO] ▶ Analyzing 7fbbacce6bfc0e9853346161267e5a68e6abe8c66a679ada1ab2cb0947a3b75a
2019/08/02 16:15:51 [INFO] ▶ Analyzing 0c63d305e34a8bb4f78f60ab0202681c4d5c1235ed1c054414d3ff56c594eee9
2019/08/02 16:15:51 [INFO] ▶ Analyzing c5e8b904b3e816597a280ea07bc725dcb90003136dbd377a8305dce8e6b59b42
2019/08/02 16:15:51 [INFO] ▶ Analyzing …
```

bump es 7.3.0

---

docker/vendor/grafana/Dockerfile
docker/vendor/grafana/include/prometheus.json

@schnie pls wait until i test it :)

switch grafana to release version

---

examples/airflow-core/.env

This is mostly to trigger a new commit on master so that CI will re-build

Update example to use airflow 1.10.4

---

docker/vendor/grafana/Dockerfile
docker/vendor/grafana/include/prometheus.json

includes fixes of https://github.com/grafana/grafana/pull/18532

bump grafana

---

docker/vendor/statsd-exporter/include/mappings.yml

should solve the issue in https://github.com/astronomer/biz-cloud/issues/95#issuecomment-528381191

[#416] Fix Statsd mapping yaml

---

.drone.yml
Makefile

Fix this:
>Error response from daemon: manifest for astronomerinc/ap-commander:0.0.0 not found

sync tag names for build and scan

---

docker/vendor/grafana/include/airflow-overview.json

**Original**:
~~**Updated**:~~ (No longer valid. In case we plan to use this we can use https://github.com/astronomer/astronomer/pull/495/commits/14cc805d6a3e2705eef7215277330f6cf251121d)
**With the last commit**:

Add Time-Series Graph for Scheduler Hearbeat Rate

---

docker/vendor/grafana/include/airflow-scheduler.json

Add Panel for Scheduler Hearbeat Rate in Scheduler Dashboard

---

docker/vendor/grafana/Dockerfile
docker/vendor/grafana/include/kubernetes-pods-metrics.json

Issue: https://github.com/astronomer/issues/issues/378

[astronomer/issues#378] Add Dashboard to capture Kubernetes Pod Metrics

---

docker/vendor/grafana/include/airflow-scheduler.json

#1 of https://github.com/astronomer/issues/issues/398
**Before**:
**Now**:

Add new Airflow Metrics to Airflow Scheduler Dashboard

---

docker/vendor/grafana/include/airflow-overview.json

Attached to https://github.com/astronomer/issues/issues/475
Removes worker exclusion in CPU & MEM usage queries.

Update PromQL to support Celery Workers

---

Makefile
docker/airflow/debian-1.10.5/onbuild/Dockerfile

To make the onbuild image get auto-updated we needed to make it follow
the expected pattern already

Auto-build our debian image

---

docker/vendor/registry/Dockerfile

Closes https://github.com/astronomer/issues/issues/557

Update registry to version 2.7.1

---

charts/kubed/templates/kubed-deployment.yaml

Related to this kind of alert https://astronomerteam.slack.com/archives/CR8965Z89/p1579816165004400

Increase the timeout on liveness probe for kubed

---

.circleci/config.yml
bin/setup-kind
charts/postgresql/Chart.yaml
charts/postgresql/requirements.lock
charts/postgresql/requirements.yaml
charts/postgresql/templates/astronomer-bootstrap-secret.yaml
charts/postgresql/values.yaml
configs/local-dev.yaml
requirements.yaml
values.yaml

Zero config database support

---

charts/astronomer/templates/houston/houston-configmap.yaml

Disable the pod disruption budgets by default

---

Chart.yaml
charts/postgresql/templates/astronomer-bootstrap-secret.yaml

Conditional postgresql secret

---

charts/keda/requirements.lock
charts/keda/requirements.yaml

Use keda-1.2 chart

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml
charts/prometheus/templates/prometheus-config-configmap.yaml

fix https://github.com/astronomer/issues/issues/764

Alert Emails missing Workspace Label

---

charts/astronomer/templates/houston/houston-configmap.yaml

Fix pod mutation hook

---

charts/elasticsearch/templates/es-configmap.yaml

Complete PR here https://github.com/astronomer/astronomer/pull/570/files
**Checklist**

Configure Elasticsearch ping schedule

---

Chart.yaml
charts/astronomer/templates/commander/commander-deployment.yaml
charts/astronomer/templates/houston/houston-deployment.yaml
charts/astronomer/values.yaml

Cherry pick of https://github.com/astronomer/astronomer/pull/580 into release branch

Replicas pick

---

Chart.yaml
charts/alertmanager/Chart.yaml
charts/alertmanager/values.yaml
charts/astronomer/Chart.yaml
charts/elasticsearch/Chart.yaml
charts/elasticsearch/values.yaml
charts/fluentd/Chart.yaml
charts/grafana/Chart.yaml
charts/grafana/values.yaml
charts/keda/Chart.yaml
charts/kibana/Chart.yaml
charts/kibana/values.yaml
charts/kube-state/Chart.yaml
charts/kubed/Chart.yaml
charts/nginx/Chart.yaml
charts/nginx/values.yaml
charts/postgresql/Chart.yaml
charts/prometheus/Chart.yaml

I pushed this to the release branch already.
- bump all Chart.yaml to 0.12.0 (until we figure out subchart versioning automation)
- checked all image versions

Bump versions

---

Chart.yaml
charts/prometheus/templates/prometheus-alerts-configmap.yaml
charts/prometheus/templates/prometheus-config-configmap.yaml

Cherry pick into 0.12 https://github.com/astronomer/astronomer/pull/577

Pick prom rules

---

values.yaml

**Checklist**
- Related to https://github.com/astronomer/issues/issues/958

Set postgresqlEnabled: false by default astronomer/issues#958

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml
charts/prometheus/templates/prometheus-config-configmap.yaml

I found some areas where alerts and/or recording rules did not have the correct values for job names  and because of release name not being part of the job name. I also fixed up the alert annotations so they match how our slack messages are displayed.

Prometheus alert rules fixes after testing in stage

---

Chart.yaml
charts/astronomer/values.yaml

Upgrade Astro UI version

---

charts/astronomer/templates/houston/houston-configmap.yaml

Update default airflow chart version

---

charts/astronomer/templates/houston/houston-configmap.yaml

https://github.com/astronomer/airflow-chart/pull/61

Upgrade Airflow chart

---

bin/prereq-tests/tools/admin.bats
docs/testing.md

Adds documentation for
- testing setup
- how to run
- walkthrough of prereq-tests during installation

Docs, add testing docs

---

.gitignore
charts/astronomer/templates/houston/houston-jwt-certificate-secret.yaml
charts/astronomer/values.yaml

this is the pick to master for the patch https://github.com/astronomer/astronomer/pull/626

Add configuration to re-generate CA on each upgrade

---

configs/iks.yaml

- Related to https://github.com/astronomer/issues/issues/664
- Related to https://github.com/astronomer/issues/issues/905

Add example IKS fluentd config

---

charts/kibana/templates/kibana-pdb.yaml
charts/kibana/values.yaml

updated values file to have replica count of 2

Added podDisruptionBudget to support safely running multiple replicas

---

charts/kubed/values.yaml

Updated kubed image version for issue https://github.com/astronomer/issues/issues/470
must wait until PR https://github.com/astronomer/ap-vendor/pull/15 is complete.

Updated kubed image version

---

charts/elasticsearch/templates/exporter/es-exporter-deployment.yaml
charts/elasticsearch/values.yaml
charts/fluentd/templates/fluentd-configmap.yaml
charts/fluentd/values.yaml

cleanup release 0.13

---

charts/astronomer/templates/houston/houston-deployment.yaml
charts/astronomer/values.yaml

requested by customer, patched into 0.12 already in 0.12.7
I will go ahead and just push to 0.13 branch too

Make Houston probes more configurable

---

charts/astronomer/templates/houston/houston-configmap.yaml

This PR adds `-number` images and **buster** images too
Issue: https://github.com/astronomer/issues/issues/1119

Add list of other supported images

---

charts/astronomer/values.yaml

Marge after related PRs will be merged

bump images

---

charts/grafana/values.yaml
charts/prometheus/values.yaml

pulling in the changes from here  https://github.com/astronomer/ap-vendor/pull/18/files

Update Grafana and Prometheus

---

charts/astronomer/values.yaml
charts/prometheus-blackbox-exporter/values.yaml

fixes from QA on 4/14/20
authors:
- Andrii
- Ryan
- Jim

Houston 0.13.3 and reconfigure resources on blackbox exporter

---

bin/migration-scripts/README.md
bin/migration-scripts/upgrade.sh

0.10 renamed this secret so we need to reconfigure the airflows.

Specify new name for signing cert in upgrade script

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml

Also updated nginx 5xx alert while I was in there to fix a 4/5 typo.

Added Ingress certificate expiring alert

---

charts/astronomer/templates/houston/houston-configmap.yaml

Issue: https://github.com/astronomer/issues/issues/1143
Related to https://github.com/astronomer/ap-airflow/pull/66

Add ap-airflow 1.10.10 Images to Supported list

---

charts/keda/values.yaml

sadly appears you can't template a values.yaml

Fix breaking templates in KEDA nodeAffinities

---

Chart.yaml
charts/astronomer/values.yaml
charts/elasticsearch/values.yaml
charts/grafana/values.yaml
charts/kibana/values.yaml
charts/nginx/values.yaml
charts/prometheus/values.yaml

Image version updates for the updates created for CVEs. 
See https://github.com/astronomer/issues/issues/1250

Updates to container iamge versions

---

charts/astronomer/templates/houston/houston-configmap.yaml

Based on https://github.com/astronomer/ap-airflow/pull/75

Add support for AC 1.10.7-10 Docker images

---

charts/astronomer/values.yaml

I already added to release branch

Update commander to helm3 version

---

charts/astronomer/values.yaml

Reverts astronomer/astronomer#681

Revert "Update UI and API components for future 0.14.1 release"

---

charts/keda/values.yaml
values.yaml

All KEDA system components will launch with the platform
NodeSelector, Affinities, and tolerations

Add platform NodeSelector and affinities to KEDA

---

charts/nginx/values.yaml

fix https://github.com/astronomer/issues/issues/1199

bump ap-default-backend to 0.14.0

---

charts/astronomer/values.yaml

Latest UI/API images for upcoming 0.15 release.

Update 0.15 components

---

charts/astronomer/templates/houston/houston-configmap.yaml

Reverts astronomer/astronomer#666

Revert "Moves default configuration out of Airflow chart to Houston default"

---

charts/astronomer/values.yaml

Update to latest UI and API images

---

charts/astronomer/values.yaml

Commander 0.15.1

---

charts/astronomer/templates/houston/houston-configmap.yaml

Related PR: https://github.com/astronomer/ap-airflow/pull/93

Add support for AC 1.10.7-12 Docker images

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml
charts/prometheus/templates/prometheus-config-configmap.yaml

These changes should maintain current functionality as well as support the new free-form release names feature
fix https://github.com/astronomer/issues/issues/1397
related PR https://github.com/astronomer/houston-api/pull/335

Changes to regex to support freeform release naming feature

---

charts/nginx/values.yaml

fix https://github.com/astronomer/issues/issues/1354

bump default-backend to 0.16.0

---

charts/fluentd/templates/fluentd-daemonset.yaml

Resolution for issue https://github.com/astronomer/issues/issues/1392

Corrected Fluentd inditialDelaySeconds variable

---

charts/prometheus/templates/prometheus-config-configmap.yaml

This is related to the custom release names feature

Generalized regex to parse release name from pod name

---

charts/astronomer/templates/houston/houston-configmap.yaml

- https://github.com/astronomer/ap-airflow/pull/107
- https://github.com/astronomer/ap-airflow/pull/109
- https://github.com/astronomer/ap-airflow/pull/106

Add AC 1.10.5-9, 1.10.7-13 and 1.10.10-3 Docker Images

---

charts/elasticsearch/values.yaml
charts/kibana/values.yaml

to follow up https://github.com/astronomer/ap-vendor/pull/28

bump es and kibana to 7.7.1

---

Chart.yaml
charts/astronomer/values.yaml

prepare release-0.16

---

charts/astronomer/templates/houston/houston-deployment.yaml

Attached to astronomer/issues#1144.

Add Apollo reporting env vars

---

charts/astronomer/values.yaml

Will cheery-pick/PR into `release-0.16` next.

Bump to patched UI image

---

bin/setup-kind

this is mentioned in the release notes of Kind 0.8.0

Kind requires node version 0.15.11

---

charts/astronomer/values.yaml

Resolves these issues on 0.16:
- astronomer/issues#1474
- astronomer/issues#698

0.16 Patch

---

charts/astronomer/values.yaml

Update CLI Version to match latest Astro CLI release.
based on issue from [slack](https://astronomerteam.slack.com/archives/CLKRQNKJ9/p1595263645001100?thread_ts=1595263423.000600&cid=CLKRQNKJ9) 
and https://github.com/astronomer/astro-cli/releases/tag/v0.16.1

Update cli version

---

charts/astronomer/values.yaml

Updating to version `0.16.1` of astro-cli.

Update for the latest version of astro-cli

---

README.md
bin/reset-local-dev
bin/setup-kind

This is just small cleanup of existing code, with a bit of improvement by adding optargs with help text.
* Implement optargs for reset-local-dev, including help text
* Fix many shellcheck complaints
* Use array for KIND_OPTIONS

Improve local dev code, docs

---

charts/astronomer/templates/cli-install/cli-install-configmap.yaml
charts/astronomer/values.yaml

Merge once [astronomer/astro-cli](https://github.com/astronomer/astro-cli) has its default branch set to `main`.

CLI default branch update

---

bin/migration-scripts/upgrade-to-lts.sh

Closes: https://github.com/astronomer/issues/issues/1576

Update to LTS bugfixes

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Bumps astro-ui to `0.17.1` to fix `inviteToken` error.
(https://astronomerteam.slack.com/archives/C30GY05NG/p1595774296000100)

Update astro-ui version

---

templates/psp/restrictive-psp.yaml

The one customer that would be broken has made their changes so we can re-enable the restrictive policy again.

Made restrictive psp restrictive again

---

charts/astronomer/templates/houston/api/houston-configmap.yaml

- https://github.com/astronomer/ap-airflow/pull/121
- https://github.com/astronomer/ap-airflow/pull/122
- https://github.com/astronomer/ap-airflow/pull/123

Add AC 1.10.5-10, 1.10.7-14 and 1.10.10-4 Docker Images

---

charts/astronomer/values.yaml

Update astronomer patch version

---

charts/elasticsearch/values.yaml
charts/kibana/values.yaml

fix astronomer/issues#1569
related PR https://github.com/astronomer/ap-vendor/pull/39
Last sprints i did ES/kibana upgrade so we can release it in 0.18.0

bump es and kibana to 7.8.0

---

charts/astronomer/templates/houston/api/houston-configmap.yaml

based on slack conversation:
```
workers:
autoscaling:
enabled: false
maxReplicas: 10
minReplicas: 1
targetCPUUtilization: 80
targetMemoryUtilization: 80
keda:
cooldownPeriod: 30
enabled: true
namespaceLabels:
name: astronomer # <-- add this line
pollingInterval: 5
```
for ref https://github.com/astronomer/issues/issues/1625

add missing keda namespaceLabels

---

Makefile
charts/elasticsearch/templates/es-psp-rolebinding.yaml
charts/fluentd/templates/fluentd-psp-rolebinding.yaml
charts/nginx/templates/nginx-psp-rolebinding.yaml
charts/prometheus/templates/prometheus-alerts-configmap.yaml
charts/stan/templates/statefulset.yaml

wrt https://github.com/astronomer/issues/issues/1607

Fix a few places where release name and namespace were conflated

---

charts/astronomer/values.yaml

astronomerinc/ap-houston-api:0.19.0
Features added:
> b07a349 Adjust defaultExtraAu validation (#420)
> 2506cb9 Replacing mapCustomEnvironmentVariables with secretName (#415)
> 3f49554 fix: upgrade openid-client from 3.15.8 to 3.15.9 (#421)
> afc16f8 Wait for NATS Host and Port (#423)
> f51e48f Fix flakey test (#359)
> e66c4a3 Implement NATS Update Deployments (#412)
> bcfe6ad Enable Delete and Create Deployment Workers (#417)
> eaca3d4 fix: package.json & yarn.lock to reduce vulnerabilities (#419)
> 10c0d98 Update code coverage minimum (#418)
> 24213c3 add nats cluster to docker-compose-nats-cluster.yml (#386)
> 1c6e40d Create wrapper for publisher error handling (#411)
> 79bfbd2 fix: upgrade multiple dependencies with Snyk (#409)
> 21d8ea0 Update workers codeowners (#410)
> 8c81f2f Add …

Turn on NATs integration and add RBAC for environment variables

---

charts/astronomer/values.yaml

Fixes issues with Houston not correctly reconnecting with NATS.
Resolves astronomer/issues#1722
The …

Reconnect correctly for NATS in Houston

---

.github/pull_request_template.md

Update the PR request template
N/A (this is a minor update)
> Please add helm unit testing if possible
N/A
> Add screenshots to illustrate the changes, if applicable
N/A

Add checklist item to ensure PR title update

---

charts/astronomer/values.yaml

Update to the latest version of the LTS CLI `0.16.4`, update Houston API to `0.16.12` and update the Airflow Chart version to `0.15.6`
> If there is only one commit in the PR, when clicking the merge button, be …

Minor bug fixes and updates for Astro CLI, Houston and Airflow Chart Version

---

charts/astronomer/values.yaml

Fix setting mount all from secret name on create deployment
> If there is only one commit in the PR, when clicking the merge button, be sure to copy the PR title …

Fixing setting mountAllFromSecretName on createDeployment

---

.pre-commit-config.yaml
Chart.yaml
bin/functional-tests/test_astronomer.py
charts/alertmanager/templates/alertmanager-statefulset.yaml
charts/astronomer/templates/registry/registry-statefulset.yaml
charts/astronomer/values.yaml
charts/elasticsearch/templates/data/es-data-statefulset.yaml
charts/elasticsearch/templates/master/es-master-statefulset.yaml
charts/grafana/dashboards/core-dns.json
charts/grafana/dashboards/kube-dns.json
charts/postgresql/templates/statefulset-slaves.yaml
charts/postgresql/templates/statefulset.yaml
charts/prometheus/templates/prometheus-config-configmap.yaml
charts/prometheus/templates/prometheus-statefulset.yaml
templates/_apivers.tpl

Fixing env var mounting when executor is kubernetes
> If there is only one commit in the PR, when clicking the merge button, be sure to copy the PR title into the PR …

Fixing env var mounting when executor is kubernetes

---

.circleci/config.yml
.circleci/config.yml.j2
.gitignore
.pre-commit-config.yaml
Chart.yaml
bin/functional-tests/README.md
bin/functional-tests/conftest.py
bin/functional-tests/requirements.txt
bin/functional-tests/test_config.py
bin/functional-tests/test_versioning.py
bin/run-ci
bin/test-ap
charts/astronomer/Chart.yaml
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/templates/daemonset.yaml
charts/prometheus-node-exporter/templates/service.yaml
charts/prometheus-node-exporter/tests/daemonset_test.yaml
charts/prometheus-node-exporter/tests/service_test.yaml

To make sure "helm upgrade" works between patch versions
Closes https://github.com/astronomer/issues/issues/1622
This change is to add tests

Add patch version upgrade testing

---

charts/astronomer/values.yaml

Update the image version for release 0.20
No associated issue
This change just updates the image version

Update db-bootstrapper to support Prisma2

---

bin/functional-tests/test_config.py
charts/nginx/templates/nginx-networkpolicy.yaml

Fix Nginx ingress network policy

---

charts/astronomer/values.yaml

Release Houston API and Astro CLI version 0.20.0 …

Migrate to Prisma 2 for Houston API, Astro UI and minor fixes for Astro CLI

---

charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/tests/test-deployment.yaml

Make sure the disabling of this feature is working
no associated issue
I can add a unit test

Prometheus postgres exporter disable functionality

---

charts/astronomer/values.yaml

Resolve a bug with the workspace not returning the correct trial expiration date and stripe customer ID.
> If there is only one commit in the PR, when clicking the merge button, be sure to copy the PR title …

Fix Stripe Customer ID missing bug in Houston API

---

charts/astronomer/values.yaml

Adds patch fix in astronomer/houston-api#459
Needs to be cherry-picked to `release-0.20` branch.
N/A

Patch Houston with query response bugfix

---

charts/astronomer/values.yaml

Fix error with prisma 2 queries within the Workers …

Fix primsa 2 queries in Houston Workers

---

charts/astronomer/values.yaml

Fix the Astro UI DateTime issue
> If there is only one commit in the PR, when clicking the merge button, be sure to copy the PR title into the PR squash and merge option's commit message. By default with a …

Update Astro UI DateTime issue

---

charts/astronomer/values.yaml

Adds null check for cardState variable in WorkspaceBillingUpdateForm.
> If there is only one commit in the PR, when clicking the merge button, be sure to copy the PR title into the PR squash and merge option's …

Add null check to Astro UI card state

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml

This alert is astronomer specific and is being put in to the platform through other means. 
Resolves https://github.com/astronomer/issues/issues/1530

Removing node count prometheus alert. 

---

charts/astronomer/values.yaml

bump houston-api to 0.20.5

---

charts/astronomer/values.yaml

bump houston-api to 0.20.6 to solve a delete cascade related issue preventing clean deletion of user records from the system

---

charts/astronomer/templates/houston/houston-configmap.yaml

We haven't released AC 1.10.12-1 yet but just created a PR so that we can release it with the next platform release. So when we do release AC 1.10.12-1 the platform already supports it.
cc @paolaperaza

Add Support for AC 1.10.12-1

---

charts/astronomer/values.yaml

Fixing rolebinding auth error message and broken invitation flow
> If there is only one commit in the PR, when clicking the merge button, be sure to copy the PR …

Fixing rolebinding auth error message and broken invitation flow

---

charts/astronomer/values.yaml

Fixes a bug with creating deployments (flower and redis were not starting for new deployments using default settings).  See issue for more details.
> If there is only one commit in the PR, when clicking the …

Fix create deployment helm chart creation

---

charts/astronomer/values.yaml

related to https://github.com/astronomer/houston-api/pull/477

Fix Token Validation Bug in Houston API

---

Chart.yaml
charts/astronomer/Chart.yaml

changing the inviteToken and was still able to signup on the platform. #1891
resolves https://github.com/astronomer/issues/issues/1891

changing the inviteToken and was still able to signup on the platform. #1891 (bump chart to 0-20-1)

---

Chart.yaml
charts/astronomer/Chart.yaml

Bump chart version to 0.20.2 for next release.
Bump chart version to 0.20.2 for next release.

Bump chart and app version to 0.20.2

---

charts/astronomer/values.yaml

Create Workspace using service account API returns an error [prisma1]

Create Workspace using service account API returns an error [prisma1] && bump houston api 0 16 15

---

charts/astronomer/templates/houston/houston-configmap.yaml

- https://github.com/astronomer/ap-airflow/pull/139
- https://github.com/astronomer/airflow/releases/tag/1.10.5-11

Add AC 1.10.5-11 to supported images

---

charts/nginx/values.yaml

Updated Nginx Ingress controller image
Resolves https://github.com/astronomer/issues/issues/1895

Default nginx version updated to mitigate CVEs

---

charts/astronomer/values.yaml

fixing service account downgrading user role
> If there is only one commit in the PR, when clicking the merge button, be sure to copy the PR title into the PR squash …

fixing service account downgrading user role

---

.github/pull_request_template.md

In GH PR template, use HTML comments instead of markdown comment syntax so lazy PRs look cleaner.
Rework GH PR template

Use HTML comments in GH PR template for cleaner lazy PRs.

---

charts/astronomer/tests/deployment_test.yaml
charts/astronomer/values.yaml
charts/astronomer/values.yaml.orig

bump platform images

---

Chart.yaml
charts/astronomer/Chart.yaml

bump chart version to 0.21.0

---

charts/astronomer/values.yaml

Resolves astronomer/issues#1767
Resolves astronomer/issues#1933

Update Houston API NATS and DB Migration issues

---

charts/astronomer/values.yaml

drop old constraint User_localCredential_fkey in User table (#506)

---

charts/nats/Chart.yaml
charts/nats/values.yaml
charts/stan/Chart.yaml

Update our custom NATS image to `2.1.8`
Resolves astronomer/issues#1767
Pod describe to make sure that after deployment the correct version of NATS is installed on the dev cluster.

Update NATS to version 2.1.8

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml

Adds specific alerts for ElasticSearch disk usage water mark levels, Low, High and Flood
Resolves https://github.com/astronomer/issues/issues/1869
Existing tests cover helm config map. Promtool for testing correctness of alerts.

Add elastic search watermark alerts

---

charts/nginx/values.yaml

Increasing the maximum file size nginx allows to be uploaded 
Resolves https://github.com/astronomer/issues/issues/1983

Allow pushing larger docker images

---

charts/astronomer/templates/_helpers.yaml
charts/astronomer/templates/houston/api/houston-deployment.yaml

fixes https://github.com/astronomer/issues/issues/1987

expired deployments cronjob misconfigured

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Add bug fixes, patches, and package updates for Houston API.
https://github.com/astronomer/houston-api/pull/501
https://github.com/astronomer/houston-api/pull/507
https://github.com/astronomer/houston-api/pull/508
https://github.com/astronomer/houston-api/pull/509
https://github.com/astronomer/houston-api/pull/511
https://github.com/astronomer/houston-api/pull/512
https://github.com/astronomer/houston-api/pull/514
https://github.com/astronomer/houston-api/pull/518
https://github.com/astronomer/houston-api/pull/519
https://github.com/astronomer/houston-api/pull/521
https://github.com/astronomer/houston-api/pull/523
https://github.com/astronomer/houston-api/pull/524
https://github.com/astronomer/houston-api/pull/525

Add patches and bug fixes for Houston API

---

charts/fluentd/templates/_helpers.tpl
charts/fluentd/values.yaml

This commit adds the posibility to configure:
- s3 path where the airflow logs will be stored (path): https://github.com/fluent/fluent-plugin-s3/blame/master/README.md#L500
- server side encryption when storing airflow logs to an S3 bucket (use_server_side_encryption): https://github.com/fluent/fluent-plugin-s3/blame/master/README.md#L613
> Please make the PR title informative to the user experience. For example when adding a feature, say "Add metrics tab for Deployments" instead of "Bump Astro-UI to version X.Y.Z". Bugs are sometimes harder to make customer-facing because they are very detailed, but do what you can. Instead of "Fix metrics cardinality bug" (user does not know what 'cardinality' means and does not matter to them), say "Fix bug slowing down the metrics tab". The PR title …

Add more fluentd s3 plugin configuration options

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

This PR fixes the bug in forgot password flow where an incorrect email is sent out to a local credentials user that is trying to reset the password.

Forget password flow fix

---

charts/astronomer/templates/commander/commander-networkpolicy.yaml
charts/astronomer/templates/houston/cronjobs/houston-check-airflow-version-updates-cronjob.yaml

fix issue https://github.com/astronomer/issues/issues/1728

Hotfix: network policy airflow update check

---

charts/astronomer/templates/commander/commander-role.yaml

with airflow 2 commander needs to be able to create and delete job resources
Resolves https://github.com/astronomer/issues/issues/2083

Add create and delete on job resource abilities to commander role

---

README.md
charts/keda/values.yaml

Manually tested that the links and docker images work.
Relates to astronomer/issues#1355

Switch a few references to quay.io

---

charts/astronomer/values.yaml

based on https://app.circleci.com/pipelines/github/astronomer/houston-api/2565/workflows/7c8e8ba0-fb93-4a05-8736-932be4f90a72/jobs/8806

bump houston-api and astro-ui to 0.22

---

Chart.yaml
charts/astronomer/Chart.yaml

bump umbrella chart to 0.22

---

charts/astronomer/values.yaml

Fix a bug in Astro UI for Updating Airflow Version

Fix a bug in Astro UI for Updating Airflow Version

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Fix to delete deployment service accounts when a deployment is deleted

Fix to delete deployment service accounts when adeployment is deleted

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Fix for deleting deployment with service accounts

Fix for deleting deployment with service accounts

---

templates/trust-private-ca-on-all-nodes/psp.yaml

Typo was not caught, specific to both PSP and private CA on.

Fix PSP on and Private CA on

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Fix to create synthetic rolebindings for service accounts
Resolves astronomer/issues#2156

Fix to create synthetic rolebindings for service accounts

---

bin/functional-tests/test_config.py
bin/migration-scripts/README-support-training.md
bin/migration-scripts/README.md
bin/prereq-tests/run.sh
charts/nats/values.yaml
charts/postgresql/values-production.yaml
charts/postgresql/values.yaml
charts/prometheus-blackbox-exporter/templates/blackbox-networkpolicies.yaml
configs/iks.yaml
configs/starter.yaml

Fix spelling

---

charts/astronomer/values.yaml

bump airflow chart version to 0.18.2

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

releasing astro-ui and houston-api 0.23.0 release

releasing astro-ui and houston-api 0.23.0 release

---

charts/astronomer/values.yaml

bump db-bootstrapper to 0.23

---

.circleci/config.yml
.circleci/config.yml.j2
.circleci/generate_circleci_config.py
.pre-commit-config.yaml
bin/kind-loop
bin/kind/readme.md
bin/migration-scripts/README-support-training.md
bin/migration-scripts/README.md
bin/reset-local-dev

Deprecate Kube 1.14 and 1.15.
Related to astronomer/issues#2266

deprecate k8s 1.14 and 1.15

---

charts/astronomer/templates/_helpers.yaml
charts/astronomer/templates/houston/houston-configmap.yaml
charts/astronomer/values.yaml

Resolves https://github.com/astronomer/issues/issues/2183

Allow for offline update of Airflow Releases

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml

adjusting the container memory alert threshold to 95%

update container memory alert threshold

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

prepare release 0.23.4

---

charts/astronomer/values.yaml

Fixing airflowVersion is defaulting to incorrect version of Airflow, airflow upgrade check & generating namespace labels

houston bug fixes

---

charts/astronomer/values.yaml

Fix Houston API schema change bug.
Resolves astronomer/issues#2361

Fix Houston API Schema Bug

---

charts/alertmanager/templates/alertmanager-configmap.yaml
charts/prometheus/templates/prometheus-alerts-configmap.yaml

utilizing the blackhole-receiver to persist the cputhrottling* alerts
- [ X] The PR title is informative to the user experience

persisting silences for cputhrottling* alerts

---

charts/astronomer/templates/houston/houston-configmap.yaml

- https://github.com/astronomer/updates.astronomer.io/pull/31
- https://github.com/astronomer/airflow/releases/tag/v1.10.14%2Bastro.1
- https://github.com/astronomer/ap-airflow/pull/179

Add Support for AC 1.10.14-1

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml

fix a query that doesn't take `Completed` pods into account
tested against our local prometheus to verify counts were correct

updated query to get correct number of running pods

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml
charts/prometheus/tests/prometheus-alerts-configmap_test.yaml

added release name to drive the filter on nodes correctly
tested the output from `helm template --name-template astrodev` in dev and the query works

updated alert to use Release.Name

---

bin/functional-tests/conftest.py
bin/functional-tests/test_config.py
charts/astronomer/templates/houston/api/houston-backend-secret.yaml
charts/astronomer/templates/houston/api/houston-deployment.yaml
charts/astronomer/templates/houston/helm-hooks/houston-upgrade-deployments-job.yaml

fixes https://github.com/astronomer/issues/issues/2251

release_name-houston-backend secret is being deleted in error

---

.pre-commit-config.yaml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

- Bump houston-api to the latest version.
- Bump pre-commit
- Whitespace changes

Bump houston-api version. Bump pre-commit.

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

relates to https://github.com/astronomer/issues/issues/2468

bump houston-api: Got invalid value for airflow chart version on prisma updateOneDeployment #2468

---

bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml

Update the release version to test 0.23.9-rc.1

Update the release version to test 0.23.9-rc.1

---

Chart.yaml
bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

This includes a new release for Houston API to fix the upgrade deployment scripts
Fixes astronomer/issues#2479

FIx the upgrade deployment scripts

---

bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml

Upgrade YAML to use 0.23.9-rc2

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

This PR includes 2 houston-api bugfixes:
- Astro CLI: Error message thrown when trying to create a deployment against 0.23.9-rc.1 #2481 https://github.com/astronomer/issues/issues/2481
- 0.16.5-/0.23.7/0.23.9 Upgrade: Astronomer UI shows that each deployment needs to be upgraded #2452
https://github.com/astronomer/issues/issues/2452

release bugfixes

---

Chart.yaml
charts/astronomer/Chart.yaml

Update astro chart from release candidates to 0.23.9 as it looks stable.
Please don't merge until @ernest-kr says 0.23.9 is stable and certified from an upgrade perspective.

Update astro chart to 0.23.9

---

charts/stan/templates/statefulset.yaml

Fixes CVE security issue: https://avd.aquasec.com/nvd/cve-2020-1971/

Fix ap-base containing security flaw

---

charts/prometheus-postgres-exporter/templates/deployment.yaml
charts/prometheus-postgres-exporter/templates/networkpolicy.yaml
charts/prometheus-postgres-exporter/templates/service.yaml
charts/prometheus-postgres-exporter/values.yaml
charts/prometheus/templates/prometheus-config-configmap.yaml

changes were needed to get the postgres operator up and running.  this still is not FULLY working, but i wanted to open up the PR to get some discussions going on how we can move forward.
the project that this uses is *mostly* dead, little patches here and there but seems like the guy that runs it doesn't have time (and not sure he wants help...).  just wanted to note that.
this was all run against our dev cluster, with me running local modifications testing to get this working.

trying to get the postgres exporter working

---

Chart.yaml
charts/astronomer/Chart.yaml

bumping the mainline branch to next version of release, 0.24.x

bump main/master to 0.24.0 release

---

charts/astronomer/templates/houston/api/houston-backend-secret.yaml
charts/astronomer/templates/houston/api/houston-deployment.yaml
charts/astronomer/values.yaml
values.yaml

Add a connection limit parameter for the Houston Database connection
Related to https://github.com/astronomer/db-bootstrapper/pull/30
Resolves astronomer/issues#2476
There are testing steps listed in the issue link.  We'll need to conduct further testing in `dev` and `staging`.

Add connection limit to Houston DB

---

.circleci/config.yml
.circleci/generate_circleci_config.py
bin/kind-loop
bin/kind/readme.md
bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/Dockerfile
bin/setup-kind

Bump `kind` patch versions for 1.17 and 1.18.

Bump kind versions

---

Chart.yaml
bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Bug fixes in houston and astro-ui around service accounts
Resolves astronomer/issues#2533

Release candidate for 0.23.11

---

bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
charts/astronomer/values.yaml

Updating Docker file to add yarn.lock

Updating Docker file to add yarn.lock in Houston and fixing a bug with respect to deletion of service accounts

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Delete deployment  should delete all deployment service accounts
Resolves astronomer/issues#2588

Delete deployment service account fix

---

Chart.yaml
charts/astronomer/Chart.yaml

updating chart version to 0.23.11

Rollout 0.23.11

---

.circleci/config.yml
.circleci/config.yml.j2
charts/astronomer/values.yaml

- Remove e2e test image from default values.yaml
- Fix whitespace issue in CI config.yaml
- Bump CircleCI image runner version

Remove e2e test image from default values.yaml. Cleanup.

---

CHANGELOG.md
bin/kind/readme.md
bin/migration-scripts/README.md
bin/migration-scripts/lts-to-lts/0.16-to-0.23/README.md
bin/prereq-tests/helpers/semver.bash
charts/kube-state/templates/kube-state-serviceaccount.yaml
charts/prometheus-postgres-exporter/values.yaml
configs/local-dev-ha.yaml
configs/local-dev.yaml
configs/single-namespace.yaml
docs/testing.md

chore: fix spelling

---

charts/grafana/templates/grafana-deployment.yaml

Use postgresql schema name "grafana" for grafana.

Use postgresql schema name "grafana" for grafana

---

charts/astronomer/values.yaml
charts/grafana/values.yaml

Related to https://github.com/astronomer/issues/issues/2679, https://github.com/astronomer/db-bootstrapper/pull/32

Bump db-bootstrapper to 0.25.0

---

charts/astronomer/values.yaml

UI patch that includes fix for astronomer/issues#2689

Astro UI 0.23 patch

---

charts/astronomer/values.yaml

Resolves astronomer/issues#2721

update ap-astro-ui image to 0.23.8 to push a hotfix

---

charts/astronomer/values.yaml

bump houston-api to 0.23.21

---

charts/astronomer/values.yaml

resolves https://github.com/astronomer/issues/issues/2790

bump houston-api:0.23.22

---

charts/astronomer/templates/_helpers.yaml
charts/astronomer/templates/houston/api/houston-deployment.yaml
charts/astronomer/values.yaml

related to https://github.com/astronomer/houston-api/pull/660

implement NFS mount dag deployment

---

charts/astronomer/templates/_helpers.yaml
charts/astronomer/values.yaml

Reverts astronomer/astronomer#1055

Revert "implement NFS mount dag deployment"

---

charts/astronomer/values.yaml

resolves https://github.com/astronomer/issues/issues/2836
based https://app.circleci.com/pipelines/github/astronomer/ap-vendor/370/workflows/9935b1ea-0cae-46d8-81bc-65e0d25eed22/jobs/26051

bump docker registry to support IRSA

---

charts/nats/values.yaml
charts/stan/values.yaml

bump nats/nats-streaming

---

charts/astronomer/values.yaml

bump houston/astro-ui

---

charts/elasticsearch/values.yaml

Bump ap-curator version to 5.8.4.

bump curator version to 5.8.4

---

Chart.yaml

bump chart version

---

charts/astronomer/values.yaml

bump registry

---

charts/astronomer/values.yaml

Bump houston-api
Related to:
- astronomer/issues#2920
- astronomer/houston-api#694

Bump houston-api to fix upgrade data shape bug.

---

README.md

Changing CTAs to reach out to point to https://www.astronomer.io/get-astronomer

Updating contact links

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml

numerator for the divide is corrected now 5m

---

charts/astronomer/templates/_helpers.yaml
charts/astronomer/templates/registry/registry-statefulset.yaml
charts/astronomer/values.yaml
values.yaml

resolves https://github.com/astronomer/issues/issues/3007

Add ability to use option when random data

---

charts/nginx/values.yaml

Resolves astronomer/issues#2933

update nginx in order to fix a newly reported CVE

---

charts/grafana/templates/grafana-auth-sidecar-configmap.yaml
charts/kibana/templates/kibana-auth-sidecar-configmap.yaml
charts/prometheus/templates/prometheus-auth-sidecar-configmap.yaml

A few renames and comment changes were missed in the original PR (#1103).

Minor auth sidecar cleanup

---

charts/grafana/values.yaml
charts/kibana/values.yaml

Related to astronomer/issues#3164 and astronomer/issues#3166

Update grafana and kibana to resolve some CVEs

---

charts/astronomer/values.yaml

Resolves astronomer/issues#3184

update ap-cli-install to resolve CVEs

---

charts/prometheus-blackbox-exporter/values.yaml

resolves astronomer/issues#3185

update ap-blackbox-exporter package

---

charts/nginx/values.yaml

related PR https://github.com/astronomer/default-backend/pull/16

bump default backend

---

charts/alertmanager/values.yaml
charts/elasticsearch/values.yaml
charts/fluentd/values.yaml
charts/stan/values.yaml

Bump some component versions

---

charts/astronomer/templates/commander/commander-deployment.yaml
charts/astronomer/values.yaml

https://github.com/astronomer/issues/issues/2851

add option to value to enable airgapped commander

---

charts/astronomer/values.yaml

bump astro-ui to `0.25.3` and houston-api to `0.25.8`

bump astro-ui and houston-api for 0.25.5 release

---

charts/stan/values.yaml

This fixes a permission problem we encountered after dropping privs in ap-stan. https://github.com/astronomer/issues/issues/3244

Set securityContext to that of new stan user permissions.

---

charts/astronomer/tests/deployment_test.yaml
charts/astronomer/values.yaml

https://github.com/astronomer/issues/issues/3222
bump houston to include https://github.com/astronomer/houston-api/pull/739
bump commander to include https://github.com/astronomer/commander/pull/52

bump houston-api and commander to include airgap

---

charts/elasticsearch/templates/nginx/nginx-es-configmap.yaml
charts/elasticsearch/values.yaml

astronomer/issues#1290
pls merge together with https://github.com/astronomer/ap-vendor/pull/123

ap-nginx-es: image should be created with a non root user

---

charts/astronomer/values.yaml

bump commander

---

.circleci/config.yml
.circleci/config.yml.j2
.pre-commit-config.yaml
requirements/chart-tests.txt
requirements/functional-tests.txt
requirements/lts-23-to-25-tests.txt
tests/README.md

- Fix typo
- Bump some CI related versions

Fix typo bump versions

---

charts/nats/values.yaml

update ap-nats-server to fix running as root user problem

---

README.md

Edit README to link out to more relevant documentation.
Link out specifically to Enterprise documentation
Resolves https://github.com/astronomer/docs/issues/408

Link out specifically to Enterprise documentation

---

.pre-commit-config.yaml
charts/alertmanager/templates/_helpers.tpl
charts/alertmanager/templates/alertmanager-statefulset.yaml
charts/astronomer/templates/_helpers.yaml
charts/astronomer/templates/registry/registry-statefulset.yaml
charts/elasticsearch/templates/_helpers.tpl
charts/elasticsearch/templates/data/es-data-statefulset.yaml
charts/elasticsearch/templates/master/es-master-statefulset.yaml
charts/prometheus/templates/_helpers.yaml
charts/prometheus/templates/prometheus-statefulset.yaml
charts/stan/templates/_helpers.tpl
charts/stan/templates/statefulset.yaml
requirements/chart-tests.txt
requirements/functional-tests.txt
requirements/lts-23-to-25-tests.txt
tests/test_alertmanager.py
tests/test_global_storageclass.py

global storageclass values to reflect on all platform deployments
https://github.com/astronomer/issues/issues/3313

global storage class change to apply on all platform deployments

---

charts/alertmanager/values.yaml
charts/astronomer/values.yaml
charts/prometheus/values.yaml
charts/stan/values.yaml

Includes new image versions with updated security packages 
updated images with newer security  patches

updated images with newer security  patches

---

.circleci/config.yml
.circleci/config.yml.j2

backport some security changes that were made after the codecov security incident.

Fix gcp context in release-0.23

---

charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
charts/external-es-proxy/templates/external-es-proxy-configmap.yaml
charts/external-es-proxy/templates/external-es-proxy-deployment.yaml
charts/external-es-proxy/templates/external-es-proxy-networkpolicy.yaml
charts/external-es-proxy/templates/external-es-proxy-serviceaccount.yaml
charts/external-es-proxy/values.yaml
values.yaml

* integration with aws elasticsearch
* support for aws keys
* general configs

 Support for AWS elasticsearch

---

charts/elasticsearch/values.yaml
charts/nats/values.yaml
charts/nginx/values.yaml
charts/prometheus-blackbox-exporter/values.yaml

changes wrt to new openssl CVE fixes
update astronomer images

bump updated images for astronomer

---

charts/astronomer/values.yaml

ap-registry base image includes fixes for CVE's

bump ap-registry image

---

charts/fluentd/templates/fluentd-configmap.yaml
values.yaml

https://github.com/astronomer/issues/issues/3424

make fluentd to gather logs from all namespaces if preCreatedNamespaces is enabled

---

charts/astronomer/templates/commander/commander-deployment.yaml
charts/astronomer/values.yaml
configs/local-dev.yaml
tests/__init__.py
tests/helm_template_generator.py
tests/test_astronomer_commander.py

Add upgrade timeout to helm chart

Add upgrade timeout to commander helm release23

---

charts/astronomer/templates/commander/commander-deployment.yaml
charts/astronomer/values.yaml
configs/local-dev.yaml
tests/test_astronomer_commander.py

Add upgrade timeout to helm chart

add upgrade timeout to helm chart

---

Chart.yaml
charts/astronomer/Chart.yaml

All changes have been merged for 0.23.15.

Bump to 0.23.15-rc2

---

charts/astronomer/values.yaml

release-0.25.7
adds pre-created namespaces functionality

platform update release

---

charts/elasticsearch/values.yaml

curator cleanup service was failing due to new python elasticsearch SDK
https://github.com/astronomer/issues/issues/3463

bump curator image

---

charts/fluentd/templates/fluentd-configmap.yaml

Adds triggerer logs to fluentd such that the logs are sent to kibana

add triggerer to fluentd

---

charts/astronomer/values.yaml

this should probably be updated via CICD somehow?
Fixes  https://github.com/astronomer/issues/issues/2802

update Astro CLI version to latest verison

---

charts/nginx/values.yaml

bump default backend image to 0.25.3

---

charts/astronomer/templates/commander/commander-role.yaml
charts/astronomer/templates/commander/commander-rolebinding.yaml
tests/test_global_cluster_roles.py
values.yaml

resolves https://github.com/astronomer/issues/issues/3521

add global flag for global.clusterRoles

---

charts/prometheus/templates/prometheus-alerts-configmap.yaml

Should be a no-op, only alert wording was changed.

Fix two typos in prom alerts

---

charts/astronomer/values.yaml

add astro-cli -0.26 Release to 0.26 release

add astro-cli -0.26 Release to 0.26 release

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Main change of interest is the ability to use oAuth auth_code flow.

Bumping version of UI and Houston for 0.27 RC1

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

bump houston 0.26.10
bump commander 0.26.4
bump platform 0.26.4-rc1

Bump release 0.26.4-rc1

---

.circleci/config.yml
.circleci/config.yml.j2
.pre-commit-config.yaml
bin/setup-circleci-shell-env.sh
requirements/chart-tests.txt
requirements/functional-tests.txt

Bump a bunch of CI image versions and dev component versions. Nothing here affects end users, only dev workflows.

Bump ci images

---

charts/astronomer/templates/houston/helm-hooks/houston-db-migration-job.yaml
charts/astronomer/templates/houston/helm-hooks/houston-upgrade-deployments-job.yaml
charts/astronomer/templates/houston/worker/houston-worker-deployment.yaml

resolves https://github.com/astronomer/issues/issues/3759

add prisma_connection_limit to worker pods too

---

values.schema.json

Resolves astronomer/issues#3715. See https://github.com/astronomer/airflow-chart/pull/260#issuecomment-961965285 for context.

Add JSON schema file

---

charts/fluentd/values.yaml

Huge number of meta warn errors are generated from kubernetes_metafilter plugin and newer module updates
bump fluentd image
https://github.com/astronomer/issues/issues/3723

bump fluentd image to 1.14.2

---

charts/prometheus-postgres-exporter/values.yaml

bump postgres exporter
Resolves astronomer/issues#3770

bump postgres exporter

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml
values.schema.json

- update houston 0.27 -> 0.27.1
- update astro ui 0.27 -> 0.27.1
- bump platform version to 0.27.0-rc2

upgarde platform to release0.27 rc2

---

charts/astronomer/templates/commander/commander-role.yaml

resolves https://github.com/astronomer/issues/issues/3782

fix: failed to create resource

---

charts/astronomer/values.yaml

bump airflow-chart to 1.0.7 to fix git sync error by bumping image version

bump airflow-chart to 1.0.7

---

Chart.yaml
charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
charts/astronomer/templates/houston/houston-configmap.yaml
charts/external-es-proxy/templates/_helpers.tpl
charts/external-es-proxy/templates/external-es-proxy-configmap.yaml
charts/external-es-proxy/templates/external-es-proxy-deployment.yaml
charts/external-es-proxy/templates/external-es-proxy-serviceaccount.yaml
charts/fluentd/templates/fluentd-daemonset.yaml
tests/test_external_elasticsearch.py
values.yaml

Follow helm naming guidelines 
rename custom_logging to customLogging

rename custom_logging to customLogging

---

charts/astronomer/values.yaml

Bump airflow chart version for master to 1.1.0

bump airflowChartVersion to 1.1.0

---

charts/astronomer/values.yaml

related to https://github.com/astronomer/houston-api/pull/841

bump houston-api image to 0.27.3

---

bin/create-initial-user
bin/helpers.sh
bin/prep-k8s
bin/reset-local-dev
bin/run-ci
bin/setup-circleci-shell-env.sh
bin/setup-kind
charts/astronomer/templates/commander/commander-role.yaml

Begin work on allowing us to test for arbitrary namespaces so we can detect improper handling of namespace names.
Related to <https://github.com/astronomer/issues/issues/3813>
This is a first step towards testing odd namespaces. These changes only allow us to specify the namespace everywhere, but do not actually change the namespace during testing. We can do that in a follow up PR.

Handle namespace as variable everywhere for better namespace edge case testing

---

charts/astronomer/values.yaml

bump astro-ui to 0.27.3 from 0.27.2

bump astro-ui to 0.27.3 from 0.27.2

---

charts/astronomer/values.yaml

related PR https://github.com/astronomer/commander/pull/72
https://github.com/astronomer/issues/issues/3674

bump commander to 0.27.0

---

charts/astronomer/values.yaml

Bump ap-houston to 0.27.5

---

charts/astronomer/values.yaml

bump ap-commander to 0.27.1

---

charts/astronomer/values.yaml

update version of cli for 0.27 major change is adding podman support as well as fixing some bugs
astronomer/issues#3920
astronomer/issues#3425
cli changes have been tested by qa

update version for cli to 0.27 with podman support

---

README.md

Update URLs in the readme to the new docs URLs.
N/A
N/A

Update Astronomer docs URLs

---

charts/grafana/values.yaml
charts/nats/values.yaml
charts/nginx/values.yaml
charts/prometheus-node-exporter/values.yaml
charts/stan/values.yaml
tests/test_stan_sts.py

Bump several images to latest version so we keep up with the latest bug and security fixes.
N/A, just regular ongoing maintenance stuff.
No testing done, but this should be tested as part of QA before the next release.

Bump several images to latest available

---

charts/astronomer/templates/houston/houston-configmap.yaml
tests/test_houston_configmap.py
values.yaml

resolves https://github.com/astronomer/issues/issues/3900

support global.kubedEnabled in houston

---

values.schema.json

This adds the sidecar logging properties to the JSON schema file.
astronomer/issues#3562

Validate sidecar logging properties

---

charts/elasticsearch/values.yaml

multiple CVE fixes reported by trivy scan
https://github.com/astronomer/issues/issues/4000
NA

bump nginx es image

---

charts/astronomer/values.yaml
charts/grafana/values.yaml

Bump 3 images to latest available.
N/A
I have tested grafana to verify it works. I'm not sure what testing the other images have undergone.

Bump 3 images to latest available

---

charts/kube-state/templates/kube-state-deployment.yaml
charts/kube-state/values.yaml
charts/prometheus-node-exporter/values.yaml
tests/test_resource_limits.py

set resources limits to node exporter and kube state metrics
https://github.com/astronomer/issues/issues/4056
NA

set resources limits on node exporter and kube state metrics

---

charts/elasticsearch/values.yaml

fix ap-base vulnerability 
https://github.com/astronomer/issues/issues/4089
NA

fix critical cve es base

---

charts/astronomer/values.yaml

update main with versions from 0.28 release
https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.28.0+
0.28 is being tested by qa

Bump airflow-chart, houston-api, astro-ui

---

charts/astronomer/values.yaml

* includes security fixes and enhancements
* ref release notes : https://github.com/astronomer/airflow-chart/releases/tag/v1.0.11
Issue Link: github.com/astronomer/issues/issues/4210
QA should able to deploy airflow deployment without any issues ( Celery/Local/kubernetes executors)

update airflowchartversion to 1.0.11 for release-26

---

requirements/chart-tests.in
requirements/chart-tests.txt
requirements/functional-tests.txt

Bump the test requirements files. Add black so it gets installed automatically in the venv so vscode doesn't complain.
N/A
CI tests should be enough to cover this.
This change set should be merged into all supported branches (or just `git checkout master requirements` in those branches.)

Add black. Update requirements.

---

charts/nginx/templates/nginx-deployment.yaml
charts/nginx/templates/nginx-role.yaml
charts/nginx/values.yaml
tests/test_nginx_service.py

* add electionID flag to nginx controller
* update values files for overrides
Issue Link: https://github.com/astronomer/issues/issues/4392
Need to update

nginx ingress controller enhancements

---

charts/external-es-proxy/values.yaml
charts/fluentd/values.yaml
charts/kubed/values.yaml

update ap-openresty 1.19.9 1.19.9-1
update ap-fluentd  1.14.3-1 1.14.5
update ap-kubed  0.13.0 -> 0.13.2
Need to check 
QA should be able to deploy platform without any issues or exceptions

bump vendor images for improved security

---

.pre-commit-config.yaml
README.md
bin/functional-tests/README.md
charts/astronomer/templates/houston/houston-configmap.yaml
charts/grafana/values.yaml
charts/postgresql/values-production.yaml
charts/postgresql/values.yaml
tests/test_ingress.py
tests/test_postgres.py
values.yaml

Found some typos. Added pre-commit hook `codespell` and fixed the typos.
N/A
One typo was in actual code, but it was test code, so if tests pass we're good. The rest are just comments.

Add codespell. Fix typos.

---

charts/astronomer/templates/houston/cronjobs/houston-check-runtime-updates.yaml
charts/astronomer/templates/houston/cronjobs/houston-check-updates-cronjob.yaml
charts/astronomer/values.yaml
tests/test_cronjob_chech_runtime_updates.py

https://github.com/astronomer/issues/issues/4057

add runtime check cronjob

---

charts/astronomer/values.yaml

Update commander to version 0.28.3

bump commander to 0.28.3

---

charts/astronomer/values.yaml

cherry pick release 0.28: bump commander to 0.28.3

---

charts/astronomer/values.yaml
charts/grafana/values.yaml

update db-bootstrapper 0.26.4 -> 0.26.5
Fixes zlib cve
NA

bump db booststrapper

---

charts/astronomer/values.yaml

add changes for 0.28.4
https://github.com/astronomer/issues/issues/4394
https://github.com/astronomer/issues/issues/4375
https://github.com/astronomer/issues/issues/4334
https://github.com/astronomer/issues/issues/4342
https://github.com/astronomer/issues/issues/4455
https://github.com/astronomer/issues/issues/4414
https://github.com/astronomer/issues/issues/4394
https://github.com/astronomer/issues/issues/4375
https://github.com/astronomer/issues/issues/4334
https://github.com/astronomer/issues/issues/4342
https://github.com/astronomer/issues/issues/4455
https://github.com/astronomer/issues/issues/4414
tested in dev

bump houston to 0.28.13 from 0.28.11

---

charts/astronomer/values.yaml

* bump airflow chart version 1.4.0 -> 1.4.1
* update commander image 0.28.3 -> 0.28.4
NA
QA should able to install airflow chart with correct version without any issues

update commander service

---

charts/astronomer/values.yaml

ship pgbouncer and exporter components with cve fixes, ship with update airflow chart in commander and tag in astronomer/astronomer
NA
QA should able to deploy platform without any issues

Sync master release 028

---

.github/pull_request_template.md

Add a section to the PR template detailing which branches the change should be merged / cherry-picked into.
N/A
None needed.
This change isn't needed in any release branches because GH uses the default branch's pull request template.

Add section: Merging

---

charts/fluentd/values.yaml

bump fluentd image 1.14.5-1 -> 1.14.6
NA
NA
Merge changes to master

bump fluentd image

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

bump to 0.29.0-rc3

---

tests/chart_tests/test_authsidecar.py
values.yaml

Replace nginx unprivileged image with ap-authsidecar 
NA
NA
merge this change to master

Use ap-auth-sidecar

---

charts/astronomer/values.yaml

https://github.com/astronomer/issues/issues/4557

bump houston 0.29.5 to bring runtime hotfixes

---

charts/astronomer/values.yaml

Add airflow chart version to master branch
NA
NA
merge to release-0.29 branch

airflow chart not added in master branch

---

charts/astronomer/values.yaml

runtime fixes, BYO, and idp jwt fixes
ui
Related https://github.com/astronomer/issues/issues/4603
houston
Related https://github.com/astronomer/issues/issues/4586
https://github.com/astronomer/issues/issues/4609
Related https://github.com/astronomer/issues/issues/4605
Related https://github.com/astronomer/issues/issues/4594
tested in dev
release-0.29

Bump astro ui 0.29.5 and houston 0.29.8

---

charts/astronomer/values.yaml
charts/grafana/values.yaml

https://github.com/astronomer/astronomer/pull/1507
https://github.com/astronomer/astronomer/pull/1506
https://github.com/astronomer/astronomer/pull/1508

release new chart

---

charts/astronomer/values.yaml

bump astro ui to fix logs issue
Related https://github.com/astronomer/issues/issues/4617
in dev
0.29

bump astro ui to 0.29.6 from 0.29.5

---

charts/astronomer/values.yaml

Bump up Houston and Astro-ui
Related https://github.com/astronomer/issues/issues/4625
Tested locally
release 0.29

bump up houston and astro ui

---

.circleci/config.yml
charts/astronomer/values.yaml

fix triggerer logs for runtime deployments
astronomer/issues#4640
tested in dev
0.29

bump astro ui to 0.29.8 from 0.29.7

---

.circleci/config.yml
charts/astronomer/values.yaml

bump houston to 0.29.22
Issue #4407
Tested locally. Dev contains 0.28.4, so couldn't test there
0.29.0

bump houston to 0.29.22

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Updated Fix Elasticsearch log_id_template in airflow-chart

0.29.0-rc28

---

.circleci/config.yml
.circleci/config.yml.j2
.circleci/generate_circleci_config.py
.circleci/slack_message_templates/security_scan_fail.json
.circleci/trivyignore
.pre-commit-config.yaml
bin/trivy-scan.sh

This PR adds the scan notifications to Slack (#team-software-infra-bot) on fail. It will only report the fail scan (that found vulnerabilities).
Master PR: https://github.com/astronomer/astronomer/pull/1548
https://github.com/astronomer/issues/issues/4620

Issue-4620 Docker Image Scan and its notifications to slack (#1548)

---

.circleci/config.yml
.circleci/config.yml.j2
.circleci/generate_circleci_config.py
.circleci/slack_message_templates/security_scan_fail.json
.circleci/trivyignore
bin/kind/calico-crds-v1.18.yaml
bin/trivy-scan.sh

- This PR is adding CircleCI workflow that scan docker images with Trivy and Snyk. We have trigger set to perform this everyday. 
- It will also send Slack notifications to channel #team-software-infra-bot on fail. 
Master PR: https://github.com/astronomer/astronomer/pull/1548
https://github.com/astronomer/issues/issues/4620
Testing was done as by verifying notifications coming to slack channels on build.
N/A

Issue-4620 Docker Image Scan and its notifications to slack

---

.circleci/config.yml
charts/elasticsearch/values.yaml
charts/stan/values.yaml

bump ap-base 3.15.4 -> 3.16.0 to elasticsearch and stan service
NA
NA
cherry-pick to release-0.26,0.27,0.28 and 0.29

update ap-base image

---

.circleci/config.yml
bin/trivy-scan.sh
charts/elasticsearch/values.yaml
charts/kibana/values.yaml
values.yaml

Update the elastic-es docker image.
Scan only CRITICAL Vulnerabilities
https://github.com/astronomer/astronomer/pull/1558

Issue-Fix-Critical | Fix nginx-es image and Check CRITICAL vulnerability

---

charts/elasticsearch/templates/exporter/es-exporter-deployment.yaml
charts/elasticsearch/values.yaml
tests/chart_tests/test_elasticsearch.py

ES Exporter is set to run as root it's not needed anymore , current change will run the service a less privileged user.
**changes**
* run as non root service to removed unnecessary root usage
Yet to define
Yet to define
Yet to define

enhance es exporter service

---

.pre-commit-config.yaml
bin/kind/calico-crds-v1.18.yaml
bin/setup-kind
requirements/chart-tests.txt
requirements/functional-tests.txt
requirements/lts-23-to-25-tests.txt

- Update requirements
- Bump pre-commit
N/A, just normal maintenance.
If CI passes that should be good enough.
These changes are only meant for release-0.25 branch.

Update requirements for release-0.25

---

charts/prometheus/templates/prometheus-config-configmap.yaml
charts/prometheus/values.yaml
tests/chart_tests/test_prometheus_config_configmap.py
values.yaml

Addresses the gh issue [4752](https://github.com/astronomer/issues/issues/4782)
https://github.com/astronomer/issues/issues/4782
Add test case

Issue-4752 | Add configurable scrape interval for prometheus

---

charts/astronomer/templates/houston/api/houston-deployment.yaml
charts/astronomer/templates/houston/houston-configmap.yaml
tests/chart_tests/test_houston_configmap.py
values.yaml

Load external vector configmap to a k8 secret
https://github.com/astronomer/issues/issues/4733
0.29.2

added customConfig and secretName to loggingSidecar

---

.circleci/config.yml
charts/elasticsearch/values.yaml
charts/kibana/values.yaml

Update elastic vendor packages
* update ap-kibana 7.17.4 -> 7.17.5
**release notes**
https://www.elastic.co/guide/en/kibana/7.17/release-notes-7.17.5.html
https://www.elastic.co/guide/en/security/7.17/release-notes-header-7.17.0.html#release-notes-7.17.5
* update ap-elasticsearch 7.17.4 -> 7.17.5
**release notes**
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/release-notes-7.17.5.html
NA
NA
cherry-pick to release-0.29,0.28,0.27

bump elastic images

---

.circleci/config.yml
charts/astronomer/values.yaml

Updating AstroUI image that supports on-demand file logs controlled by environment variables.
More detailed PR on AstroUI: https://github.com/astronomer/astro-ui/pull/1457
https://github.com/astronomer/issues/issues/4472
N/A
- release-0.29

AstroUI  - Support on-demand file-logs

---

tests/chart_tests/test_prometheus_config_configmap.py

Addresses the [issue](https://github.com/astronomer/issues/issues/4804)

Issue 4804 | testcase to check the behavior of nodeExporterEnabled

---

charts/astronomer/templates/houston/houston-configmap.yaml
tests/chart_tests/test_houston_configmap.py
values.yaml

This change externalizes adding custom vector images
https://github.com/astronomer/issues/issues/4733
Tested on kind cluster
0.29.2

pushed vector image configuration

---

bin/reset-local-dev

Fixed this issue - https://astronomer.slack.com/archives/C02J8JT58CC/p1657653921310739
Locally
master
old release branches?

Fixed the timeout issue on local

---

requirements/chart-tests.txt
requirements/functional-tests.txt
tests/chart_tests/test_astronomer_bootstrap_secret.py

Quick tests for astronomer-bootstrap secret.
N/A, but discussion is here: <https://astronomer.slack.com/archives/C02J8JT58CC/p1657577430460649?thread_ts=1657576624.426129&cid=C02J8JT58CC>
Only tests are changing so nothing else is needed.
Merge into all supported branches: 0.29, 0.28, 0.25

Add some tests for astronomer-bootstrap secret. Bump requirements.

---

.circleci/config.yml
.circleci/trivyignore
charts/astronomer/values.yaml
charts/fluentd/values.yaml
tests/chart_tests/test_houston_configmap.py
values.yaml

bump ap-fluentd 1.14.6-1 -> 1.15.0 
bump ap-vector 0.22.3 -> 0.23.0 
bump ap-registry 3.15.4-1 -> 3.16.1
added fluentd resource limits in globals to avoid OOM error
NA

Add vendor packages

---

Chart.yaml
charts/astronomer/Chart.yaml

Cut over to 0.29.3 rc1 
https://github.com/astronomer/issues/issues/4876
NA
merge to release-0.29

release 0.29.3 rc1

---

Chart.yaml
charts/astronomer/Chart.yaml

Remove rc tag and release 0.29.3
Issue Link: https://github.com/astronomer/issues/issues/4876
NA
merge to release-0.29

remove rc tag and release 0.29.3

---

.circleci/config.yml
charts/astronomer/values.yaml

update images astro-ui 0.30.1 and houston  0.30.7 with new issues
astro uii:
Related https://github.com/astronomer/issues/issues/4852
Related https://github.com/astronomer/issues/issues/4793
Related https://github.com/astronomer/issues/issues/4793
Related https://github.com/astronomer/issues/issues/4879
houston:
Related https://github.com/astronomer/issues/issues/4880
Related https://github.com/astronomer/issues/issues/4886
Related https://github.com/astronomer/issues/issues/4598
Related https://github.com/astronomer/issues/issues/4897
dev
release-0.30 rc2

Update release 0.30 houston UI

---

.circleci/config.yml
charts/astronomer/values.yaml

bump houston to include the two issues below
Related https://github.com/astronomer/issues/issues/4922
https://github.com/astronomer/houston-api/pull/1210
was tested by developers
0.30 rc4

bump houston to 0.30.9 from 0.30.7

---

.circleci/config.yml
charts/astronomer/values.yaml

add new changes for rc5
https://github.com/astronomer/issues/issues/4838
Related https://github.com/astronomer/issues/issues/4926
Related https://github.com/astronomer/issues/issues/4698
dev
0.30 rc5

bump astro ui to 0.30.2 and houston to 0.30.11

---

charts/prometheus/values.yaml

some value  cleanup which are not needed.
Issue Link https://github.com/astronomer/issues/issues/4782
NA
merge to release-0.30

cleanup values for prometheus

---

.circleci/config.yml
charts/astronomer/values.yaml

bump houston in 0.30 release
Related https://github.com/astronomer/issues/issues/4953
dev
release-0.30

bump houston to 0.30.13 from 0.30.12

---

.circleci/config.yml
charts/astronomer/values.yaml

add new airflow chart and update chart 
https://github.com/apache/airflow/pull/25031
0.30

update airflow chart and commander with new chart

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

refactored shell script to pull from internal 
https://github.com/astronomer/commander/commit/2b8d35572df9dc691261eecf50db355979e8561c
qa will test
0.30

bump commander with new helm internal chart and bump platform to rc7

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

bump to 0.30.2-rc1

---

charts/alertmanager/templates/_helpers.tpl
charts/astronomer/templates/_helpers.yaml
charts/elasticsearch/templates/_helpers.tpl
charts/external-es-proxy/templates/_helpers.tpl
charts/fluentd/templates/_helpers.tpl
charts/grafana/templates/_helpers.yaml
charts/kibana/templates/_helpers.tpl
charts/kube-state/templates/_helpers.yaml
charts/nats/templates/_helpers.tpl
charts/nginx/templates/_helpers.tpl
charts/postgresql/templates/_helpers.tpl
charts/prometheus-blackbox-exporter/templates/_helpers.tpl
charts/prometheus-node-exporter/templates/_helpers.tpl
charts/prometheus-postgres-exporter/templates/_helpers.tpl
charts/prometheus/templates/_helpers.yaml
charts/stan/templates/_helpers.tpl
tests/chart_tests/test_houston_api_deployment.py

Only adds imagePullSecret if the secret name is actually defined as a null name causes issues.
https://github.com/astronomer/issues/issues/5055
Unit tested
0.31.0 0.30.3

Only add image pull secret if secret name is defined

---

charts/astronomer/values.yaml

Minor doc changes
N/A
N/A docs changes

Update values.yaml - crontab link for all cron times in file

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

- https://github.com/astronomer/issues/issues/4954

cutover 0.29.5-rc3 release

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

* bump houston-api 0.25.15 -> 0.25.16
NA
QA should validate platform should  work without any issues 
merge to release-0.25

update houston api 0.25.15 -> 0.25.16

---

Chart.yaml
charts/astronomer/Chart.yaml

Release 0.28.7

---

charts/astronomer/templates/houston/houston-configmap.yaml
tests/chart_tests/test_houston_configmap.py
values.yaml

Ability to add env vars to logging sidecars
https://github.com/astronomer/issues/issues/5106
https://github.com/astronomer/issues/issues/5095

sidecar logging enhancements

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

- Fixed a bug at `astro-ui` level, where the astronomer user was seeing an error on the deployment level service account page.
- https://github.com/astronomer/issues/issues/5128

cutover 0.25.15-rc2 release

---

Chart.yaml
charts/astronomer/Chart.yaml

Release 0.25.15

---

tests/chart_tests/test_fluentd_index_configmap.py

fix tests cases for  fluentd index configmap
NA
NA
cherry-pick to valid release branches

fix tests cases for  fluentd index configmap

---

.circleci/config.yml
charts/astronomer/values.yaml

Bug Fixes on astro-ui service
fixes an issue with extra_au and fix for Deployment level service account
Related https://github.com/astronomer/issues/issues/5128
Related https://github.com/astronomer/issues/issues/5006
QA can refer above issue tickets 

release-0.30 update astro ui image

---

charts/alertmanager/templates/alertmanager-networkpolicy.yaml
charts/astronomer/templates/astro-ui/astro-ui-networkpolicy.yaml
charts/astronomer/templates/cli-install/cli-install-networkpolicy.yaml
charts/astronomer/templates/commander/commander-networkpolicy.yaml
charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
charts/astronomer/templates/houston/worker/houston-worker-networkpolicy.yaml
charts/astronomer/templates/registry/registry-networkpolicy.yaml
charts/elasticsearch/templates/client/es-client-networkpolicy.yaml
charts/elasticsearch/templates/data/es-data-networkpolicy.yaml
charts/elasticsearch/templates/exporter/es-exporter-networkpolicy.yaml
charts/elasticsearch/templates/master/es-master-networkpolicy.yaml
charts/elasticsearch/templates/nginx/nginx-es-ingress-networkpolicy.yaml
charts/fluentd/templates/fluentd-networkpolicy.yaml
charts/grafana/templates/grafana-networkpolicy.yaml
charts/kibana/templates/kibana-networkpolicy.yaml
charts/kube-state/templates/kube-state-networkpolicy.yaml
charts/nats/templates/networkpolicy.yaml
charts/nginx/templates/nginx-default-backend-networkpolicy.yaml
charts/nginx/templates/nginx-metrics-networkpolicy.yaml
charts/nginx/templates/nginx-networkpolicy.yaml
charts/nginx/templates/nginx-service.yaml
charts/postgresql/templates/networkpolicy.yaml
charts/prometheus/templates/prometheus-networkpolicy.yaml
charts/stan/templates/stan-networkpolicy.yaml
tests/chart_tests/helm_template_generator.py
tests/chart_tests/test_global_network_policy_flag.py
tests/chart_tests/test_nginx_service.py

Fix schema validation by using strict schema. We ran into some networkPolicy errors that should have been caught by schema validation. Using strict caught them, and another error that existed in our chart.
While debugging the schema validation problem I also added a previously impossible test by adding headers to some templates. And while adding those headers, I lined up some header contents on some other files.
https://github.com/astronomer/issues/issues/5137
These are tests. I don't think any further testing needs to be done.
AFAIK these changes should be merged into all supported branches.

5137 fix schema validation

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Bump houston to get ford fix in
0.30.3

bumpHouston to 0.30.25

---

charts/astronomer/templates/_helpers.yaml
tests/chart_tests/test_houston_api_deployment.py

add a new env for houston to know its host
N/A
going to test in dev
release-0.31

add a new env for houston to know its host

---

.circleci/config.yml
charts/nginx/values.yaml

* bump ap-nginx:1.3.1 -> 1.3.1-1
https://github.com/astronomer/issues/issues/5174
NA
cherry-pick to release-0.29,0.30,0.31

update nginx image

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

fix SCIM bug 
https://github.com/astronomer/houston-api/pull/1333 
tested in dev 
release-0.31

bump rc2 and latests for houston, ui

---

.circleci/config.yml
charts/astronomer/values.yaml

fix task custom calender picker
https://github.com/astronomer/issues/issues/5210
local/dev
release-0.31

Bug task based calender

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Bump astronomer to 0.31.0-rc5, houston-api to 0.31.8, astro-ui to 0.31.6

0.31.5-rc5. also bump houston and astro ui

---

.circleci/config.yml
charts/astronomer/values.yaml

fix a houston permission issue for workspace admins
https://github.com/astronomer/issues/issues/5254
local/dev
0.31

bump houston from 0.31.8 to 0.31.9

---

Chart.yaml
charts/astronomer/Chart.yaml

version 0.31.0
N/A
Lots of testing was performed on this in rc phase. This is the same as rc7.
Merge only into release-0.31

version 0.31.0

---

.circleci/config.yml
.circleci/config.yml.j2
bin/trivy-scan.sh

Report the docker Image Scan Result to the vulnerability portal.
[issues/5293](https://github.com/astronomer/issues/issues/5293)
The changes were tested by sending data to the portal.
Changes need to merge to all major and minor releases.

Report Image Scan Result

---

.circleci/config.yml
charts/astronomer/values.yaml

ap-houston-api 0.31.12
N/A
This will be tested in the 0.31.1-rc cycle
Merge to release-0.31. I'm not sure about others though.

ap-houston-api 0.31.12

---

Chart.yaml
charts/astronomer/Chart.yaml

release rc2 for 0.30.5
NA
NA
NA

release rc2 for 0.30.5

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/elasticsearch/values.yaml
charts/grafana/values.yaml
charts/nats/values.yaml
charts/prometheus-blackbox-exporter/values.yaml
charts/stan/values.yaml

cherry-pick 3.16.3 image updates for resolving CVE fixes 
https://github.com/astronomer/issues/issues/5291
QA should validate all services works without any issues
merge to release-0.28.

fix conflict and update images

---

.circleci/config.yml
.circleci/generate_circleci_config.py
bin/kind/calico-crds-v1.26.yaml
tests/__init__.py

K8s 1.26 support for astronomer/astronomer
https://github.com/astronomer/issues/issues/5366

add k8s 1.26 support to astronomer

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

bump ap-astro-ui from 0.31.10 to 0.31.11
bump houston-api 
0.31.2

bumped astro-ui 0.31.11 for rc2

---

.circleci/config.yml
.circleci/config.yml.j2
bin/build-helm-chart.sh

In the effort of implementing QA Iterative Feature Testing, adding a workflow to release the helm chart with a datewise tag.
https://github.com/astronomer/issues/issues/5369
No testing requirements as it is a CI workflow update.
- release-0.31

Adding QA Helm Chart Release Workflow

---

.circleci/config.yml

Fixing CircleCI Config
N/A
Testing with passing build in CircleCI.
N/A

Fixing CircleCI Config

---

.pre-commit-config.yaml
requirements/chart-tests.txt
requirements/functional-tests.txt
tests/chart_tests/test_astronomer_houston_sidecar.py
tests/chart_tests/test_registry_statefulset.py
tests/chart_tests/test_svc.py

Bump pre-commit hooks and rebuild requirements.
N/A, regular maintenance.
No manual testing needed. If CI passes then we're good.

Bump pre-commit and requirements

---

.circleci/config.yml
.circleci/config.yml.j2
bin/install-ci-tools
bin/setup-circleci-shell-env.sh

Bump a bunch of dev component versions, including a security update in helm https://github.com/helm/helm/releases/tag/v3.11.1
N/A, regular maintenance
No manual testing needed. If CI passes we're good.

Bump dev component versions

---

.circleci/config.yml
.circleci/config.yml.j2
bin/trigger_rc_tests.py

Adding CircleCI Job extending workflow `build-and-release-helm-chart` to trigger `test_upgrade` workflow of `terraform-aws-astronomer` on RC build.
Issue: https://github.com/astronomer/issues/issues/5461
As this is the CircleCI Workflow, it can be tested as execution.
https://github.com/astronomer/astronomer/pull/1835

Adding CircleCI Job to trigger test_upgrade on RC build

---

.circleci/config.yml
.circleci/config.yml.j2

- Updating workflow `build-and-release-helm-chart` to trigger RC test.
- Adding workflow `qa-build-and-release-helm-chart`.
(cherry picked from commit e2da42de63c72365e4161685eabbf3a735e7fae1)
N/A
https://github.com/astronomer/astronomer/pull/1849

Improving QA Workflow (#1849)

---

.circleci/config.yml
.circleci/config.yml.j2

Adding missing dependency between jobs in CI.
- release-0.31

Adding missing CI dependency

---

.circleci/config.yml
charts/astronomer/values.yaml

- houston-api 0.32.3
- astro-ui 0.32.1
N/A
I have deployed these changes to an AWS cluster and they are working.
Merge only to release-0.32

houston, astro-ui updates for 0.32

---

.circleci/config.yml
charts/astronomer/values.yaml

- astro-ui 0.32.2
- houston-api 0.32.24
N/A, but slack thread about prep work for 0.32.0-rc1 is here: <https://astronomer.slack.com/archives/C04JELRC6J3/p1681505901801589?thread_ts=1681492861.192949&cid=C04JELRC6J3>
N/A
These are only meant for release-0.32

astro-ui 0.32.2, houston-api 0.32.24

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

0.32.0-beta1
N/A
N/A
This should only go into release-0.32 branch.

0.32.0-beta1

---

Chart.yaml
charts/astronomer/Chart.yaml

Bump astronomer chart from 0.32.0-beta1 -> 0.32.0-beta2
release-0.32

bump astronomer chart beta1 -> beta2

---

.circleci/config.yml
charts/external-es-proxy/values.yaml
values.yaml

* Resolves createContainerConfigError in openresty service
* Add appropriate resource values for elasticsearch nginx service
https://github.com/astronomer/issues/issues/5589
QA should able to run external es proxy service without any issues 
cherry-pick to release 0.32.

update openresty image and es nginx resource values

---

Chart.yaml
charts/astronomer/Chart.yaml

Update astronomer helm chart to 0.32.0
N/A
All testing has been performed. This is just the version bump.
Merge to release-0.32.0 only.

update chart version to 0.32.0

---

.circleci/config.yml
charts/astronomer/values.yaml

Houston api 0.30.34 -> 0.30.35
Astro-ui 0.30.12 -> 0.30.13
0.30.7

Bump houston, astro-ui for 0.30.7-rc

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

cut rc1 for release-0.30 with version 0.30.7
NA
NA
merging to release-0.30

0.30.7 release rc1 patch

---

charts/prometheus/templates/prometheus-config-configmap.yaml
tests/chart_tests/test_prometheus_config_configmap.py

When manualNamespaceNames is enabled, attach labels the same was as done for pre-created-ns
https://github.com/astronomer/issues/issues/4650
Locally
0.32.1
0.30.7

When manualNamespaceNames is enabled, attach labels the same was as done for pre-created-ns

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

v0.30.7rc6 - bump houston version for graphql subscriptions testing

---

.circleci/config.yml
charts/astronomer/values.yaml

includes airflow chart general enhancements
https://github.com/astronomer/issues/issues/5640
QA should able to deploy airflow instances without any issues

airflow-chart 1.8.5, commander 0.32.4

---

.circleci/config.yml
charts/nginx/values.yaml

* resolves CVE-2023-27561 
https://github.com/astronomer/issues/issues/5644
QA should able to access app URL without any issues

nginx ingress controller 1.7.1

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/grafana/values.yaml
charts/postgresql/values.yaml
charts/prometheus/values.yaml

| ap-configmap-reloader |0.8.0 | 0.11.0 |
|ap-db-bootstrapper | 0.31.2 | 0.31.3 | 
| ap-postgresql | 15.2.0-1 | 15.2.0-3|
https://github.com/astronomer/issues/issues/5649

update vendor packages

---

.circleci/config.yml
charts/astronomer/values.yaml

ap-houston-api: 0.32.11 -> 0.32.13
tested locally 
0.32

bump houston from 0.32.11 to 0.32.13

---

.circleci/config.yml
.circleci/config.yml.j2
bin/trivy-scan.sh

We are moving towards a different approach (Sigma Dashboard) for tracing the vulnerabilities. Updating Vulnerabilities Reporting is optional to AstroSec.
No testing requires as it is a CI flow change.
- release-0.30
- release-0.31
- release-0.32

Updating Vulnerabilities Reporting To Optional 

---

Chart.yaml
charts/astronomer/Chart.yaml

0.32.1-rc3 -> 0.32.1-rc4
tested locally
0.32

release rc4

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander and airflowchart version
https://github.com/astronomer/issues/issues/5665
QA should able to deploy airflow without any issues

update commander and airflow chart

---

Chart.yaml
charts/astronomer/Chart.yaml

version: 0.32.1-rc4 -> 0.32.1
tested locally
0.32

update release version from 0.32.1-rc4 to 0.32.1

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml
charts/nginx/templates/nginx-configmap.yaml

This PR fixes two problems:
- handle empty URL parameter values in nginx
- Revert changes in houston RBAC
- https://github.com/astronomer/issues/issues/5684
- https://github.com/astronomer/issues/issues/5683
The nginx changes have been extensively tested. The RBAC changes are a reversion to older behaviors and have been run in prod before.
This change set should only go to release-0.32 branch. The houston change will still need to be made elsewhere though.

version 0.32.2-rc1

---

.circleci/config.yml
charts/grafana/values.yaml

Upgrade from grafana 8 to grafana 10.
- https://github.com/astronomer/issues/issues/5707
I have done manual testing in dev and found no issues.
This should be merged to all supported branches.

grafana 10.0.1

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Add rc tag for 0.33 release 
ap-astro-ui:0.32.6 -> ap-astro-ui:0.33.1
ap-houston-api:0.32.15 -> ap-houston-api:0.33.1
NA
NA
NA

add 0.33 rc tag

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Add rc tag for 0.33 rc3 release 
ap-astro-ui: 0.33.1-> ap-astro-ui:0.33.2
ap-houston-api: 0.33.1 -> ap-houston-api:0.33.2
NA
NA
NA

update cluster to rc3

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Add rc tag for 0.33 rc4 release 
ap-astro-ui: 0.33.2-> ap-astro-ui:0.33.3
ap-houston-api: 0.33.2-> ap-houston-api:0.33.3
NA
NA
NA

update 0.33.0-rc4 release

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Add rc tag for 0.33 rc5 release 
ap-houston-api: 0.33.3-> ap-houston-api:0.33.4
NA
NA
NA

update 0.33.0-rc5 release

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

release 0.32.3-rc1 
ap-houston-api: 0.32.18 ->  0.32.19
included with all CVE fixes, newer features
NA

release  0.32.3-rc1

---

.circleci/config.yml
charts/astronomer/values.yaml

astro ui enhancements 
Related https://github.com/astronomer/issues/issues/5712
Related https://github.com/astronomer/issues/issues/5725
Related https://github.com/astronomer/issues/issues/3954
Related https://github.com/astronomer/issues/issues/5731
Related https://github.com/astronomer/issues/issues/5734
QA should able to verify 

update astro-ui image 0.32.7

---

.circleci/config.yml
Chart.yaml

Bump to 0.32.3- rc2

---

.circleci/config.yml
charts/astronomer/values.yaml

Do not break login flow, if microsoft teams fetch api fails
Related https://github.com/astronomer/issues/issues/5766
NA

update houston-api 0.32.21

---

.circleci/config.yml
charts/astronomer/values.yaml

Changed scimEnabled logic based on https://github.com/astronomer/issues/issues/5744#issuecomment-1695566260
Related https://github.com/astronomer/issues/issues/5744
NA

update houston api

---

Chart.yaml
charts/astronomer/Chart.yaml

Bump chart to 0.32.3-rc3
Release-0.32

bump to 0.32.3-rc3

---

.circleci/config.yml
charts/astronomer/values.yaml

update houston and astro ui image
https://github.com/astronomer/issues/issues/5647
https://github.com/astronomer/issues/issues/3954
https://github.com/astronomer/issues/issues/5672
https://github.com/astronomer/issues/issues/5594
https://github.com/astronomer/issues/issues/5723
https://github.com/astronomer/issues/issues/5134
https://github.com/astronomer/issues/issues/5710
https://github.com/astronomer/issues/issues/5706
https://github.com/astronomer/issues/issues/5651
QA should validate above tagged issues

update astro-ui and houston-api

---

Chart.yaml
charts/astronomer/Chart.yaml

Internal release for 0.30.8 rc1
QA to test
0.30

release 0.30.8 rc1

---

Chart.yaml
charts/astronomer/Chart.yaml

0.33.0 final rc -> release 0.33.0-rc5
NA
NA

0.33 update release

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.30.8 rc2

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Update 
ap-houston-api: 0.30.38 --> 0.30.39
astronomer/issues/issues/5821
QA
0.30

update grpc package for protobufjs

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Update 
ap-houston-api: 0.30.39 --> 0.30.40
astronomer/issues/issues/5830
QA
0.30.8

Release 0.30.8 rc4

---

.circleci/config.yml
charts/astronomer/values.yaml

update airflow chart 1.7.11 
https://github.com/astronomer/issues/issues/5670
QA should able to deploy airflow chart 

update airflow chart version

---

.circleci/config.yml
charts/astronomer/values.yaml

houston improvements
https://github.com/astronomer/issues/issues/4809
https://github.com/astronomer/issues/issues/5844
https://github.com/astronomer/issues/issues/5691
https://github.com/astronomer/issues/issues/4460
https://github.com/astronomer/issues/issues/5830
https://github.com/astronomer/issues/issues/5736
https://github.com/astronomer/issues/issues/5771
https://github.com/astronomer/issues/issues/5760
https://github.com/astronomer/issues/issues/5746
https://github.com/astronomer/issues/issues/5429
https://github.com/astronomer/issues/issues/5249
https://github.com/astronomer/issues/issues/5769
https://github.com/astronomer/issues/issues/5744
https://github.com/astronomer/issues/issues/5723
https://github.com/astronomer/issues/issues/5134 …

update houston api version 0.33.5

---

.circleci/config.yml
charts/astronomer/values.yaml

update astro-ui service 0.33.4 
https://github.com/astronomer/issues/issues/5893
https://github.com/astronomer/issues/issues/5883
https://github.com/astronomer/astro-ui/issues/1604
https://github.com/astronomer/issues/issues/5801
QA should able to validate above linked issues

update astro-ui service 0.33.4

---

.circleci/config.yml
charts/elasticsearch/values.yaml
charts/fluentd/values.yaml
charts/kibana/values.yaml

| ap-base | 3.18.3 | 3.18.4 |
| ap-init | 3.18.3-1 | 3.18.4 |
| ap-fluentd | 1.16.2 | 1.16.2-1 | 
https://github.com/astronomer/issues/issues/5894
NA

Fix CVE-2023-4911 in vendor packages

---

Chart.yaml
charts/astronomer/Chart.yaml

preparing 0.33.1-rc1 release
NA
NA
cherry-pick to release-0.33 branch

prepare 0.33.1 rc release

---

.circleci/config.yml
charts/grafana/values.yaml
charts/postgresql/values.yaml

update grafana and postgresql services
| ap-grafana |10.0.2 | 10.0.8 |
| ap-postgresql | 15.2.0-3 | 15.4.0-1 |
https://github.com/astronomer/issues/issues/5894
https://github.com/astronomer/issues/issues/5851
QA should able to run incluster postgres and grafana service

upgrade grafana and postgresql packages

---

.circleci/config.yml
charts/astronomer/values.yaml

update houston api 0.33.6
https://github.com/astronomer/issues/issues/4460
https://github.com/astronomer/issues/issues/5736

update houston-api 0.33.6

---

Chart.yaml
charts/astronomer/Chart.yaml

preparing the release for rc2
NA
NA.

prepare 0.33.1-rc2

---

.circleci/config.yml
charts/astronomer/values.yaml

Log idp id token refer issue ticket for more details
https://github.com/astronomer/issues/issues/5907
QA should check linked issue for more details

houston-api 0.33.7 and astro-ui 0.33.5

---

Chart.yaml
charts/astronomer/Chart.yaml

prepare 0.33.1-rc3 with all changes to release to public
NA
NA
NA

prepare 0.33.1 rc3

---

Chart.yaml
charts/astronomer/Chart.yaml

This PR officially releases 0.33.1 to public use 
NA
NA

release astronomer  0.33.1 

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

-prepare release 0.32.4 rc1
-bump houston to 0.32.23
NA
NA

Prepare release 0.32.4 rc1

---

Chart.yaml
charts/astronomer/Chart.yaml

preparing 0.32.4 rc2 release
NA
NA
NA.

release 0.32.4 rc2

---

Chart.yaml
charts/astronomer/Chart.yaml

prepare 0.33.2 rc1

---

Chart.yaml
charts/astronomer/Chart.yaml

update 0.33.2 rc2 version

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/elasticsearch/values.yaml

update db-boostrapper and ap-base
https://github.com/astronomer/issues/issues/5988
NA

update db-bootstrapper and ap-base

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.33.2-rc3

---

.circleci/config.yml
charts/astronomer/values.yaml

update houston-api and astro-ui images
https://github.com/astronomer/issues/issues/4460
https://github.com/astronomer/issues/issues/5249
https://github.com/astronomer/issues/issues/5515
https://github.com/astronomer/issues/issues/5684
https://github.com/astronomer/issues/issues/5771
https://github.com/astronomer/issues/issues/5760
https://github.com/astronomer/issues/issues/5769
https://github.com/astronomer/issues/issues/5844
https://github.com/astronomer/issues/issues/5907
https://github.com/astronomer/issues/issues/5942
https://github.com/astronomer/issues/issues/5948
https://github.com/astronomer/issues/issues/5953
https://github.com/astronomer/issues/issues/5966
https://github.com/astronomer/issues/issues/5953
https://github.com/astronomer/issues/issues/5722 …

update houston and astro-ui images

---

Chart.yaml
charts/astronomer/Chart.yaml

Changes astronomer chart version for releasing 0.32.5 to public
https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.32.5
Tested and signed off by QA
https://astronomer.slack.com/archives/C04JELRC6J3/p1701898404806069
release-0.32

release 0.32.5 to public

---

charts/astronomer/templates/registry/registry-statefulset.yaml
tests/chart_tests/test_registry_statefulset.py

extend privateCA config option to registry service  
https://github.com/astronomer/issues/issues/5939
Yet to update
Yet to update

add privateCA config to registry service

---

Chart.yaml
charts/astronomer/Chart.yaml

Bump up to rc2

---

.circleci/config.yml
.pre-commit-config.yaml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Release 0.34 rc1
release-0.34.0 issues in QA lane as of now
0.34.0

Release 0.34 rc1

---

Chart.yaml
charts/astronomer/Chart.yaml

Release 0.33.3 publicly
Tested by QA
release-0.33

Release 0.33.3 publicly

---

templates/trust-private-ca-on-all-nodes/containerd-ca-update-script.yaml
templates/trust-private-ca-on-all-nodes/containerd-daemonset.yaml
templates/trust-private-ca-on-all-nodes/daemonset.yaml
tests/chart_tests/test_containerd_privateca.py
values.yaml

minor enhancements to containerd certs update
added new flag for containerd and dockerd certs update
https://github.com/astronomer/issues/issues/6022
update in the above ticket on testing this feature 
release-0.34

add support run both docker and containerd certs update

---

templates/trust-private-ca-on-all-nodes/containerd-ca-update-script.yaml

* optimize the script
* remove containerd daemon restart when containerd config has config_path set
* remove unnecessary code
https://github.com/astronomer/issues/issues/6022
updated on issue ticket

fix containerd host config path

---

.circleci/config.yml
charts/astronomer/values.yaml

update houston api version 0.34.1
NA
NA

update houston api version

---

values.yaml

update dag-deploy 0.3.1 -> 0.3.2
https://github.com/astronomer/issues/issues/5969
QA can refer above ticket

update dag server image version 0.3.2

---

.circleci/config.yml
charts/astronomer/values.yaml

update airflow chart version 1.10.0
update commander image 0.34.0
https://github.com/astronomer/issues/issues/5969
refer ticket

release airflow version 1.10.0

---

.circleci/config.yml
charts/astronomer/values.yaml

update astro-ui image with tag 0.34.1
Related https://github.com/astronomer/issues/issues/6105
Related https://github.com/astronomer/issues/issues/6088
Related https://github.com/astronomer/issues/issues/6087
Related https://github.com/astronomer/issues/issues/6086
Related https://github.com/astronomer/issues/issues/6082
Related https://github.com/astronomer/issues/issues/6066
Related https://github.com/astronomer/issues/issues/6057
Related https://github.com/astronomer/issues/issues/5990 
refer above tickets

update astro-ui image with tag 0.34.1

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.34.0 rc2

---

charts/alertmanager/templates/alertmanager-statefulset.yaml
charts/astronomer/templates/houston/houston-configmap.yaml
charts/grafana/templates/grafana-deployment.yaml
charts/kibana/templates/kibana-deployment.yaml
charts/prometheus/templates/prometheus-statefulset.yaml
templates/_helpers.tpl

Add private registry support for authsidecar for platform and airflow components
https://github.com/astronomer/issues/issues/6113
when private registry is configured no action required by customer to manually update the values 

update private registry for authsidecar

---

.circleci/config.yml
charts/astronomer/values.yaml

Bump astro-ui 0.34.2 houston-api 0.34.4
Related https://github.com/astronomer/issues/issues/6146
Related https://github.com/astronomer/issues/issues/6131
Related https://github.com/astronomer/issues/issues/6144
Related https://github.com/astronomer/issues/issues/6138
Related https://github.com/astronomer/issues/issues/6139
QA should validate above tagged issues
cherry-pick to master and release

Bump astro-ui 0.34.2 houston-api 0.34.4

---

templates/_helpers.tpl
templates/trust-private-ca-on-all-nodes/containerd-daemonset.yaml
templates/trust-private-ca-on-all-nodes/daemonset.yaml
tests/enable_all_features.yaml
values.yaml

remove private registry enhancements and imagepull secrets fixes for certCopier service
https://github.com/astronomer/issues/issues/6102
NA
NA

revoke private registry enhancements

---

Chart.yaml
charts/astronomer/Chart.yaml

Bump astronomer helm chart to 0.34.0-rc3 for internal QA
release-0.34

bump chart to 0.34.0-rc3

---

charts/astronomer/templates/houston/helm-hooks/houston-au-strategy-job.yaml

Add default env values  to houston au strategy job 
Related https://github.com/astronomer/issues/issues/6152
QA should able to verify resource strategy switch 
cherry-pick to release-0.34 and master

add env values to houston au strategy job

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.34.0 version
NA
NA
NA

release 0.34.0 version

---

bin/helpers.sh
bin/run-ci
bin/waitfor-platform

We've had CI failures lately that have been hard to debug. This PR tweaks some code to make it easier to debug CI failures by just looking at the logs.
- astronomer/issues#6136
No manual testing needed, CI passing is enough.
Merge everywhere

Improve CI logging

---

charts/kibana/templates/_helpers.tpl
charts/kibana/templates/kibana-deployment.yaml
charts/prometheus/templates/_helpers.yaml
charts/prometheus/templates/prometheus-statefulset.yaml

remove openshift scc changes
NA
NA
merge to release-0.32

remove openshift changes backmerged

---

.circleci/config.yml
charts/astronomer/values.yaml

Update commander 0.32.11
https://github.com/astronomer/issues/issues/6159
regular testing is fine
cherry-pick to release 0.32

commander 0.32.11 

---

Chart.yaml
charts/astronomer/Chart.yaml

prepare 0.32.6-rc1 build for release-0.32
NA
NA
NA

generating 0.32.6-rc1 build 

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.32.6 rc2

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.32.6

---

charts/kibana/templates/kibana-default-index-cronjob.yaml
charts/nats/templates/jetstream-job.yaml

exclude istio-proxy pod on common jobs
NA
NA
all valid release branches

exclude istio-proxy pod on common jobs

---

.circleci/config.yml
charts/astronomer/values.yaml

update astro-ui image version 0.34.4
NA
NA

update astro-ui image version 0.34.4

---

.circleci/config.yml
charts/astronomer/values.yaml

update houston-api image to 0.34.5
NA
NA

update houston-api image to 0.34.5

---

.circleci/config.yml
charts/kibana/values.yaml
charts/stan/values.yaml

update ap-init image 3.18.6-1
https://github.com/astronomer/issues/issues/6227
QA basic validation is good to go

update ap-init image 3.18.6-1

---

.circleci/config.yml
charts/elasticsearch/values.yaml
values.yaml

update ap-base 3.18.6-1
NA
QA basic validation is fine 

update ap-base 3.18.6-1

---

charts/astronomer/templates/houston/worker/houston-worker-deployment.yaml
charts/astronomer/values.yaml

Add update-ca-certificates as default for worker
https://github.com/astronomer/issues/issues/6229
updated on ticket

update houston worker command args

---

Chart.yaml
charts/astronomer/Chart.yaml

Update release 0.34.1-rc1
N/A
N/A
0.34

Update release 0.34.1-rc1

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/grafana/values.yaml
charts/nats/values.yaml

|ap-db-bootstapper |0.31.11|0.31.12
NA

db-bootstapper 0.31.12 

---

.circleci/config.yml
charts/elasticsearch/values.yaml

curator 8.0.13

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander image 0.34.1
https://github.com/astronomer/issues/issues/6247
NA

update commander image 0.34.1

---

Chart.yaml
charts/astronomer/Chart.yaml

update release 0.34 rc3
NA
NA
NA

update release 0.34 rc3

---

.circleci/config.yml
.circleci/config.yml.j2

remove feature stack kind testing 
https://github.com/astronomer/issues/issues/6269
NA
cherry-pick to release branches

remove feature stack kind testing 

---

.circleci/config.yml
.circleci/config.yml.j2

update ci dependencies for qa stack
https://github.com/astronomer/issues/issues/6269
NA
cherry-pick to release branch

update ci dependencies for qa stack

---

.circleci/config.yml
charts/astronomer/values.yaml

update astro-ui image version 0.34.5
NA
NA

update to ap-astro-ui mage version 0.34.5

---

charts/astronomer/templates/houston/houston-configmap.yaml
tests/chart_tests/test_houston_configmap.py
values.yaml

add security context support for logging sidecar service
https://github.com/astronomer/issues/issues/6328
Yet to update
Yet to update

add security context support for logging sidecar service

---

.circleci/config.yml
charts/astronomer/templates/houston/houston-configmap.yaml
charts/astronomer/values.yaml
tests/chart_tests/test_authsidecar.py
tests/chart_tests/test_houston_configmap.py
values.yaml

Add's security context support for logging sidecar and authsidecar configuration
https://github.com/astronomer/issues/issues/6328
QA can refer test cases in issue list
merge to release-0.34

add sidecar components security context improvements

---

.circleci/config.yml
charts/astronomer/values.yaml

bug fixes and enhancements to api
https://github.com/astronomer/issues/issues/6308
https://github.com/astronomer/issues/issues/6367
https://github.com/astronomer/issues/issues/6358
check for issue tickets
merge to release-0.34

update houston api version 0.34.8

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander and airflow chart version 1.10.1
https://github.com/astronomer/issues/issues/6379
https://github.com/astronomer/issues/issues/6141

commander 0.34.2, airflow-chart 1.10.1

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Minor enhancements and airflow chart improvements
https://github.com/astronomer/issues/issues/6123
https://github.com/astronomer/issues/issues/6141
https://github.com/astronomer/issues/issues/6325
https://github.com/astronomer/issues/issues/6328
https://github.com/astronomer/issues/issues/6381
refer above issue tickets

update platform images and rc2 tags

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

CVE fixes and other minor enhancements
https://github.com/astronomer/issues/issues/6387
https://github.com/astronomer/issues/issues/6385
QA should able to verify email templates without any breaks

update houston api and release rc tag

---

Chart.yaml
charts/astronomer/Chart.yaml

version 0.34.2

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/grafana/values.yaml
charts/nats/values.yaml
values.yaml

releasing new platform images
https://github.com/astronomer/issues/issues/5292
https://github.com/astronomer/issues/issues/6423
NA

update latest platform images

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.35.0 rc1

---

Chart.yaml
charts/astronomer/Chart.yaml

update astronomer chart version 0.35.0-rc2
NA
NA

update astronomer chart version 0.35.0-rc2

---

.circleci/config.yml
charts/astronomer/values.yaml

Related https://github.com/astronomer/issues/issues/6450
Related https://github.com/astronomer/issues/issues/6446
Related https://github.com/astronomer/issues/issues/6414
Related https://github.com/astronomer/issues/issues/6429
Related https://github.com/astronomer/issues/issues/6418
Related https://github.com/astronomer/issues/issues/6420
Related https://github.com/astronomer/issues/issues/6445
Related https://github.com/astronomer/issues/issues/6216
Related https://github.com/astronomer/issues/issues/6432
Related https://github.com/astronomer/issues/issues/6442
Related https://github.com/astronomer/issues/issues/6428
Related https://github.com/astronomer/issues/issues/6420
Refer linked tickets 
cherry-pick to …

update houston api version 0.35.3

---

.circleci/config.yml
.pre-commit-config.yaml
bin/generate_circleci_config.py
bin/install-ci-tools
bin/kind/calico-crds-v1.25.yaml
bin/kind/calico-crds-v1.26.yaml
bin/kind/calico-crds-v1.27.yaml
bin/kind/calico-crds-v1.28.yaml
bin/kind/calico-crds-v1.29.yaml
bin/setup-kind
requirements/chart-tests.txt
requirements/functional-tests.txt

Update dev workflow components and CI runner versions.
NA, regular maintenance that only affects dev workflows and CI.
Not needed. If CI tests pass that is fine.

Dev workflow updates

---

Chart.yaml
charts/astronomer/Chart.yaml

update astronomer chart version 0.35.0-rc3
NA
NA
NA

update astronomer chart version 0.35.0-rc3

---

Chart.yaml
charts/astronomer/Chart.yaml

0.35.0-rc4
N/A release work
Version bump, no testing needed.
Merge into release-0.35

0.35.0-rc4

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

0.35.0-rc5
update astro ui image
| Header | Header | Header |
| quay.io/astronomer/ap-astro-uii | 0.35.2 | 0.35.3 |
Related astronomer/issues#6463
N/A
0.35

0.35.0-rc5

---

Chart.yaml
charts/astronomer/Chart.yaml

Version 0.35.0
N/A - release work
Lots of testing has been done on this release.
Merge only into release-0.35 branch.

version 0.35.0

---

charts/fluentd/templates/fluentd-daemonset.yaml
charts/fluentd/values.yaml
tests/chart_tests/test_fluentd.py

add extraEnv support for fluentd
https://github.com/astronomer/issues/issues/6465
Yet to update
cherry-pick to release-0.34,release-0.35

add extraEnv support for fluentd

---

charts/nginx/templates/nginx-deployment.yaml
charts/nginx/values.yaml
tests/chart_tests/test_nginx_service.py

add more nginx ingress configuration features
Related astronomer/issues#6389
QA effort not required

add more nginx ingress configuration features

---

.circleci/config.yml
charts/astronomer/values.yaml

update airflow chart version 1.11.2 and commander version 0.35.4
https://github.com/astronomer/issues/issues/6305
https://github.com/astronomer/issues/issues/6462

airflow-chart 1.11.2, commander 0.35.3

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander 0.35.5 and helm chart version 1.11.3
https://github.com/astronomer/issues/issues/6459
https://github.com/astronomer/issues/issues/6436
refer ticket

update commander and helm chart version

---

charts/astronomer/templates/commander/commander-deployment.yaml
values.yaml

remove tiller related configuration from helm chart which is no longer used
https://github.com/astronomer/issues/issues/6155
NA

remove tiller config from helm chart

---

charts/astronomer/templates/commander/commander-deployment.yaml
tests/chart_tests/test_astronomer_commander.py

enhance commander template with common shipped flags
https://github.com/astronomer/issues/issues/6389

enhance commander template with common shipped flags

---

values.yaml

update dag server version 0.5.0
https://github.com/astronomer/issues/issues/6487
https://github.com/astronomer/issues/issues/6506
cherry-pick release-0.35,release-0.36

update dag server version 0.5.0

---

.circleci/config.yml
charts/astronomer/values.yaml

update astro-ui 0.35.4
Related https://github.com/astronomer/issues/issues/6455
cherr-pick to release-0.35

update astro-ui 0.35.4

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.35.2-rc1

---

values.yaml

dag-deploy 0.5.1
- https://github.com/astronomer/issues/issues/6522
- https://github.com/astronomer/dag-deploy/pull/31
Needs lots of rollback testing.
Merge to 0.35, 0.36

dag-deploy 0.5.1

---

charts/fluentd/templates/fluentd-configmap.yaml

add dag server component in fluentd
https://github.com/astronomer/issues/issues/6523
refer issue ticket for more details
cherry-pick to release-0.36 , release-0.35

add dag server component in fluentd

---

.circleci/config.yml
charts/astronomer/values.yaml

astro-ui 0.35.7 fixes a date range bug.
- https://github.com/astronomer/astro-ui/pull/1791
- https://github.com/astronomer/issues/issues/6455
Testing would be great. More tests for the astro-ui change are coming in https://github.com/astronomer/issues/issues/6528
Merge to 0.35, 0.36

astro-ui 0.35.7

---

.circleci/config.yml
charts/astronomer/values.yaml

update astro-ui 0.35.8
Related https://github.com/astronomer/issues/issues/6526
Related https://github.com/astronomer/issues/issues/6531
Related https://github.com/astronomer/issues/issues/6455
refer issue tickets 
cherry-pick to release-0.35. master

update astro-ui 0.35.8

---

Chart.yaml
charts/astronomer/Chart.yaml

update release 0.35.2 rc4
NA
NA
NA

update release 0.35.2 rc4

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.32.2 rc5

---

.circleci/config.yml
charts/astronomer/values.yaml

update houston api 0.35.11
https://github.com/astronomer/issues/issues/6531
NA
cherry-pick to master, release-0.35

houston-api 0.35.11

---

Chart.yaml
charts/astronomer/Chart.yaml

release-0.35.2-rc6  

---

CODEOWNERS

Widen who can approve PRs in this repo, otherwise we'll only have three people who can approve any changes, or two people if somebody in the list is the one making the PR.
- Old team: https://github.com/orgs/astronomer/teams/maintainers-astronomer/members
- New team: https://github.com/orgs/astronomer/teams/astronomer-software/members
https://github.com/astronomer/issues/issues/6507
Not needed
No merging needed, only the default branch CODEOWNERS matters. We can merge anywhere if we want to though.

Allow approvals from anybody in @astronomer/astronomer-software

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander 0.36.3 and airflow chart 1.11.5
https://github.com/astronomer/issues/issues/6401
https://github.com/astronomer/issues/issues/6547
https://github.com/astronomer/issues/issues/6523
https://github.com/astronomer/issues/issues/6401
NA

update commander 0.36.3 and airflow chart 1.11.5

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/nginx/values.yaml

| ap-auth-sidecar | 0.26.25 | 0.26.26 |
| ap-nginx-es | 0.28.26 | 0.28.27 |
https://github.com/astronomer/issues/issues/6634
NA

update default backend and cli install

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander api 0.35.7
https://github.com/astronomer/issues/issues/6401
https://github.com/astronomer/issues/issues/6560
https://github.com/astronomer/issues/issues/6319
regular QA flow 

update commander api 0.35.7

---

values.yaml

update dag server version 0.5.4
Related https://github.com/astronomer/issues/issues/6437
Related https://github.com/astronomer/issues/issues/6663
QA should able to pass description the api
cherry-pick to release-0.36,release-0.35

update dag server version 0.5.4

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.35.3-rc3

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.35.4-rc1
NA
NA
merging to release-0.35 branch

release 0.35.4-rc1

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml
tests/chart_tests/test_astronomer_houston_hook_job.py
values.yaml

Update platform image versions
| astro-ui | 0.34.5 | 0.34.7 |
| commander | 0.34.4 | 0.34.5 |
| houston-api | 0.34.11 | 0.34.14 |
NA
Need to be tested by QA
0.34.4

Updated the houston and UI tags and released rc1

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Updated houston api, astro ui tag and released rc2
To be tested by QA
0.35

Updated houston api, astro ui tag and released rc2

---

values.yaml

Improvements to dag server debug modes
https://github.com/astronomer/issues/issues/6696
refer above ticket
cherry-pick to release-0.35, release-0.36

update dag server version 0.6.2

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml
templates/trust-private-ca-on-all-nodes/containerd-daemonset.yaml
tests/chart_tests/test_containerd_privateca.py
values.yaml

Updated houston api tag and released rc2
To be tested by QA
0.34

0.34.4-rc2 with component version bumps

---

Chart.yaml
charts/astronomer/Chart.yaml

Change 0.35.4-rc2 to 0.35.4 for release to public
[List of issues](https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.35.4+is%3Aclosed)

Release to public 0.35.4

---

Chart.yaml
charts/astronomer/Chart.yaml

Update chart from 0.34.4-rc2 to 0.34.4 for public release
[List of issues](https://github.com/astronomer/issues/issues?q=is%3Aissue+label%3A0.34.4+is%3Aclosed)

update chart to 0.34.4

---

charts/astronomer/templates/config-syncer/config-syncer-cronjob.yaml
charts/astronomer/templates/houston/cronjobs/houston-check-airflow-version-updates-cronjob.yaml
charts/astronomer/templates/houston/cronjobs/houston-check-runtime-updates.yaml
charts/astronomer/templates/houston/cronjobs/houston-check-updates-cronjob.yaml
charts/astronomer/templates/houston/cronjobs/houston-cleanup-airflow-db-cronjob.yaml
charts/astronomer/templates/houston/cronjobs/houston-cleanup-deploy-revisions-cronjob.yaml
charts/astronomer/templates/houston/cronjobs/houston-cleanup-deployments-cronjob.yaml
charts/astronomer/templates/houston/cronjobs/houston-cleanup-task-data-cronjob.yaml
charts/astronomer/templates/houston/cronjobs/houston-populate-daily-task-metrics.yaml
charts/astronomer/templates/houston/cronjobs/houston-populate-hourly-ta-metrics.yaml
charts/astronomer/templates/houston/helm-hooks/houston-db-migration-job.yaml
charts/astronomer/templates/houston/helm-hooks/houston-upgrade-deployments-job.yaml
charts/astronomer/values.yaml
charts/elasticsearch/templates/curator/es-curator-cronjob.yaml
charts/elasticsearch/values.yaml
charts/nats/templates/jetstream-job.yaml
tests/chart_tests/test_astronomer_config_syncer.py
tests/chart_tests/test_check_platform_updates.py
tests/chart_tests/test_container_resources.py
tests/chart_tests/test_cronjob_check_airflow_updates.py
tests/chart_tests/test_cronjob_check_runtime_updates.py
tests/chart_tests/test_resources.py
tests/enable_all_features.yaml

Add missing resources definition for astronomer components
https://github.com/astronomer/issues/issues/6615
QA should able to pass resources to above referenced commented services
cherry-pick to master, release-0.36

Add missing resources definition for astronomer components

---

.circleci/config.yml
charts/nginx/values.yaml
tests/functional_tests/test_config.py

run ingress-nginx with no capabilities
https://github.com/astronomer/issues/issues/6622
QA should see ingress controller comes up with no issues

run ingress-nginx with no capabilities

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/grafana/values.yaml
charts/nats/values.yaml

This PR intends to update images to 0.36.0 for ap-houston-api, ap-astro-ui and ap-db-bootstrapper. 
Na, part of release
NA
NA

updating images to 0.36 version

---

Chart.yaml
charts/astronomer/Chart.yaml

This PR intends to release version:  0.36.0-rc1
NA 
NA
0.36

Releasing version:  0.36.0-rc1

---

Chart.yaml
charts/astronomer/Chart.yaml

This PR intends to update version to 0.36.0-rc2
NA
NA
NA

version update to rc2

---

.circleci/config.yml
charts/astronomer/values.yaml

This PR intends to update new airflow version 1.11.7 to release 0.35
- astronomer/issues#6401
- astronomer/issues#6547
- astronomer/issues#6523
- astronomer/issues#6401
- astronomer/issues#6518
- astronomer/issues#6459
- astronomer/issues#6436	
-  astronomer/issues#6479
- astronomer/issues#6620
NA
NA

Update airflow version in 0.35 release

---

charts/grafana/templates/_helpers.yaml
charts/grafana/values.yaml
tests/chart_tests/test_byo_sa.py

Add support for grafana service account chart overrides 
- https://github.com/astronomer/issues/issues/6736
Yet to update

update grafana service account 

---

.circleci/config.yml
charts/astronomer/values.yaml

This PR intends to update images of astronomer components
Airflow Chart Changes
- https://github.com/astronomer/issues/issues/6729
-https://github.com/astronomer/issues/issues/6650
- https://github.com/astronomer/issues/issues/6593
- https://github.com/astronomer/issues/issues/6594
- https://github.com/astronomer/issues/issues/6729
Houston Api Changes
- https://github.com/astronomer/issues/issues/6729
QA should verify above mapped issues
merge to master and cherry-pick to release-0.36

update platform components and airflow chart 

---

Chart.yaml
charts/astronomer/Chart.yaml

This PR intends to upgrade to 0.36.0RC4
1. https://github.com/astronomer/issues/issues/6749
2. https://github.com/astronomer/issues/issues/6537
3. https://github.com/astronomer/issues/issues/6742
NA
0.36

Releasing rc4

---

.circleci/config.yml
charts/astronomer/values.yaml

airflow-chart version 1.13.5
https://github.com/astronomer/issues/issues/6761
Check pgbouncer-exporter metrics to make sure they work.
Merge anywhere we're using airflowChartVersion 1.13

airflow-chart 1.13.5

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Updated houston tag and released rc6

Updated houston tag and released rc6

---

Chart.yaml
charts/astronomer/Chart.yaml
charts/nginx/templates/nginx-headers-configmap.yaml

Fix issue with GraphQL playground and Altair IDE rendering with errors
https://github.com/astronomer/issues/issues/6765)
astronomer/astronomer/pull/2405
N/A
0.36

Release 0.36 rc8

---

charts/nginx/templates/nginx-headers-configmap.yaml
charts/nginx/values.yaml

This PR allows external src to allow conditionally with astronomer platform  
- https://github.com/astronomer/issues/issues/6749
- https://github.com/astronomer/issues/issues/6709
QA should able to open the playground without any errors in webbrowser console logs by default

add conditional csp flag

---

.circleci/config.yml
charts/prometheus/values.yaml

update prometheus 2.53.3
NA
NA
cherry-pick to all releases

update prometheus 2.53.3

---

.circleci/config.yml
values.yaml

update vector 0.42.0
https://github.com/astronomer/issues/issues/6474
Regular testing on vector changes

update vector 0.42.0

---

.circleci/config.yml
charts/elasticsearch/values.yaml
charts/external-es-proxy/values.yaml
charts/kibana/values.yaml
charts/nginx/values.yaml
charts/postgresql/values.yaml
charts/stan/values.yaml

| Header | Header | Header |
| quay.io/astronomer/ap-openresty | 1.25.3-2 | 1.27.1 |
| quay.io/astronomer/ap-init | 3.18.9 | 3.19.4 |
| quay.io/astronomer/ap-nginx | 1.11.2-1 | 1.11.3 |
| quay.io/astronomer/ap-postgresql | 15.8.0 | 15.9.0 |
- https://github.com/astronomer/issues/issues/6791
QA should able to verify if all components works as expected

update common vendor packages

---

.github/workflows/pr_checks.yml

Add a GH action that checks the PR description for:
- at least 20 characters
- Contains the string `astronomer/issues` OR has the label `ktlo`
- Does not contain the text `Do not merg e` (Deliberate typo to avoid triggering this check)
NA, KTLO work
I tested this a bunch in a test repo I created specifically for this.
This does not need to be merged anywhere outside master, but it wouldn't hurt if it goes into any other branches.

Add a GH action to check PR descriptions

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Created rc1 for 0.34.5
release-0.34

Created 0.34.5-rc1

---

Chart.yaml
charts/astronomer/Chart.yaml

release 0.34.5 rc2

---

charts/postgresql/templates/_helpers.tpl
charts/postgresql/templates/serviceaccount.yaml
charts/postgresql/templates/statefulset-slaves.yaml
charts/postgresql/templates/statefulset.yaml
charts/postgresql/values.yaml
tests/chart_tests/test_argo_sync-wave.py

fix postgresql service account tpl and config
- https://github.com/astronomer/issues/issues/6747
- https://github.com/astronomer/issues/issues/6805
QA should able to customize posgresql service account 

fix postgresql service account tpl and config

---

.circleci/config.yml
charts/pgbouncer/values.yaml

update pgbouncer krb 1.17.0-15
- https://github.com/astronomer/issues/issues/6810
NA

update pgbouncer krb 1.17.0-15

---

.circleci/config.yml
charts/postgresql/values.yaml

update postgresql version 15.10.0
- https://github.com/astronomer/issues/issues/6813
NA

update postgresql version 15.10.0

---

Chart.yaml
charts/astronomer/Chart.yaml

Public release - Updated the tag
Related astronomer/issues#XXXX

Public release - Updated the tag

---

charts/prometheus-blackbox-exporter/templates/deployment.yaml
charts/prometheus-blackbox-exporter/values.yaml

This is a generic enhancement in cleaning up old values which is no longer relevant
we already have tests covering these changes so if CI passes we are okay with this change
- https://github.com/astronomer/issues/issues/6821
QA generic testing is okay for validation 

fix blackbox exporter obsolete values

---

charts/nats/templates/jetstream-job-scc.yaml
templates/default-deny-network-policy/networkpolicy.yaml
templates/trust-private-ca-on-all-nodes/serviceaccount.yaml

generic conditional tpl fixes in astronomer chart
- https://github.com/astronomer/issues/issues/6821
Our existing tests covers this changes

generic conditional tpl fixes in astronomer chart

---

charts/prometheus/templates/prometheus-role.yaml
charts/prometheus/templates/prometheus-rolebinding.yaml

This PR aims to reduce the configuration used to configure prometheus cluster role and role binding
Yet to update
Yet to update

minimize the flags introduced to maintain prometheus cluster role

---

charts/prometheus/templates/prometheus-config-configmap.yaml
charts/prometheus/values.yaml
tests/chart_tests/test_prometheus_config_configmap.py

Add feature flag to disable/enable prometheus self scrape
- https://github.com/astronomer/issues/issues/6886
NA

add flag to disable prometheus self scrape

---

bin/release-bom

- Clean up a bunch of terrible ChatGPT code.
- Upload index.json.
- Parent ticket <https://github.com/astronomer/issues/issues/6907>
- Follow-up to <https://github.com/astronomer/astronomer-bom-generator/pull/15>
I have manually tested this by changing the `gsutil` lines to `echo`, and by removing some of the lines with required variables that I do not have on my system. I am fairly sure this will work. We'll have to wait until we release a new tag to be sure. We can always generate these boms by hand though, so merging this without 100% certainty that it works is not a big deal.

Clean up a bunch of terrible ChatGPT code. Upload index.json.

---

.circleci/config.yml
charts/elasticsearch/values.yaml
charts/external-es-proxy/values.yaml
charts/grafana/values.yaml
charts/postgresql/values.yaml
values.yaml

add updated vendor packages
| ap-auth-sidecar | 1.27.2 | 1.27.3 |
| ap-grafana | 10.4.14 | 10.4.15 |
| ap-nginx-es | 1.27.2 | 1.27.3 |
| ap-openresty | 1.27.1 | 1.27.1-1 |
| ap-postgresql | 15.0.0 | 15.0.0-1 | 
- https://github.com/astronomer/issues/issues/6830
General chart testing 
cherry-pick to all branches

add updated vendor packages

---

charts/airflow-operator/templates/_helpers.yaml
charts/airflow-operator/templates/manager/controller-manager-metrics-service.yaml
charts/airflow-operator/values.yaml
tests/chart_tests/test_airflow_operator.py

fix operator metrics port
- https://github.com/astronomer/issues/issues/7011
- https://github.com/astronomer/issues/issues/7012
QA should able to deploy depricated image version controlled by api and exclusion from af operator
NA

fix operator metrics port

---

charts/airflow-operator/templates/_helpers.yaml
charts/airflow-operator/values.yaml

This PR moves the image section to its own section to follow existing chart practises
- https://github.com/astronomer/issues/issues/7015
no QA testing involved

optimize operator chart with existing flow

---

charts/airflow-operator/templates/rbac/controller-manager-serviceaccount.yaml

rework operator sa templates
- https://github.com/astronomer/issues/issues/7015
NA

rework operator sa templates

---

.circleci/config.yml
charts/astronomer/values.yaml

update houston api 0.37.2 
- https://github.com/astronomer/issues/issues/7009
- https://github.com/astronomer/issues/issues/7010
- astronomer/issues#7014
- astronomer/issues#7018
test all mapped and release tagged issues 

update houston api 0.37.2

---

Chart.yaml
charts/astronomer/Chart.yaml

0.37.0-rc2
Dev work as part of 0.37.0.
- https://github.com/astronomer/issues/issues/6497
- https://github.com/astronomer/issues/issues/6680
- https://github.com/astronomer/issues/issues/6745
- https://github.com/astronomer/issues/issues/6747
- https://github.com/astronomer/issues/issues/6786
- https://github.com/astronomer/issues/issues/6789
- https://github.com/astronomer/issues/issues/6822
- https://github.com/astronomer/issues/issues/6828
- https://github.com/astronomer/issues/issues/6830
No testing needed.
Merge to master, check the diff between release-0.37 to ensure same content, and then recreate release-0.37 branch from master.

0.37.0-rc2

---

.circleci/config.yml
charts/astronomer/values.yaml

update platform images astro-ui and houston-api
- https://github.com/astronomer/issues/issues/7027
- https://github.com/astronomer/issues/issues/7017
- https://github.com/astronomer/issues/issues/7017
- https://github.com/astronomer/issues/issues/7023
- https://github.com/astronomer/issues/issues/7005
QA should validate above mapped issues 

update platform  images

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander version 0.37.3
- https://github.com/astronomer/issues/issues/7036
generic issue testing

update commander version 0.37.3

---

Chart.yaml
charts/astronomer/Chart.yaml

update astronomer chart version 0.37.0-rc3
NA, general ktlo work
NA
cherry-pick to master and release-0.37

update astronomer chart version 0.37.0-rc3

---

.circleci/config.yml
charts/astronomer/values.yaml

| ap-houston-api | 0.37.6 | 0.37.7 |
| ap-astro-ui | 0.37.2| 0.37.3 |
- Related https://github.com/astronomer/issues/issues/7049
- Related https://github.com/astronomer/issues/issues/7052
N/A
0.37

update houston api and astro-ui

---

charts/airflow-operator/values.yaml

follows same comment format every where
- Related https://github.com/astronomer/issues/issues/7043
NA

fix comments for webhook config 

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

update platform images and rc5  release
- https://github.com/astronomer/issues/issues/7056
QA should able to validate above mapped issues
cherry-pick to master and release-0.37

update platform images and rc5  release

---

Chart.yaml
charts/astronomer/Chart.yaml

Release 0.37.0 to public
List of issues
https://github.com/astronomer/issues/issues?q=is%3Aissue%20label%3A0.37.0%20
QA complete
release-0.37 branch

release 0.37.0 to public

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

This PR intends to release RC1 for QA
N/A
N/A
0.36

adding 36-rc1 tags

---

tests/chart_tests/test_houston_configmap.py

Add tests verifying that we can customize the images used by airflow-chart by changing values in the astronomer/astronomer chart.
The changes needed to solve https://github.com/astronomer/issues/issues/6180 was merged in https://github.com/astronomer/astronomer/pull/2490 but did not include tests that showed that customizing the astronomer/astronomer values worked as expected. These are those tests.
- <https://github.com/astronomer/issues/issues/6180>
- <https://github.com/astronomer/astronomer/pull/2490> is where the fixes were implemented, and it links to two other tickets.
These are tests, no application code is changed, so no further testing is needed.
This should go into 0.37 and 0.36. I have already verified that this works with 0.36.

Test customizability of airflow images

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml
charts/elasticsearch/values.yaml
values.yaml

This PR intends to release 0.36RC2
N/A
- N/A
- Releasing RC2
release-0.36

Releasing 0.36RC2

---

.circleci/config.yml
charts/elasticsearch/values.yaml
charts/kibana/values.yaml

update elastic packages to 8.15.5
NA, ktlo work
cherry-pick to master, release-0.36, release-0.37

update elastic packages to 8.15.5

---

.circleci/config.yml
charts/astronomer/values.yaml

update astro ui images 0.36.5
- Related astronomer/issues#7088

update astro ui images

---

.circleci/config.yml
charts/elasticsearch/values.yaml
charts/external-es-proxy/values.yaml
charts/nats/values.yaml
charts/stan/values.yaml
values.yaml

fix CVE-2025-27113
NA, ktlo
NA
cherry-pick to release-0.36, release-0.37 and master

fix CVE-2025-27113

---

values.yaml

Adds tiny as entrypoint loader to fix worker  termination issue
- https://github.com/astronomer/issues/issues/6714
QA should now see workers gets properly terminated
cherry-pick to master, release-0.36, release-0.37

update dag server version 0.6.5

---

Chart.yaml
charts/astronomer/Chart.yaml

add 0.36.1 rc4

---

charts/astronomer/templates/houston/houston-configmap.yaml
tests/chart_tests/test_houston_configmap.py
tests/chart_tests/test_scc.py

fix scc reuse bug with default values
- https://github.com/astronomer/issues/issues/7097
QA should see true false if sccEnabled by default else it will be defaults to false
merge to all releases

fix scc reuse bug with default values 

---

Chart.yaml
charts/astronomer/Chart.yaml

This PR public updates release 0.36.1 for astronomer helm chart 
NA, ktlo work
NA
NA

update 0.36.1 release

---

tests/k8s_schema/v1.32.0-standalone/namespace-v1.json
tests/k8s_schema/v1.32.0-standalone/storageclass-storage-v1.json

Two schema files used in tests were left out of #2515. This PR adds them.
- <https://github.com/astronomer/issues/issues/6882>
No testing or documentation needed. This is just a test run optimization.

Add 1.32 schema files that were missed in #2515

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander version 0.37.5
General Commander testing
merge to release-0.37 and master

update commander version 0.37.5

---

README.md

This pull request contains fixing the release notes link
Fix release notes link
Fix release notes link
Fix release notes link

Fix release notes link in README

---

.circleci/config.yml
charts/prometheus/values.yaml

update prometheus 2.53.4

---

.circleci/config.yml
charts/alertmanager/values.yaml
charts/astronomer/values.yaml
charts/elasticsearch/values.yaml
charts/external-es-proxy/values.yaml
charts/kibana/values.yaml
charts/nats/values.yaml
charts/pgbouncer/values.yaml
charts/prometheus-blackbox-exporter/values.yaml
charts/prometheus-postgres-exporter/values.yaml
charts/stan/values.yaml
values.yaml

update ap-base package updates 
Generic QA testing

update ap-base package updates 

---

.circleci/config.yml
charts/elasticsearch/values.yaml
charts/external-es-proxy/values.yaml
values.yaml

fix nginx webservice cve 
cherry-pick to release-0.37, release-0.36, master

fix nginx webservice cve 

---

Chart.yaml
charts/astronomer/Chart.yaml

update 0.37.1 rc1
NA, ktlo
NA
NA

update 0.37.1 rc1

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander version 0.37.6
- - https://github.com/astronomer/issues/issues/7122

update commander version 0.37.6

---

Chart.yaml
charts/astronomer/Chart.yaml

update release version 0.37.1-rc2
NA, ktlo work
NA, ktlo work
NA, ktlo work

update release version 0.37.1-rc2

---

.circleci/config.yml
charts/astronomer/values.yaml

update astro ui image 0.37.6
Related https://github.com/astronomer/issues/issues/7140
refer issue ticket 

update astro ui image 0.37.6

---

.circleci/config.yml
charts/astronomer/values.yaml

update platform and astro-ui
- Related https://github.com/astronomer/issues/issues/6572
- Related https://github.com/astronomer/issues/issues/7168
QA should verify above linked issues 

update platform and astro-ui

---

.circleci/config.yml
charts/astronomer/values.yaml

ap-commander:0.37.8
- <https://github.com/astronomer/issues/issues/6572>
Testing this change will be covered as part of release 0.37.1.
Merge only to release-0.37

ap-commander 0.37.8

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

update 0.37.1 rc3
ktlo work
Related astronomer/issues#7171
NA
NA

update 0.37.1 rc3

---

Chart.yaml
charts/astronomer/Chart.yaml

Bump version to 0.37.1-rc4
N/A, release related work
No testing needed, this is just the version bump.
Merge to master, cherry-pick to release-0.37.

0.37.1-rc4

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

PR intends to release 0.37.2-rc1
0.37

0.37.2 rc1

---

.circleci/config.yml
values.yaml

updated  ap-redis version  7.4.3
https://github.com/astronomer/issues/issues/7215
Generic QA testing 
cherry-picked into. release-0.37 release-0.36

 update ap-redis version 

---

Chart.yaml
charts/astronomer/Chart.yaml

add release 0.37.2 rc4

---

.circleci/config.yml
charts/astronomer/values.yaml

houston-api 0.37.21
- https://github.com/astronomer/issues/issues/7262
- https://github.com/astronomer/issues/issues/7238
Need to verify that the subPath behavior in shared_volume mode works as expected.
Only for 0.37

houston-api 0.37.21

---

.circleci/config.yml
charts/grafana/values.yaml
charts/nginx/values.yaml
charts/prometheus/values.yaml
values.yaml

This PR intends to update ap-vendor images for Astronomer Software images. 
N/A
N/A
0.37

Update ap-vendor images on astronomer platform

---

templates/trust-private-ca-on-all-nodes/containerd-daemonset.yaml
tests/chart_tests/test_probes_resources_serviceaccount.py

This PR adds comprehensive unit tests to validate that all pods and containers across the Astronomer platform meet the resource and serviceAccount requirements
- Validate ServiceAccount Configuration
- Validate Resource Configuration
- Platform Coverage
Related astronomer/issues#7294
Ran the test locally and it passes.
0.37.

Adding Comprehensive Unit Tests for Container Resources and ServiceAccount Configuration

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/elasticsearch/values.yaml
charts/fluentd/values.yaml
charts/kibana/values.yaml
charts/prometheus/values.yaml

This PR intends to add all new images for rc4
Related astronomer/issues#7315
0.37

fluentd and commander image update

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml
values.yaml

This PR intends to release 0.37.3 rc4 with latest changes.
0.37

Release 0.37.3 RC4

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
values.yaml

PR intends to release RC5 for 0.37.3 
https://github.com/astronomer/security-issues/issues/107
0.37

Releasing RC5

---

Chart.yaml
charts/astronomer/Chart.yaml

PR intends to release 0.37.3 
0.37

version 0.37.3

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

This PR releases 0.37.4-rc1
0.37

0.37.4-rc1 release

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

PR intends to release RC5
0.37

0.37.4-rc5

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

Add extraEnv vars support for cleanup airflow metadb feature
- https://github.com/astronomer/issues/issues/7423

Add extraEnv vars support for cleanup airflow metadb feature

---

charts/astronomer/templates/commander/commander-deployment.yaml
charts/astronomer/templates/commander/commander-metadata.yaml

This PR enhances the existing JWKS hook job with improved cleanup policies and flexible environment variable configuration support.
- Related astronomer/issues#7448
NA

Add default metadata and hook ordering

---

charts/astronomer/templates/registry-auth-secret.yaml
charts/astronomer/templates/registry/registry-statefulset.yaml

Generate unique secret has from the signed tls certificate
- https://github.com/astronomer/issues/issues/7534
refer issue ticket for testing notes

fix registry auth header secret hash

---

charts/prometheus/templates/prometheus-config-configmap.yaml

This PR adds some improvements that are required for Prometheus operation.
Related astronomer/issues#7505
- Prometheus testcases already exist, and ensured that the. unittests pass.
- Testing and will demo prometheus the k8s cluster. 
1.0

Add some fixes for Prometheus

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/templates/houston/cronjobs/houston-cleanup-deploy-revisions-cronjob.yaml
charts/astronomer/values.yaml
charts/grafana/values.yaml
charts/nats/values.yaml
charts/prometheus/templates/prometheus-statefulset.yaml
charts/prometheus/values.yaml
tests/chart_tests/test_prometheus_statefulset.py
values.yaml

This PR does the following:
- PR to release rc1
- Addresses duplicate security contexts present in houston cronjob cleanup pod
- Adds Variables needed by Prometheus Statefulset for kuiper latest release. 
- Updates Platform images for removing CVEs
- https://github.com/astronomer/issues/issues/7595
- https://github.com/astronomer/security-issues/issues/3195
- https://github.com/astronomer/security-issues/issues/4093
- https://github.com/astronomer/security-issues/issues/4198
- https://github.com/astronomer/security-issues/issues/4200
- https://github.com/astronomer/security-issues/issues/4202
release-0.37

0.37.5 rc1

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/templates/houston/houston-configmap.yaml
charts/astronomer/values.yaml
charts/elasticsearch/values.yaml
charts/nginx/values.yaml
charts/prometheus/values.yaml
tests/chart_tests/test_astronomer_dag_only_deploy.py
values.yaml

PR for releasing 0.37.5-rc2

---

.circleci/config.yml
.circleci/config.yml.j2
bin/setup-kind.py

Remove twistlock
- astronomer/issues#7618
No tests needed if CI passes.

Remove twistlock

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

fix broken invalid fields added on reuse fix
- https://github.com/astronomer/issues/issues/7526
- https://github.com/astronomer/issues/issues/7335
QA should able  to verify no reuse values are being added for nodeSelector, affinity and tolerations

update commander image version 0.37.24

---

.circleci/config.yml
charts/astronomer/values.yaml

Updates platform core api images
| Header | Header | Header |
| ap-astro-ui | 1.0.1 | 1.0.2 |
| ap-commander | 0.37.24 | 1.0.0 |
| ap-houston-api | 1.0.0 | 1.0.1 |
| airflowChartVersion | 1.15.7 | 1.17.0 | 
NA
NA

update platform core images

---

charts/astronomer/templates/ingress.yaml

Add control and unified condition for common ingress as it is not needed by data plane.
Related astronomer/issues#XXXX
- All Unittests work as expected. 
- 
1.0

add condition for common ingress

---

.circleci/config.yml
charts/astronomer/values.yaml

| ap-astro-ui | 1.0.2 | 1.0.3 |
| ap-commander | 1.0.0 | 1.0.1 |
| ap-houston-api | 1.0.1 | 1.0.2 |
NA
NA

update core images

---

charts/astronomer/templates/_helpers.yaml

This PR removes an extra '.' present in the dataplaneURL.
- https://github.com/astronomer/issues/issues/7722
N/A
master

Remove extra . from dataplane URL.

---

charts/astronomer/templates/_helpers.yaml

add namespace pools support in helm chart
- Related https://github.com/astronomer/issues/issues/7708
QA should able to validate namespace pools from commander meta endpoint

add namespace pools support in helm chart

---

.circleci/config.yml
charts/astronomer/values.yaml

add namespace pools support in commander  api
- Related https://github.com/astronomer/issues/issues/7708
QA should able to validate namespace pools from commander meta endpoint

update api images

---

.circleci/config.yml
charts/astronomer/values.yaml
charts/vector/templates/vector-clusterrole.yaml
charts/vector/templates/vector-clusterrolebinding.yaml
charts/vector/templates/vector-configmap.yaml
charts/vector/templates/vector-daemonset.yaml
charts/vector/templates/vector-networkpolicy.yaml
charts/vector/templates/vector-serviceaccount.yaml
tests/chart_tests/test_vector.py

Adding mode flags to vector log templates (#2826)

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

1.0 rc2 changes 
NA
NA
merge to release-1.0

1.0 rc2 changes 

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml

update api core images and release rc3 
NA
NA

update api core images and release rc3

---

charts/astronomer/templates/registry/registry-networkpolicy.yaml
charts/nginx/templates/controlplane/nginx-cp-networkpolicy.yaml
charts/nginx/templates/dataplane/nginx-dp-networkpolicy.yaml
charts/prometheus/templates/prometheus-networkpolicy.yaml

rework all network ingress policy config
- https://github.com/astronomer/issues/issues/7824
QA should able to provision astronomer chart with proper network policy in place

fix all network policy configurations

---

.circleci/config.yml
charts/astronomer/values.yaml

update apc api version 1.0.15
- https://github.com/astronomer/issues/issues/7771
QA should able to open airflow UI

update apc aka astro ui to 1.0.15

---

.circleci/config.yml
Chart.yaml
charts/astronomer/values.yaml

release apc 1.0 rc5
- https://github.com/astronomer/issues/issues/7888
- https://github.com/astronomer/issues/issues/7896
N/A
release-1.0

software-v1.0.0-rc4 with houston-v1.0.18 and ui-v1.0.16

---

charts/prometheus/templates/prometheus-federation-auth-deployment.yaml
charts/vector/templates/vector-daemonset.yaml

remove duplicate yaml keys from templates
- https://github.com/astronomer/issues/issues/7914
NA

remove duplicate yaml keys from templates

---

.circleci/config.yml
charts/astronomer/templates/_helpers.yaml
charts/astronomer/values.yaml
tests/chart_tests/test_astronomer_commander.py

update commander version 1.0.7
- https://github.com/astronomer/issues/issues/7915
No longer need to manage health status in helm chart

update commander version 1.0.7

---

charts/nginx/templates/controlplane/nginx-cp-networkpolicy.yaml
charts/nginx/templates/dataplane/nginx-dp-networkpolicy.yaml
tests/functional/unified/test_network_security.py

remove egress network policies and fix labels
- https://github.com/astronomer/issues/issues/7922
QA should able to access the astro cloud UI without issues

remove egress network policies and fix labels

---

charts/astronomer/templates/commander/commander-networkpolicy.yaml
charts/elasticsearch/templates/client/es-client-networkpolicy.yaml
charts/elasticsearch/templates/nginx/nginx-es-networkpolicy.yaml
charts/nginx/templates/dataplane/nginx-dp-networkpolicy.yaml
charts/prometheus/templates/prometheus-federate-networkpolicy.yaml
tests/chart_tests/test_elasticsearch.py
tests/chart_tests/test_tags.py

rework dataplane network policies to sync with control plane 
- https://github.com/astronomer/issues/issues/7926
QA should able to access the CP and DP ingress without any issues

fix network policies on dataplane mode

---

.circleci/config.yml
charts/astronomer/values.yaml

update commander and airflow chart version
https://github.com/astronomer/issues/issues/7955
https://github.com/astronomer/issues/issues/7952
QA should validate network policies 

update commander and airflow chart version

---

.circleci/config.yml
charts/astronomer/values.yaml

update houston api 1.0.23
- Related https://github.com/astronomer/issues/issues/7826
- Related https://github.com/astronomer/issues/issues/7952
Dag Processor fixes
Plane mode fixes 

update houston api 1.0.23

---

.circleci/config.yml
Chart.yaml
charts/astronomer/Chart.yaml
charts/astronomer/values.yaml
charts/nats/values.yaml
values.yaml

This PR is for APC rc5 release with 
- houston-api:1.0.25
- astro-ui:1.0.19
- https://github.com/astronomer/issues/issues/7283
- https://github.com/astronomer/issues/issues/7451
- https://github.com/astronomer/issues/issues/7607
- https://github.com/astronomer/issues/issues/7710
- https://github.com/astronomer/issues/issues/7771
- https://github.com/astronomer/issues/issues/7826
- https://github.com/astronomer/issues/issues/7831
- https://github.com/astronomer/issues/issues/7884
- https://github.com/astronomer/issues/issues/7897
- https://github.com/astronomer/issues/issues/7906
- https://github.com/astronomer/issues/issues/7917
- https://github.com/astronomer/issues/issues/7924
- https://github.com/astronomer/issues/issues/7937
- https://github.com/astronomer/issues/issues/7952
- …

1.0.0-rc5 release with houston-api:1.0.25, astro-ui:1.0.19, and more
