- charts/kube-state/templates/kube-state-deployment.yaml
- tests/chart_tests/test_kube_state_deployment.py
Fix a 3.5 year old bug with kube-state singleNamespace behavior. Hat tip to @cdabella for finding it and showing us the fix!
<https://github.com/astronomer/issues/issues/5083>
I created tests that caught the old error, fixed the error to make tests pass, and improved old test cases for when the flag is set to default.
This should be merged into all supported branches.
> Fix kube-state singleNamespaces bug

- .circleci/config.yml
- charts/fluentd/values.yaml
update fluentd package 1.15.1 -> 1.15.2
Release notes https://github.com/fluent/fluentd/releases/tag/v1.15.2
https://github.com/astronomer/issues/issues/5076
QA should verify if fluentd works as expected
cherry-pick to all supported release branches
> update fluentd image 1.15.1 -> 1.15.2

- .circleci/config.yml
- .circleci/trivyignore
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/kube-state/values.yaml
- charts/nats/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-node-exporter/values.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
- tests/chart_tests/test_prometheus_statefulset.py
- values.yaml
release 0.29 - backport changes
include CVE fixes and enhancements
Issue Link: https://github.com/astronomer/issues/issues/5050
Issue Link: https://github.com/astronomer/issues/issues/5065
Issue Link: https://github.com/astronomer/issues/issues/4981
https://github.com/astronomer/astronomer/commit/9b46dbb1b76eb8d142250cac54c57ff3c9ed5ea5
https://github.com/astronomer/astronomer/commit/ea2a67c9720ff0b2c7001f2052955a65b3d4b3b5
> Patch release 0.29.5 - backport changes

- .circleci/config.yml
- .circleci/config.yml.j2
revert back ubuntu-2204:2022.09.1  -> ubuntu-2204:2022.07.1. As per https://circleci.com/developer/machine/image/ubuntu-2204 vm image list
Issue Description:
Job was rejected because resource class medium, image ubuntu-2204:2022.09.1 is not a valid resource class
NA
merge to all valid release branches
> revert to valid circleci machine image

- .circleci/config.yml
- .circleci/trivyignore
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/kube-state/values.yaml
- charts/nats/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-node-exporter/values.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
- values.yaml
--    | --  | --
ap-registry |  3.16.2 | 3.16.2-1
ap-db-bootstrapper | 0.26.9 |  0.26.11
ap-elasticsearch | 7.17.5 | 7.17.6
ap-curator | 5.8.4-18 | 5.8.4-19
ap-base | 3.16.2  | 3.16.2-1
ap-kibana  | 7.17.5 | 7.17.6   
ap-awsesproxy | 1.3-4 | 1.3-8
ap-kube-state | 2.5.0 | 2.6.0
ap-nats-server | 2.8.1-2 | 2.8.1-3
ap-nats-exporter | 0.10.0 | 0.10.0-1
ap-blackbox-exporter | 0.21.1-2 | 0.22.0 
ap-node-exporter  | 1.3.1 | 1.4.0
ap-prometheus | 2.37.0 | 2.37.1
ap-nats-streaming | 0.24.5-2 | 0.24.5-3
ap-fluentd | 1.15.1 | 1.15.2
ap-commander | 0.28.6 | 0.28.7
ap-houston | 0.28.26  | 0.28.28
ap-astro-ui | 0.28.16 | 0.28.17
**additionalNotes**
updates airflowChartVersion 1.4.2 ->  1.4.3
https://github.com/astronomer/issues/issues/5065
Do not merge this PR until this text is …
> release-0.28 backport security fixes

- .circleci/config.yml
- charts/prometheus/values.yaml
bump 0.7.1 -> 0.8.0
Includes golang module cve fixes
https://github.com/astronomer/issues/issues/5097
QA should validate if configmap updates reflects in prometheus
cherry-pick to release-0.25,0.28,0.29,0.30.
> update prometheus configmap reloader

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-node-exporter/values.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
- tests/test_privateca.py
- values.yaml
--    | --  | --
ap-base | 3.16.2  | 3.16.2-1
ap-registry |  3.16.2 | 3.16.2-1
ap-db-bootstrapper | 0.26.9 |  0.26.11
ap-elasticsearch | 7.17.5 | 7.17.6
ap-kibana  | 7.17.5 | 7.17.6   
ap-curator | 5.8.4-18 | 5.8.4-19
ap-fluentd | 1.15.1 | 1.15.2
ap-nats-server | 2.8.1-2 | 2.8.1-3
ap-nats-exporter | 0.10.0 | 0.10.0-1
ap-blackbox-exporter | 0.21.1-2 | 0.22.0 
ap-node-exporter  | 1.2.2 | 1.4.0
ap-prometheus | 2.37.0 | 2.37.1
ap-nats-streaming | 0.24.5-1 | 0.24.5-3
ap-auth-sidecar | | 1.23.1-1
ap-configmap-reloader | 0.7.1 | 0.8.0
Additional Updates
replaced nginxinc/nginx-unprivileged:latest  -> quay.io/astronomer/ap-auth-sidecar:1.23.1-1
replaced alpine:3.14 -> alpine:3.16
replaced quay.io/prometheus/node-exporter:v1.2.2 -> quay.io/astronomer/ap-node-exporter:1.4.0 …
> release-0.25 backport security fixes 

- charts/astronomer/templates/houston/cronjobs/houston-cleanup-task-data-cronjob.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_houston_task_metrics.py
- values.yaml
This is a cronjob to hard delete task usage data in houston db older than 90 days
https://github.com/astronomer/issues/issues/5070
0.31.0
> Add houston-cleanup-task-usage-data CronJob

- .circleci/config.yml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/elasticsearch/values.yaml
- charts/fluentd/values.yaml
- charts/kibana/values.yaml
- charts/prometheus/templates/prometheus-alerts-configmap.yaml
- charts/prometheus/templates/prometheus-config-configmap.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_houston_configmap.py
- tests/chart_tests/test_prometheus_config_configmap.py
- tests/enable_all_features.yaml
- values.yaml
updates to vendor images
bump ap-config-reloader 0.7.1 -> 0.8.0
bump ap-elasticsearch 7.17.5 -> 7.17.6
bump ap-kibana 7.17.5 -> 7.17.6
bump ap-fluentd image 1.15.1 -> 1.15.2
Additionally Included:
namespaceFreeForm fixes 
Related to https://github.com/astronomer/issues/issues/5003 
Related to https://github.com/astronomer/issues/issues/5036
Related to https://github.com/astronomer/issues/issues/5061
Related to https://github.com/astronomer/issues/issues/5065
Related to https://github.com/astronomer/issues/issues/5066
Related to https://github.com/astronomer/issues/issues/5076
Related to https://github.com/astronomer/issues/issues/5097
cherrypicked to release-0.30 branch.
> release 0.30 backport changes

- .circleci/config.yml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_configmap.py
- values.yaml
Ability to add env vars to logging sidecars
https://github.com/astronomer/issues/issues/5106
https://github.com/astronomer/issues/issues/5095
QA should able to pass extra env to logging sidecar and should able to validate passed env in logging sidecar
cherry-picked to release-0.30
> backport loggingsidecar extra env

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/test_houston_configmap.py
Fixes issue with es logging.
New es library used has moved host param to node
- https://github.com/astronomer/issues/issues/5129
QA team should able to see logs in astro-ui
> fixes  an issue with es logging

- charts/astronomer/templates/houston/cronjobs/houston-populate-daily-task-data
- charts/astronomer/templates/houston/cronjobs/houston-populate-daily-task-metrics.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_houston_task_metrics.py
Cronjob to aggregate day-wise task usage metrics from houston's task data audit table to daily task usage aggregate table. This runs on a daily schedule
https://github.com/astronomer/issues/issues/5073
0.31.0
> cron to populate daily task metrics

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
- values.yaml
Allow loggingsidecar resource to override the default limits from astronomer platform 
https://github.com/astronomer/issues/issues/5029
QA should able to pass custom resources to logging sidecar and able to see them on logging deployments
cherry-pick to release-0.30.
> allows loggingsidecar resource overrides

- charts/elasticsearch/templates/es-configmap.yaml
This PR disables Elasticsearch built-in security features which are not used by astronomer. 
Additionally it suppresses the fluent warnings related to elastic build in security as well
https://github.com/astronomer/issues/issues/4400
QA should not see any warnings in fluend  similar to below
```
warning: 299 Elasticsearch-7.17.3-5ad023604c8d7416c9eb6c0eadb62b14e766caff "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."
warning: 299 Elasticsearch-7.17.3-5ad023604c8d7416c9eb6c0eadb62b14e766caff "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be …
```
> disable es security settings by default

- charts/astronomer/templates/commander/commander-networkpolicy.yaml
add cron job network policies for commander, two new cron jobs were unable to communicate with commander we forgot to add the network policies 
Related https://github.com/astronomer/issues/issues/5118
will be tested in dev
0.31
> add cron job network policies for commander

- charts/astronomer/templates/registry/registry-networkpolicy.yaml
add cron job network policies for registry, two new cron jobs were unable to communicate with registry we forgot to add the network policies 
Related https://github.com/astronomer/issues/issues/5118
will be tested in dev
0.31
> add cron jobs to registry network policy

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
* bump ap-astro-ui 0.30.6 -> 0.30.7
* bump ap-houston-api 0.30.22 -> 0.30.23
Related https://github.com/astronomer/issues/issues/4954
QA should able to override components defaults
cherry-pick to release-0.30 .
> release-0.30 backport  components fix for astro-ui and houston images

- .circleci/config.yml
- charts/astronomer/values.yaml
* bump ap-houston-api 0.30.23 -> 0.30.24
https://github.com/astronomer/issues/issues/5144
QA should able to customize runtime min airflow version and runtime version 
```
config:
deployments:
minAstroRuntimeVersion: 4.2.1
airflowMinimumAstroRuntimeVersion: 2.2.4
```     
cherry-pick to release-0.30 .
> release-0.30 ap-houston-api:0.30.24

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
bump ap-commander 0.30.4 -> 0.30.5
airflowChartVersion 1.7.0 -> 1.7.1
https://github.com/astronomer/issues/issues/5065
QA should able to deploy airflow and pgbouncer services should function normally
cherry-pick to release-0.30.
> update commander and airflow chart version

- charts/astronomer/templates/houston/cronjobs/houston-populate-daily-task-metrics.yaml
- charts/astronomer/templates/houston/cronjobs/houston-populate-hourly-task-audit-metrics.yaml
Stop multiple cron jobs of same time being added if one is stuck
N/A- just saw lots of stacked cronjobs in dev 
will test in dev
0.31
> dont allow concurrent jobs

- charts/astronomer/templates/_helpers.yaml
- tests/chart_tests/test_houston_api_deployment.py
Allow updates url for runtime and certified to be passed to env vars.
This resolves an issue where customer/user to add url separately as env vars to houston pods
https://github.com/astronomer/issues/issues/5127
> allow updates url to be added as env vars to houston

- charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
allow for houston-populate-hourly-task-audit-metrics to be able to talk to housotn
N/A
tested in dev
release-0.31
> allow cronjob to talk to houston

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_astronomer_houston_task_metrics.py
in this pr: https://github.com/astronomer/houston-api/pull/1319 
the way the flag was added was changed, so have to change code up in houston to reflect those changes
Related https://github.com/astronomer/issues/issues/5158
https://github.com/astronomer/houston-api/pull/1319
release-0.31
> refactor feature flags for task based pricing

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nginx/values.yaml
- values.yaml
* bump ap-nginx-es 1.23.1-1 -> 1.23.2
* bump ap-default-backend 0.28.9 ->  0.28.10
* bump ap-auth-sidecar 1.23.1-1 -> 1.23.2
https://github.com/astronomer/issues/issues/5174
NA
> update nginx base images

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- bin/kind/calico-crds-v1.24.yaml
- tests/__init__.py
Run tests against k8s 1.24.
https://github.com/astronomer/issues/issues/5148
No manual testing needed.
The 1.24 bits of this should be merged into any branches that support 1.23. The only important changes are the generate_circleci_config.py and tests/__init__.py changes, everything else is auto-generated, so if cherry-picking fails we can just manually make those changes.
> test against kubernetes 1.24

- charts/nginx/templates/nginx-service.yaml
- tests/chart_tests/test_nginx_service.py
In #1052 we merged a change that was mostly good, but had one edge case that was broken, which is that when the serviceType is ClusterIP, there can be no externalTrafficPolicy.
- Internal ticket describing the core problem being fixed here: <https://github.com/astronomer/issues/issues/4991>
- Original PR where the change that caused this problem was made: <https://github.com/astronomer/astronomer/pull/1052>
I've added tests for the new code change as well as previously untested configuration combinations.
The original problem showed up in 0.29.2, so this should be merged to 0.29, 0.30, 0.31.
- <https://kubernetes.io/docs/concepts/services-networking/service/#external-traffic-policy>
- <https://www.asykim.com/blog/deep-dive-into-kubernetes-external-traffic-policies>
> Skip externalTrafficPolicy when using ClusterIP

- charts/astronomer/templates/houston/cronjobs/houston-update-root-admin-password.yaml
Instead of generating a random password we need to pull the password from the k8s secrets.
astronomer/issues#5185
trying to test in dev
0.31
> fixUpdateRootAdminJob pull password from secret instead of random

- charts/astronomer/templates/houston/ingress.yaml
- tests/chart_tests/test_houston_ingress.py
currently we expose houston v1 metrics endpoint to identify the status of houston pod and generate alerts. This was available publically as well, this change now restricts public access since all those were consumed using internal service url
https://github.com/astronomer/issues/issues/5187
> limit public access to houston v1 metrics endpoint

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
-- | -- | --
ap-awsesproxy  |  1.3-8 | 1.3-9
ap-base | 3.16.2-1   |3.16.2-4
ap-blackbox-exporter | 0.22.0 | 0.22.0-1
ap-curator | 5.8.4-19 | 5.8.4-21
ap-nats-exporter | 0.10.0-1 | 0.10.0-2
ap-nats-server | 2.8.1-3 | 2.8.1-4
ap-nats-streaming | 0.24.5-3 | 0.24.5-4
ap-pgbouncer-krb | 1.17.0-3 | 1.17.0-4
ap-registry | 3.16.2-1 | 3.16.2-4
https://github.com/astronomer/issues/issues/5189
None of the updates here are huge, so testing should only involve looking to see if the components continue to work.
> update ap-base images

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/stan/values.yaml
Use the new ap-init image for stan initContainer in order to avoid running as root user.
- https://github.com/astronomer/issues/issues/5150
- https://github.com/astronomer/ap-vendor/pull/440 blocked by this merge. once 440 is is merged we should re-run tests here.
Stan should come up and run normally. This should be covered by CI testing, so no manual testing is needed.
Merge to all supported branches.
> Use new ap-init image

- tests/chart_tests/test_astronomer_commander.py
- values.yaml
Increase commander resources. Refactor some tests.
- https://github.com/astronomer/issues/issues/4927
Most of these changes are test changes. The others are deployed to prod, with the exception that the memory limit isn't increased quite as much here. Looking at the past month, the highest we got was just above 4GB total memory usage for the entire deployment, with each individual pod not going over 2Gi. With that in mind, no manual testing is needed here. The only time we'd get near the new limit is under severely strained circumstances.
This should be merged into all supported branches.
> 4927 double commander memory resources

- .circleci/config.yml
- charts/postgresql/values.yaml
* moving to next minor version 11.15.0 -> 11.17.0
Note: A dump/restore is not required for those running 11.X.
https://github.com/astronomer/issues/issues/5101
QA should able to run astronomer platform without any issues after upgrade
> update postgres version 11.15.0-1 -> 11.17.0

- .circleci/config.yml
- values.yaml
* bump 0.23.3-1  -> 0.24.1-1
* resolves libexpat1  CVE-2022-43680 
https://github.com/astronomer/issues/issues/5203
QA should validate the sidecar logging feature log 
cherry-pick to release-0.30,0.31.
> update vector service image

- .circleci/config.yml
- charts/astronomer/templates/houston/api/houston-root-admin-secret.yaml
- charts/astronomer/templates/houston/cronjobs/houston-update-root-admin-password.yaml
- charts/astronomer/templates/houston/helm-hooks/create-root-admin-job.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_root_admin_secret.py
- values.yaml
Remove the ability for a user to change root admin username
Reuses root admin secret if it already exists
astronomer/issues#5218
astronomer/issues#5220
astronomer/issues#5226
locally in kind
0.31
> Remove the ability for a user to change root admin username

- .circleci/config.yml
- charts/prometheus/values.yaml
* bump prometheus 2.37.2 -> 2.37.3
Link to release notes https://github.com/prometheus/prometheus/releases/tag/v2.37.3
https://github.com/astronomer/issues/issues/5247
NA
cherry-pick to all release branches.
> update prometheus 2.37.2 -> 2.37.3

- .circleci/config.yml
- charts/astronomer/values.yaml
update airflow chart version 1.7.0 -> 1.7.2
update commander image 0.31.0
https://github.com/astronomer/issues/issues/5224
https://github.com/astronomer/issues/issues/5207
QA should validate and verify installation of airflow 
cherry-pick to release-0.31 branch
> update airflow chart version 1.7.0 -> 1.7.2

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/generate_circleci_config.py
- bin/repo-state-report.sh
- Improve the helm repo state script by adding CircleCI information.
- Templatize the machine image version and use the latest version everywhere
- Bump docker minor version to 20.10.18
- Stop using pyenv since we're well past python2
https://github.com/astronomer/issues/issues/5152
```
$ helm pull astronomer-internal/astronomer --version 0.31.0-rc3-build67164
$ tar -xzf astronomer-0.31.0-rc3-build67164.tgz
$ cat astronomer/repo_state.log
Build time:  2022-11-14T23:53:53+0000
Git repo:    git@github.com:astronomer/astronomer.git
Git branch:  5152-improve-repo-state-report
Git SHA:     1d298135e30a2e8cfa9843deb15de8a31ca97b81
CircleCI Build URL:       https://circleci.com/gh/astronomer/astronomer/67164
CircleCI Build Number:    67164
CircleCI Repository URL: …
```
> Add CircleCI info

- .circleci/config.yml
- .pre-commit-config.yaml
- values.yaml
vector 0.24.2, which solves CVE-2021-46848
https://github.com/astronomer/issues/issues/5178
Testing should be performed to validate that sidecar logs ship as expected.
Merge into any branches that use vector 0.24.x
> vector 0.24.2

- .circleci/config.yml
- charts/astronomer/values.yaml
- airflowChartVersion: 1.7.3
- commander 0.31.1 which includes airflow-chart 1.7.3
Blocked by:
- https://github.com/astronomer/commander/pull/128
- https://github.com/astronomer/airflow-chart/pull/373
- https://github.com/astronomer/airflow-chart/pull/375
N/A
1.7.3-rc's were tested as part of the 0.31.0 release
Merge to 0.31.0, 0.30, which are already on 1.7.x
> airflowChartVersion: 1.7.3

- charts/astronomer/templates/houston/houston-configmap.yaml
Sidecar Occasionally Fails To Terminate
curl query changed to 
`curl -fsSL --retry 5 --max-time 10 --retry-connrefused -XPOST {{ .Values.global.loggingSidecar.terminationEndpoint }}"`
Earlier it was 
`curl -fsSL -XPOST {{ .Values.global.loggingSidecar.terminationEndpoint }}"`
There doesn't seem to be an easy way to test the added behavior because we don't have a rich functional test setup. I'd say we will have to leave this as "just make sure sidecar log containers continue to function" for now. (filled in by @danielhoherd)
Merge everywhere that sidecar logging exists. (filled in by @danielhoherd)
> bug-fix-sidecar-fails-to-terminate

- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_prometheus_statefulset.py
current we don't support passing extraFlags which prometheus offers for tuning, this PR addresses that issue and allows configurable flags
https://github.com/astronomer/issues/issues/5284
QA can validate this option with
```yaml
prometheus:
extraFlags:
- "--log.level=debug"
```
> add extraFlags option for prometheus service

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
* bump ap-kibana 7.17.6 -> 7.17.8
* bump ap-elasticsearch 7.17.6 -> 7.17.8
* bump ap-grafana 8.5.10 -> 8.5.13
NA - since these image updates dont fix any CRITICAL cve.
QA should verify after upgrades these service should work as expected.
cherry-pick all valid release branches.
> update ap-vendor packages

- .circleci/config.yml
- charts/external-es-proxy/values.yaml
* resolves CVE-2021-44716 CVE-2022-27664 in awsesproxy service
https://github.com/astronomer/issues/issues/5299
NA
cherry-pick to valid release branches.
> ap-awsesproxy 1.3-10

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/kube-state/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-node-exporter/values.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_default_chart.py
-- | -- | --
ap-db-bootstrapper  | 0.26.13  | 0.26.14
ap-curator | 5.8.4-21 | 5.8.4-22
ap-kube-state | 2.6.0 | 2.7.0
ap-blackbox-exporter | 0.22.0-1 | 0.23.0
ap-node-exporter | 1.4.1 | 1.5.0
ap-prometheus | 2.37.3 | 2.37.5
ap-kibana | 7.17.6 |  7.17.8
ap-elasticsearch | 7.17.6 | 7.17.8
ap-grafana | 8.5.10 | 8.5.13
awsesproxy | 1.3-9 |  1.3-10
https://github.com/astronomer/issues/issues/5290
https://github.com/astronomer/issues/issues/5287
https://github.com/astronomer/issues/issues/5286
> update vendor packages (#1761)

- .circleci/config.yml
- charts/postgresql/values.yaml
update postgresql to 11.17.0-debian-11-r42
resolves CVE-2021-46848 
https://github.com/astronomer/issues/issues/5304
> postgresql 11.17.0-1

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
- Bump all component versions that use ap-base, and a few more.
- Use new airflow-chart because it also had ap-base 3.16.3 updates
- We'll need a new commander version with the new chart (TBD)
- We also need a new houston-api version https://github.com/astronomer/houston-api/pull/1387
- ~Blocked by airflow-chart https://github.com/astronomer/airflow-chart/pull/381~
- ~Blocked by houston-api https://github.com/astronomer/houston-api/pull/1387~
- ~Blocked by commander https://github.com/astronomer/commander/pull/132~
- ap-base 3.16.3 update https://github.com/astronomer/issues/issues/5291
We'll need to test that all the updated components work.
Merge into 0.31, 0.30, and 0.28.
> Bump component versions

- Makefile
- charts/pgbouncer/templates/_helpers.yaml
- tests/chart_tests/test_pgbouncer.py
when private registry is set to true and  pgbouncer  is enabled  this change  wont work as expected since the referenced tag location is wrong. This PR corrects the behavior and resolves it 
https://github.com/astronomer/issues/issues/5318
validated via unit testing
> fix template when private registry is used for pgbouncer krb

- .circleci/config.yml
- .circleci/config.yml.j2
- charts/external-es-proxy/templates/_helpers.tpl
- charts/external-es-proxy/templates/external-es-proxy-deployment.yaml
- tests/chart_tests/test_external_elasticsearch.py
currently external es proxy images does not support global private registry . This changes makes it compactible to support global private registry
https://github.com/astronomer/issues/issues/5323
> make externales proxy images to support private registry

- .circleci/config.yml
- charts/alertmanager/values.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nginx/values.yaml
- values.yaml
resolves multiple CVE's in vendor packages
* bump ap-auth-sidecar 1.23.2 -> 1.23.3
* bump ap-default-backend 0.28.10 -> 0.28.11
* bump ap-nginx-es 1.23.2 -> 1.23.3
* bump ap-cli-install 0.26.9 -> 0.26.10
* bump ap-alertmanager 0.23.0 -> 0.25.0
https://github.com/astronomer/issues/issues/5322
https://github.com/astronomer/issues/issues/5321
NA
> update vendor package to resolve CVE

- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_prometheus_statefulset.py
Adding `timeoutSeconds` option in liveness and readiness for the prometheus block in the helm chart to make the value persistent.
Customers are not able to set timeoutSeconds in the prometheus block through the helm.
https://github.com/astronomer/issues/issues/5324
This can be tested by providing any numeric value to `timeoutSeconds` in values.YAML file and verifying the same in the Prometheus STS.
"This should be safe to merge to all supported branches." - DanielH
> Adding timeoutSeconds option in the prometheus block #5324

- .circleci/config.yml
- charts/astronomer/values.yaml
* bump airflow chart version 1.7.4 -> 1.7.5
* update commander 0.31.2 -> 0.31.3
https://github.com/astronomer/issues/issues/5329
QA should be able to install airflow deployments properly. main validation should be done map_id index in airflow logging for elastic search
cherry-pick to release-0.31.
> update airflow chart version 1.7.5

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/nginx/values.yaml
- values.yaml
* bump ap-auth-sidecar 1.23.3 -> 1.23.3-1
* bump ap-nginx-es  1.23.3 -> 1.23.3-1 
* bump ap-nginx 1.23.3 -> 1.23.3-1 
* resolves CVE-2022-3996 
https://github.com/astronomer/issues/issues/5328
NA
cherry-pick release-0.30 , release-0.31
> fix CVE-2022-3996 in vendor packages

- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_commander.py
- tests/chart_tests/test_houston_configmap.py
Increase timeouts related to airflow upgrades. This is due to a new dag parsing behavior in Airflow that makes upgrades take longer when there are lots of dags present.
- Issue: https://github.com/astronomer/issues/issues/5301
- These changes were already applied to Nebula in https://github.com/astronomer/google-environments/pull/1031 
Tests are added, but it wouldn't be bad to double-check them in QA testing.
This should be merged to all supported releases because it addresses a core airflow behavior.
> Add delay for nats.ackWait, upgradeTimeout. Improve some test syntaxes.

- .circleci/config.yml
- .circleci/trivyignore
- charts/postgresql/values.yaml
exclude CVE-2022-29162 in gosu service used in postgresql
update postgresql version 11.18.0 
cherry-pick to release-0.30,release-0.31.
> update postgresql version 11.18.0

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
* Bump component versions to those that use ap-base 3.16.3
https://github.com/astronomer/issues/issues/5291
This PR already merged to master and release-0.31. Left out in release-0.30 so re-adding them
> Bump component versions to ap-base 3.16.3 (#1768)

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/nginx/values.yaml
resolves CVE-2022-29162 
update ap-cli-install 0.26.10 -> 0.26.11
update ap-default-backend 0.28.11 -> 0.28.12
https://github.com/astronomer/issues/issues/5328
> resolve CVE-2022-29162

- .circleci/config.yml
- .circleci/trivyignore
- charts/alertmanager/values.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nginx/values.yaml
- charts/postgresql/values.yaml
- values.yaml
-- | -- | --
ap-alertmanager  | 0.23.0 | 0.25.0
ap-cli-install | 0.26.8 | 0.26.11
ap-nginx-es | 1.23.1-1 | 1.23.3-1 
ap-nginx | 1.3.1 | 1.3.1-1
ap-default-backend | 0.28.9 | 0.28.12
ap-postgresql | 11.17.0 | 11.18.0
ap-auth-sidecar | 1.23.1-1 | 1.23.3-1
ap-grafana | 8.5.10 | 8.5.15
ap-kibana | 7.17.6 | 7.17.8
ap-elasticearch | 7.17.6 | 7.17.8
> release-0.28 backport CVE fixes

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
* bump db-bootstrapper  0.26.14 -> 0.31.0 
* bump commander 0.28.7 -> 0.28.8
* update airflow chart version 1.4.3 -> 1.4.4
* bump ap-houston 0.28.29 -> 0.28.30
NA
QA should able to able to deploy platform and airflow without any issues 
cherry-pick and direct merge to release-0.28 since its already diverged with lots of changes.
> Update release 0.28 images

- .circleci/config.yml
- values.yaml
update vector 0.24.2 -> 0.26.0
https://github.com/astronomer/issues/issues/5178
QA should validate vector service should work as usual
> update vector 0.24.2 -> 0.26.0

- .circleci/config.yml
- charts/fluentd/values.yaml
* bump fluentd 1.15.2 -> 1.15.3-1
* adds kafka plugin support
https://github.com/astronomer/issues/issues/5330
cherry-pick to release-0.31.
> update fluentd image version 1.15.3-1

- charts/astronomer/templates/houston/ingress.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_ingress.py
currently we are unable to set specific ingress annotation overrides for houston. This change allows users to add customer ingress annotation supported by ingress providers
https://github.com/astronomer/issues/issues/5385
0.31.2
> update houston ingress to support extra annotation

- .circleci/config.yml
- charts/astronomer/values.yaml
* bump airflow chart version 1.7.5 -> 1.7.6
https://github.com/astronomer/issues/issues/5386
QA should able to deploy airflow with platform without any issues
cherry-pick to release-0.31.
> update commader 0.31.4

- README.md
- bin/reset-local-dev
- templates/NOTES.txt
Update instructions with modern kind syntax and also syntaxes that give the user instruction on how to log into astronomer root user account now that we have public signups disabled by default.
N/A, just stuff I found while developing locally.
This change modifies test scripts, so as long as tests pass then we're good with that. It would also be good to verify that the text at the end of the CI invocation of `bin/reset-local-dev` is correct. I've already verified it on my local machine.
> Update local-dev text to give accurate instructions.

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
Bump astronomer helm chart to rc3 and astro-ui to 0.31.12
0.31.2
> bump astro-ui to 0.31.12 and chart to rc3

- .circleci/config.yml
- charts/fluentd/templates/fluentd-configmap.yaml
currently we don't capture gitsync relay pod logs . In case after deployment it goes into error state ( like clone error or branch error) , customer should get access to k8s cluster for that release and verify those errors. This way it can send them to elasticsearch and can be used for further processing
https://github.com/astronomer/issues/issues/5246
> allow fluentd to gather gitsync relay pod logs

- charts/elasticsearch/templates/nginx/nginx-es-ingress-networkpolicy.yaml
- charts/external-es-proxy/templates/external-es-proxy-networkpolicy.yaml
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_external_elasticsearch.py
Allow gitsync relay pod to ingest logs to elasticsearch from vector container.
This PR adds extra network policies to allow git-sync-relay pod vector sidecar to connect elasticsearch
https://github.com/astronomer/issues/issues/5246
QA should able to see logs when used in combination with vector and incluster es and external es proxy in elasticsearch
This is a release-0.32 feature should get cherry-picked  once its available.
> add gitsync network policy exclusion for gitsync relay logs

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
- values.yaml
resolves CVE-2023-0286 cve in ap-base packages reference in 
image | existing | new
-- | --| --|
awsesproxy | 1.3-10 | 1.3-11
blackbox-exporter | 0.23.0-1 | 0.23.0-3
curator |  5.8.4-23 | 7.0.0-2
init | 3.16.3 | 3.16.3-1
nats-exporter | 0.10.0-3 | 0.10.0-4
nats-server | 2.8.4 | 2.8.4-2
nats-streaming | 0.24.6 | 0.24.6-2
pgbouncer-krb | 1.17.0-5 | 1.17.0-6
registry | 3.16.3 | 3.16.3-2
ap-base | 3.16.3 | 3.16.3-2
default-backend | 0.28.12 | 0.28.13
ap-cli-install | 0.26.11 | 0.26.12
> resolves CVE-2023-0286 in astronomer vendor packages

- charts/elasticsearch/templates/nginx/nginx-es-configmap.yaml
- tests/chart_tests/test_elasticsearch.py
Add nginx rewrite rules that lock all user operations into their own indices.
- https://github.com/astronomer/issues/issues/5417
- https://astronomer.slack.com/archives/C04P3TRUV3L
This should be tested with both sidecar and vector.
@jedcunningham and I have personally tested these changes in a dedicated AWS cluster and they all look good to us.
These changes should be good to merge everywhere.
> Confine user actions to the index of the user performing the action

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/postgresql/values.yaml
* bump ap-elasticsearch 7.17.8 -> 7.17.8-1
* bump ap-fluentd 1.15.3-1 -> 1.15.3-2
* bump ap-postgresql 11.18.0 -> 11.18.0-1
* bump ap-db-boostrapper 0.30.0 -> 0.30.1
> update vendor packages to resolve CVE-2023-0286

- .circleci/config.yml
- charts/astronomer/values.yaml
* bump ap-houston-api 0.31.15 -> 0.31.17
* bump ap-astro-ui   0.31.10 ->  0.31.13
https://github.com/astronomer/issues/issues/5365
https://github.com/astronomer/issues/issues/5381
QA should now able to test with docker buildx images with this release 
cherry-pick to release-0.31, release-0.32
> update platform images

- .circleci/config.yml
- charts/astronomer/values.yaml
* bump ap-commander 0.31.4 -> 0.31.5
QA should able to deploy airflow without any issues
cherry-pick to release-0.31.
> update commander version

- .circleci/config.yml
- values.yaml
resolves openssl and libcrypto CVE
QA should validate the sidecar funtionality should work as expected
> update vector image to resolve openssl CVE

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.31.17 -> 0.31.18
https://github.com/astronomer/issues/issues/5221
QA should able to override  AIRFLOW_LOGGING ENV var 
cherry-pick to release-0.31 branch.
> update houston api version 0.31.18

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nginx/values.yaml
resolves openssl and libcrypto CVE's in vendor base packages
image | existing | new
-- | --| --|
ap-elasticsearch | 7.17.8-1 | 7.17.9
ap-grafana| 8.5.16 | 8.5.16-2
ap-kibana | 7.17.8 |  7.17.9
ap-nginx | 1.3.1-2 |  1.3.1-3
> final changes for openssl CVE in vendor packages

- charts/elasticsearch/templates/nginx/nginx-es-configmap.yaml
- tests/chart_tests/test_elasticsearch.py
Allow the version endpoint through the proxy unmodified.
https://github.com/astronomer/issues/issues/5434 which is a follow-up to https://github.com/astronomer/issues/issues/5417
We have unit tests for this, but really we need functional tests for these kinds of things. We do not do an airflow deployment into the CI workflow, so there's no way to test this with the existing test setup. I think a good middle-ground is to launch a pod with the labels of a webserver pod and run these proxy tests from there, but I also think we can handle that in a follow-up ticket so that this can be merged and shipped quickly.
As for QA testing, this is a really minor change that I'm not sure has any consequence right now, but could potentially solve unobserved failure scenarios. I've tested this in staging …
> Allow `/_cluster/state/version`

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/pgbouncer/values.yaml
- charts/postgresql/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
- values.yaml
cherry-pick CVE commits to release-0.30 branch 
image-name | current | new
-- | -- | --
ap-astro-ui |0.30.10 | 0.30.12
ap-auth-sidecar |1.23.3-1 | 1.23.3-2
ap-awsesproxy |1.3-10 |  1.3-11
ap-base | 3.16.3 | 3.16.3-2 
ap-blackbox-exporter | 0.23.0-1 |  0.23.0-3 
ap-cli-install | 0.26.11 |  0.26.12
ap-curator | 5.8.4-23 |  7.0.0-2
ap-db-bootstrapper  | 0.31.0 | 0.31.1
ap-default-backend | 0.28.12 |  0.28.13
ap-elasticsearch | 7.17.8 | 7.17.9
ap-fluentd  |1.15.2 |  1.15.3-2
ap-grafana |8.5.16 |  8.5.16-2
ap-houston-api | 0.30.32 |  0.30.34
ap-init | 3.16.3 |  3.16.3-1
ap-kibana | 7.17.8 | 7.17.9
ap-nats-exporter | 0.10.0-3 | 0.10.0-4
ap-nats-server | 2.8.4 |  2.8.4-2
ap-nats-streaming |0.24.6 |  0.24.6-2
ap-nginx-es | 1.23.3-1 | 1.23.3-2
ap-nginx | 1.3.1-2 | 1.3.1-3
ap-openresty | 1.21.4-3 | …
> cherry-pick commits to release-0.30

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
- Bump houston-api 0.31.19 -> 0.31.21
- Bump chart version to rc4
0.31
> bump houston-api 0.31.21 and chart to rc4

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/generate_circleci_config.py
- .pre-commit-config.yaml
- tests/functional_tests/__init__.py
- tests/functional_tests/conftest.py
- tests/functional_tests/test_config.py
- tests/functional_tests/test_network_security.py
These changes are mostly code reorganization. There aren't any code additions. There are minor removals.
- Use newer circleci ubuntu machine image
- Use ruff in place of pyupgrade, flake8
- Remove unneeded inclusion of the `request` pytest fixture
- Rename pytest fixture `get_kube_client` to `get_core_v1_client`
- Move `get_core_v1_client` out of `conftest.py` to `__init__.py` since it is not a fixture and will be used by more functions in the near future.
- Delete some old CoreDNS branching logic that is no longer relevant.
- Replace `randint` with `strftime('%s')` which is unique enough for our needs while providing useful information.
- Add some docstrings.
- Switch from raising an exception when `HELM_CHART_PATH` is unset to just skipping the test.
This is indirectly related to …
> Incremental functional test improvements

- .circleci/config.yml
- values.yaml
Use vector 0.26.0-4 with ap-base
- <https://github.com/astronomer/issues/issues/5472>
- <https://github.com/astronomer/ap-vendor/pull/500>
Normal logging sidecar testing should cover this.
This should be merged everywhere.
> Use vector 0.26.0-4 with ap-base

- .circleci/config.yml
- charts/postgresql/values.yaml
ap-postgresql 15.2.0.  This should not be merged until we are ready for 0.32.
- https://github.com/astronomer/issues/issues/5374
- https://github.com/astronomer/issues/issues/5454
This is a big jump so we should definitely keep an eye out for any changes to postgres behaviors. We should expect improved performance.
This is only meant for release-0.32 and newer.
Upgrading to this is not possible without manual intervention, and customers who are using in-cluster postgres (which goes against our advice and is not a supported configuration) should be advised about this change and urged to migrate away from in-cluster postgres. AFAIK we are not planning to support an upgrade path from postgres 11 to 15 because in-cluster postgres was never a supported configuration for production. CC …
> ap-postgresql 15.2.0

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/trigger_rc_tests.py
Adding CircleCI Job extending workflow `build-and-release-helm-chart` to trigger `test_upgrade` workflow of `terraform-aws-astronomer` on RC build.
Issue: https://github.com/astronomer/issues/issues/5461
As this is the CircleCI Workflow, it can be tested as execution.
- [release-0.32](https://github.com/astronomer/astronomer/tree/release-0.32)
- [release-0.31](https://github.com/astronomer/astronomer/tree/release-0.31)
- [release-0.30](https://github.com/astronomer/astronomer/tree/release-0.30)
> Adding CircleCI Job to trigger `test_upgrade` on RC build

- .circleci/config.yml
- charts/astronomer/values.yaml
Bump airflowChartVersion to 1.8.1, which fixes the statsd problem caused by statsd configmap changes in OSS airflow, along with other changes.
Here is the change set for astronomer/airflow-chart: https://github.com/astronomer/airflow-chart/compare/v1.7.6..09b8efc
- https://github.com/astronomer/issues/issues/5476
- https://github.com/astronomer/airflow-chart/pull/409
- https://github.com/astronomer/commander/pull/146
- https://github.com/astronomer/astronomer/pull/1839
I manually tested this in dev and in an aws cluster.
This should only be merged to release-0.32, which is the only branch that uses astronomer/airflow-chart 1.8.x. We'll release new versions of astronomer/airflow-chart 1.7 for other branches.
> airflowChartVersion: 1.8.1

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/trigger_feature_stack_update.py
- bin/trigger_rc_tests.py
Adding a trigger to call the `feature_stack` workflow that performs the deployment on the cluster. This will add the capability to refresh the cluster with the latest build immediately.
- release-0.30
- release-0.31
> Adding Trigger to call feature_stack deployment

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/trigger_feature_stack_update.py
Adding a trigger to call the `feature_stack` workflow that performs the deployment on the cluster. This will add the capability to refresh the cluster with the latest build immediately.
https://github.com/astronomer/astronomer/pull/1842
> Adding Trigger to call feature_stack deployment (#1842)

- .circleci/config.yml
- charts/grafana/values.yaml
Bump grafana to a version that has newer dashboards, migrated dashboards, and deleted kube-dns dashboard.
https://github.com/astronomer/ap-vendor/pull/506
This has been tested in dev.
This should be merged everywhere.
> ap-grafana 8.5.22

- .circleci/config.yml
- .circleci/config.yml.j2
- Now trigger the RC test on approval to avoid calling on each internal release from the release branch. 
- Removing the feature stack update from `build-and-release-helm-chart` workflow as the internal release will fail if not unique tag. For the release branch, we don't generate the unique tag instead we use the static tag from Chart.
- Adding feature stack update to workflow `qa-build-and-release-helm-chart` workflow.
N/A
- release-0.30
- release-0.31
- release-0.32
> Improving QA Workflow

- .circleci/config.yml
- .circleci/config.yml.j2
- Now trigger the RC test on approval to avoid calling on each internal release from the release branch. 
- Removing the feature stack update from `build-and-release-helm-chart` workflow as the internal release will fail if not unique tag. For the release branch, we don't generate the unique tag instead we use the static tag from Chart.
- Adding feature stack update to workflow `qa-build-and-release-helm-chart` workflow.
(cherry picked from commit e2da42de63c72365e4161685eabbf3a735e7fae1)
N/A
https://github.com/astronomer/astronomer/pull/1849
> Improving QA Workflow (#1849)

- .circleci/config.yml
- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
- values.yaml
Refactor logging sidecar signaling mechanism to be filesystem based. Handle brutal killing of airflow container in kubernetes executor pods.
This change goes hand in hand with the vector changes in this PR https://github.com/astronomer/ap-vendor/pull/511
https://github.com/astronomer/issues/issues/5469
I have done a lot of testing with this while iterating on it. I'm fairly confident all cases are covered, but as it is with humans, especially when working on iterations of something, it's possible that I've missed some cases. We will definitely need to test these changes in all known sidecar logging configurations.
This is being merged into 0.31 because that is the branch I used when testing. These changes are compatible with 0.32 though, so they can be cherry-picked to main and to 0.32.0. …
> Better signaling between primary and sidecar container

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nginx/values.yaml
- values.yaml
| Image Name  | Old Tag  | New Tag |
| ------------- | ------------- | --------|
| ap-auth-sidecar | 1.23.3-2  | 1.23.4 |
| ap-nginx-es | 1.23.3-2 | 1.23.4 |
| ap-default-backend | 0.28.13 | 0.28.14 |
| ap-cli-install | 0.26.12 | 0.26.13 |
https://github.com/astronomer/issues/issues/5561
> nginx base images in vendor packages

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/trigger_rc_tests.py
Remove the `rc` keyword to filter when triggering the upgrade test.
(cherry picked from commit 3f4039ae88471c0b274a3cd091e78fe98e2a5b75)
https://github.com/astronomer/issues/issues/5566
No testing require as it is CI flow change.
https://github.com/astronomer/astronomer/pull/1862
> Removing RC keyword filter (#1862)

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/trigger_rc_tests.py
Remove the `rc` keyword to filter when triggering the upgrade test.
(cherry picked from commit 3f4039ae88471c0b274a3cd091e78fe98e2a5b75)
https://github.com/astronomer/issues/issues/5566
No testing require as it is CI flow change.
https://github.com/astronomer/astronomer/pull/1862
> Removing RC keyword filter. (#1862)

- .circleci/config.yml
- .circleci/trivyignore
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
resolves CVE-2023-0464 in ap-vendor packages 
| Image Name                     | Old Tag             |    New Tag     |
| ----------------------    | -------------     | ------------- | 
| ap-blackbox-exporter    | 0.23.0-3             |     0.23.0-4     |
| ap-curator                       | 7.0.0-3                |      7.0.0-4       |
| ap-git-daemon                | 3.16.3-2              |     3.16.5         |
| ap-init                              | 3.16.3-1                | 3.16.5         |
| ap-nats-exporter            | 0.10.0-4               | 0.10.0-5 |
| ap-nats-server                | 2.8.4-2                 | 2.8.4-3  |
| ap-nats-streaming          | 0.24.6-2               | 0.24.6-3 |
| ap-registry                       | 3.16.3-2                | 3.16.5|
| ap-aws-es-proxy …
> resolves CVE-2023-0464 in ap-vendor packages

- charts/external-es-proxy/templates/external-es-proxy-deployment.yaml
- tests/chart_tests/test_external_elasticsearch.py
- values.yaml
Support allowing extraEnv values for es proxy service 
https://github.com/astronomer/issues/issues/5559
https://github.com/astronomer/issues/issues/5544
0.32.0
> add option to allow extraenv in esproxy service

- charts/astronomer/templates/commander/commander-networkpolicy.yaml
- charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
- charts/astronomer/templates/houston/cronjobs/houston-cleanup-airflow-db-cronjob.yaml
- charts/astronomer/templates/registry/registry-networkpolicy.yaml
- charts/astronomer/values.yaml
- Added network policy for registry and commander for airflow db cleanup cron
- Replaced connection Id cron variable with provider env secret name
https://github.com/astronomer/issues/issues/5451
0.32.0
> added network policy for registry and commander

- .circleci/config.yml
- charts/astronomer/values.yaml
This PR includes fixes for migrating airflow chart 1.7.x to 1.8.x  along with commander changes 
* bump commander 0.32.0 -> 0.32.2
* bump airflow chart 1.8.0 -> 1.8.3
https://github.com/astronomer/issues/issues/5500
> update commander image and default airflow version

- charts/astronomer/templates/houston/cronjobs/houston-cleanup-airflow-db-cronjob.yaml
- charts/astronomer/values.yaml
Allows airflow db cleanup to accept list of tables or run cleanup on specific tables based on the customer needs.
NA
QA/dev should able to pass specific table and should validate exported data should only have that table data in CSV format
> add table flag for airflow db cleanup

- .circleci/config.yml
- charts/elasticsearch/values.yaml
Resolves CVE's as mentioned in the issue ticket
update ap-elasticsearch. 7.17.9 -> 7.17.9-1
update  ap-curator 7.0.0-2 -> 7.0.0-4
https://github.com/astronomer/issues/issues/5581
QA should able to run curator service without any issues and elasticsearch should work as expected
cherry-pick to release-0.32.
> update elasticsearch packages

- .circleci/config.yml
- charts/nginx/values.yaml
resolves multiple CRITICAL and HIGH cve in ingress controller service
https://github.com/astronomer/issues/issues/5582
https://github.com/astronomer/issues/issues/5575
QA should able to access astronomer platform ingress and airflow ingress without any issues 
> update nginx ingress controller 1.7.0

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander and airflowChartVersion to 1.8.4
NA
QA should able to deploy airflow with the shipped commander image and airflow chart 
> update commander and airflowChartVersion to 1.8.4

- charts/prometheus/templates/prometheus-config-configmap.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_prometheus_config_configmap.py
Allow configuring kubernetes-apiservers with insecure_skip_verify. This starts a pattern of mirroring the prometheus config in helm values with some slight tweaks to make it more helm friendly.
- https://github.com/astronomer/issues/issues/5612
- https://github.com/astronomer/astronomer/issues/1880
Unit tests are included. I have not run any functional tests, though the changes match what was purported to fix the problem being solved.
This should be merged into 0.30, 0.32
> Allow configuring kubernetes-apiservers with insecure_skip_verify

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nginx/values.yaml
- values.yaml
* nginx base images in vendor packages
* update ap-cli-install 0.26.12 -> 0.26.13
* update scan images
> nginx base images in vendor packages (#1860)

- charts/prometheus/templates/prometheus-config-configmap.yaml
- tests/chart_tests/test_prometheus_config_configmap.py
For pre-created namespaces pods, Relabeling and storing the release names in `release` tag, so that they can be fetched by the query made from houston, under metrics tab
[4650](https://github.com/astronomer/issues/issues/4650)
Kind cluster locally. Also, spinning up a separate cluster.
0.32.1
> Relabeling to release for precreatednamespaces and also namespaceFreeFormEntry

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
- charts/external-es-proxy/templates/_helpers.tpl
- charts/external-es-proxy/templates/external-es-proxy-deployment.yaml
- tests/chart_tests/test_external_elasticsearch.py
airflowChartVersion: 1.7.8 -> 1.7.9
houston: 0.30.35 -> 0.30.36
commander: 0.30.8 -> 0.30.9
> bump houston and airflowChartVersion for 0.30.7 rc2

- charts/nginx/templates/nginx-configmap.yaml
Mask the `token` query param in referrer and request url string, in our nginx logs
[#5608
](https://github.com/astronomer/issues/issues/5608)
Local kind cluster
0.32.1
> Masked token from request_uri and referrer in nginx ingress logs

- charts/prometheus/templates/prometheus-config-configmap.yaml
- tests/chart_tests/test_prometheus_config_configmap.py
worker metrics are missing in metrics table due to labels not included , this change address the issue and show metrics in the UI
https://github.com/astronomer/issues/issues/4650
QA should able to see worker metrics in astro-ui metrics tab
cherry-pick to release-0.30,0.32
> include worker pods for metrics

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/nginx/values.yaml
- charts/pgbouncer/values.yaml
- values.yaml
| imageName | oldtag | newTag |
| ap-auth-sidecar | 1.24.0-1 | 1.24.0-2 |
| ap-curator | 7.0.0-4 | 7.0.0-5 | 
| ap-grafana | 8.5.24-1 | 8.5.24-2 | 
| ap-nginx-es | 1.24.0-1 | 1.24.0-2 |
| ap-nginx | 1.7.1 | 1.7.1-1 | 
| ap-pgbouncer-krb | 1.17.0-7 | 1.17.0-8 |
| ap-vector| 0.28.2-1 | 0.28.2-2 |
https://github.com/astronomer/issues/issues/5649
QA should able to deploy all components without issues
> resolves CVE-2023-29491 in vendor packages

- charts/prometheus/templates/prometheus-config-configmap.yaml
- tests/chart_tests/test_prometheus_config_configmap.py
include git-sync-relay lable to show pod status in astro-ui when precreated namespace or namespace free form entry
https://github.com/astronomer/issues/issues/4650
QA should able to see pod status in astro-ui
> add git-sync-relay labels in prometheus

- charts/astronomer/templates/registry/registry-statefulset.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_registry.py
- values.yaml
Allow referencing custom env vars and secret ref in registry env vars to remove sensitive information passed as direct values in config. 
https://github.com/astronomer/issues/issues/4559
QA should able to verify by passing env vars for registry configuration
cherry-pick to release-0.30 and release-0.32.
> add extraenv support for registry backend service

- .circleci/config.yml
- charts/grafana/values.yaml
* update grafana version 8.5.24-2 -> 8.5.26
*  fixes platform dashboard for missing metrics
https://github.com/astronomer/issues/issues/5660
QA should able to verify platform dashboard overview dashboard showing the data properly
cherry-pick to release 0.30, 0.32
> update grafana version includes dashboard fixes

- charts/nginx/templates/nginx-configmap.yaml
Resolves an issue when a empty query param is passed or sent its being handled properly rather ending with 500 internal server error
https://github.com/astronomer/issues/issues/5683
cherry-pick to release-0.30, 0.32
> Handle empty URL parameter values

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- bin/install-ci-tools
- bin/kind/calico-crds-v1.27.yaml
Adds support for k8s 1.27 for CI testing
Add Note: Calico v3.26 will not work on Kubernetes v1.20 or below
https://github.com/astronomer/issues/issues/5702
cherry-pick to release-0.30, release-0.32,release-0.33
> Add k8s 1.27 support in CI

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/registry/registry-serviceaccount.yaml
- charts/astronomer/templates/registry/registry-statefulset.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_registry.py
Registry is by default configured to use default serviceAccount , this changes allows user to enable serviceAccount to be added either with custom name or default name. This allows user to make use of IRSA and GKE Managed Identity.
https://github.com/astronomer/issues/issues/5692
> add service account to registry service

- charts/prometheus/templates/_helpers.yaml
- charts/stan/templates/_helpers.tpl
- tests/chart_tests/test_default_chart.py
- Add more tests to validate privateRegistry functionality.
- Fix a two cases where privateRegistry was not being used.
https://github.com/astronomer/issues/issues/5698
Tests are included for the bug fixes so no human testing is necessary.
This bugfix should be merged to all supported branches.
> Fix private registry init containers

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nginx/values.yaml
- values.yaml
upgrades nginx version 1.25.1
https://github.com/astronomer/issues/issues/5712
> update nginx packages 1.25.1

- .circleci/config.yml
- charts/prometheus/values.yaml
upgrade prometheus to newer LTS version 2.45.0
https://prometheus.io/docs/introduction/release-cycle/#list-of-lts-releases
https://github.com/astronomer/issues/issues/5711
QA should able to validate  the prometheus features without issues
> update prometheus version 2.45.0

- .circleci/config.yml
- charts/astronomer/values.yaml
Bump airflowChartVersion to 1.9.0.
- https://github.com/astronomer/issues/issues/5670
This is a big jump, from OSS airflow chart 1.8 to 1.11, so we should be extra careful to investigate things that are not working perfectly during testing.
This could be merged everywhere that 1.8.x was used if we want to do that, otherwise we can just put it in 0.33.
> airflowChartVersion: 1.9.0

- .circleci/config.yml
- charts/grafana/values.yaml
update grafana version 10.0.2
resolves multiple CVE
https://github.com/advisories/GHSA-69cg-p879-7622
https://github.com/advisories/GHSA-fxg5-wq6x-vr4w
https://github.com/advisories/GHSA-vvpx-j8f3-3w6h
https://github.com/advisories/GHSA-69ch-w2m2-3vjp
Fix grafana cli syntax
https://github.com/astronomer/issues/issues/5707
QA should able to validate existing graphs should work as usual without any issues.
> update grafana version 10.0.2

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/kibana/values.yaml
Generic updates from elastic with minor internal improvements
release notes:
Kibana -> https://www.elastic.co/guide/en/kibana/current/release-notes-8.8.2.html
Elasticsearch -> https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.8.2.html
https://github.com/astronomer/issues/issues/5721
QA should able to validate es services should work as expected 
> update elastic packages 8.8.1 -> 8.8.2

- .circleci/config.yml
- charts/astronomer/values.yaml
update airflow chart 1.9.0 -> 1.9.1
https://github.com/astronomer/issues/issues/5720
gitsync image update issue -> https://github.com/astronomer/issues/issues/5689
pgbouncer-exporter issue -> https://github.com/astronomer/issues/issues/5316
QA should validate triggerer log consumer works as expected and other airflow features
> update commander and airflow chart version 1.9.1

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/stan/values.yaml
update ap-init, ap-base to 3.18
https://github.com/astronomer/issues/issues/5655
QA should able to latest images
> update ap-base to 3.18.0

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
Refactor houston configmap's handling of cleanup cron splay.
https://github.com/astronomer/issues/issues/5670
We have unit tests for the changes here, but seeing the cron splay in e2e tests will be required for us to be confident that everything is in place.
This should only be merged to branches that support airflowChartVersion 1.9.0
> Refactor houston config's handling of cron splay

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
Offloads job schedule timing to airflow chart to generate cron timing randomly for evenly distributing schedule
https://github.com/astronomer/issues/issues/5670
QA should able to validate different spread timings 
> fix cron template render issue

- .circleci/config.yml
- charts/external-es-proxy/values.yaml
resolves CVE  CVE-2023-3138  in openresty image and upgrades alpine to 3.18
https://github.com/astronomer/issues/issues/5655
NA
> update openresty image version

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/helm_template_generator.py
- tests/chart_tests/test_prometheus_alerts_configmap.py
- Add the ability to disable each of airflow and platform default alerts.
- Refactor the render_chart function to make DEBUG env var do useful things like do not delete the temp file and print up debug info.
https://github.com/astronomer/issues/issues/4915
I have unit tests for all of the changes. It would be good to have a critical eye go over them and maybe test things out, especially if I forgot some edge case.
Merge only to 0.33 since this is a new feature.
> allow disabling default platform and airflow alerts

- charts/grafana/values.yaml
- tests/chart_tests/test_grafana.py
runAsUser in grafana  securityContext creates a constraint in openshift not to run the deployment since the UID range is not in specified range of openshift approved  ones.
https://github.com/astronomer/issues/issues/5737
QA should able to see grafana pod in running status
cherry-pick to release-0.32, 0.33
> remove uid changes from main config

- templates/scc/astronomer-nodeexporter-scc.yaml
- tests/chart_tests/test_scc.py
- values.yaml
Adds security context config for openshift to allow and run  node exporter service 
https://github.com/astronomer/issues/issues/5740
by enabling nodeExporterSccEnabled: true node exporter service should come up without any issues
> add openshift scc template to prometheus node exporter

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander version 0.33.2 
update airflowchartversion 1.9.2
https://github.com/astronomer/issues/issues/5742
QA should able to deploy airflow instance without any issues
> update airflow chart and commander version

- .circleci/config.yml
- .circleci/config.yml.j2
Adding integration of Prisma Cloud Docker Image Scans using `twistcli`.
N/A
This change was tested directly by calling the Circleci job. 
Example: https://app.circleci.com/pipelines/github/astronomer/astronomer/9133/workflows/91275c9f-c0c4-4ebb-8b34-6ddb354196b3
All active releases.
> Integrate Prisma Cloud Docker Image Scans

- .circleci/config.yml
- .circleci/config.yml.j2
Disable the Slack notifications for Docker Image scans.
N/A
N/A
Please merge it to all active releases.
> Disable the Slack notifications for Docker Image scans

- .circleci/config.yml
- .circleci/config.yml.j2
Making slack notification optional for docker image scan.
(cherry picked from commit a6bc2db91f670425ea30c7114d9561dff4191148)
N/A
N/A
N/A
https://github.com/astronomer/astronomer/pull/1956
> Disable the Slack notifications for Docker Image scans v0.32 (#1956)

- .circleci/config.yml
- .circleci/config.yml.j2
Making slack notification optional for docker image scan.
(cherry picked from commit a6bc2db91f670425ea30c7114d9561dff4191148)
N/A
N/A
N/A
https://github.com/astronomer/astronomer/pull/1956
> Disable the Slack notifications for Docker Image scans v0.30 (#1956)

- .circleci/config.yml
- charts/astronomer/values.yaml
update astro-ui image 0.30.14
https://github.com/astronomer/issues/issues/5712
QA should able to run UI without any issues
> update astro-ui image 0.30.14

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.32.17
https://github.com/astronomer/issues/issues/3954
https://github.com/astronomer/issues/issues/5647
https://github.com/astronomer/issues/issues/5594
QA should validate all marked features for 0.32
> update houston api 0.32.17

- .circleci/config.yml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_configmap.py
update commander service with airflow chart 1.8.8
https://github.com/astronomer/issues/issues/5670
https://github.com/astronomer/issues/issues/5762
QA should able to create and deploy airflow instance
> Update airflow chart 1.8.8

- .circleci/config.yml
- charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_configmap.py
Introducing a change to switch to internal url when enableHoustonInternalAuthorization: true is enabled.
https://github.com/astronomer/issues/issues/5733
https://github.com/astronomer/issues/issues/5725
https://github.com/astronomer/issues/issues/5745
> support internal houston authorization

- charts/astronomer/templates/registry/registry-scc.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_registry.py
Add scc template to registry service when custom service account or release based service account generated
https://github.com/astronomer/issues/issues/5765
QA should able to run registry with custom service account with ``` .Values.registry.serviceAccount.create .Values.registry.serviceAccount.sccEnabled ```
cherry-pick to release-0.32 release-0.30 release-0.33
> add scc flag for registry service when custom name is defined

- charts/elasticsearch/templates/curator/es-curator-configmap.yaml
- charts/elasticsearch/values.yaml
- tests/chart_tests/test_elasticsearch.py
starting from elasticsearch 8.0 curator config moved to elasticearch section, this PR fixes the behavior and makes compactible with newer elastic version
8.0 curator configuration reference https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html
7.0 curator configuration reference https://www.elastic.co/guide/en/elasticsearch/client/curator/7.0/configfile.html
https://github.com/astronomer/issues/issues/5767
cherry-pick to release-0.33 and release-0.32 release-0.30
> fix curator config to support es 8

- .circleci/config.yml
- charts/alertmanager/values.yaml
update alertmanager 0.25.0 -> 0.26.0
resolves CVE-2022-41723  in alertmanager 
https://github.com/astronomer/issues/issues/5797
QA should able to validate alertmanager service works as expected
> update alertmanager version 0.26.0

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
update dbbooststrapper image for grafana and astronomer to vesion 0.31.5
https://github.com/astronomer/issues/issues/5777
QA should able to run db bootstrapper service without issues 
> update dbbootstrapper 0.31.5

- .circleci/config.yml
- charts/fluentd/values.yaml
update fluentd version to 1.16.2
link to release notes https://github.com/fluent/fluentd/releases/tag/v1.16.2
https://github.com/astronomer/issues/issues/5798
QA should validate fluentd service should run without any issues
> update fluentd version 1.6.2

- .circleci/config.yml
- charts/prometheus/values.yaml
update configmap release 0.11.0
https://github.com/astronomer/issues/issues/5649
QA should able to validate configmap syncer reloads prometheus 
> update configmap reload 0.11.0

- .circleci/config.yml
- charts/astronomer/values.yaml
update registry version to 2.8.2 and tag to 3.18.3
https://github.com/astronomer/issues/issues/5772
QA should able to verify registry service should work as expected
cherry-pick to all valid branches once QA verified in release-0.30
> update registry version 2.8.2 and image 3.18.3

- .circleci/config.yml
- charts/astronomer/values.yaml
updates commander dependencies to latest version
https://github.com/astronomer/issues/issues/5787
https://github.com/astronomer/issues/issues/5772
QA should able to deploy airflow without any issues
> update commander image 0.30.11

- .circleci/config.yml
- charts/astronomer/values.yaml
Add support for GCS backend
https://github.com/astronomer/issues/issues/5772
QA should now able to deploy registry with GCS backend
> update registry version 3.18.3

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
Resolves CVE-2023-38325 in dbbootstrapper
https://github.com/astronomer/issues/issues/5822
QA should able to deploy db-boostrapper 
> update dbbootstrapper 0.31.6

- charts/prometheus-blackbox-exporter/templates/blackbox-networkpolicy.yaml
- tests/chart_tests/test_global_network_policy_flag.py
Black box exporter service applies network policies while global.networkPolicy  is set to false. This PR fixes the behaviour and respects the  global.networkPolicy flag
https://github.com/astronomer/issues/issues/5843
QA should able to validate with no network policies when global.networkPolicy  set to false
> blackbox-exporter: respect .global.networkPolicy.enabled

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/nginx/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- values.yaml
| ap-auth-sidecar | 1.25.1 | 1.25.2 |
|ap-cli-install | 0.26.17 | 0.26.18 |
|ap-curator | 8.0.8-1 | 8.0.8-2 | 
|ap-default-backend | 0.28.18| 0.28.19| 
|ap-elasticsearch-exporter| 1.5.0-1 | 1.6.0 | 
|ap-nginx-es| 1.25.1| 1.25.2| 
|ap-openresty | 1.21.4-9 |1.21.4-10 | 
|ap-postgres-exporte | 0.12.0-1 | 0.14.0|
| ap-vector | 0.28.2-3 | 0.32.2 |
https://github.com/astronomer/issues/issues/5882
https://github.com/astronomer/issues/issues/5881
https://github.com/astronomer/issues/issues/5879
https://github.com/astronomer/issues/issues/5878
https://github.com/astronomer/issues/issues/5877
QA should able to deploy platform 
> update latest vendor packages

- .circleci/config.yml
- charts/nginx/templates/nginx-configmap.yaml
- charts/nginx/templates/nginx-deployment.yaml
- charts/nginx/values.yaml
update nginx ingress controller 1.9.0. Adds 2 new features from upstream 
* enable-annotation-validation 
* allowSnippetAnnotations 
https://github.com/astronomer/issues/issues/5890
QA should able to deploy platform 
> update nginx ingress controller 1.9.0

- .circleci/config.yml
- charts/prometheus/values.yaml
update prometheus and configmap reloader service
|ap-configmap-reloader| 0.11.0  | 0.12.0  |
| ap-prometheus | 2.45.0 | 2.45.1 |
NA
QA should able to validate prometheus service 
> update prometheus and configmap reloader service

- .circleci/config.yml
- charts/astronomer/values.yaml
update airflow chart version 1.9.3 and commander version 0.33.3
https://github.com/astronomer/issues/issues/5895
QA should able to deploy and upgrade airflow instances
> airflow-chart 1.9.3

- charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_configmap.py
Introducing a change to switch to internal url when enableHoustonInternalAuthorization: true is enabled.
https://github.com/astronomer/issues/issues/5733
QA should able to verify airflow  ingress auth url should use internal service
> support internal houston authorization (#1964)

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander with airflow chart 1.9.4
https://github.com/astronomer/issues/issues/5904
QA should able to deploy airflow instances without any issues
> commander 0.33.4, airflowChartVersion 1.9.4

- .circleci/config.yml
- charts/astronomer/values.yaml
revert registry service version to 3.16.5-1
https://github.com/astronomer/issues/issues/5905
if configured with AWS IAM roles it should work as expected 
> revert to ap-registry 3.16.5-1

- charts/nginx/values.yaml
- tests/chart_tests/test_nginx_service.py
Enable allowSnippetAnnotations by default. This allows user configured snipped annotation to work.
https://github.com/astronomer/issues/issues/5909
QA should able to access ingress URL which has user configured snipped 
> enable nginx allow snippet annotation by default

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nginx/values.yaml
- charts/stan/values.yaml
- values.yaml
| ap-auth-sidecar | 1.25.2 | 1.25.2-1 |
| ap-cli-install | 0.26.18 | 0.26.19 |
|ap-default-backend | 0.28.19 |0.28.20 |
|ap-grafana | 10.0.8 | 10.0.9 |
| ap-init | 3.18.4 | 3.18.4-1 | 
| ap-nginx-es | 1.25.2 | 1.25.2-1 |
| ap-openresty | 1.21.4-10 | 1.21.4-11|
https://github.com/astronomer/issues/issues/5908
NA
> Update ap vendor packages

- .circleci/config.yml
- charts/nginx/values.yaml
fix  CVE-2023-38545,CVE-2023-44487  in nginx service
https://github.com/astronomer/issues/issues/5890
https://github.com/astronomer/issues/issues/5908
nginx should work as expected
> nginx ingress controller 1.9.0-1

- .circleci/config.yml
- charts/elasticsearch/values.yaml
resolves below listed CVE in curator packages
https://github.com/astronomer/issues/issues/5908
QA should able to run curator service without any errors on execution 
> update curator service 8.0.8-3

- charts/kibana/templates/kibana-networkpolicy.yaml
- tests/chart_tests/test_authsidecar.py
- tests/chart_tests/test_kibana.py
Add seperate network policy within kibana network policy template this fixes an odd behaviour when authsidecar is enabled
https://github.com/astronomer/issues/issues/5912
QA should able to validate kibana index pattern creation with authsidecar enabled
> segregate kibana index network policy

- .circleci/config.yml
- charts/astronomer/values.yaml
resolves  CVE-2023-38545,CVE-2023-44487  , CVE-2023-38039,CVE-2023-4863 in astro-ui services
https://github.com/astronomer/issues/issues/5908
https://github.com/astronomer/issues/issues/5893
QA should able to run astro-ui
> update astro-ui image 0.32.8

- .circleci/config.yml
- charts/astronomer/values.yaml
updates all the old go modules of registry distribution and docker packages to resolve CVE's.
https://github.com/astronomer/issues/issues/5787
https://github.com/astronomer/issues/issues/5772
QA should able to validate commander service 
> update commander 0.32.9

- charts/prometheus-blackbox-exporter/templates/deployment.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- tests/chart_tests/test_prometheus_blackbox_exporter.py
convert individual security context config values to single parsable config to pass user defined custom values.
One of the improvement requirement for openshift native config
https://github.com/astronomer/issues/issues/5919
Yet to update
> format to new securitycontext configuration for blackbox exporter

- .circleci/config.yml
- charts/nginx/values.yaml
update nginx ingress controller version 1.9.0 -> 1.9.4
release notes link: https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.9.4
https://github.com/astronomer/issues/issues/5954
QA should able to deploy nginx ingress controller without any issue and able to acess ingress URL
cherry-pick to release 0.32,0.33
> update nginx ingress controller 1.9.4

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/kibana/values.yaml
| imageName | oldTag | newTag |      release notes    |
|--------|--------|--------|--------|
| ap-elasticsearch | 8.8.2 | 8.9.2 | https://www.elastic.co/guide/en/elasticsearch/reference/8.9/release-notes-8.9.2.html
| ap-kibana  | 8.8.2 | 8.9.2 | https://www.elastic.co/guide/en/kibana/8.9/release-notes-8.9.2.html
https://github.com/astronomer/issues/issues/5776
QA should able to deploy elastic search without any issue
cherry-pick to release 0.32,0.33
> update elasticsearch version 8.9.2

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
update  ap-vendor images with ap-base image 3.18.4-1 to resolve the CVE in the dockerize package
imageName | oldTag | newTag
-- | -- | --
ap-postgres-exporter | 0.15.0 | 0.15.0-1
ap-curator | 8.0.8-3 | 8.0.8-4
ap-blackbox-exporter | 0.24.0-2 | 0.24.0-3
ap-awsesproxy | 1.5.0-1 | 1.5.0-2
ap-init | 3.18.4-1 | 3.18.4-2
ap-base| 3.18.4 | 3.18.4-1
<br class="Apple-interchange-newline">
https://github.com/astronomer/issues/issues/5960
https://github.com/astronomer/issues/issues/5866
https://github.com/astronomer/issues/issues/5873
QA should be able to deploy all the components without any issues 
cherry-pick to release 0.32,0.33
> Update vendor packages in astronomer/astronomer

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- values.yaml
imageName | oldTag | newTag | extraInfo
-- | -- | -- | --
ap-auth-sidecar | 1.25.2-1 | 1.25.2-2 | resolves CVE-2023-43787
ap-nginx-es | 1.25.2-1 | 1.25.2-2 | resolves CVE-2023-43787
https://github.com/astronomer/issues/issues/5974
QA should be able to deploy ap-auth-sidecar and ap-nginx-es without any issues. 
cherry-pick to release 0.32,0.33
> update nginx base packages in astronomer 

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/nginx/values.yaml
resolves CVE-2023-43787 in below services
| ap-cli-install | 0.26.19 |0.26.20 |
| ap-default-backend |0.28.20 |0.28.21 |
https://github.com/astronomer/issues/issues/5974
NA
cherry-pick to release-0.32, release-0.33
> update nginx base in vendor packages

- .circleci/config.yml
- values.yaml
resolves CVE in ap-vector services
https://github.com/astronomer/issues/issues/5960
https://github.com/astronomer/issues/issues/5873
NA
cherry-pick to release-0.32, release-0.33
> update vector image 0.32.2 -> 0.32.2-1

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/external-es-proxy/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
- charts/stan/values.yaml
- values.yaml
| ap-fluentd | 1.16.2-1 | 1.16.2-2 |
| ap-nats-exporter | 0.12.0 | 0.12.0-1 |
| ap-nats-server | 2.10.2 | 2.10.2-1 |
| ap-nats-streaming | 0.25.5 | 0.25.5-1 |
| ap-openresty | 1.21.4-11 | 1.21.4-12 | 
| ap-db-bootstrapper | 0.31.6 | 0.31.7 |
https://github.com/astronomer/issues/issues/5960
QA should able to run astronomer platform without issues
cherry-pick to release-0.32. release-0.33
> update vendor packages in astronomer helm chart

- .circleci/config.yml
- charts/external-es-proxy/values.yaml
updates aws-es-proxy go modules to resolve x/net CVE
https://github.com/astronomer/issues/issues/5960
NA
cherry-pick to release-0.32, release-0.33
> update aws-es-proxy version 1.5.0-3

- .circleci/config.yml
- charts/astronomer/values.yaml
| ap-houston-api | 0.33.7 | 0.33.8 |
| ap-astro-ui | 0.33.5 | 0.33.6 |
houston-api
Related https://github.com/astronomer/issues/issues/5977
Related https://github.com/astronomer/issues/issues/5966
Related https://github.com/astronomer/issues/issues/5942
Related https://github.com/astronomer/issues/issues/5950
Related https://github.com/astronomer/issues/issues/5942
Related https://github.com/astronomer/issues/issues/5948
Related https://github.com/astronomer/issues/issues/5922
Related https://github.com/astronomer/issues/issues/5953
astro-ui
Related https://github.com/astronomer/issues/issues/5948
Related https://github.com/astronomer/issues/issues/5914
QA should able to verify above link issues
> update houston-api and astro-ui images

- .circleci/config.yml
- charts/astronomer/values.yaml
| ap-astro-ui | 0.33.6 | 0.33.8 |
| ap-houston-api | 0.33.8 | 0.33.9 |
Related https://github.com/astronomer/issues/issues/5948
QA should able to verify above link issues
> update  houston-image and astro-ui-image

- .circleci/config.yml
- charts/astronomer/values.yaml
Add supports for triggerer pod status
https://github.com/astronomer/issues/issues/5722
https://github.com/astronomer/issues/issues/5977
QA should able to validate triggerer pod status 
> update houston 0.33.11 and astro-ui 0.33.9

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
- values.yaml
|ap-base | 3.18.4-1 | 3.18.4-2 |  
| ap-blackbox-exporter | 0.24.0-3 | 0.24.0-4 |  
| ap-nats-exporter | 0.12.0-1 |0.12.0-2 |
| ap-nats-server | 2.10.2-1 | 2.10.2-2 |
| ap-curator | 0.25.5-1 | 0.25.5-2 |
| ap-awsesproxy | 1.5.0-3 | 1.5.0-4 |
| ap-init | 3.18.4-2 | 3.18.4-3 |
| ap-openresty | 1.21.4-12 | 1.21.4-13 |
| ap-postgres-exporter | 0.15.0-1 | 0.15.0-2 | 
| ap-authsidecar | 1.25.2-2 | 1.25.2-3 |
| ap-nginx-es | 1.25.2-2 | 1.25.2-3 |
| ap-nginx | 1.9.4 | 1.9.4-1 | 
| ap-cli-install | 0.26.20 | 0.26.21 | 
| ap-default-backend | 0.28.21 | 0.28.22 |
https://github.com/astronomer/issues/issues/5988
QA basic sanity testing to be done
> fix CVE-2023-5678 in vendor packages

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
update ap-db-bootstrapper version 0.31.9
https://github.com/astronomer/issues/issues/5976
NA
cherry-pick to release-0.32,0.33
> update ap-db-bootstrapper version 0.31.9

- .circleci/config.yml
- charts/prometheus-node-exporter/values.yaml
Update  node_expoter version from 1.6.1 to 1.7.0
imageName | oldTag | newTag
-- | -- | --
node_expoter | 1.6.1 | 1.7.0
https://github.com/astronomer/issues/issues/6008
QA should be able to deploy without any issues.
cherry-pick to release 0.32, 0.33
> node-exporter 1.7.0

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander version 0.32.10 and airflow chart 1.8.9
https://github.com/astronomer/issues/issues/6007
https://github.com/astronomer/issues/issues/6006
QA should able to deploy airflow without issues
> update commander version 0.32.10 and airflow chart 1.8.9

- .circleci/config.yml
- charts/grafana/values.yaml
update grafana version 10.1.5
resolves permission issue caused by newer grafana version
https://github.com/astronomer/issues/issues/5775
QA should able to see all dashboards for fresh install
> update grafana version 10.1.5

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/fluentd/values.yaml
- charts/kibana/values.yaml
- charts/kube-state/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
imageName | oldTag | newTag
-- | -- | --
ap-base | 3.18.4-2 | 3.18.5
ap-blackbox-exporter | 0.24.0-4 | 0.24.0-5
ap-nats-exporter | 0.13.0 | 0.13.0-1
ap-nats-server | 2.10.9 | 2.10.9-1
ap-curator | 8.0.8-5 | 8.0.8-6
ap-awsesproxy | 1.5.0-5 | 1.5.0-6
ap-init | 3.18.4-3 | 3.18.5
ap-postgres-exporter | 0.15.0-2 | 0.15.0-3
ap-fluentd | 1.16.2-2 | 1.16.3 
ap-kibana | 8.9.2 | 8.11.4 
ap-nginx | 1.9.4-1 | 1.9.5 
ap-kubesate | 2.8.2 | 2.10.1 
ap-openresty | 1.21.4-13 | 1.25.3
ap-prometheus | 2.45.1 | 2.45.2
ap-nats-streaming | 0.25.5-1 | 0.25.6
https://github.com/astronomer/ap-vendor/pull/669
https://github.com/astronomer/ap-vendor/pull/666
https://github.com/astronomer/ap-vendor/pull/677
https://github.com/astronomer/ap-vendor/pull/676
https://github.com/astronomer/ap-vendor/pull/667 …
> Update ap-vendor-packages 

- .circleci/config.yml
- charts/nats/values.yaml
- charts/stan/values.yaml
| ap-nats-exporter | 0.13.0-1 | 0.14.0 |
NA
nats exporter metrics endpoint should work as expected
> update nats exporter version 0.14.0

- charts/kube-state/values.yaml
- tests/chart_tests/test_kube_state_deployment.py
by default kube-state-metrics 2.10.x has changed the default behaviour of exposing pod lables to reduce the memory usage and number of metrics being exposed, since we are relying on that metrics we have updated our kube-state-metrics command args to include pod label metrics to resolve this issue
https://github.com/astronomer/issues/issues/6084
QA should able to verify the metrics tab with all the necessary metrics
cherry-pick to all valid release version
> update kube state metrics command args

- .circleci/config.yml
- charts/grafana/values.yaml
upgrade grafana version 10.2.3
https://github.com/astronomer/issues/issues/6060
https://github.com/astronomer/issues/issues/5880
QA should able to validate grafana dashboard without auth when logged in with SYS_ADMIN 
> upgrade grafana version 10.2.3

- charts/astronomer/templates/registry/registry-statefulset.yaml
- tests/chart_tests/test_registry_statefulset.py
fixes an issue where private ca added in wrong indent causing registry deployment not exposing ca-volumes causing deployments to not able to patch 
https://github.com/astronomer/issues/issues/5939
QA should able to see CA certs when registry type is deployment 
> add custom ca volume on right indent

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/generate_circleci_config.py
- .pre-commit-config.yaml
- Makefile
- bin/verify_image_tags.py
- Add `bin/verify_image_tags.py` which ensures that there is only one tag version for every docker image
- Add verify-image-tags pre-commit hook that runs `bin/verify_image_tags.py` when tpl or yaml files are changed.
- Modernize the .circleci config by removing deprecated fields
- Use `--set forceIncompatibleKubernetes=true` so that `make show-docker-images` will always succeed.
https://github.com/astronomer/issues/issues/6115
I've tested this manually on my computer. These are only dev workflow changes, so there are no production concerns here.
This should be merged everywhere.
> Prevent multiple component versions

- .circleci/config.yml
- charts/astronomer/values.yaml
revert upstream registry repo since aws iam role is broken in distribution repo upstream
https://github.com/astronomer/issues/issues/5939
https://github.com/astronomer/issues/issues/5905
QA should able to validate aws iam roles with new image
> update ap-registry 3.16.5-1 -> 3.18.5-1

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_astronomer_dag_only_deploy.py
- values.yaml
- Adding functionality to enable dag only deployment controls from global values
- Add security context default and override
https://github.com/astronomer/issues/issues/5969
unit tests are included, but we'll need testing from QA.
This is only for release-0.34
> add dagOnlyDeployment feature flag in astronomer helm chart

- .circleci/config.yml
- .circleci/config.yml.j2
- Use cimg/base:current-22.04
- use /usr/bin/bash for shell
- move shell options to their own step
https://github.com/astronomer/issues/issues/6125
This should be manually tested. It only affects dev workflows, not the product itself.
This should be merged everywhere
> Fix broken scan-docker-images CI job

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api version 0.34.2
Related https://github.com/astronomer/issues/issues/6109
Related https://github.com/astronomer/issues/issues/6120
Related https://github.com/astronomer/issues/issues/5969
Related https://github.com/astronomer/issues/issues/6109
NA
> update houston api version 0.34.2

- charts/astronomer/templates/houston/houston-configmap.yaml
- templates/_helpers.tpl
- tests/chart_tests/test_astronomer_dag_only_deploy.py
Add out of box private registry support for dag deploy
QA should able to enable private and does not require to modify image for dag server
> Add out of box private registry support for dag deploy

- Makefile
- bin/show-docker-images.py
- charts/alertmanager/templates/alertmanager-statefulset.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/grafana/templates/grafana-deployment.yaml
- charts/kibana/templates/kibana-deployment.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- templates/_helpers.tpl
Add a python script that parses the output of `helm template` and finds all the container specs and prints the images that are used in them. This avoids printing containers that are inside of nested yaml like the houston configmap.
```
$ bin/show-docker-images.py --help
usage: show-docker-images.py [-h] [--private-registry] [-v]
options:
-h, --help          show this help message and exit
--private-registry
-v, --verbose
```
https://github.com/astronomer/issues/issues/6113
https://github.com/astronomer/issues/issues/4862 - fixing this issue as well with this PR
I've tested this extensively while developing, which is enough. This is not a product feature and is not customer facing so no QA is needed.
This should be merged everywhere.
> Add bin/show-docker-images.py

- .circleci/config.yml
- charts/postgresql/values.yaml
update postgresql version 15.5.0
https://github.com/astronomer/issues/issues/6134
since we are upgrading from 15.4.0 -> 15.5.0 basic upgrade sanity should be fine
cherry-pick to release branches
> update postgresql version 15.5.0

- .circleci/config.yml
- values.yaml
update vector image with latest ap-base 
resolves CVE-2023-7104  
https://github.com/astronomer/issues/issues/5984
basic sanity testing is okay 
> update vector image version

- templates/_helpers.tpl
- templates/trust-private-ca-on-all-nodes/containerd-daemonset.yaml
- templates/trust-private-ca-on-all-nodes/daemonset.yaml
- tests/enable_all_features.yaml
- values.yaml
move cert copier image alpine:3.18 to astronomer managed quay repo 
alpine:3.18 -> quay.io/astronomer/ap-base:3.18 
https://github.com/astronomer/issues/issues/6102
when global private registry it should auto switch to private registry
> Replace cert copier image

- charts/astronomer/templates/houston/helm-hooks/houston-db-migration-job.yaml
Workaround to an order-of-operations bug that we discovered. More details in the issue linked below.
https://github.com/astronomer/issues/issues/6152
This solves a problem where houston requires deploys to happen twice before picking up the AU vs resources configuration setting.
AFAIK this would only be needed in release-0.34, but the root cause may be happening elsewhere and we haven't noticed.
> Make houston-db-migrations run both pre-upgrade and post-upgrade helm hooks

- bin/waitfor-platform
This works around a false positive when checking for failures during CI. This may be the root cause of astronomer/issues#6136
astronomer/issues#6158
No manual tests needed, CI is sufficient.
> Work around kibana-default-index false positive

- templates/_helpers.tpl
- templates/trust-private-ca-on-all-nodes/daemonset.yaml
- tests/enable_all_features.yaml
- values.yaml
move cert copier image alpine:3.18 to astronomer managed quay repo
https://github.com/astronomer/issues/issues/6102
when global private registry it should auto switch to private registry
> replace cert copier image (#2116)

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/stan/values.yaml
- values.yaml
Update AP base image from 3.18.5 --> 3.18.6
imageName | oldTag | newTag | CVE-UPDATES
-- | -- | -- | --
ap-base | 3.18.5 | 3.18.6
ap-awsesproxy | 1.5.0-6 | 1.5.0-7 | CVE-2023-6129, CVE-2023-6237
ap-blackbox-exporter | 0.24.0-5 | 0.24.0-6  | CVE-2023-6129, CVE-2023-6237
ap-curator | 8.0.8-6 |8.0.8-7 | CVE-2023-6129, CVE-2023-6237
ap-git-daemon | 3.18.5 | 3.18.6 | CVE-2023-6129, CVE-2023-6237
ap-git-sync-relay | 0.0.3-1 | 0.0.3-2
ap-init | 3.18.5 | 3.18.6 | CVE-2023-6129, CVE-2023-6237
ap-nats-exporter | 0.14.0 | 0.14.0-1 | CVE-2023-6129, CVE-2023-6237
ap-nats-server | 2.10.9-1 | 2.10.9-2
ap-nats-streaming | 0.25.6 | 0.25.6-1 | CVE-2023-29406, CVE-2023-29409, <br /> CVE-2023-39318,  CVE-2023-39319 , <br /> CVE-2023-39323, CVE-2023-46129, <br /> CVE-2023-47090, CVE-2023-46129 …
> update base and circleci config

- .circleci/config.yml
- charts/astronomer/values.yaml
updating astro-ui image from 0.32.9 to 0.32.10
https://github.com/astronomer/astro-ui/pull/1701
QA should able to validate above linked issue
> astro-ui 0.32.10

- .circleci/config.yml
- charts/astronomer/values.yaml
update airflow commander version 1.8.10
NA
QA should verify generic flow
> update airflow commander version 1.8.10

- charts/prometheus/templates/prometheus-config-configmap.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_prometheus_config_configmap.py
We want to scrape other services like ie: Push gateway running on the same cluster and we need to be able to modify the Prometheus configuration. 
is this something that could be supported by Astronomer?
> add additional scrape jobs for prometheus

- .circleci/config.yml
- charts/alertmanager/values.yaml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/postgresql/values.yaml
- charts/prometheus/values.yaml
|ap-postgresql|15.5.0-1|15.6.0
|ap-curator|8.0.8-7|8.0.9
|ap-grafana|10.2.3|10.2.4
|ap-alertmanager|0.26.0|0.27.0
|ap-prometheus|2.45.3|2.45.4
|ap-nginx-es|1.25.3-1|1.25.4
NA
> Update ap verdor packages 

- .circleci/config.yml
- charts/nginx/values.yaml
- tests/functional_tests/test_config.py
> Update nginx version 1.9.5 -> 1.9.6

- bin/generate_circleci_config.py
Abort `bin/generate_circleci_config.py` if Calico CRDs are not found for k8s versions that are being added to `.circleci/config.yml`. This has bitten us before, and it's not a huge deal, but it is wasteful and time consuming to have to go through that iteration.
I canceled CI because no CI-facing code changed. This is strictly a developer local-workstation change.
https://github.com/astronomer/issues/issues/6240
This is strictly a dev workflow improvement, not customer facing, and does not change the shipped product in any way, so no QA is needed.
> Add check for Calico CRDs for each tested k8s version

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
|ap-nats-server |2.10.9-2|2.10.10
|ap-base| 3.18.6| 3.18.6-1
|ap-awsesproxy| 1.5.0-7 | 1.5.0-8
|ap-blackbox-exporter| 0.24.0-6 | 0.24.0-7
|ap-curator | 8.0.13| 8.0.13-1
|ap-nats-exporter| 0.14.0-1| 0.14.0-2
|ap-nats-streaming| 0.25.6-1| 0.25.6-2
|ap-pgbouncer-krb| 1.17.0-10 | 1.17.0-11
|ap-postgres-exporter|0.15.0-4|0.15.0-5
|ap-registry| 3.18.6-1|3.18.6-2
NA
> Update ap-base image and nat-server version 

- .circleci/config.yml
- charts/postgresql/values.yaml
update postgresql base image version 15.6.0-1
https://github.com/astronomer/issues/issues/6248
NA
> update postgresql base image version 15.6.0-1

- charts/astronomer/templates/_helpers.yaml
- charts/nats/templates/_helpers.tpl
- charts/nats/values.yaml
- tests/chart_tests/test_nats_jetstream.py
This PR fixes an issue where mounted client side tls are not respected by the system path due long nested path. 
https://github.com/astronomer/issues/issues/6259
QA should not see any TLS error in nats service
> fix jetstream client certificate mount path

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_openshift.py
PR supresses a issue where airflow runtime services failed to comes up with native openshift configuration
https://github.com/astronomer/issues/issues/6261
QA should able to create runtime deployments with no extra privileges
> updates airflow services with security context

- .circleci/config.yml
- values.yaml
imageName | oldTag |new tag | 
-- | -- | -- |
ap-vector| 0.32.2-4 | 0.33.1-1
After enabling sidecar with create deployments with previous version of sidecar , after deployment comes up update to newer version of sidecar to see if it still works fine and able to view and query logs in the UI and kibana.
> Update ap-vector version 0.32.2-4 -> 0.33.1-1

- charts/nats/templates/statefulset.yaml
- tests/chart_tests/test_nats_sts.py
combined config from two metadata.annotations
There are two annotation sections in the NATS statefulsets, 
fixes: https://github.com/astronomer/issues/issues/6284
> remove duplicate annotation in nats statefulset

- charts/astronomer/templates/commander/commander-role.yaml
Add PodDisruptionBudget permissions to commander role
https://github.com/astronomer/issues/issues/6295
Unfortunately I do not know of a good way to test this automatically without writing a bunch of involved functional test code.
QA can test this by:
1. Install this version of the astronomer chart with pdb enabled (`global.podDisruptionBudgetsEnabled=true`)
2. Create a new airflow deployment
3. Upgrade the airflow deployment by creating a new env var or something
4. Verify that the upgrade succeeded and no `patch` error occurred.
This should be merged everywhere since it is a permission bug that will affect all of our versions and the fix is small and easy.
> Add pdb patch permissions to commander role

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
update db bootstrapper image to support mysql and postgresql
QA should validate that bootstrapper recognises the connection string and creates secret if any of supported db are found
> update db bootstrapper image

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_authsidecar.py
- values.yaml
add security context support for auth sidecar service
https://github.com/astronomer/issues/issues/6328
QA should validate passing securityContext from helm values to see if it gets interpretted to airflow components for more info on testing check the issues
> add support for authsidecar security context

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_astronomer_dag_only_deploy.py
Fixes a behaviours where dag server resources are not formatted to newly configured resource spec.
This PR addresses the issue to pass the resources properly back to dag server and client
https://github.com/astronomer/issues/issues/6348
QA should able to override resource from global dagServer values
```
global:
dagOnlyDeployment:
enabled: true
image: quay.io/astronomer/ap-dag-deploy:0.3.2
securityContext:
fsGroup: 50000
resources:
limits:
cpu: 100m
memory: 400Mi
requests:
cpu: 100m
memory: 400Mi
```
cherry-pick to release-0.34, 0.35
> move dag server resource to new supported format

- charts/external-es-proxy/templates/external-es-proxy-configmap.yaml
- tests/chart_tests/test_data/default-external-es-nginx.conf
- tests/chart_tests/test_data/external-es-nginx-with-aws-secrets.conf
- tests/chart_tests/test_external_elasticsearch.py
Fixes log search in search endpoint to its own indexes
https://github.com/astronomer/issues/issues/6339
QA should able to see task logs in webserver
cherry-pick to release-0.34, release-0.35
> fix external es search configuration

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.34.6
https://github.com/astronomer/issues/issues/6335
https://github.com/astronomer/houston-api/pull/1664
https://github.com/astronomer/issues/issues/6216
Updated more info on ticket
cherry-pick to release-0;34
> ap-houston-api 0.34.6

- charts/grafana/templates/grafana-deployment.yaml
- tests/chart_tests/test_grafana.py
Adds support for securityContext for db-bootstrapper init container configuredin grafana  service.
QA should able to validate securityContext in db-boostrapper initContainer in grafana service
Not decided yet which release it will be mapped for so leaving it on master
> add grafana db-bootstrapper securityContext

- charts/nats/templates/jetstream-job.yaml
- tests/chart_tests/test_nats_jetstream.py
currently jetstream job does not have securityContext defined , this PR adopts nats securityContext configuration to jetstream to share same securityContext
> add nats securityContext to jetstream job

- templates/trust-private-ca-on-all-nodes/containerd-daemonset.yaml
- tests/chart_tests/test_containerd_privateca.py
- values.yaml
Add priority class support for containerd daemonset service 
https://github.com/astronomer/issues/issues/6366
user should able to pass priorityclass 
```yaml
global:
privateCaCertsAddToHost:
enabled: true
addToContainerd: true
priorityClassName: xyz
```
> add priorityclass support for containerd daemonset

- charts/stan/templates/statefulset.yaml
- tests/chart_tests/test_stan_sts.py
This PR adds support for configurable securityContext for stan service to support passing securityContext from values 
QA should able to pass supported securityContext at container level for stan service
> add configurable security context for stan service

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/config-syncer/config-syncer-cronjob.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_config_syncer.py
Adds securitycontext support for config syncer job
QA should able to pass supported securityContext at container level for config syncer job  service
> add security context support for config syncer cron job

- charts/kibana/values.yaml
- charts/prometheus-node-exporter/templates/daemonset.yaml
- charts/prometheus-postgres-exporter/templates/deployment.yaml
- charts/prometheus-postgres-exporter/values.yaml
- tests/chart_tests/test_prometheus_node_exporter.py
- tests/chart_tests/test_prometheus_postgres_exporter.py
rework securityContext config for prometheus-node-exporter and postgres-exporter
QA should able to pass multiple securityContext config for above mentioned services
> update security context for missing exporters

- charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
- tests/chart_tests/test_global_network_policy_flag.py
Add a NetworkPolicy to be used with dag-deploy server to communicate with houston about new files that are uploaded.
https://github.com/astronomer/issues/issues/6233
Tests are included. I have also manually tested this. QA doesn't need to do any testing specific to this PR because it will be quite obvious if it's not working as intended.
Merge only to release-0.35 because rollback feature is only intended for 0.35.
> 6233 networkpolicy for dag deploy rollback

- charts/nats/templates/jetstream-job.yaml
- charts/nats/values.yaml
- tests/chart_tests/test_nats_jetstream.py
Add flag to disable jetstream job 
https://github.com/astronomer/issues/issues/6245
QA should pass to disable jetstream hook job
```
nats:
nats:
createJetStreamJob: false 
```
cherry-pick to release-0.34,release-0.35
> add flag to disable jetstream job

- templates/trust-private-ca-on-all-nodes/containerd-daemonset.yaml
- tests/chart_tests/test_containerd_privateca.py
- values.yaml
Add support for configurable containerd hostPath
https://github.com/astronomer/issues/issues/6341
QA should able to override the containerd hostpath
cherry-pick to release-0.34 and release-0.35
> add configurable containerd host path

- charts/astronomer/templates/commander/commander-role.yaml
Add role to get kubernetes job details from commander
https://github.com/astronomer/issues/issues/6309
while making downgrade  our internal service should downgrade the airflow deployments sucessfully
> modify commander role to get job name in rbac

- charts/elasticsearch/templates/curator/es-curator-cronjob.yaml
- charts/elasticsearch/values.yaml
- tests/chart_tests/test_elasticsearch.py
Add support for allowing security context to elasticsearch curator cronjob
QA should able to override or add security context for elasticsearch cron jon
> Add configurable container securityContext for curator cronjob

- charts/elasticsearch/templates/exporter/es-exporter-deployment.yaml
- charts/elasticsearch/templates/nginx/nginx-es-deployment.yaml
- charts/elasticsearch/values.yaml
- tests/chart_tests/test_elasticsearch.py
removed hardcoded security context from elasticsearch exported and reworked it support both pod and container security context and tweaked default privilges
elasticsearch exporter should able to expose metrics
cherry-pick to releaase-0.35
> add es security context for missing components

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
- tests/functional_tests/conftest.py
- tests/functional_tests/test_config.py
This PR updates db boostrapper service to 0.35.4 and includes various fixes
Implements funtional testing to validate connection strings assertion
https://github.com/astronomer/issues/issues/6430
funtional tests should pass and connection strings should include service specific db_name
> add functional test for connection strings validation

- .circleci/config.yml
- charts/alertmanager/values.yaml
update alertmanager version 0.27.0-1
https://github.com/astronomer/issues/issues/6334
> update alertmanager version 0.27.0-1

- .circleci/config.yml
- charts/astronomer/values.yaml
update airflow chart 1.11.1 and commander 0.35.1
https://github.com/astronomer/issues/issues/6423
https://github.com/astronomer/issues/issues/6383
https://github.com/astronomer/issues/issues/6309
https://github.com/astronomer/issues/issues/6403
refer issue ticket 
> update airflow chart 1.11.1 and commander 0.35.1

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston-api 0.35.3 -> 0.35.4
Related https://github.com/astronomer/issues/issues/6452
Related https://github.com/astronomer/issues/issues/6394
Related https://github.com/astronomer/issues/issues/6404
Related https://github.com/astronomer/issues/issues/6446
refer above linked issues
> update houston-api 0.35.3 -> 0.35.4

- .circleci/config.yml
- charts/astronomer/values.yaml
update astro-ui image to 0.35.2
Related https://github.com/astronomer/issues/issues/6456
> update astro-ui image to 0.35.2

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander and houston api images
| Header | Header | Header |
| quay.io/astronomer/ap-commander | 0.35.1 | 0.35.2 |
| quay.io/astronomer/ap-houston-api | 0.35.4 | 0.35.5 |
Related https://github.com/astronomer/issues/issues/6456
Related https://github.com/astronomer/issues/issues/6459
Related https://github.com/astronomer/issues/issues/6309
Related https://github.com/astronomer/issues/issues/6403
refer linked tickets
> update commander and houston api images

- .circleci/config.yml
- charts/astronomer/values.yaml
rename dag server annotation to correct naming to fix reuse values bug
https://github.com/astronomer/issues/issues/6459
> update commander image 0.35.3

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
db-bootstrapper 0.35.5
https://github.com/astronomer/issues/issues/6430
We need to test both mysql and postgres with underscores and hyphens to make sure the behavior is consistent and does not throw db connection errors.
This should be merged everywhere because it is a bugfix for db-bootstrapper and is not specific to the 0.35 release.
> db-bootstrapper 0.35.6

- .circleci/config.yml
- charts/alertmanager/values.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-node-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
- values.yaml
Image Name | Old Tag | New Tag
-- | -- | -- | 
ap-base | 3.18.6-2 | 3.18.7-1
ap-alertmanager | 0.27.0-1 | 0.27.0-2
ap-awsesproxy | 1.5.0-8 | 1.5.0-9
ap-blackbox-exporter | 0.25.0 | 0.25.0-1
ap-curator | 8.0.14 | 8.0.15-1 
ap-init | 3.18.6-2 | 3.18.7-1
ap-nats-exporter | 0.15.0 | 0.15.0-1 
ap-nats-server | 2.10.14 | 2.10.14-1
ap-nats-streaming | 0.25.6-3 |0.25.6-4 
ap-pgbouncer-krb | 1.17.0-11 | 1.17.0-12
ap-postgres-exporter| 0.15.0-5 | 0.15.0-6
ap-registry | 3.18.6-2 | 3.18.7-1 
ap-configmap-reloader | 0.12.0 | 0.13.1
ap-grafana |  10.2.4 | 10.4.5 
ap-prometheus | 2.45.5 | 2.45.6
ap-node-exporter | 1.8.1 | 1.8.1-1
ap-vector | 0.33.1-1 | 0.38.0-1
ap-kibana| 8.12.0 | 8.12.1
ap-elasticsearch| 8.12.0 | 8.12.1
https://github.com/astronomer/issues/issues/6305 …
> Updating ap-vendor packages

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.34.11 
https://github.com/astronomer/issues/issues/6374
https://github.com/astronomer/issues/issues/5623
https://github.com/astronomer/issues/issues/6489
https://github.com/astronomer/issues/issues/6421
refer above issues 
> update houston api 0.34.11

- charts/astronomer/templates/commander/commander-networkpolicy.yaml
- charts/astronomer/templates/registry/registry-networkpolicy.yaml
Remove commander expire-deployments networkPolicies. This is a follow-up to https://github.com/astronomer/astronomer/pull/2252
https://github.com/astronomer/issues/issues/6510
No extra human testing needed. However, if we do encounter any failures related to this, it only points to an additional bug. It is unlikely we have such a bug, but if we do find one, we should fix it instead of worrying about this change. With that in mind, all we need to do is be aware that this change has been made.
Merge everywhere that we are merging https://github.com/astronomer/astronomer/pull/2252
> Remove commander expire-deployments networkPolicies

- .circleci/config.yml
- charts/astronomer/values.yaml
update airflow chart 1.11.4 and commander version 0.35.6
https://github.com/astronomer/issues/issues/6487
https://github.com/astronomer/issues/issues/6506
https://github.com/astronomer/issues/issues/6518
refer issue tickets
> update airflow chart 1.11.4 and commander version 0.35.6

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston-api version 0.35.6
https://github.com/astronomer/issues/issues/6487
https://github.com/astronomer/issues/issues/6506
https://github.com/astronomer/issues/issues/6451
refer linked tickets 
> update houston-api version 0.35.6

- .circleci/config.yml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_dag_only_deploy.py
- values.yaml
enable dag server persistance spec 
https://github.com/astronomer/issues/issues/6436
```
global:
dagOnlyDeployment:
enabled: true
persistence:
persistentVolumeClaimRetentionPolicy:
whenDeleted: Delete
whenScaled: Retain
```
Action explanation:
whenDeleted: Delete - this means once the statefulset template is deleted kubernetes will automatically delete the pvc as well
whenScaled: Retain. - his means once the statefulset scaled up or down pvc is retained
> enable dag server persistance spec

- values.yaml
ap-dag-deploy 0.5.2 makes rollbacks and dag-deploy work well together.
https://github.com/astronomer/issues/issues/6393
This will need a lot of testing.
Merge to 0.35, 0.36.
> ap-dag-deploy:0.5.2

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.35.8 and astro-ui 0.35.5
Related https://github.com/astronomer/issues/issues/6422
Related https://github.com/astronomer/issues/issues/6498
Related https://github.com/astronomer/issues/issues/6393
Related https://github.com/astronomer/issues/issues/6513
refer issue tickets 
> update houston api 0.35.8 and astro-ui 0.35.5

- .circleci/config.yml
- charts/astronomer/templates/houston/cronjobs/houston-cleanup-deploy-revisions-cronjob.yaml
- charts/astronomer/values.yaml
- values.yaml
update houston api 0.35.9 and dag server with 0.5.3
Related https://github.com/astronomer/issues/issues/6531 
Related https://github.com/astronomer/issues/issues/6455
Related https://github.com/astronomer/issues/issues/6529
Related https://github.com/astronomer/issues/issues/6451
> houston-api 0.35.9, dag-server 0.5.3

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.35.10
https://github.com/astronomer/issues/issues/6527
NA
cherry-pick to master, release-0.35
> update houston api 0.35.10

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/nginx/values.yaml
| imageName | oldVersion | newVersion |
| ap-cli-install | 0.26.24 | 0.26.25 |
| default-backend | 0.28.25 | 0.28.26 |
https://github.com/astronomer/issues/issues/6533
NA
cherry-pick release-0.35, release-0.36
> cli-install 0.26.25, default-backend 0.28.26

- charts/alertmanager/templates/alertmanager-statefulset.yaml
- charts/alertmanager/values.yaml
- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- charts/elasticsearch/values.yaml
- charts/postgresql/templates/statefulset-slaves.yaml
- charts/postgresql/templates/statefulset.yaml
- charts/postgresql/values.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/values.yaml
- charts/stan/templates/statefulset.yaml
- charts/stan/values.yaml
- tests/chart_tests/test_alertmanager.py
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_postgres.py
- tests/chart_tests/test_prometheus_statefulset.py
- tests/chart_tests/test_stan_sts.py
Adds persistance policy support for below components
alertmanager
prometheus
elasticsearch
postgresql
stan
scope: for POC adding these policy cleans up the pvc after the uninstallation of platform
https://github.com/astronomer/astronomer/issues/1974
cherry-pick to release-0.35 and release-0.36
> add persistance policy for platform components

- charts/kibana/templates/kibana-deployment.yaml
- tests/chart_tests/test_kibana.py
currenly with existing kibana we see below warning 
with this new change the warning will go away 
https://github.com/astronomer/issues/issues/6539
https://github.com/astronomer/astronomer/issues/1275
QA should not see any warning when kibana url is opened
cherry-pick to release-0.35 and release-0.36
> fix kibana ui warnings

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
- values.yaml
Update ap-base packages with 3.18.8
Image Name |  old  Tag| New tag |
-- | -- | -- |
ap-blackbox-exporter | 0.25.0-1| 0.25.0-2
ap-registry| 3.18.7-1 | 3.18.8
ap-postgres-exporter|0.15.0-6 |  0.15.0-7
ap-nats-streaming| 0.25.6-4 | 0.25.6-5
ap-nats-server| 2.10.14-1 | 2.10.14-2
ap-nats-exporter| 0.15.0-1 | 0.15.0-2
ap-init | 3.18.7-1 | 3.18.8
ap-curator | 8.0.15-1 |  8.0.16-1
ap-awsesproxy| 1.5.0-9 | 1.5.0-10
ap-vector | 0.48.0| 0.48.0-1
ap-pgbouncer-krb |1.17.0-12 | 1.17.0-13
ap-base | 3.18.7-1 | 3.18.3 
All components should run without any issues 
Need to Cherry-pic release-0.34,0.35,0.36
> Update ap base packages

- .circleci/config.yml
- .pre-commit-config.yaml
- Makefile
- bin/test-ap
- charts/fluentd/values.yaml
- charts/prometheus/values.yaml
| Image Name    | Old-tag | New-tag  |
| ------------- | ------- | -------- |
| ap-prometheus | 2.45.6  | 2.53.1   |
| ap-fluentd    | 1.16.5  | 1.17.0-1 |
https://github.com/astronomer/issues/issues/6514
Due to the huge fluentd changes we will need to test this one quite a bit and make sure all fluentd logging scenarios are working as expected. @pgvishnuram is the SME on what edge cases may pop up due to these changes.
cherry-pick to 0.35,0.36 and 0.34 branches
> Update prometheus and  fluentd packages

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander 0.36.2 with airflow chart 1.11.4
https://github.com/astronomer/issues/issues/6401
https://github.com/astronomer/issues/issues/6547
https://github.com/astronomer/issues/issues/6523
https://github.com/astronomer/issues/issues/6401
refer issue tickets
> update commander 0.36.2 with airflow chart 1.11.4

- .circleci/config.yml
- charts/nginx/values.yaml
This is a yolo attempt at blindly bumping the version of nginx from 1.9.x to 1.11.x to see if it works. There may be changes between these two versions that cause this to break, so we'll have to pay attention to all nginx-ingress related things. Looking at the [list of breaking changes](https://github.com/kubernetes/ingress-nginx/issues/10186) between 1.9 and 1.11, I think we should be good with 1.11.
- https://github.com/astronomer/issues/issues/6591
All nginx-ingress related features should be tested.
This should be cherry-picked into all supported versions to fix CVE-2024-7646.
> Fix CVE-2024-7646 by bumping nginx to 1.11.2

- charts/nginx/templates/nginx-deployment.yaml
- charts/nginx/values.yaml
- tests/chart_tests/test_nginx_service.py
This PR adds electionTTL configurable args to nginx ingress controller
https://github.com/astronomer/issues/issues/6600
QA should able to validate electionTTL args in nginx deployment spec 
cherry-pick to all valid releases which has nginx ingress >= 1.11
> add nginx electionTTL overrides

- .circleci/config.yml
- charts/postgresql/values.yaml
- values.yaml
Image Name |  Old-tag|  New-tag 
-- | -- | -- 
ap-vector | 0.40.0-1 |0.40.1
ap-postgresql | 15.7.0-1 | 15.8.0
QA should see the components up and running and able see the all the logs when logging side car enabled 
this PR should be cherry-picked into release-0.34, 0.35, 0.36
> updating vector and postgresql packages

- charts/fluentd/templates/fluentd-configmap.yaml
Add airflow downgrade component logs support in fluentd
https://github.com/astronomer/issues/issues/6401
QA should able to see logs in the astro ui when a downgrade is triggered 
> add airflow downgrade component logs for fluentd

- .circleci/config.yml
- bin/install-ci-tools
- bin/kind/calico-crds-v1.31.yaml
- metadata.yaml
- tests/k8s_schema/v1.31.0-standalone/clusterrole-rbac-v1.json
- tests/k8s_schema/v1.31.0-standalone/clusterrolebinding-rbac-v1.json
- tests/k8s_schema/v1.31.0-standalone/configmap-v1.json
- tests/k8s_schema/v1.31.0-standalone/cronjob-batch-v1.json
- tests/k8s_schema/v1.31.0-standalone/daemonset-apps-v1.json
- tests/k8s_schema/v1.31.0-standalone/deployment-apps-v1.json
- tests/k8s_schema/v1.31.0-standalone/endpoints-v1.json
- tests/k8s_schema/v1.31.0-standalone/ingress-networking-v1.json
- tests/k8s_schema/v1.31.0-standalone/job-batch-v1.json
- tests/k8s_schema/v1.31.0-standalone/namespace-v1.json
- tests/k8s_schema/v1.31.0-standalone/networkpolicy-networking-v1.json
- tests/k8s_schema/v1.31.0-standalone/poddisruptionbudget-policy-v1.json
- tests/k8s_schema/v1.31.0-standalone/role-rbac-v1.json
- tests/k8s_schema/v1.31.0-standalone/rolebinding-rbac-v1.json
- tests/k8s_schema/v1.31.0-standalone/secret-v1.json
- tests/k8s_schema/v1.31.0-standalone/service-v1.json
- tests/k8s_schema/v1.31.0-standalone/serviceaccount-v1.json
- tests/k8s_schema/v1.31.0-standalone/statefulset-apps-v1.json
- tests/k8s_schema/v1.31.0-standalone/storageclass-storage-v1.json
- Support k8s 1.31
- Bump patch versions of existing k8s versions
- Use helm 3.15.4
https://github.com/astronomer/issues/issues/6560
Normal testing is fine. QA can start testing k8s 1.31 clusters if they are not already.
> 6560 k8s 1 31

- charts/astronomer/templates/commander/commander-role.yaml
we recently introduced configmap based metrics collection in order to reduce the usage of cluster scoped resource privilges that introuded some edge cases where the configmap is maintained outside of helm and hard deleting the deployment was consuming deletecollection rbac on configmap to delete the resources created which was missing and causing the hard delete feature to  fail. 
This PR fixes that edge case and allows hard delete to function normally without any issues
https://github.com/astronomer/issues/issues/6620
QA should see resources and namespaces getting deleted without any issues
cherry-pick to master and release-0.36
> add deletecollection privilge to commander roles

- charts/kube-state/values.yaml
- tests/chart_tests/test_kube_state_deployment.py
reduce kube state default unused collectors
https://github.com/astronomer/issues/issues/6571
QA should able to validate platform metrics dashboard on astro-ui fully functional
> reduce kube state default unused collectors

- .circleci/config.yml
- charts/alertmanager/values.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
- values.yaml
Update ap-base packages from 3.18.8 to 3.18.9
Image Name |  old  Tag| New tag |
-- | -- | -- |
ap-alertmanager | 0.27.0-2 | 0.27.0-3
ap-blackbox-exporter | 0.25.0-2 | 0.25.0-3
ap-registry| 3.18.8 | 3.18.9
ap-postgres-exporter|0.15.0-7 |  0.15.0-8
ap-nats-streaming| 0.25.6-5 | 0.25.6-6
ap-nats-server| 2.10.18 | 2.10.18-1
ap-nats-exporter| 0.15.0-2 | 0.15.0-3
ap-init | 3.18.8 | 3.18.9
ap-curator | 8.0.16-1 | 8.0.16-2
ap-awsesproxy| 1.5.0-10 | 1.5.0-11
ap-pgbouncer-exporter | 0.15.0-10 | 0.15.0-11
ap-vector | 0.40.1| 0.40.1-1
ap-pgbouncer-krb |1.17.0-13 | 1.17.0-14
ap-base | 3.18.8 | 3.18.9
https://github.com/astronomer/issues/issues/6634
All components should be up and running without any errors, QA should test vector logs 
cherry-pick to …
> Update ap-base packages from 3.18.8 to 3.18.9

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston-api with version 0.35.14
NA
QA should able to see all existing features works as expected
> update houston-api with version 0.35.14

- charts/nats/values.yaml
- tests/chart_tests/test_nats_jetstream.py
This PR removes the default usage of the jetstream component. 
Related astronomer/issues#6651
Tested locally with the modified testcases
> Fix 6651 disable default jetstream

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.35.15 and astro ui 0.35.9
astro-ui
Related https://github.com/astronomer/issues/issues/6574
Related https://github.com/astronomer/issues/issues/6316
Related https://github.com/astronomer/issues/issues/6519
houston
Related https://github.com/astronomer/issues/issues/6369
Related https://github.com/astronomer/issues/issues/6643
> update houston api 0.35.15 and astro ui 0.35.9

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- values.yaml
| ap-auth-sidecar | 1.25.5 | 1.27.1 |
| ap-nginx-es | 1.27.0 | 1.27.1 |
https://github.com/astronomer/issues/issues/6634
> update nginx packages with 1.27.1

- .circleci/config.yml
- charts/external-es-proxy/values.yaml
update the ap-openresty from 1.25.3-1 to 1.25.3-2
Related astronomer/issues#XXXX
this PR should be merged / cherry-picked into 0.35,0.36.0.34
> update the ap-openresty from 1.25.3-1 to 1.25.3-2

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
update db-bootstrapper with 0.35.7
NA
cherry-pick to all release-0.35,release-0.36
> db-bootstrapper 0.35.7

- .circleci/config.yml
- charts/elasticsearch/values.yaml
update es exporter version 1.8.0
QA generic validation
> update es exporter version 1.8.0

- .circleci/config.yml
- charts/grafana/values.yaml
- charts/nginx/templates/nginx-deployment.yaml
- charts/nginx/values.yaml
- charts/postgresql/values.yaml
- charts/prometheus-node-exporter/values.yaml
- tests/chart_tests/test_nginx_service.py
update missing vendor packages
| ap-grafana | 10.4.5 | 10.4.6 |
| ap-node-exporter | 1.8.1-1 | 1.8.2 |
| ap-postgresql | 15.6.0-1 | 15.8.0 | 
NA
> update missing vendor packages

- charts/fluentd/templates/fluentd-configmap.yaml
- tests/chart_tests/test_fluentd.py
fix fluentd logging on reducing cluster role privileges
https://github.com/astronomer/issues/issues/6639
QA should able to see logs on astro-ui and airflow webserver ui task logs section
cherry-pick to release-0.36 and master
> fix fluentd logging on reducing cluster role privileges

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston-api version 0.35.16
Related https://github.com/astronomer/issues/issues/6437
Related https://github.com/astronomer/issues/issues/6666
Related https://github.com/astronomer/issues/issues/6667
Related https://github.com/astronomer/issues/issues/6369
refer above linked issues
> update houston-api version 0.35.16

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_astronomer_dag_only_deploy.py
Adds astro.dagDeploy.serviceAccount.create and astro.dagDeploy.serviceAccount.name to let users specify a service account name and specify that they don't want the chart to create the service-account and associated rolebindings for the dag-deploy server.
https://github.com/astronomer/issues/issues/6583
https://github.com/astronomer/issues/issues/6662
QA should able to override service account in dag server service 
> allow service account modification for dag server config

- charts/astronomer/templates/houston/helm-hooks/houston-au-strategy-job.yaml
- charts/astronomer/templates/houston/helm-hooks/houston-upgrade-deployments-job.yaml
remove rbac conditional changes
This is a continutation from the PR https://github.com/astronomer/astronomer/pull/2301
our original intention was to mix it up with global.rbacEnabled so that we will be removing the serviceAccount section from all the templates, with the redefined approach we configured our helper templates to use default service account when serviceAccount create is set to false and no name is defined it will fallback the serviceAccountName to default 
https://github.com/astronomer/issues/issues/6537
https://github.com/astronomer/issues/issues/6583
refer notion doc
> remove rbac conditional changes

- .circleci/config.yml
- charts/astronomer/values.yaml
- values.yaml
update houston 0.35.17 and dag server 0.6.0
Related https://github.com/astronomer/issues/issues/6674
Related https://github.com/astronomer/issues/issues/6437
Related https://github.com/astronomer/issues/issues/6419
QA should able to validate above tagged issues
> update houston 0.35.17 and dag server 0.6.0

- values.yaml
Bump dag-deploy from 0.6.0 to 0.6.1
https://github.com/astronomer/issues/issues/6674
Need to test the canDeployDags behaviors
Merge only into 0.35, 0.36
> dag-deploy 0.6.1

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander version 0.35.8
https://github.com/astronomer/issues/issues/6696
https://github.com/astronomer/issues/issues/6693
QA need to verify above issues 
> update commander version 0.35.8

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_authsidecar.py
This PR intends to add auth sidecar resource requests and limits to the Houston config map so that customers can add resource requests and limits from global.authsidecar values. 
1. Currently when authsidecar is enabled:
```
shubhamsingh@Shubhams-MacBook-Pro astro % helm -n astronomer get values astronomer | grep authSidecar: -A2
authSidecar:
enabled: true
```
2. The auth-proxy does get applied with authproxy sidecar container:
```
shubhamsingh@Shubhams-MacBook-Pro astro % kubectl get pods -n "$NS" -o json |
jq -r '.items[] | .metadata.name as $podname | .spec.containers[] | "\($podname) \(.name)"' |
column -t | grep auth
nuclear-cosmology-7338-flower-69bfb888-rwgsg       auth-proxy
nuclear-cosmology-7338-webserver-7b47fb994d-kvrh2  auth-proxy
```
3. But the limit and requests are not …
> add authSidecar resources to houston configmap

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_api_deployment.py
- tests/chart_tests/test_houston_configmap.py
Allow users to pass runtime versions list  overrides from astronomer helm chart 
https://github.com/astronomer/issues/issues/6680
QA should able to pass custom runtime versions config from helm values
> add support for runtime release config overrides from config

- charts/postgresql/templates/serviceaccount.yaml
- charts/prometheus-postgres-exporter/templates/role.yaml
- charts/prometheus-postgres-exporter/templates/rolebinding.yaml
- charts/prometheus-postgres-exporter/templates/serviceaccount.yaml
This PR intends to add BYO SA condition to prometheus-postgres-exporter.
Related astronomer/issues#6704
Upon setting global. rbacEnabled to False., kubectl get as should show only default SA created by k8s namespace. 
Needs to be cherry picked to 0.36.0
> Added rbac condition for porometheus-postgres

- charts/kibana/values.yaml
- tests/chart_tests/test_kibana.py
This PR disables kibana telemetry data collection setting by default
Related https://github.com/astronomer/issues/issues/6706
before this option
after this option
> disable kibana telemetry by default

- charts/nginx/values.yaml
- tests/chart_tests/test_nginx_service.py
This PR intends to add the ability for ingress-nginx to run with the CAPABILITY_DROP ALL option
Related astronomer/issues#6672
QA needs to verify that correct security context is added to nginx and with CAPABILITY_DROP option nginx is stable.
Original security context:
```
pod: astronomer-nginx-75ffb7c956-4lp4b
PodSecurity Context is not set
container name: nginx
image: quay.io/astronomer/ap-nginx:1.11.2                                      
allowPrivilegeEscalation: <no value>   
privileged: <no value>                               
readOnlyRootFilesystem: <no value>       
runAsGroup: <no value>                               
runAsNonRoot: true                           
runAsUser: 101
```
Cherry pick to …
> Adding CAPABILITY_DROP to nginx component

- charts/astronomer/templates/commander/commander-role.yaml
- charts/astronomer/templates/commander/commander-rolebinding.yaml
- values.yaml
This PR introduces a keep flag so the already create role and rolebindings are not deleted and synchronize on a helm update/upgrade. Disable management of commander namespace resources.
Related https://github.com/astronomer/issues/issues/6582
> Introduce rbac flag to optionate role and rolebindings for namespace pools

- charts/elasticsearch/templates/curator/es-curator-cronjob.yaml
- charts/external-es-proxy/templates/external-es-proxy-deployment.yaml
- charts/kibana/templates/kibana-default-index-cronjob.yaml
- charts/nats/templates/jetstream-job.yaml
- charts/pgbouncer/templates/pgbouncer-deployment.yaml
- charts/prometheus-blackbox-exporter/templates/deployment.yaml
- charts/prometheus-postgres-exporter/templates/deployment.yaml
- tests/__init__.py
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_external_elasticsearch.py
- tests/chart_tests/test_fluentd.py
- tests/chart_tests/test_kibana.py
- tests/chart_tests/test_nats_jetstream.py
- tests/chart_tests/test_nats_sts.py
- tests/chart_tests/test_platform_node_pools.py
- tests/chart_tests/test_privateca.py
- tests/chart_tests/test_prometheus_blackbox_exporter.py
- tests/chart_tests/test_prometheus_postgres_exporter.py
- tests/chart_tests/test_stan_sts.py
Add scheduling support for kibana index job and jetstream job
- https://github.com/astronomer/issues/issues/6676
- https://github.com/astronomer/issues/issues/6684
- https://github.com/astronomer/astronomer/issues/2319
QA should able to define nodeselector, tolleration, affinity for these pods 
> add nodeSelector, affinity, and toleration support

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
currently the astronomer tls secret name is hardcoded in airflow ingress templates with no option to pass overrides, with this new features it extends the flexibility to overrides secret names across all places
https://github.com/astronomer/issues/issues/6344
QA should able to override custom secret name to airflow deployments globally
> add tls secret overrides for airflow chart

- tests/__init__.py
- tests/chart_tests/conftest.py
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_external_elasticsearch.py
- tests/chart_tests/test_kibana.py
- tests/chart_tests/test_prometheus_blackbox_exporter.py
- tests/chart_tests/test_prometheus_postgres_exporter.py
- tests/chart_tests/test_stan_sts.py
Turn global_platform_node_pool_config into a fixture to avoid race conditions where global state is modified.
https://github.com/astronomer/issues/issues/6720
I have manually tested this and it has worked 100%. I was skeptical that the original code would work because of the global state change, and by chance I did not trigger the race condition when I tested the original code. The problem is well understood and fixtures are really the right way to do this.
This is only test code changes, no product changes are affected by this, so no further testing is needed. Only `pytest` runs are affected by the bug.
QA does not need to do anything here.
The original bug was only merged into 0.36, so this should only go to master and 0.36.
> Turn global_platform_node_pool_config into a fixture

- charts/fluentd/templates/fluentd-daemonset.yaml
- tests/chart_tests/test_platform_node_pools.py
- tests/chart_tests/test_prometheus_node_exporter.py
Adds common tests to validate platformnodepool configuration
- https://github.com/astronomer/issues/issues/6684
- https://github.com/astronomer/astronomer/issues/2319
- https://github.com/astronomer/issues/issues/6701
tests covers this validation
> improves platform nodepool tests

- charts/astronomer/templates/_helpers.yaml
- tests/chart_tests/test_byo_sa.py
This PR intends to update the configsyncer SA helper template
Related astronomer/issues#6537
Upon creation of custom SA configsyncer pod should be able to pick the correct configsyncer SA. 
cherry pick to 0.36
> Fix typo in  configsyncer service account template

- values.yaml
update dag server version 0.6.3
- Parent ticket https://github.com/astronomer/issues/issues/6524
- Related houston issue https://github.com/astronomer/houston-api/pull/1844
refer above ticket 
chery-pick to release-0.36
> update dag server version 0.6.3

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.36.3
- Related https://github.com/astronomer/issues/issues/6524
- Related https://github.com/astronomer/dag-deploy/pull/44
- Related https://github.com/astronomer/issues/issues/6712
- Related https://github.com/astronomer/issues/issues/6717
- Relatedhttps://github.com/astronomer/issues/issues/6344
QA should validate above issues
> update houston api 0.36.3

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander version 0.36.6
- https://github.com/astronomer/issues/issues/6726
QA should able to update deployment without any issues
> update commander version 0.36.6

- charts/astronomer/templates/commander/commander-deployment.yaml
- charts/astronomer/templates/commander/commander-role.yaml
- charts/astronomer/templates/commander/commander-rolebinding.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_astronomer_namespace_pools.py
- tests/chart_tests/test_houston_configmap.py
This change introduces more granular config for namespace pools to optionate namespace creation and management , additionally when namespace management is disabled it will switch to configmap based labelling query in houston.
with existing approach  when namespace pools  create set to true namespace will be auto created with roles with subsequent deloyment approach the status indicator will be broken showing status indicating deploying....
this change will fix these behaviours
Related https://github.com/astronomer/issues/issues/6582
QA should able to verify global.features.namespacePools.enabled: true and global.features.namespacePools.createRbac: true/false changes
> add conditional approach for namespace create

- charts/astronomer/templates/config-syncer/config-syncer-role.yaml
- charts/astronomer/templates/config-syncer/config-syncer-rolebinding.yaml
- charts/kube-state/templates/kube-state-role.yaml
- charts/kube-state/templates/kube-state-rolebinding.yaml
- tests/chart_tests/test_astronomer_namespace_pools.py
This feature provisions service account with no roles for kube state, config syncer when rbacCreate is set to false with  namespace pools 
https://github.com/astronomer/issues/issues/6731
QA should not see any roles for these platform services when namespace pools is enabled with createRbac flag set to false
> extend rbac create for namespace pools

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_astronomer_dag_only_deploy.py
- values.yaml
This PR intends to update dag server security contexts default format to allow usage of security contexts with separate pod and container capabilities. 
Related astronomer/issues#6729
0.36
> update dag server security context default format

- .circleci/config.yml
- charts/grafana/values.yaml
update missing vendor packages
| ap-grafana | 10.4.6 | 10.4.10 |
QA should be able to access the Grafana UI, without any issues. 
> Update Grafana package from 10.4.6 to 10.4.10

- charts/prometheus/templates/prometheus-role.yaml
- charts/prometheus/templates/prometheus-rolebinding.yaml
- charts/prometheus/templates/prometheus-serviceaccount.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_prometheus_statefulset.py
Allow prometheus to indepently disable rbac and service account when global.rbacEnabled is set to true 
- https://github.com/astronomer/issues/issues/6537
- https://github.com/astronomer/issues/issues/6742
QA should able to disable prometheus service account and rbac below config
```
prometheus:
serviceAccount:
create: false 
name: platform-prometheus
```
NA
> allow prometheus to disable rbac independently

- charts/nginx/templates/nginx-headers-configmap.yaml
Refactor Nginx CSP:
- remove third party entries: jsdeliver, stripe, segment, metarouter, intercom, lr-ingest, grafana.com
- Reformat yaml as folded strip block style https://yaml-multiline.info>
https://github.com/astronomer/issues/issues/6749
I have not tested this. I also don't know a good way to write a valuable unit test for this. We will need to manually make sure this does not break anything.
> Refactor nginx CSP

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api version to 0.36.6
- https://github.com/astronomer/issues/issues/6719
- https://github.com/astronomer/issues/issues/6729
- https://github.com/astronomer/issues/issues/6732
- https://github.com/astronomer/issues/issues/6716
QA should verify above mapped issues 
> update houston api 0.36.6

- charts/prometheus/templates/prometheus-statefulset.yaml
- tests/chart_tests/test_prometheus_statefulset.py
This PR fixes a typo in tolleration config in prometheus statefulset.
PS: we have added test cases to assert against this issue to not fall into typo pitfalls
NA
standard test cases has been included. QA can pass custom tolleration config to see its being overriding the globals 
> fix prometheus tollerations typo error

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/nginx/values.yaml
- charts/prometheus/values.yaml
- values.yaml
| quay.io/astronomer/ap-auth-sidecar  | 1.27.1 | 1.27.2 |
| quay.io/astronomer/ap-cli-install | 0.26.26 | 0.27.27 |
| quay.io/astronomer/ap-configmap-reloader | 0.13.1 | 0.14.0 |
| quay.io/astronomer/ap-default-backend | 0.28.27 | 0.28.28 |
| quay.io/astronomer/ap-grafana | 10.4.10 | 10.4.13 | 
| quay.io/astronomer/ap-nginx-es | 1.27.1 | 1.27.2 |
NA
NA
cherry-pick to all branches
> update vendor packages 

- charts/postgresql/templates/statefulset-slaves.yaml
- charts/postgresql/templates/statefulset.yaml
- tests/chart_tests/test_postgres.py
- tests/chart_tests/test_prometheus_statefulset.py
add toleration support postgresql service
- https://github.com/astronomer/issues/issues/6792
QA now should able to apply global platform tolerations to postgresql component
> add toleration support postgresql service

- tests/__init__.py
- tests/chart_tests/test_astronomer_config_syncer.py
- tests/chart_tests/test_astronomer_houston_airflow_db_cleanup.py
- tests/chart_tests/test_astronomer_houston_cronjob.py
- tests/chart_tests/test_astronomer_houston_task_metrics.py
- tests/chart_tests/test_check_platform_updates.py
- tests/chart_tests/test_cronjob_check_airflow_updates.py
- tests/chart_tests/test_cronjob_check_runtime_updates.py
- tests/chart_tests/test_elasticsearch.py
Fold `get_cronjob_containerspec_by_name()` features into `get_containers_by_name()`. Having one function that does the same thing to all pod manager docs is easier than having to handle Jobs separately from other pod managers.
This was created as part of https://github.com/astronomer/issues/issues/6747 but is not directly related to that work. I'm just breaking this out into its own PR so it's easy to backport.
These are only test changes, so no human QA is needed. CI passing is enough.
This should be merged to all branches to make our test functions consistent.
> Fold features of get_cronjob_containerspec_by_name into get_containers_by_name

- .circleci/config.yml
- charts/prometheus-postgres-exporter/values.yaml
update postgres exporter 0.16.0
- https://github.com/astronomer/issues/issues/6802
QA should able to see postgres metrics 
> update postgres exporter 0.16.0

- .circleci/config.yml
- charts/fluentd/values.yaml
update fluend version 1.17.1
- https://github.com/astronomer/issues/issues/6806
QA generic testing
cherry-pick to all branches
> update fluentd version 1.17.1

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
update db-boostrapper version 0.36.2
- https://github.com/astronomer/issues/issues/6808
generic QA testing
> update db-boostrapper version 0.36.2

- .circleci/config.yml
- charts/kube-state/values.yaml
update kube state metrics version 2.14.0
- https://github.com/astronomer/issues/issues/6807
Generic metrics testing
> update kube state metrics version 2.14.0

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander version 0.36.9
- https://github.com/astronomer/issues/issues/6816
NA
> update commander version 0.36.9

- charts/astronomer/templates/commander/commander-serviceaccount.yaml
- charts/astronomer/templates/houston/api/houston-bootstrap-serviceaccount.yaml
- charts/elasticsearch/templates/es-serviceaccount.yaml
- charts/external-es-proxy/templates/external-es-proxy-serviceaccount.yaml
- charts/fluentd/templates/fluentd-serviceaccount.yaml
- charts/grafana/templates/grafana-bootstrap-serviceaccount.yaml
- charts/kube-state/templates/kube-state-serviceaccount.yaml
- charts/nats/templates/nats-serviceaccount.yaml
- charts/pgbouncer/templates/pgbouncer-serviceaccount.yaml
- charts/prometheus-blackbox-exporter/templates/blackbox-serviceaccount.yaml
- charts/prometheus-node-exporter/templates/serviceaccount.yaml
- charts/prometheus-postgres-exporter/templates/serviceaccount.yaml
- charts/prometheus/templates/prometheus-serviceaccount.yaml
- charts/prometheus/values.yaml
- charts/stan/templates/stan-serviceaccount.yaml
- tests/chart_tests/test_byo_sa.py
This PR extends the scope of serviceAccount support and adds additional enhancements to existing changes
- https://github.com/astronomer/issues/issues/6814
QA should able to control individual creation of service account when global.rbacEnabled set to true
Yet to update
> extend service account support

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_api_deployment.py
This PR implements a change to include config name support to mount volume and volume mounts automatically by providing a file name 
- https://github.com/astronomer/issues/issues/6680
QA should able to provide pre-created configmap with runtime and airflow versions list
cherry-pick to release-0.36 , release-0.37
> add configmap names support for airflow  runtime version

- charts/astronomer/values.yaml
- tests/chart_tests/test_poddisruptionbudget.py
- tests/enable_all_features.yaml
disable default platform check job
- https://github.com/astronomer/issues/issues/6680
QA should see update-platform-job check 
> disable default platform check job

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
- values.yaml
This PR adds configurable liveness/readiness probes for authsidecar and dagdeployment for houston config
Related astronomer/issues#6745
N/A
0.37.0
> Add configurable liveness/readiness probes for authsidecar and dagdeployment

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
Add airflow extra ingress annotation support
- https://github.com/astronomer/issues/issues/6744
QA should able to see custom ingress annotation passed from global.extraAnnotations to airflow ingress objects as well
> add airflow extra ingress annotation support

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/registry/registry-statefulset.yaml
- tests/chart_tests/test_global_storageclass.py
This PR intends to fix the indentation of storageclass component for registry stateful sets. 
Related astronomer/issues#6380
Tested manually for the indentation:
```
shubhamsingh@Shubhams-MacBook-Pro astronomer % helm template --kube-version 1.31.0 release-name . --set global.baseDomain=example.com --set global.storageClass=gp1 --set astronomer.registry.persistence.storageClassName=gp2  --show-only charts/astronomer/templates/registry/registry-statefulset.yaml
---
#####################################
#####################################
kind: StatefulSet
apiVersion: apps/v1
metadata:
name: release-name-registry
labels:
component: registry
tier: astronomer
release: release-name
chart: "astronomer-0.36.0"
heritage: Helm
spec:
replicas: 1
selector:
matchLabels:
component: registry
tier: …
```
> fixing storageclass indentation for registry

- charts/astronomer/templates/commander/commander-role.yaml
- charts/prometheus/templates/prometheus-config-configmap.yaml
- tests/chart_tests/test_astronomer_commander.py
- tests/chart_tests/test_prometheus_config_configmap.py
This PR adds support for managing Airflow Operator deployments and collecting their metrics by:
1. **Commander RBAC Enhancements**
- Added new RBAC rules to enable Commander to manage Airflow CRDs:
```yaml
- apiGroups: ["airflow.apache.org"]
resources: ["airflows"]
verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```
- These permissions enable Commander to:
- Create and manage Operator-based deployments
- Monitor deployment status
- Update configurations
- Handle lifecycle operations
2. **Prometheus Service Discovery Updates**
- Added new relabel configuration in Prometheus ConfigMap:
```yaml
- source_labels: [__meta_kubernetes_service_label_astronomer_io_platform_release]
regex: ^astronomer$
action: keep
```
- This change addresses a key difference between Helm and …
> Commander and Prometheus changes needed for Airflow Operator Support.

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
- values.yaml
Add liveliness and readiness support for dag deploy server and client
- Related https://github.com/astronomer/issues/issues/6745
https://github.com/astronomer/issues/issues/6928
QA should be able to pass liveliness and readiness probes for both dag server client and server
> add dag server and client probes support

- tests/chart_tests/test_airflow_operator.py
- tests/chart_tests/test_prometheus_config_configmap.py
Add unit tests for Airflow Operator chart components
This PR adds comprehensive unit tests for the Airflow Operator chart components in test_airflow_operator.py. The new tests cover:
- Cert Manager configuration testing
- Verifies proper rendering of self-signed issuer and serving cert certificate
- Validates when cert manager is enabled
- CRD template testing
- Tests rendering of all 14 CRD templates when CRD creation is enabled
- Includes CRDs for core components (airflow, scheduler, webserver)
- Includes CRDs for supporting services (postgres, redis, etc.)
- Webhook TLS Secret testing
- Tests webhook TLS secret generation with custom certs
- Validates proper rendering with provided caBundle, tlsCert and tlsKey
- Webhook Configuration testing
- Tests rendering of both mutating and …
> Operator unittest

- .circleci/config.yml
- charts/alertmanager/values.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
- values.yaml
This PR Update  ap-vendor packages to resolve some of the CVE's for astronomer software 
| Image Name            | old Tag   | New tag   |
| --------------------- | --------- | --------- |
| ap-alertmanager       | 0.27.0-3  | 0.27.0-4  |
| ap-awsesproxy         | 1.5.0-11  | 1.5.0-12  |
| ap-base               | 3.18.9    | 3.20.3-1  |
| ap-blackbox-exporter  | 0.25.0-3  | 0.25.0-4  |
| ap-curator            | 8.0.17    | 8.0.17-1  |
| ap-grafana            | 10.4.13   | 10.4.14   |
| ap-init               | 3.19.4    | 3.20.3-1  |
| ap-nats-exporter      | 0.15.0-3  | 0.15.0-4  |
| ap-nats-server        | 2.10.18-1 | 2.10.18-2 |
| ap-nats-streaming     | 0.25.6-6  | 0.25.6-7  |
| ap-pgbouncer-exporter | 0.18.0    | 0.18.0-1  |
| ap-pgbouncer-krb      | 1.17.0-15 | 1.17.0-16 |
| …
> upgrade ap-vendor packages 

- .circleci/config.yml
- charts/alertmanager/values.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
- values.yaml
Update all ap-base derived images to use ap-base:3.20.5
https://github.com/astronomer/issues/issues/6962
No testing was done. These tests will all be covered by normal QA tests.
This is just for 0.37. I'm not sure that all of these images will work on 0.36 so we can hold off on that for now.
> ap-base 3.20.5 updates

- charts/astronomer/templates/commander/commander-role.yaml
Add batch jobs delete collection rbac commander for cleanup call
- https://github.com/astronomer/issues/issues/6707
No rbac error on worker when cleanup cron is triggered 
> add jobs delete rbac for cleanup activity

- charts/prometheus/templates/prometheus-config-configmap.yaml
- tests/chart_tests/test_prometheus_config_configmap.py
Added missing action: keep directive in the Prometheus configuration for the Airflow job's relabel configuration. This fixes an issue where Prometheus would fail to start with the error: "relabel configuration for replace action requires 'target_label' value".
Added explicit action: keep to the Airflow job's relabel configuration where we filter based on __meta_kubernetes_service_annotation_astronomer_io_platform_release
Updated corresponding tests to include this required field
Related astronomer/issues#6954
Without specifying the action, Prometheus defaults to action: replace which requires a target_label field. However, for this particular relabel configuration, we want to filter metrics rather than replace labels, making keep the appropriate action.
Verified Prometheus starts …
> Fix Prometheus Configuration for Airflow Operator Job

- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_prometheus_statefulset.py
update prometheus no cluster role test cases
https://github.com/astronomer/issues/issues/6342
QA should see status indicator similar to defaults with cluster role disabled
> update prometheus no cluster role test cases

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
- ap-commander 0.37.1
- ap-houston-api 0.37.0
- ap-astro-ui 0.37.0
- airflowChartVersion 1.13.6
- Astronomer "Software" 0.37.0-rc1
0.37.0 release related work, somewhat related to <https://github.com/astronomer/issues/issues/6786>
No extra testing needed, CI is fine.
Merge only into 0.37.0, after <https://github.com/astronomer/commander/pull/259>
> 0.37.x image updates, 0.37.0-rc1

- charts/airflow-operator/templates/_helpers.yaml
- charts/airflow-operator/templates/manager/controller-manager-metrics-service.yaml
- charts/airflow-operator/values.yaml
- tests/chart_tests/test_airflow_operator.py
PR to remove kube-proxy-rbac component from operator as this component is not used by us.
Related astronomer/issues#6969
Local Testing and unittests 
0.37
> remove kube-proxy-rbac

- .circleci/config.yml
- bin/show-docker-images.py
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_houston_configmap.py
- values.yaml
Added a default images section under deployments.helm config so that those images are picked up in the operator flow
Currently, other components in Airflow (redis, pgb etc) use the tags specified in the operator version and they don't use the tags specified under the airflow chart. This PR changes the behaviour by adding the default image tags under the houston values section.
Related astronomer/issues#7014
Will test on stage after rc2 is released.
0.37.0
> Added a default images section under deployments.helm config so that those images are picked up in the operator flow

- charts/astronomer/templates/houston/cronjobs/houston-cleanup-deploy-revisions-cronjob.yaml
- tests/chart_tests/test_astronomer_houston_deploy_revisions.py
This PR fixes component name mismatch for cleanup deploy revision job
- https://github.com/astronomer/issues/issues/7021
kubectl get -lcomponent=houston -n astronomer 
should show only houston specific components list
> fix component name mismatch for cleanup deploy revision job

- charts/astronomer/templates/houston/cronjobs/houston-cleanup-airflow-db-cronjob.yaml
fix cleanup flags with new inputs
- https://github.com/astronomer/issues/issues/7009
- https://github.com/astronomer/issues/issues/7010
cleanup cronjob should adopt new flags
> fix cleanup flags with new inputs

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.37.4
- astronomer/issues#7037
QA should not see any issues while upgrading from 0.36 to 0.37 
> update houston api 0.37.4

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api and astro-ui 
| ap-houston-api | 0.37.4 | 0.37.5 |
| ap-astro-ui | 0.37.1 | 0.37.2 |
- Related https://github.com/astronomer/issues/issues/6900
- Related https://github.com/astronomer/issues/issues/6980
- Related https://github.com/astronomer/issues/issues/7039
- Related https://github.com/astronomer/issues/issues/6980
- Related https://github.com/astronomer/issues/issues/7037
- Related https://github.com/astronomer/issues/issues/7044
QA should refer above issues for more validation
> update houston api and astro-ui

- .circleci/config.yml
- charts/grafana/values.yaml
- charts/kube-state/values.yaml
- charts/prometheus-node-exporter/values.yaml
- values.yaml
update vendor packages for upstream packages
| ap-grafana | 10.4.15 | 10.4.16 |
| ap-kube-state | 2.14.0 | 2.15.0 |
| ap-node-exporter | 1.8.2 | 1.9.0 |
| ap-pgbouncer-exporter | 0.18.0 | 0.18.0-2 |
| ap-pgbouncer | 1.23.1-1 | 1.23.1-4 | 
| ap-statsd-exporte| 1.27.2 | 0.28.1| 
NA, generic ktlo work for CVE patches
- https://github.com/astronomer/issues/issues/6791
generic QA testing effort
> update vendor packages for upstream packages

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/prometheus/values.yaml
| ap-houston-api | 0.37.5 | 0.37.6 |
| ap-kuiper-reloader | 0.1.3 | 0.1.5 |
-  Related https://github.com/astronomer/issues/issues/7048
- Related https://github.com/astronomer/issues/issues/6980
- Related https://github.com/astronomer/issues/issues/7041
- Related https://github.com/astronomer/issues/issues/7042
- Related https://github.com/astronomer/issues/issues/6869
> update platform images includes api enhancements 

- charts/airflow-operator/templates/manager/webhook-service.yaml
- charts/airflow-operator/templates/webhooks/mutating-webhook-configuration.yaml
- charts/airflow-operator/templates/webhooks/validating-webhook-configuration.yaml
- charts/airflow-operator/values.yaml
- tests/chart_tests/test_airflow_operator.py
This PR adds a configuration flag to control webhook installation, as webhooks require cluster-admin privileges that may not be available in all environments. By default the setting to `false`, we ensure installations don't fail in restricted environments while still allowing users to enable webhooks when appropriate permissions exist.
This change addresses a key installation issue with the Airflow Operator chart. Currently, webhook components are always installed when the operator is enabled, which requires cluster-admin privileges. This creates a barrier for users in restricted environments where such privileges aren't available, effectively preventing them from using the operator functionality.
- Added `webhooks.enabled` flag (defaulted to `false`) in values.yaml
- Modified …
> Add flag for webhook installation in Operator. 

- .circleci/config.yml
- bin/show-docker-images.py
- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
- values.yaml
update gitsync images in houston config
- https://github.com/astronomer/issues/issues/7047
QA should see latest git sync images while upgrading existing git sync deployments
> update gitsync images in houston config

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api image 0.37.9
- Related https://github.com/astronomer/issues/issues/7042
QA should validate above mapped issue
cherry-pick to master and release-0.37
> update houston api image 0.37.9

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_openshift.py
This PR standardizes the security context configuration for all components when running in OpenShift mode by setting `runAsNonRoot: true` across all components. Previously, there was inconsistency where some Airflow components used `runAsNonRoot: false` while others used `runAsNonRoot: true`.
Improved security posture by enforcing consistent non-root execution
Simplified configuration and security reviews
Better alignment with OpenShift's security model and best practices
Related astronomer/issues#6758
- Updated unit tests to verify all components now use runAsNonRoot: true
- Deployed to a test OpenShift cluster to confirm all components start successfully
- Patched one of the existing kubeexecutor deployments with `runAsNonRoot: true` and confirmed that the pods came up fine:
- Patched …
> Standardize security context configuration for all components 

- .circleci/config.yml
- values.yaml
This PR updates the sidecar-log-consumer image tag from 0.44.0-2 to 0.45.0 to incorporate recent improvements to the sidecar loop functionality. The update includes enhanced error handling for the Kubernetes watch process, ensuring more robust handling of timeouts and continuous monitoring of ConfigMap events.
Related astronomer/issues#6714
- Tested that with this new version the pods are terminating without any issues. 
0.36
> Update sidecar-log-consumer to version 0.45.0 

- .circleci/config.yml
- values.yaml
update git sync version 0.0.3-9
- https://github.com/astronomer/issues/issues/7067
revert git sync image for 0.36 release
> update git sync version 0.0.3-9

- charts/astronomer/templates/commander/commander-role.yaml
- tests/chart_tests/test_astronomer_commander.py
- tests/chart_tests/test_scc.py
fixes an issue with scc priviges where users switch from sccEnabled to openshiftEnabled back and forth. check issue link for more information
- https://github.com/astronomer/issues/issues/7085
QA should now able to enabled sccEnabled for upgrades 
cherry-pick to release-0.36 and release-0.37
> fix commander scc privileges

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston and astro-ui images
| ap-houston-api | 0.36.14 | 0.36.17 |
| ap-astro-ui | 0.36.2 | 0.36.3 |
- Related https://github.com/astronomer/issues/issues/6511
- Related https://github.com/astronomer/issues/issues/7083
> update houston and astro-ui images

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/external-es-proxy/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
- values.yaml
update vendor packages with new ap-base changes
|ap-awsesproxy | 1.5.0-13 | 1.5.0-14 |
| ap-blackbox-exporter| 0.25.0-5  | 0.25.0-6 |
| ap-git-daemon | 3.20.5 | 3.21.3-1 |
| ap-git-sync | 4.2.3-1 | 4.2.3-3 |
| ap-init | 3.20.5 | 3.21.3-1 | 
| ap-nats-server | 2.10.18-3 |2.10.18-4 | 
| ap-nats-streaming |0.25.6-8 | 0.25.6-9 | 
| ap-pgbouncer-exporter | 0.18.0-2 | 0.18.0-3 | 
| ap-pgbouncer-krb | 1.17.0-17  | 1.17.0-18 | 
| ap-pgbouncer | 1.23.1-4 | 1.24.0-1 |
| ap-postgres-exporter | 0.16.0-2 | 0.16.0-3 | 
| ap-registry | 3.20.5 | 3.21.3-1 |
| ap-vector | 0.45.0 | 0.45.0-1 |
- https://github.com/astronomer/issues/issues/6830
cherry-pick to master
> update vendor packages with new ap-base changes

- .circleci/config.yml
- charts/astronomer/values.yaml
update commander version 0.36.12 and airflow chart 1.13.9
- https://github.com/astronomer/issues/issues/7085
QA should able to upgrade existing kube executor deployments with not uid and gid issues
> update commander version 0.36.12 and airflow chart 1.13.9

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_openshift.py
add default git sync security context for openshift
- https://github.com/astronomer/issues/issues/7089
QA should able to deploy git sync deployment sidecars on airflow components
> add default git sync security context for openshift

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston image
| ap-houston-api | 0.36.17 | 0.36.18 |
- Related https://github.com/astronomer/issues/issues/6845
> Update houston image to 0.36.18

- .circleci/config.yml
- charts/astronomer/values.yaml
fixes pgbouncer service account with global.sccEnabled 
- https://github.com/astronomer/issues/issues/7096
QA should able to create new deployments with scc feature
> update commander version 0.36.13 and airflow chart 1.13.10

- charts/astronomer/templates/commander/commander-role.yaml
- charts/astronomer/templates/commander/commander-rolebinding.yaml
- tests/chart_tests/test_astronomer_commander.py
This PR renames the scc specific roles with scc tagged naming not to conflict existing cluster roles causing commander existing roles getting merged with defaults blocking the entire deployment creation,update and other activities
- https://github.com/astronomer/issues/issues/7093
QA with global.sccEnabled + namespacePolls should able to test deployment features
> rename scc clusterrole conflicts with default commander role

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
update houston 0.36.19 and rc5 tag
- Related https://github.com/astronomer/issues/issues/6845
refer above issue
> update houston 0.36.19 and rc5 tag

- charts/elasticsearch/templates/client/es-client-deployment.yaml
Remove duplicate serviceAccountName from es-client-deployment that was introduced in https://github.com/astronomer/astronomer/pull/2428/files#diff-7efc2adb130709e5d46c8d396d03530e644ad6b74499bc6dda3cf48885c5ee9f
This supersedes https://github.com/astronomer/astronomer/pull/2544
- <https://github.com/astronomer/issues/issues/7099>
No extra testing is needed.
This should be merged everywhere that https://github.com/astronomer/astronomer/pull/2428 was merged to.
> Remove redundant serviceAccountName in es-client-deployment

- bin/release-bom
The release-bom script is failing with a "Repository not found" error due to two issues:
1. Missing separator between the repository URL and version tag in the pip install command (this is only for 0.36 release branch)
2. The version format needs to be without the 'v' prefix when generating the JSON filename. 
Related astronomer/issues#7109
- Ran the script as SSH session in CircleCI and was able. to publish 0.36.1.json: https://updates.astronomer.io/astronomer-software/releases/astronomer-0.36.1.json
- Script:
- Logs:
Everywhere
> Fix Repository URL and Version Format in release-bom Script

- .circleci/config.yml
- charts/nginx/values.yaml
update nginx ingress 1.11.5
- https://github.com/astronomer/issues/issues/7110
General Ingress Testing
cherry-pick to master and all release branches
> update nginx ingress 1.11.5

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api 0.37.10
- Related https://github.com/astronomer/issues/issues/7104
Generic QA testing
> update houston api 0.37.10

- tests/chart_tests/helm_template_generator.py
Update the raw.githubusercontent.com URL for accessing assets from within the GH repo used by the k8s schema file validator.
Also add `parents=True` to `Path.mkdir()` when caching k8s schema files.
- <https://github.com/astronomer/issues/issues/7102>
I've manually tested this by deleting all the schema files and observed them being recreated and producing no diff.
Merge everywhere since this is a change in a third party resource that needs to be updated.
> Update BASE_URL_SPEC, mkdir(parents=True)

- .circleci/config.yml
- charts/nginx/values.yaml
- values.yaml
Update some images to latest versions available in quay.
old version | new version
--- | ---
quay.io/astronomer/ap-default-backend:0.28.28 | quay.io/astronomer/ap-default-backend:0.28.29
quay.io/astronomer/ap-git-sync:4.2.3-4 | quay.io/astronomer/ap-git-sync:4.2.4
quay.io/astronomer/ap-statsd-exporter:0.28.1 | quay.io/astronomer/ap-statsd-exporter:0.28.0-2
The above data is from `git diff master.. --word-diff .circleci/config.yml | grep -- -quay | sed 's/.*-\(quay.*\)-\]{+\(quay.io.*\)+\}/\1 | \2/g'`
https://github.com/astronomer/issues/issues/7106
I have not tested these changes. There are no significant version bumps. Normal testing is sufficient.
> 7106 update images

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- values.yaml
platform and vendor package CVE fixes
| ap-astro-ui | 0.37.4 | 0.37.5 |
| ap-auth-sidecar | 1.27.4-2 | 1.27.4-3 |
| ap-default-backend | 0.28.29 | 0.28.30 |
| ap-nats-server | 2.10.18-5 | 2.10.19 | 
| ap-nginx-es | 1.27.4-2 | 1.27.4-3 | 
merge to master and release-0.37
> platform and vendor package CVE fixes

- .circleci/config.yml
- values.yaml
update git-sync-relay version 0.1.11
- https://github.com/astronomer/issues/issues/7069
General QA testing against openshift cluster
merge to master and release-0.37
> update git-sync-relay version 0.1.11

- charts/elasticsearch/templates/es-scc.yaml
- charts/elasticsearch/values.yaml
- tests/chart_tests/test_astronomer_registry.py
- tests/chart_tests/test_elasticsearch.py
- tests/k8s_schema/v1.29.0-standalone/securitycontextconstraints-security-v1.json
- tests/k8s_schema/v1.30.0-standalone/securitycontextconstraints-security-v1.json
- tests/k8s_schema/v1.31.0-standalone/securitycontextconstraints-security-v1.json
- tests/k8s_schema/v1.32.0-standalone/securitycontextconstraints-security-v1.json
enable es scc tpl to allow custom service account
- https://github.com/astronomer/issues/issues/7131
QA should able to bring up elastic components without any custom config changes
merge to all valid releases
> enable es scc tpl to allow custom service account

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/sign-images.py
This PR adds image signing capabilities to our CI/CD pipeline using Cosign. It enables us to cryptographically sign our release images to provide stronger security guarantees and verify the authenticity of our published container images.
- Add a new Python script (bin/sign-images.py) that fetches the BOM file for a specified release and signs all Astronomer images with Cosign
- Update the CircleCI configuration to include a sign-released-image job that runs after release
- Configure the job to use environment variables from the software-cosign-keys context
- The script handles base64-encoded keys from environment variables
Related astronomer/issues#7082
- The script reads COSIGN_PRIVATE_KEY, COSIGN_PUBLIC_KEY, and COSIGN_PASSWORD from environment variables
- It fetches the BOM file for …
> Add Docker Image Signing With Cosign

- charts/elasticsearch/templates/nginx/nginx-es-configmap.yaml
- charts/elasticsearch/values.yaml
- tests/chart_tests/test_elasticsearch.py
This pull request adds the client_max_body_size directive to the NGINX Elasticsearch ConfigMap, defaulting to 100M and making it configurable through Helm values.
- The client_max_body_size directive in NGINX controls the maximum allowed size of client request bodies. 
- Setting this value appropriately helps prevent issues with large requests being rejected while still providing protection against excessive resource consumption.
- Added client_max_body_size directive to the HTTP block in the NGINX Elasticsearch ConfigMap
- Set the default value to 100M
- Made the value configurable via Helm values
- Added unit tests to verify the directive is present with both default and custom values
Related astronomer/issues#7164
- Unit tests have been added to verify that:
- The directive is present …
> Add configurable client_max_body_size to NGINX Elasticsearch ConfigMap

- charts/astronomer/templates/commander/commander-role.yaml
- charts/astronomer/templates/commander/commander-rolebinding.yaml
- charts/astronomer/templates/config-syncer/config-syncer-role.yaml
- charts/astronomer/templates/config-syncer/config-syncer-rolebinding.yaml
- charts/kube-state/templates/kube-state-role.yaml
- charts/kube-state/templates/kube-state-rolebinding.yaml
Fix incorrectly rendered yaml doc separators. I found this while looking at something completely unrelated. The way it was rendering before has `enabled---`, which is the error:
```
$ helm template . --kube-version 1.31.0 --set global.baseDomain=example.com --show-only charts/astronomer/templates/commander/commander-rolebinding.yaml | head
---
######################################
######################################
apiVersion: rbac.authorization.k8s.io/v1
```
And after being fixed it is:
```
$ helm template . --kube-version 1.31.0 --set global.baseDomain=example.com --show-only charts/astronomer/templates/commander/commander-rolebinding.yaml | head
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: release-name-commander
roleRef:
apiGroup: …
```
> Fix incorrectly rendered yaml doc separators

- .circleci/config.yml
- charts/astronomer/values.yaml
Bump houston API to 0.37.12
Related astronomer/issues#7060
Already tested via unit tests and deploying in GKE cluster
0.37
> Bumps houston api image version to 0.37.12

- charts/fluentd/templates/fluentd-configmap.yaml
add fluentd dag processor support
Related astronomer/issues#6572
QA should see dag processor logs in the UI
> add fluentd dag processor support

- .circleci/config.yml
- .circleci/config.yml.j2
Remove sign-released-image job from scan-docker-images workflow to fix image scanning, and because it doesn't seem like the right place for that job.
- <https://github.com/astronomer/issues/issues/7167>
No testing needed. This is not related to the product and doesn't change anything about the way the software runs. This is purely a CI fix.
Merge everywhere just to be consistent.
> Remove sign-released-image job from scan-docker-images workflow.

- .circleci/config.yml
- values.yaml
Image Name | Old Tag | New Tag 
-- | -- | -- |
ap-pgbouncer-exporter| 0.18.0-4 | 0.19.0
https://github.com/astronomer/issues/issues/7106
Generic QA testing
cherry-pick to release-0.37, release-0.36
>  updating ap-pgbouncer-exporter

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_openshift.py
add dagProcessor openshift support and optimize scc usage
https://github.com/astronomer/issues/issues/6572
QA should able to deploy airflow deployments with dag processor enabled 
merge to master and release-0.37
> add dagProcessor openshift support

- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/elasticsearch/templates/nginx/nginx-es-networkpolicy.yaml
- charts/external-es-proxy/templates/external-es-proxy-networkpolicy.yaml
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_external_elasticsearch.py
- tests/chart_tests/test_prometheus_statefulset.py
Add relevant nwtwork policies for dag processor siercar logging container
- Related astronomer/issues#6572
QA should able to see logs when sidecar logging is enabled
> fix dag processor config

- charts/elasticsearch/templates/nginx/nginx-es-networkpolicy.yaml
- charts/external-es-proxy/templates/external-es-proxy-networkpolicy.yaml
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_external_elasticsearch.py
some of the airflow custom components logs are not whitelisted on sidecar logging method this PR fixes the behavior and allows us to log all component logs in the elasticsearch and reflects back to Astro UI
fixes https://github.com/astronomer/issues/issues/7178
QA should able to see logs for dag server , airflow downgrade .
merge to all valid releases
> update network policies for airflow components

- .circleci/config.yml
- charts/postgresql/values.yaml
Bump from postgres 16 to 17. This effectively bumps from postgres 15 in 0.37.0 to postgres 17 in 0.37.1. This change requires customers who are using in-cluster postgres to pin their old version of postgres 17. Not doing so is not a destructive operation, but the postgres pod will not come up until the version has been pinned to the prior major version (which is output in the postgres logs) or until the db files are manually upgraded to 17. Customers are advised to never use in-cluster postgres.
https://github.com/astronomer/issues/issues/6266
No extra testing is needed. In-cluster postgres is used during CI so if CI passes then we are good.
Merge only to 0.37.
> 6266 postgres 17

- .circleci/config.yml
- .circleci/config.yml.j2
This PR fixes the failed `sign-release-image` job by ensuring the Cosign version is correctly formatted with a leading 'v' prefix as required by the Cosign orb.
Related astronomer/issues#7188
- Updated Cosign version in `.circleci/config.yml` from "2.2.2" to "v2.4.1"
- Updated Cosign version in `.circleci/config.yml.j2` from "2.2.2" to "v2.4.1"
- The Cosign orb validates version strings using a regex pattern that requires a leading 'v' prefix: `^v([0-9]+\.){0,2}(\*|[0-9]+)$`. 
```
semver='^v([0-9]+\.){0,2}(\*|[0-9]+)$'
if [[ ${COSIGN_VERSION:?} =~ ${semver} ]]; then
echo "INFO: Custom Cosign Version ${COSIGN_VERSION:?}"
else
echo "ERROR: Unable to validate cosign version: '${COSIGN_VERSION:?}'"
exit 1
fi
```
- Our configuration was using "2.2.2" (without the 'v'), causing the validation …
> Fix Cosign Version Format in CI Configuration

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
Better error handling in db-bootstrapper with quay.io/astronomer/ap-db-bootstrapper:0.37.3
https://github.com/astronomer/issues/issues/7166
No special testing needed.
> ap-db-bootstrapper:0.37.3

- .circleci/config.yml
- values.yaml
Image Name |  old  Tag| New tag |
-- | -- | -- |
ap-pgbouncer | 1.24.0-1 |  1.24.1
ap-vector |  0.45.0-2  |  0.46.1
https://github.com/astronomer/issues/issues/7217
https://github.com/astronomer/issues/issues/7215
Tested and validated the metrics and logs with vector 
cherry-pick into release-0.37 and release-0.36
>  updating ap-vendor packages

- .circleci/config.yml
- values.yaml
updated ap-gitsync from 4.2.4-1 to 4.4.0-1
https://github.com/astronomer/issues/issues/7215
gitsync deployments should work as expected
cherry-picked into all branches
> updating ap-gitsync

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api and ui images
| ap-astro-ui | 0.37.10 | 0.37.11 |
| ap-houston-api | 0.37.17 | 0.37.19 |
- https://github.com/astronomer/issues/issues/7223
QA should able to scale the pgbouncer connections by increasing the extraAU and extraCapacity
merge to master nad cherry-pick to release-0.37
> update houston api and ui images

- .github/workflows/pr_checks.yml
Avoid PR description checks by adding 'Yet to update' to forbidden PR description phrases.
N/A, KTLO.
Not needed, this is just GH workflow stuff, not product code.
This only needs to go in master branch.
> Add 'Yet to update' to forbidden PR description phrases.

- bin/generate_circleci_config.py
Remove ap-build, which is no longer used.
These changes do not affect the product and do not require release notes, documentation, or QA.
Resolves https://github.com/astronomer/issues/issues/7241
No testing needed.
> Remove ap-build

- tests/chart_tests/test_nginx_networkpolicy.py
- tests/chart_tests/test_nginx_service.py
- tests/functional_tests/conftest.py
This PR refactors the chart tests to support iterating through multiple documents returned by `render_chart()`. The main change is converting single document testing pattern to a loop-based approach where we iterate through all returned documents and perform the same validation on each controlplane and dataplane template.
- Changed individual `doc` variable to `docs` (plural) across all test files
- Maintained all existing assertions but applied them to each document in the CP-DP template.
- Added specific test for disabled network policies in `test_nginx_networkpolicy.py`
- Standardized naming convention for chart test variables
Related astronomer/issues#7148
- All existing tests pass with the new …
> Refactor Chart Tests to support Nginx Control and Data plane templates

- charts/nginx/templates/nginx-default-backend-networkpolicy.yaml
Fix Network Policy for Nginx Default Backend, This update is necessary to ensure that both the CP and DP Nginx components can communicate properly with the default backend service, which serves as a catch-all for unmatched requests. Without this fix, users may experience errors when accessing undefined routes.
- After splitting the Nginx ingress controller into separate control plane and data plane components, our functional tests were failing specifically at the test_nginx_can_reach_default_backend test. 
- The root cause is that the current network policy only allows access to the default backend from pods with the old label component: ingress-controller 
- Our new architecture uses components: `cp-ingress-controller` and  `dp-ingress-controller`. 
Related astronomer/issues#7148
Update …
> adding podselector for controlplane and dataplane in nginx-default ingress.

- .gitignore
- .helmignore
- charts/alertmanager/templates/ingress.yaml
- charts/astronomer/templates/astro-ui/astro-ui-ingress.yaml
- charts/astronomer/templates/houston/ingress.yaml
- charts/astronomer/templates/ingress.yaml
- charts/astronomer/templates/registry/registry-ingress.yaml
- charts/kibana/templates/ingress.yaml
- charts/prometheus/templates/ingress.yaml
- tests/chart_tests/test_global_ingress_annotation.py
- Add annotation tests to verify that all ingresses support extraAnnotations with per-host ingress and without
- Fix one ingress extraAnnotations
- Remove k8s 1.19 ingress block
Related astronomer/issues#6744
Unit tests are covering all cases here, so no extra testing is needed.
This is intended for 0.37, but should work with other release branches.
> 6744 annotation tests and improvements

- charts/astronomer/templates/config-syncer/config-syncer-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-check-runtime-updates.yaml
- charts/astronomer/templates/houston/cronjobs/houston-check-updates-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-cleanup-airflow-db-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-cleanup-deploy-revisions-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-cleanup-deployments-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-cleanup-task-data-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-populate-daily-task-metrics.yaml
- charts/astronomer/templates/houston/cronjobs/houston-populate-hourly-ta-metrics.yaml
- charts/astronomer/templates/houston/helm-hooks/houston-au-strategy-job.yaml
- charts/astronomer/templates/houston/helm-hooks/houston-db-migration-job.yaml
- charts/astronomer/templates/houston/helm-hooks/houston-upgrade-deployments-job.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/templates/curator/es-curator-cronjob.yaml
- charts/elasticsearch/values.yaml
- charts/kibana/templates/kibana-default-index-cronjob.yaml
- charts/kibana/values.yaml
- tests/__init__.py
- tests/chart_tests/__init__.py
- tests/chart_tests/test_data/enable_all_probes.yaml
- tests/chart_tests/test_probes.py
add probes support for cronjob and jobs
- https://github.com/astronomer/issues/issues/7289
QA should pass liveliness and readiness config for listed services to get covered on the testing
merge to master and cherry-pick to release-0.37
> add probes support for cronjob and jobs

- tests/chart_tests/test_astronomer_cp_dp_feature.py
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_houston_api_deployment.py
- tests/chart_tests/test_nats_sts.py
- tests/chart_tests/test_nginx_networkpolicy.py
This PR updates our test suite to align with the new standardized plane mode configuration approach implemented in the previous PR. It refactors all tests to use the new global.plane.mode pattern instead of the legacy controlplane.enabled and dataplane.enabled flags
- Updated test assertions to check for the new plane mode values ("control", "data", "unified")
- Refactored test values configurations to use global.plane.mode pattern:
- `{"global": {"plane": {"mode": "control"}}}` replaces `{"global": {"controlplane": {"enabled": true}, "dataplane": {"enabled": false}}}`
- `{"global": {"plane": {"mode": "data"}}}` replaces `{"global": {"controlplane": {"enabled": false}, "dataplane": {"enabled": true}}}`
- `{"global": {"plane": {"mode": "unified"}}}` replaces `{"global": {"controlplane": …
> Updated Unit Tests for Plane Mode Configuration Standardization

- .circleci/config.yml
- charts/astronomer/values.yaml
- ap-houston-api 0.37.23
- Fixes dag-downloader tini configs
Note: i got the issue number wrong in the branch name.
- https://github.com/astronomer/issues/issues/6714
This new image make dag-downloader sidecars launch with `tini` as the first command in `/proc/1/cmdline` and `tini` should show up in `kubectl describe pod` for any pods that have a `dag-downloader` sidecar.
Merge to 0.37, 0.36, 0.34, since this is a bugfix.
> ap-houston-api 0.37.23

- .circleci/config.yml
- bin/show-docker-images.py
- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
- values.yaml
This PR ports the certgenerator image configuration from the astronomer/airflow-chart repository to the astronomer/astronomer repository, enabling the Astronomer platform to manage and deploy the certgenerator component across all Airflow deployments.
[Related astronomer/issues#638](https://github.com/astronomer/security-issues/issues/638)
1. Added certgenerator to global airflow images configuration
2. Updated Houston ConfigMap template
- Verified Helm template rendering produces correct configuration
0.37 and cherrypick everywhere
> Port certgenerator image configuration to astronomer/astronomer

- .circleci/config.yml
- values.yaml
ap-certgenerator:0.1.9 (fix CVEs)
https://github.com/astronomer/issues/issues/7315
No extra QA needed, no docs needed.
This change should probably go everywhere since it fixes CVEs, but 0.37 is the main target.
> ap-certgenerator:0.1.9

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/sign-images.py
This PR intends to add a flag to skip artifact signature upload to Rekor and also verify without the signature present in Rekor which is used by default in cosign to store signature. 
- Added `--tlog-upload=false` flag to skip artifact signatures upload to Rekor. 
- Added `--insecure-ignore-tlog=true` flag to verify the signature that was not uploaded to Rekor.
Related astronomer/issues#7334
- All Astronomer images for release 0.37.3 have been manually signed using these updated scripts to ensure:
- Proper cosign functionality with the new version
- Successful authentication with Quay.io registry
- Tested that the new flags work as expected. 
- Image mentioned in the screenshot is signed:
- No third-party dependencies
- Works in air-gapped environments
- Signatures stored only in …
> Updating Cosign Scripts.

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/install-ci-tools
Remove kubent because it is redundant to our json schema validator.
https://github.com/astronomer/issues/issues/7343
No additional QA is needed. This is purely a CI change. No documentation is needed.
Merge into 0.x
> Remove kubent

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/commander/commander-deployment.yaml
- charts/astronomer/templates/houston/api/houston-deployment.yaml
- tests/chart_tests/test_houston_api_deployment.py
- tests/functional_tests/test_container_no_root.py
This PR adds the COMMANDER_WAIT_ENABLED environment variable to both the wait-for-db init container and the main houston container in the Houston deployment, with conditional logic based on the plane mode configuration, so that houston doesn't wait for commander when `control` mode is set. 
This is related to: https://github.com/astronomer/houston-api/commit/8490d76f2cbe6e2efe02d6bc7e3d81403c65dc38
- Implemented conditional logic based on .Values.global.plane.mode:
- unified mode → COMMANDER_WAIT_ENABLED = "true"
- control mode → COMMANDER_WAIT_ENABLED = "false"
This ensures that the commander wait functionality is only enabled in unified plane deployments where houston and commander are in same cluster, while remaining disabled in control plane and other deployment modes
- Fixed …
> Add COMMANDER_WAIT_ENABLED Environment Variable to Houston Deployment

- charts/astronomer/templates/config-syncer/config-syncer-cronjob.yaml
- charts/astronomer/templates/config-syncer/config-syncer-role.yaml
- charts/astronomer/templates/config-syncer/config-syncer-rolebinding.yaml
- charts/astronomer/templates/config-syncer/config-syncer-serviceaccount.yaml
- tests/chart_tests/test_astronomer_config_syncer.py
This PR adds plane mode restrictions to the config-syncer component, ensuring it only deploys on data and unified planes where workloads run, and is excluded from control planes. This will be needed by the registry for synchronising the Houston JWKS between dataplanes.
Related astronomer/issues#7359
- Added plane mode conditional to all config-syncer templates:
```
{{- if or (eq .Values.global.plane.mode "data") (eq .Values.global.plane.mode "unified") }}
``` 
- Added tests for the above change.
- All existing tests continue to pass
- New tests validate plane mode conditional logic.
- Tested manual rendering in unified mode:
- Tested manual rendering in data mode:
- Tested manual rendering in control mode:
1.0
> Config Syncer to run in Data and Unified Planes Only

- charts/astronomer/templates/registry/registry-configmap.yaml
- charts/astronomer/templates/registry/registry-ingress.yaml
- charts/astronomer/templates/registry/registry-networkpolicy.yaml
- charts/astronomer/templates/registry/registry-scc.yaml
- charts/astronomer/templates/registry/registry-secret.yaml
- charts/astronomer/templates/registry/registry-service.yaml
- charts/astronomer/templates/registry/registry-serviceaccount.yaml
- charts/astronomer/templates/registry/registry-statefulset.yaml
- tests/chart_tests/test_astronomer_registry.py
- tests/chart_tests/test_registry_statefulset.py
This PR migrates the Astronomer Registry from TLS certificate authentication to JWT certificate authentication when running in dataplane mode, enabling secure communication between Houston (controlplane) and Registry (dataplane) in multi-cluster deployments.
- astronomer/issues#7358
- https://github.com/astronomer/issues/issues/7160
- https://github.com/astronomer/issues/issues/7161
- Authentication Migration
- **Removed**: TLS certificate mounting (astronomer-tls secret)
- **Added**: JWT certificate mounting using Houston's JWT signing certificate
- **Mount Path**: JWT certificate now mounted at /etc/docker/jwks instead of /etc/docker/ssl
- All Registry Components updated to use dataplane mode
```
| Plane Mode | Registry Deployment | Authentication Method | …
```
> Registry to Use JWT Authentication in Dataplane Mode

- charts/astronomer/templates/houston/cronjobs/houston-cleanup-cluster-audits-cronjob.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_houston_cluster_audits.py
- tests/chart_tests/test_byo_sa.py
- tests/chart_tests/test_data/enable_all_probes.yaml
This PR adds a cron job for cleaning up the cluster audits table. The audits have a configurable retention period after which they are clean up. It follows the already existing cron job pattern.
The corresponding houston PR (merged) is: https://github.com/astronomer/houston-api/pull/2056
Related astronomer/issues#7370
- Unit Tests
---
- Ran the command
```
helm template . --set global.astronomer.houston.cleanupClusterAudits.enabled=true --kube-version=1.32.5 --show-only charts/astronomer/templates/houston/cronjobs/houston-cleanup-cluster-audits-cronjob.yaml
```
to generate the cron job. It is generating fine.
---
- Ran the command
```
helm template . --set global.astronomer.houston.cleanupClusterAudits.enabled=true --kube-version=1.32.5 --show-only …
```
> Adds Cluster Audit cleanup cron job

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/registry/registry-configmap.yaml
- tests/chart_tests/test_registry_configmap.py
This PR adds the correct houston auth endpoint which needs to be used by Registry. 
Related astronomer/issues#7358
- Verified that the setup is working as expected in data mode.
- Unittests are passing as expected.
1.0
> Update Houston event URL and registry events configuration

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
Introduced installation mode in Houston configmap so that populating default cluster can be skipepd for non-unified mode. It would also be used for other future use cases.
Related astronomer/issues#7379
Unit tests
main
1.0
> Introduced installation mode in Houston configmap so that populating default cluster can be skipepd for non-unified mode

- charts/prometheus-postgres-exporter/templates/deployment.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- tests/chart_tests/test_container_read_only_root.py
- tests/chart_tests/test_prometheus_postgres_exporter.py
- prometheus pod containers run with read-only root. this skips authSidecar though, which will be handled separately.
- https://github.com/astronomer/issues/issues/7394
- https://github.com/astronomer/issues/issues/7407
- https://github.com/astronomer/issues/issues/7408
Unit tests are included, and are sufficient. No QA is needed.
This is only for 1.0
> 7394 prometheus read only root

- charts/alertmanager/templates/alertmanager-statefulset.yaml
- tests/chart_tests/test_container_read_only_root.py
Make alertmanager run with read-only root filesystem.
- https://github.com/astronomer/issues/issues/7394
- https://github.com/astronomer/issues/issues/7396
Unit tests are included. No special QA steps are needed.
This is only for 1.0.
> 7394 alertmanager read-only root filesystem

- charts/kube-state/templates/kube-state-deployment.yaml
- tests/chart_tests/test_container_read_only_root.py
- make kube-state deployment container with `readOnlyRootFilesystem: true`
- Fix inconsistent dict indentation style
Note to reviewers: hide whitespace to make this PR much easier to understand.
- <https://github.com/astronomer/issues/issues/7402>
- <https://github.com/astronomer/issues/issues/7394>
No manual testing is needed.
This is only for 1.0.
> 7402 kube state read-only root fs

- charts/alertmanager/templates/ingress.yaml
- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/astro-ui/astro-ui-ingress.yaml
- charts/astronomer/templates/commander/commander-grpc-ingress.yaml
- charts/astronomer/templates/commander/commander-metadata-ingress.yaml
- charts/astronomer/templates/houston/ingress.yaml
- charts/astronomer/templates/ingress.yaml
- charts/astronomer/templates/registry/registry-ingress.yaml
- charts/kibana/templates/ingress.yaml
- charts/prometheus/templates/ingress.yaml
- tests/chart_tests/README.md
- tests/chart_tests/test_ingress.py
- Remove global.acme
- Remove legacy ingress path syntaxes
- Clean up some json data in test cases
All of these code is effectively dead code, so this should function as a no-op in all environments.
- <https://github.com/astronomer/issues/issues/7473>
- <https://github.com/astronomer/issues/issues/7523>
No additional testing is needed. These changes will all be covered under normal test flows.
This is only meant for 1.0, but this could be backported to older versions. This is all effectively dead code, so backporting is not going to get us much.
> 7473 remove global.acme, legacy ingress path syntax

- charts/nats/templates/_helpers.tpl
- charts/nats/templates/jetstream-job.yaml
- charts/nats/templates/statefulset.yaml
- tests/chart_tests/test_container_read_only_root.py
- tests/chart_tests/test_nats_jetstream.py
- tests/enable_all_features.yaml
- Make nats run with read-only root fs
- Add securityContext to nats-exporter, nats config reloader
- fix typo `s/jetsream/jetstream/g`
- Some whitespace changes to remove extra spacing and indentation inconsistency
- Tweak readOnly tests to check pod name, not container name.
The only place nats writes to is /var/run/nats, and that already had its own volume.
- <https://github.com/astronomer/issues/issues/7394>
- <https://github.com/astronomer/issues/issues/7403>
No special testing is needed. We'll find if anything is wrong during normal testing.
This is only for 1.0.
> 7403 nats read-only root fs

- charts/astronomer/templates/_helpers.yaml
- tests/chart_tests/test_astronomer_commander.py
This PR updates variable name and adds default values for COMMANDER_CLOUD_PROVIDER and COMMANDER_REGION as these are required values in commander. 
Related astronomer/issues#XXXX
- The changes are already deployed on cluster with these changes.
- Unittests work as expected. 
1.0
> Update environment variable names for consistency

- charts/prometheus/templates/prometheus-statefulset.yaml
- tests/chart_tests/test_prometheus_statefulset.py
Update kuiper reloder with newly defined variable names to identify the tables  
- Related https://github.com/astronomer/issues/issues/7505
QA should able to automatically detect the dataplanes prometheus and metrics population in control plane
> update reloader env vars for table name definition

- charts/nginx/templates/dataplane/nginx-dp-deployment.yaml
- tests/chart_tests/test_nginx.py
Correct an inconsistency between the cp nginx and dp nginx volumeMounts and command needed for readOnlyRootFilesystem.
https://github.com/astronomer/issues/issues/7404
These configs are known to work in unified, so we don't need any extra QA testing for these. This just makes the feature consistent with what we intended for nginx.
This is only for 1.0.
> Use the same nginx volumeMounts and command for cp and dp. Fix tests.

- charts/prometheus/templates/prometheus-statefulset.yaml
Fix a small addition of readOnlyRootFilesystem to authSidecar that slipped through with https://github.com/astronomer/astronomer/pull/2784
- https://github.com/astronomer/issues/issues/7482
No testing needed. No docs needed. This is just a fix for our dev cycle.
Only for 1.0
> Fix mistaken authSidecar readOnlyRootFilesystem

- charts/vector/templates/vector-configmap.yaml
- charts/vector/templates/vector-daemonset.yaml
- tests/chart_tests/test_read_only_root_filesystem.py
- tests/chart_tests/test_vector.py
- tests/utils/chart.py
Turn on readOnlyRootFilesystem in vector daemonset.
Also:
- Clean up existing tests that are related to this feature
- Remove vector api server configs since we are not using it
- Better debug helm command formatting
https://github.com/astronomer/issues/issues/7400
I have manually tested this change in an eks dataplane cluster.
This is only for 1.0
> 7400 vector daemonset readOnlyRootFilesystem

- charts/elasticsearch/templates/client/es-client-deployment.yaml
- tests/chart_tests/test_elasticsearch.py
remove es client duplicate mount path
https://github.com/astronomer/issues/issues/7816
QA should not see duplicate path errror
> remove es client duplicate mount path

- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_nats_jetstream.py
This PR address an issue with privileged container context added incorrectly while refactoring the changes for readOnlyRoot file system
- https://github.com/astronomer/issues/issues/7819
QA should able to provision the deployment without any errors for elasticsearch
> fix elasticsearch and jetstream config

- charts/astronomer/templates/commander/commander-networkpolicy.yaml
fix commander network policy to allow inbound from houston for metadata reconcilation
https://github.com/astronomer/issues/issues/7824
QA should able to create/update/delete deployments with no errors
merge to release-1.0 and master
> fix commander network policy for metadata reconcilation

- charts/prometheus/templates/prometheus-federate-ingress.yaml
- charts/prometheus/templates/prometheus-federation-auth-configmap.yaml
- charts/prometheus/templates/prometheus-federation-auth-deployment.yaml
- charts/prometheus/templates/prometheus-federation-auth-service.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- tests/chart_tests/test_byo_sa.py
- tests/chart_tests/test_global_ingress_annotation.py
- tests/chart_tests/test_ingress.py
- tests/chart_tests/test_prometheus_statefulset.py
- tests/chart_tests/test_tags.py
This PR removes promproxy and federation logic from unified mode.
- https://github.com/astronomer/issues/issues/7864
- Added Unittests.
Master, 1.0
> PR to remove promproxy from unified mode

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api version 1.0.17
- https://github.com/astronomer/issues/issues/7836
QA should able to open airflow UI
> update houston api version 1.0.17

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/houston/api/houston-deployment.yaml
- charts/astronomer/templates/houston/worker/houston-worker-deployment.yaml
- tests/chart_tests/test_nats_jetstream.py
This PR adds a conditional checksum annotation to the Houston worker deployment to ensure the pod restarts when the NATS JetStream TLS client certificate changes.
Related astronomer/issues#7901
https://github.com/astronomer/issues/issues/7818
https://github.com/astronomer/issues/issues/7351
- Rendered the output locally, added a default checksum since the secret doesn't exist during helm template:
Master, 1.0
> Add checksum annotation for NATS JetStream TLS certificate to Houston worker

- charts/alertmanager/templates/alertmanager-networkpolicy.yaml
- charts/astronomer/templates/astro-ui/astro-ui-networkpolicy.yaml
- charts/astronomer/templates/commander/commander-networkpolicy.yaml
- charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
- charts/astronomer/templates/registry/registry-networkpolicy.yaml
- tests/chart_tests/test_authsidecar.py
Fix network policies and correctly use the ingress components matching the plane modes
- https://github.com/astronomer/issues/issues/7824
QA should see correct network policies when different modes are selected
> fix ingress controller component tags

- bin/helm-install.py
- charts/nats/templates/_helpers.tpl
- charts/nats/templates/configmap.yaml
- charts/nats/templates/jetstream-job-scc.yaml
- charts/nats/templates/jetstream-job.yaml
- charts/nats/templates/statefulset.yaml
- charts/nats/values.yaml
- tests/chart_tests/test_byo_sa.py
- tests/chart_tests/test_nats_jetstream.py
- tests/enable_all_features.yaml
This PR enables createJetStreamJob by default since we have removed STAN from our charts so houston needs to NATS job need to be enabled to work without issues.
Related https://github.com/astronomer/issues/issues/7818
https://github.com/astronomer/issues/issues/7351
- Fixed unittests
- No QA Needed since anyways our QA team do this through terraform values file. 
Master, 1.0
> Enable createJetStreamJob by default

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api version 1.0.20
- https://github.com/astronomer/issues/issues/7936
- https://github.com/astronomer/issues/issues/7831
- https://github.com/astronomer/issues/issues/7911
QA should be able to validate above mapped issues
> update houston api version 1.0.20

- charts/astronomer/templates/commander/commander-deployment.yaml
- charts/astronomer/templates/commander/jwks-hooks/commander-jwks-hooks.yaml
- charts/astronomer/templates/registry/registry-statefulset.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_astronomer_commander_hook_job.py
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_registry_statefulset.py
Mount custom CA volumes platform services
Adds privateCA support for 
- jwks hook job
- commander
- https://github.com/astronomer/issues/issues/7965
QA should able to use the same global.privateCaCerts to mount custom certificates to jwks hook job
> add private ca in jwks hook job

- .circleci/config.yml
- charts/astronomer/templates/houston/api/houston-networkpolicy.yaml
- charts/astronomer/values.yaml
commander image version 1.0.11
- https://github.com/astronomer/issues/issues/7968
QA should able to get commander up and running with no network policy issues
> commander image version 1.0.11

- .circleci/config.yml
- charts/astronomer/values.yaml
update houston api version 1.0.26
- https://github.com/astronomer/issues/issues/7973
QA notes fixes DOD rollback issues
> update houston api version 1.0.26
