- docker/platform/airflow/Dockerfile
This PR applies fix  which upgrades pip3 setuptools in order to resolve an install issue with googleapis-common-protos lib
> Upgrade setuptools in Dockerfile

- docker/platform/airflow/Dockerfile
Recently we merged upgrading to the latest `setuptools` to support another dependency.  This builds on that to PR #46 to pin `setuptools` like we do other Python packages so we can ensure that our builds are deterministic when future releases of `setuptools` are published.
> Pin setuptools for deterministic build

- docker/platform/airflow/Dockerfile
We were using a slightly outdated pip (9.0.1).  This upgrades to the latest and pins it similarly to #49.
> Upgrade + pin pip to 9.0.3

- docs/_includes/head.html
@jlaneve @pcmaffey Can one of you review and sign off on this officially?
The change I made was just moving the external link code inside the jQuery document.ready handler.  I also upgraded jQuery from 1.x to 3.x which wasn't strictly required, but 1.x is old, and this doesn't seem to break anything.  I will send an identical PR for the EE site.
> External links fix (Open)

- Makefile
- bin/build-images
This adds the ability for us to maintain a list of components to be built from their respective github `master` branches, rather than the tagged version in the actual `Dockerfile`.
> Add ability to build and push release candidate builds

- docker/vendor/grafana/include/airflow-containers.json
- docker/vendor/grafana/include/airflow-scheduler.json
Minor changes to regex matching and label formatting. Prometheus config in kubernetes passes release name in as part of `{{component_name}}`. Tested in docker-compose and in helm charts on kubernetes.
> Upgrades to dashboard for new kube environment

- Makefile
No longer needed since we moved the docs to https://www.astronomer.io/guides/.
Edit: Should we just drop the entire `docs` directory too?
> Remove docs commands from Makefile

- docker/platform/airflow/onbuild/Dockerfile
This creates several layers for caching and ensures that we don't `apk add` and `pip install` every time a dag/plugin file changes.
- If `packages.txt` changes, we essentially rebuild from our airflow base.
- If `requirements.txt` changes, we only rebuild starting with `pip install`, and skip `apk add`.
- If dag/plugin/anything else changes, we skip both `apk add` and `pip install`.
Since we aren't creating new layers each time, `astro airflow deploy` (`docker push`) is also a lot faster since it determines that the previously pushed layers already exist in the remote registry. 
This should speed up development and deployment.
Initial pushes will still take a little extra time since it has to push all the layers for the first time. Wondering if we could "warm the cache" in the registry …
> Rearrange COPY commands

- docker/platform/houston-api/Dockerfile
Removes `bcrypt` rebuild as we are now relying on the `bcryptjs`
> Remove bcrypt dependency

- docker/airflow/1.10.1/Dockerfile
- docker/airflow/1.9.0/Dockerfile
Installs redis in Dockerfile to avoid Celery `iteritems()` issue brought by Redis 3.X
https://github.com/celery/celery/pull/5216
> Cap redis install below 3.0.0

- docker/airflow/1.10.2/Dockerfile
Part of #244.
This also needs astronomer/helm.astronomer.io#121 to enable this plugin and
configure it.
This will have no effects without the config settings to enable it.
> Install custom  Airflow RBAC SecurityManager in Airflow image.

- docker/vendor/elasticsearch/Dockerfile
- docker/vendor/kibana/Dockerfile
```
{
name: "flailing-quetzal-elasticsearch-client-bf977b95c-h7wbn",
cluster_name: "astronomer",
cluster_uuid: "N4GbB-okSQ6zNbuGHyPrzw",
version: {
number: "7.2.0",
build_flavor: "oss",
build_type: "docker",
build_hash: "508c38a",
build_date: "2019-06-20T15:54:18.811730Z",
build_snapshot: false,
lucene_version: "8.0.0",
minimum_wire_compatibility_version: "6.8.0",
minimum_index_compatibility_version: "6.0.0-beta1"
},
tagline: "You Know, for Search"
}
```
and 
```
kubectl get pods --namespace andrii-dev | grep elastic
flailing-quetzal-elasticsearch-client-bf977b95c-h7wbn      1/1       Running   0          5m
flailing-quetzal-elasticsearch-client-bf977b95c-r99qb      1/1       Running   0          5m
flailing-quetzal-elasticsearch-data-0                      1/1       Running   0 …
```
> bump elastic and kibana to 7.2.0

- docker/airflow/1.10.3/Dockerfile
this is to fix the werkzeug bug. this should be resolved in Airflow 1.10.4
> pin flask to version 1.0.0

- docker/airflow/1.10.3/Dockerfile
- docker/airflow/1.10.3/include/entrypoint
This will come more in to play in Airflow in the future where this
command will ensure that all the dag-level access control is crrect in
the DB for new dags, but right now we want this to add the extra missing
permissions we added in astronomer/astronomer-fab-securitymanager#4
Closes astronomer/astronomer#353
> Sync Airflow permissions when starting the webserver

- bin/clair-scan.sh
- docker/vendor/grafana/Dockerfile
- docker/vendor/nginx/Dockerfile
v6.3.0-beta4
Docker: Switch base image to ubuntu:latest from debian:stretch to avoid security issues.
**before this change:**
- `2019/08/02 17:12:23 [ERRO] ▶ Image [grafana/grafana:6.0.0] contains 99 unapproved vulnerabilities`
**after this change:**
- `2019/08/02 17:08:42 [ERRO] ▶ Image [ap-grafana:latest] contains 35 unapproved vulnerabilities` 8 medium and 18 Low
```
| Unapproved | Medium CVE-2019-12904       | libgcrypt20  | 1.8.1-4ubuntu1.1         | In Libgcrypt 1.8.4, the C implementation of AES is             |
| Unapproved | Medium CVE-2019-11922       | libzstd      | 1.3.3+dfsg-2ubuntu1      | A race condition in the one-pass compression functions         |
| Unapproved | Medium CVE-2018-19591       | glibc        | 2.27-3ubuntu1            | In the GNU C Library (aka glibc or …
```
> bump grafana

- bin/clair-scan
before:
```
Docker image "astronomerinc/ap-alertmanager:0.10.0-rc.1" have: 0 High / 0 Medium / 0 Low
Docker image "astronomerinc/ap-cadvisor:0.10.0-rc.1" have: 0 High / 1 Medium / 0 Low
Docker image "astronomerinc/ap-curator:0.10.0-rc.1" have: 0 High / 0 Medium / 0 Low
Docker image "astronomerinc/ap-elasticsearch:0.10.0-rc.1" have: 0 High / 18 Medium / 5 Low
Docker image "astronomerinc/ap-elasticsearch-exporter:0.10.0-rc.1" have: 0 High / 0 Medium / 0 Low
```
after:
```
Docker image                    astronomerinc/ap-airflow:0.10.0-rc.1 have          0 High |          0 Medium |          0 Low |
Docker image               astronomerinc/ap-alertmanager:0.10.0-rc.1 have          0 High |          0 Medium |          0 Low |
Docker image …
```
> print clair output as table

- docker/vendor/statsd-exporter/include/mappings.yml
**Issue**: https://github.com/astronomer/astronomer/issues/416
This PR adds mappings to new metrics so that we no longer have metrics as follows:
Instead stuff like dag_id, task_id would become labels.
> [#416] Add mappings for new Statsd metrics

- docker/airflow/1.10.4/Dockerfile
Alpine has added lots of new python packages in their edge repos that we
can use to not have to build the big ones (numpy, panda, grpcio) form
source. This change took the image build time down to 12 minutes for me
on my laptop.
> Use pre-packaged Alpine packages from edge repo for faster builds

- docker/airflow/1.10.4/Dockerfile
- docker/airflow/1.10.4/include/clean-airflow-logs
- docker/airflow/1.10.4/include/entrypoint
Cron _really_ doesn't like to run as any user other than root, and since
we only have a single job we want to run on an easily calculated
schedule we can replace it with a small shell script, then we don't have
to run our gc containers as root.
To make this work with the existing helm charts we catch "crond"
invocations in /entrypoint and run our script instead.
> Replace cron with a shell script that sleeps

- docker/vendor/kubed/Dockerfile
Bug:
https://github.com/astronomer/issues/issues/470
0.11.0 patch notes:
"Kubed v0.11.0 updates Kubernetes dependencies to 1.14.0 and fixes a memory leak issue #357, #304 in k8s.io/client-go. Kubed now requires Kubernetes 1.11.x or later versions. To install/upgrade, please follow the deployment guide here ."
we are on 1.14 kube. I launched a deployment using this image and the webserver came up.
> Upgrade kubed to v0.11.0

- docker/airflow/1.10.5/Dockerfile
- docker/airflow/1.10.5/include/pip-constraints.txt
This file (and the env var) makes pip install this specific version of
the module when ever it might be installed.
See https://pip.pypa.io/en/stable/user_guide/#constraints-files for more
info on this feature
The env var is like setting
`--constraint=/usr/local/share/astronomer-pip-constraints.txt`
automatically on every pip command
> Create a pip constraints file to fix Snowflake/Azure isssue

- docker/airflow/1.10.5/Dockerfile
I'm running a local build now this time. 
Confirmed it's got past that stage:
```
Step 24/33 : ENV PIP_CONSTRAINT=/usr/local/share/astronomer-pip-constraints.txt
---> Running in 5f1d5cd53571
Removing intermediate container 5f1d5cd53571
---> ce377aee091d
Step 25/33 : COPY include/pip-constraints.txt /usr/local/share/astronomer-pip-constraints.txt
---> d1619334ae29
```
> Fix typo in #509

- docker/airflow/1.10.5/Dockerfile
- docker/airflow/debian-1.10.5/Dockerfile
- docker/airflow/debian-1.10.5/include/clean-airflow-logs
- docker/airflow/debian-1.10.5/include/entrypoint
- docker/airflow/debian-1.10.5/include/sudoers
- docker/airflow/debian-1.10.5/onbuild/Dockerfile
This makes use of a multi-stage build to install dev dependencies in on image and only copy the resulting (compiled/installed) python modules in to the final run time image.
I picked a new userid (50000) fairly at random to run as, and added labels so
we can update the platform to know what UID to put in the Security Context, and
not have to pull the sudo tricks we do here.
> Add a debian-based Airflow image

- docker/airflow/debian-1.10.5/Dockerfile
- docker/airflow/debian-1.10.5/include/pip-constraints.txt
We added this to our alpine image in #509, which was merged before the
debian image was added in #508
> Add pip-constraints to Debian airflow image too

- bin/build-airflow
- docker/airflow/1.10.5/Dockerfile
- docker/airflow/1.10.5/onbuild/Dockerfile
- docker/airflow/debian-1.10.5/Dockerfile
- docker/airflow/debian-1.10.5/onbuild/Dockerfile
It doesn't make much difference on CI (as we don't share any layers
between builds) but locally this makes a massive difference - with the
old way each build with a new BUILD_NUMBER would cause every layer below
it to blow the cache -- we can avoid that by setting the label via
`docker build` directly.
> Move BUILD_NUMBER out of early layer

- docker/airflow/1.10.5/include/pip-constraints.txt
- docker/airflow/debian-1.10.5/include/pip-constraints.txt
Pymssql just released 3.0 which is _purposefully_ non functional and
just displays a "this project is discontinued" message, which would be
fine, apart from the fact that the airflow dep was too broad so this got
installed.
Whoops
> Constrain the version of pymssql to a working one

- .drone.yml
- Makefile
This PR comments out all the Airflow related stuff in the `Makefile` and `.drone.yml` files. I've moved our Airflow `Dockerfile`s over to the new home for our Certified Airflow Docker Images - https://github.com/astronomer/ap-airflow.
This repository still needs to live a while longer while we migrate, so just keeping things minimal until we completely separate it all out.
I went ahead and manually pushed up 6 tags from the builds in this repo to get things started while we automate building them:
- `astronomerinc/ap-airflow:1.10.5-alpine`
- `astronomerinc/ap-airflow:1.10.5-alpine-onbuild`
- `astronomerinc/ap-airflow:1.10.5-alpine3.10`
- `astronomerinc/ap-airflow:1.10.5-alpine3.10-onbuild`
- `astronomerinc/ap-airflow:1.10.5-buster`
- `astronomerinc/ap-airflow:1.10.5-buster-onbuild`
> Disable airflow builds

- bin/migration-scripts/README.md
- bin/migration-scripts/pre-0-11-upgrade.sh
Tomorrow, let's test this procedure for:
- the lowest expected astronomer version single-namespace mode
- the lowest expected astronomer version normal namespaces
- 0.10.3 astronomer version single-namespace mode
- 0.10.3 normal namespaces
before we run the procedure for each we will do the following:
- deploy 3 of each executor
- make use of Airflow secrets feature
after we run the procedure we will do the following:
- as described in the last section of the README in this PR
Do not release to customers until after we have the above QA performed
> Add 0.11 migration script

- bin/run-ci
- charts/astronomer/templates/houston/houston-upgrade-deployments-job.yaml
It will make this step unnecessary: https://github.com/astronomer/astronomer/commit/a02202993b10c6909d2836fcf91faac58951533f#
In addition, it will confirm the job is valid in CI.
> Also run the upgrade deployments after install

- charts/postgresql/templates/astronomer-bootstrap-secret.yaml
if user install astronomer chart using another release name, this fix will make it possible.
> Remove hardcoded service name

- Chart.yaml
- charts/prometheus/Chart.yaml
- charts/prometheus/templates/prometheus-alerts-configmap.yaml
PrometheusDiskUsage:
Instead of just saying there is less than 10% left, say how much is left (in percent)
**Checklist**
modified in accordance with the versioning scheme outlined here https://github.com/astronomer/issues/issues/746
> More informative Prom storage alarm

- charts/astronomer/templates/houston/houston-configmap.yaml
This PR patches over some new default values for 0.11.1 of the Airflow chart that were deployed to Cloud last night.
> Add defaults for 0.11.1+ of Airflow

- charts/astronomer/templates/houston/houston-configmap.yaml
This PR overrides the `safeToEvict` settings for the `emptyDir` pods in the Airflow Chart. This is to support deployments being upgraded that won't have the defaults in place.
> Override safeToEvict settings for emptyDir pods

- charts/postgresql/Chart.yaml
- configs/local-dev.yaml
- requirements.yaml
- values.yaml
This PR standardizes the way we enable/disable the new postgresql subchart. I was digging into this comment https://github.com/astronomer/astronomer/pull/546/files#r375550051, and came across it.
Everything seems to work as expected in this format.
**Checklist**
> Standardize how we enable postgresql

- bin/migration-scripts/README.md
Noticed that the migration script git repo was specified separately from where it currently lives in the astronomer branch.  Want to make sure we are specifying the most up-to-date version of the script.
**Checklist**
Not modifying subcharts!
> Update Migration Playbook

- bin/migration-scripts/pre-0-11-upgrade.sh
Script assumed namespace was 'astronomer' when getting list of airflow release names.  Changed to supplied namespace variable.
> Fixing assumed default namespace in migration script

- bin/release
Don't output GCP_TOKEN in CI script. This CI pipeline is not publicly accessible at the moment.
> Fix release script

- charts/prometheus/values.yaml
Closes: https://github.com/astronomer/issues/issues/766
I launched this locally and looked through Grafana. It looked fine.
**Checklist**
> Upgrade Prometheus to 2.15.2

- charts/prometheus/templates/prometheus-service.yaml
Closes: https://github.com/astronomer/issues/issues/748
History: we use prometheus to monitor. It has been restarting, and we had data gaps. To avoid this, we added a replica, and set up services have one service per pod. For applications that can't acceNow the replica has collected data up to the retention window, so we can add it into the default service.
This change switches the default prometheus services from pointing to the first replica to load balancing between replicas. It also maintains the pod-specific services, which have a different use case.
- the main service is load balanced, so it will be more available, but there may be gaps in the data where the routed pod was historically restarting. This is for the use case of viewing metrics more reliably than we do now.
- the other …
> HA Prometheus service

- Makefile
- charts/node-exporter/.helmignore
- charts/node-exporter/Chart.yaml
- charts/node-exporter/requirements.lock
- charts/node-exporter/requirements.yaml
- charts/node-exporter/values.yaml
- charts/postgresql/values.yaml
- charts/prometheus/templates/prometheus-config-configmap.yaml
- requirements.yaml
- values.yaml
This adds nodes metrics to our metrics stack.
Related issues:
- https://github.com/astronomer/issues/issues/784
- https://github.com/astronomer/issues/issues/769
This was tested locally on kind using this kind configuration:
Here is evidence that all nodes became prom targets:
Here are the pods that were running:
**Checklist**
> Add node exporter subchart

- charts/elasticsearch/Chart.yaml
- charts/elasticsearch/templates/_helpers.tpl
- charts/elasticsearch/templates/client/es-client-deployment.yaml
- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/es-configmap.yaml
- charts/elasticsearch/templates/master/es-master-service.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
Closes: https://github.com/astronomer/issues/issues/784
- make es-master service headless by setting spec.clusterIP: None
- rename service because spec.clusterIP is immutable
- change ping schedule so that Linux default TCP keep alive of 2 hours does not cause data nodes to disconnect from the master once every two hours
- reconfigure discovery for elastic search 7
- enable readiness probe for elasticsearch masters
- enable startup probes for elasticsearch clients
**Checklist**
> ElasticSearch reconfiguration

- charts/prometheus/templates/prometheus-config-configmap.yaml
prometheus was trying to scrape ports on the fluentd pods that it shouldn’t be and caused false reporting of it being a down target. 
see https://github.com/astronomer/issues/issues/880
> Fix fluentd scrape config bug

- bin/release
Thanks Ash and Tony for this fix suggestion!
This is to help with CDN propagation for new helm chart versions. I'm only doing it on the index file, because other files (artifacts, i.e. versioned helm tarballs) are intended immutable.
> Reduce cache time for index file

- charts/nginx/templates/nginx-headers-configmap.yaml
Resolves astronomer/issues#921 by adding `cdn.astronomer.io` to the `font-src` content security policy.
> Update font-src policy to allow Astronomer CDN

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
General theme is adding a bunch of alert rules to increase coverage. Sub theme is some reorganization of the groups.
* Lots of new rules to watch Kubernetes specific things as well a some more generic rules that cover all workloads and allow for the removal of workload specific rules. 
* Moved the rules from the platform group that were more infra specific out of the platform group and into groups where they were a better fit. Platform group is now solely astronomer platform workloads and not any infra stuff. 
* Changed `severity: urgent` to `severity: critical` 
* ~I did not add `tier: platform` labels to any of the new alerts, because I’m trying to separate infra platform (k8s, nodes etc) from astronomer platform (workloads that run on the infra). This goes along with proposed changes …
> Prometheus rules

- charts/nginx/templates/nginx-headers-configmap.yaml
Another!
Adds `api.segment.io` to `connect-src` within `Content-Security-Policy`.
Resolves astronomer/issues#990.
> Add additional domain to policy for Segment API

- charts/kube-state/templates/kube-state-deployment.yaml
- charts/kube-state/values.yaml
This is cleanup work reflecting state change live in prod. We upped the replicas count to 2. The chart currently did not allow us to modify the chart through a vairable. This PR allows it.
> Add ability to adjust replica count for kube-state-metrics

- charts/prometheus/templates/prometheus-config-configmap.yaml
With removing the restriction of astronomer namespace only it allows us to get node specific container metrics. the id label is part of this information, by dropping that label these were causing non-unique metrics because that id label was needed to keep them unique.
These needs to go in before we push 0.12.1 to prod
solves https://github.com/astronomer/issues/issues/1005
> Dropping things that start with id was causing duplicate records

- charts/prometheus/Chart.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/values.yaml
This PR adds the ability to enable/disable the prometheus lifecycle api endpoint. The big reason for this to be added is so we can live reload configMap changes without having to restart the prometheus pod 
Related Prometheus docs
https://prometheus.io/docs/prometheus/latest/configuration/configuration/
**Checklist**
> Prometheus lifecycle api

- charts/prometheus/templates/prometheus-config-configmap.yaml
…ce block
We have an issue where the “release” label is not being applied when it should be because it was caught up in a conditional that was for when in single namespace mode.
fix for https://github.com/astronomer/issues/issues/1048
might be fix for https://github.com/astronomer/issues/issues/986
I tested this on stage and the metrics are showing up now.
> Fix for some metrics being collected with wrong labels

- charts/nginx/templates/nginx-service.yaml
This pull request adds support for IBM Cloud Private Load Balancers to Astronomer's NGINX Ingress Controller. This change is being actively used by an IBM/Astronomer client so has been thoroughly tested.
For reference, IBM Cloud Documentation for this feature can be found here: https://cloud.ibm.com/docs/containers?topic=containers-vpc-lbaas
> Added Annotation for IBM IKS Private Load Balancer

- bin/run-ci
- charts/alertmanager/templates/_helpers.tpl
- charts/alertmanager/templates/alertmanager-networkpolicy.yaml
- charts/alertmanager/templates/ingress.yaml
- charts/prometheus/templates/_helpers.yaml
- charts/prometheus/templates/ingress.yaml
- charts/prometheus/templates/prometheus-networkpolicy.yaml
This PR creates ingress sources and modified network policies for prometheus and Alertmanager 
So they can be exposed (behind Houston auth) over the internet. 
Today in order to access these things in prod you must port forward with `kubectl`. Having this ability will enable the ability to add helpful links/buttons to our alert messages to silence alerts, go go straight to prometheus to see the raw data that triggered the alert etc.
> Ingress for monitoring

- .gitignore
- README.md
- bin/drain.sh
- bin/install-platform
- bin/kind/multi-node.yaml
- bin/reset-local-dev
- bin/setup-kind
- charts/astronomer/templates/astro-ui/astro-ui-deployment.yaml
- charts/astronomer/templates/astro-ui/astro-ui-pod-disruption-budget.yaml
- charts/astronomer/templates/commander/commander-pod-disruption-budget.yaml
- charts/astronomer/templates/houston/houston-pod-disruption-budget.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/templates/client/es-client-pod-disruption-budget.yaml
- charts/elasticsearch/templates/data/es-data-pod-disruption-budget.yaml
- charts/elasticsearch/templates/master/es-master-pod-disruption-budget.yaml
- charts/elasticsearch/values.yaml
- charts/nginx/templates/nginx-default-backend-pod-disruption-budget.yaml
- charts/nginx/templates/nginx-deployment-default.yaml
- charts/nginx/templates/nginx-pod-disruption-budget.yaml
- charts/nginx/values.yaml
- charts/prometheus/templates/prometheus-pod-disruption-budget.yaml
- configs/local-dev-ha.yaml
The point of this PR is to make replicas configuration effective for HA during voluntary disruptions for the workloads that are already HA (or were very easy to make HA). There are other parts of the platform that are not HA yet and will take a bit more work (registry, prisma).
If workloads are tolerant to voluntary disruptions, taking less than 2 minutes to move, they are candidates to run on spot instances, and this can save 80% of compute cost.
Add HA for:
- astro-ui
- nginx-default-backend
Add PDB for:
- houston
- commander
- astro-ui
- es-client
- es-master
- es-data
- nginx
- nginx default backend
- prometheus
Default to HA configuration for:
- houston
- commander
- nginx
Add to script to enable local testing of cordon and drain
Video of testing: …
> Add pod disruption budgets

- charts/astronomer/templates/houston/houston-upgrade-deployments-job.yaml
removed the invalid spec fields and added in the appropriate fields to accomplish the same goal for `kind: Job` rather than what it had which is for `kind: CronJob`
resolves https://github.com/astronomer/issues/issues/1079
> Fixed Houston upgrade deployments job has an invalid job spec

- .gitignore
- Chart.yaml
- charts/astronomer/templates/houston/houston-jwt-certificate-secret.yaml
- charts/astronomer/values.yaml
This patch, in the form of an optional configuration to 0.12, allows upgrades from before 0.10 to work without first delete --purge of the whole platform. The reason the --purge was required before is that since 0.10, there is a new secret installed by the helm hook. Since the helm hook runs by default only on installation, then delete --purge + install is performed to get the jwt token resource to create.
The solution proposed by this change request is to provide an optional configuration that configures this helm hook to run on each upgrade, in addition to installation. Since the helm template generates a self-signed certificate on each application, it will replace Houston's certificate authority on each helm upgrade.
One example for why this is valuable is that it eliminates the …
> Add configuration to re-generate CA on each upgrade

- charts/prometheus/templates/prometheus-config-configmap.yaml
raised the global default and also the kube-state-metrics, airflow scrape jobs. 
For the high frequency ones for dashboards. Starting with small step to 10 seconds. We can revisit if we are still collecting too much.
> Prometheus global scrape interval less frequent

- bin/migration-scripts/upgrade.sh
- This function will fail if platform namespace is not named "astronomer"
- Use namespace var to handle any namespace name
- Related to astronomer/issues#1123
> Add namespace var to upgrade_version_in_astro_db

- charts/astronomer/templates/_helpers.yaml
@ashb added this block a while ago, but I think it was dropped during a refactor with the `houston_environment` helper.
> Add secret block back into Houston environment

- charts/prometheus-blackbox-exporter/values.yaml
The default limit of blackbox exporter needed to be higher for a larger production environment. Again these can still be overridden at the global level but the defaults needed to be better.
> Raised the default cpu limit of blackbox exporter

- charts/prometheus/templates/prometheus-config-configmap.yaml
pods have the labels `kubernetes-executor` and `kubernetes_exector` when those get turned in to metric labels the dash becomes and underscore which causes duplicated labels. Prometheus must have unique labels per metric.
> Prevent duplicate labels of kubernetes_executor

- charts/prometheus/templates/prometheus-config-configmap.yaml
Allows us to gather metrics from the kube-apiserver itself.
This was put in live on prod last week to get info about the API Server with suspected rate limiting. Following up to get this committed so it doesn't get reverted.
> Added scrape job for kube-apiservers.

- CHANGELOG.md
Added a list of v0.13 changes (including bugfixes and improvements) to our platform changelog based on our v0.13 project board: (https://github.com/orgs/astronomer/projects/36)
A few notes:
- I did _not_ include mention of Helm3 and support for IKS environment
- I added "Stability Improvements to the Astro UI" instead of specifying exactly what we changed - is that ok?
@schnie @vishwas-astro Happy to take your feedback here, never sure how specific we need to be but I figured the more the better (relative to release notes, which are more high-level)
> Add v0.13 changes to changelog

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
Chagned CPUThrottling alert to have higher threshold and exlucde pods from kube-system namespace. In managed cloud environments there is rarely anything that can be actionable if this alert fires for things in kube-system. For other environments the cluster operators should have alerting in place for this already and our alerts are only around the astronomer platform.
Changed nginx 5xx/4xx errors to only report on the astronomer deployment namespace.
Airflow deployments produce 5XX errors when airflow is starting up and is expected behavior, people see the airflow loading page. We really want to target the astronomer platform here with these alerts not all the individual airflows.
> Updates to CPUThrottlingHigh and Nginx 5xx and 4xx alerts

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
Resolution for issue https://github.com/astronomer/issues/issues/1214
related to https://github.com/astronomer/issues/issues/1189
change labels in airflow alerts from $labels.release to $labels.deployment. I think the ones with release were there in error as we do not have `release` available as a usable label.
> Corrected labeling in airflow alerts

- charts/fluentd/values.yaml
updating the image tag to use the most recent build of fluentd that contains a fix for the plugin that was causing issues.
> Updated fluentd to use image with bugfix

- charts/astronomer/templates/registry/registry-configmap.yaml
- Increase registry timeout to 30s
- Previous default value can cause houston to loop on upgrade deployment when user pushes to registry
- Related to astronomer/issues#1194
> Increase registry timeout to 30s

- Chart.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nginx/values.yaml
- charts/prometheus/values.yaml
There were container image versions that were changed on the release-0.13 branch for the .1-alpha2 release. This is bring those changes over to master.
> Cherrypicked changes from release 0.13.1-alpha2

- charts/elasticsearch/values.yaml
Curator image had a bug after CVE updates where it was missing a python module. The image has been updated and this update is to have helm use the new image tag.
> Update curator image tag for bug fix.

- Chart.yaml
- bin/release
- charts/alertmanager/values.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/templates/exporter/es-exporter-deployment.yaml
- charts/elasticsearch/values.yaml
- charts/fluentd/templates/fluentd-configmap.yaml
- charts/grafana/values.yaml
- charts/keda/values.yaml
- charts/kibana/values.yaml
- charts/kube-state/values.yaml
- charts/nginx/templates/nginx-configmap.yaml
- charts/nginx/values.yaml
- charts/node-exporter/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus/values.yaml
git cherry -v release-0.13 | grep +
+ e9b3271b040e816ef1366341ee9cda6cd2c4df70 Add configuration to re-generate CA on each upgrade (#627)
+ f890251efd8de84e2e9f3e863393e7f90636ce66 Add upgrade script (#630)
+ 863f1c2da29f3fed839b3d2d0a3a903c2a7de211 Add example IKS fluentd config (#632)
+ 6cbd67854c176c80d550565135bd9ac4c90e5b65 Make the probes more configurable (#636)
+ dc5cef1f3fd6a1475b8c0a1899aa2d30f03047fc Made scrape intervals less frequent (#628)
+ 2c3aafd94a5e9dd7cedff70771fc8b13844ff507 Add namespace var to upgrade_version_in_astro_db (#637)
+ 81fe3031d6c1cecb0a0ff444de93fd6cd630b1a0 Add list of other supported images (#640)
+ 2423fe547e01ec1827a1f168d1e30cf3fa5a42a3 Houston 0.13.3 and reconfigure resources on blackbox exporter (#646)
+ 7b4dd139998d7d4e96bc2c281b7aa71b4190e016 …
> Add missing commits from 0 13

- CHANGELOG.md
@ryw I didn't include each specific image with a corresponding version, though I did link out to Jim's PR (within this `astronomer/astronomer` repo) which of course contains those changes.
Lemme know what you think. Maybe the master list should just live in astronomer.io/docs/astro-cve?
> update changelog with 0.13.1 CVE patches

- charts/prometheus/templates/prometheus-config-configmap.yaml
We started seeing duplicates for the label `label_kubernetes_pod_operator` that was causing kube-state-metrics  ingestion issues. A label drop was added for this label to get through the issue
> Adding prometheus label drop for a duplicate label

- charts/astronomer/templates/registry/registry-statefulset.yaml
'serviceName' should only exist when it's a stateful set. The conditional was not the negation of the conditional for the 'kind', which is:
```
{{- if or .Values.registry.gcs.enabled .Values.registry.azure.enabled }}
```
> Fix registry configuration

- charts/astronomer/values.yaml
need cherry-pick to https://github.com/astronomer/astronomer/tree/release-0.14 after merge.
> Bump houston-api image to 0.14.0

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/registry/registry-configmap.yaml
- charts/astronomer/templates/registry/registry-statefulset.yaml
- charts/astronomer/values.yaml
- Add ability to use AWS S3 bucket as registry storage backend
- Example config:
```
astronomer:
registry:
s3:
enabled: true
accesskey: my-access-key
secretkey: my-secret-key
region: us-east-1
bucket: astro-registry
```
- Driver documentation:
- https://docs.docker.com/registry/configuration/
- https://github.com/docker/docker.github.io/blob/master/registry/storage-drivers/s3.md
- Related to astronomer/issues#93
> Add support for AWS S3 registry backend

- charts/astronomer/templates/houston/houston-configmap.yaml
This PR is the Astronomer side of this PR to remove the platform refs from Airflow chart here: https://github.com/astronomer/airflow-chart/pull/66.
This essentially takes the old values that were hard-coded into the Airflow chart templates and uses the new helm variables to add them back in via the platform level.
> Moves default configuration out of Airflow chart to Houston default

- charts/elasticsearch/templates/client/es-client-deployment.yaml
- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/es-psp-clusterrole.yaml
- charts/elasticsearch/templates/es-psp-rolebinding.yaml
- charts/elasticsearch/templates/es-psp.yaml
- charts/elasticsearch/templates/es-serviceaccount.yaml
- charts/elasticsearch/templates/exporter/es-exporter-deployment.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- charts/fluentd/templates/fluentd-psp-clusterrole.yaml
- charts/fluentd/templates/fluentd-psp-rolebinding.yaml
- charts/fluentd/templates/fluentd-psp.yaml
- charts/nginx/templates/nginx-deployment.yaml
- charts/nginx/templates/nginx-psp-clusterrole.yaml
- charts/nginx/templates/nginx-psp-rolebinding.yaml
- charts/nginx/templates/nginx-psp.yaml
- templates/psp/permissive-clusterrole.yaml
- templates/psp/permissive-clusterrolebinding.yaml
- templates/psp/permissive-psp.yaml
- templates/psp/restrictive-cluserrolebinding.yaml
- templates/psp/restrictive-clusterrole.yaml
- templates/psp/restrictive-psp.yaml
- values.yaml
added policies, clusterroles and role bindings for
- nginx
- fluentd
- elasticsearch
added service account for elastic search (fluentd and Nginx already had them)
Everything else gets covered by a general restrictive and permissive policies. This will also need good testing before we can merge in to any release branch
**special attention**
Review the Policies themselves to see if we want to tighten up or change them in anyway.
> Add support for Pod Security Policies

- bin/run-ci
This will save a lot of Circle CI credits, and when Tony's PR is done we can turn it back on
> Disable e2e testing until working

- charts/elasticsearch/values.yaml
This was causing a helm 3 upgrade error: https://app.circleci.com/pipelines/github/astronomer/google-environments/27/workflows/862bed6c-2ba2-4b7c-8410-f4f080dc0869/jobs/119/parallel-runs/0/steps/0-103
we can see in the dry run it's duplicated https://app.circleci.com/pipelines/github/astronomer/google-environments/27/workflows/862bed6c-2ba2-4b7c-8410-f4f080dc0869/jobs/117/parallel-runs/0/steps/0-103
> Remove duplicate env var

- charts/astronomer/templates/houston/houston-configmap.yaml
Depends on https://github.com/astronomer/astronomer/pull/702
Based on the conversation in https://github.com/astronomer/astronomer/pull/659
**Note**: Only review last commit: https://github.com/astronomer/astronomer/pull/703/commits/c19043c68a07dee5028d2a439da5435dbc4cc731
> Add support for AC 1.10.5 & 1.10.10 Docker images

- charts/alertmanager/templates/alertmanager-configmap.yaml
- charts/alertmanager/templates/alertmanager-statefulset.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
Adds external URL setting so that alerts can have links back to alert manager and prometheus. 
Groups platform alerts by alter name to help organize things better.
> Slack alert improvment

- charts/grafana/values.yaml
Security Update and Dashboard update. 
Security update pushes us up to the 7.0 release of Grafana
https://grafana.com/docs/grafana/latest/guides/whats-new-in-v7-0/
> Update Grafana to 7.0.1-r1

- charts/astronomer/templates/astro-ui/astro-ui-deployment.yaml
The env vars here causes problems with deployment. These env var name and values should go in `.Values.astroUI.env`. The template is already setup to loop through that and add env vars.
> remove env vars that are duplicated in cloud config

- charts/astronomer/templates/houston/houston-check-updates-cronjob.yaml
- charts/astronomer/templates/houston/houston-cleanup-deployments-cronjob.yaml
- charts/astronomer/templates/houston/houston-expire-deployments-cronjob.yaml
- charts/astronomer/templates/houston/houston-upgrade-deployments-job.yaml
- charts/astronomer/values.yaml
This feature is linked to the houston-api PR located here: https://github.com/astronomer/houston-api/pull/334
I confirmed this fix by testing the following:
1. Build a docker image locally
2. Push the docker image to my personal docker hub registry
3. Change the `houston-api` image in the `charts/astronomer/values.yaml` to the newly created docker image
4. Run `./bin/reset-local-dev`
5. Check the k8s pods and logs to make sure everything is working correctly
6. Launch the `astro-ui`, log in and click test to make sure `houston-api` is responding correctly
> Change houston charts from npm to yarn

- charts/astronomer/templates/cli-install/cli-install-configmap.yaml
- charts/astronomer/values.yaml
Update install script to use GitHub API to get the latest minor version is there is a patch version mismatch between the platform and the CLI.
Fixes https://github.com/astronomer/issues/issues/1116
**Testing**
The best way to test is this to copy the script into a .sh file and try running it.  You'll need to modify `TAG` at the top of the script because when you're running in the shell you won't have access to `{{ .Chart.Version }}` like you would from the final version from helm.  The script will fallback to the `{{ .Chart.Version }}` when a version isn't provided by the user.
The script (copy lines 18-EOF from the proposed config-map.yml) can be run with the following test cases:
Update the `TAG=${1:-v{{ .Chart.Version }}}` line with test input like `TAG=${1:-v0.13.2}`.  Keep in mind …
> Update install script to get latest minor version

- charts/astronomer/templates/prisma/prisma-deployment.yaml
- charts/astronomer/templates/registry/registry-statefulset.yaml
- charts/astronomer/values.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/values.yaml
- values.yaml
I figure just add the label no matter what because it's just one less thing to worry about configuring.
> Use on-demand instances for sensitive workloads

- charts/prometheus/templates/prometheus-config-configmap.yaml
- Add support for later versions of cAdvisor that use slightly different labels
- This resolves missing CPU / Mem / Networking metrics in EE environments
- Related to astronomer/issues#1458
> Add labels for later versions of cAdvisor

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
Work for issue https://github.com/astronomer/issues/issues/1431
The new alerts are duplicates of our current pod crashlooping and pod not ready alerts, but filtered to only core platform components. 
New Alerts added:
HighNumberOfPodsNotReady (if we have greater than 25 pods not ready, sign of larger issue)
CriticalComponentPodNotReady (astronomer platform components)
CriticalComponentPodCrashLooping (astronomer platform components)
NodeDown (can't reach node-exporter on a node)
NumberOfNodesHigh (alert for nat gateway limit, solves https://github.com/astronomer/issues/issues/1253)
> Critical alert changes

- charts/astronomer/values.yaml
fix https://github.com/astronomer/issues/issues/1490
**> Note: need cherry-pick to release branch too.!**
References:
[1] https://app.circleci.com/pipelines/github/astronomer/houston-api/1131/workflows/c8afacae-a596-42ad-9b83-1707443405a4/jobs/3378
> bump houston-api image to 0.16.3

- charts/prometheus-blackbox-exporter/values.yaml
These were set too low and caused problems.
> Raise default resource request/limits for blackbox exporter

- charts/alertmanager/templates/alertmanager-configmap.yaml
- charts/alertmanager/values.yaml
If a `platformCritical` value is present, creates a route to match `critical` `platform` alerts and sends them to a critical alert receiver that only sends to pager duty. 
The route is configured such that an alert that matches the `platformCritical` receiver can continue matching other routes such as `platform`. This allows us keep the critical receiver scoped to just pager duty handling and not have to add any of the slack configs that we already have for platform alerts.
> Alert routing changes

- charts/astronomer/templates/registry/registry-statefulset.yaml
In order to run docker registry with multiple replicas all pods must use the same http secret.
This http secret is generated by helm as a random string of 32 characters. This will be updated every time/anytime the helm release is installed or upgraded. 
I choose the random string route rather creating a secret and storing it so that we don't have to manage the secret in anyway. 
What this parameter is for, from the docker docs. 
> A random piece of data used to sign state that may be stored with the client to protect against tampering. For production environments you should generate a random piece of data using a cryptographically secure random generator. If you omit the secret, the registry will automatically generate a secret when it starts. If you are building a cluster of registries …
> Added env var for REGISTRY_HTTP_SECRET

- charts/astronomer/templates/registry/registry-statefulset.yaml
- charts/astronomer/values.yaml
Previously the registry was hardcoded at number of replicase == 1. Now that we are setting up for HA registry with multiple replicas the template needs to be variable so it can populate the template from a values file. This PR does that, with a default value of 1 for non HA deployments.
> Allow registry template to specify replica count via values.

- Makefile
- bin/release-helm-chart
We are now using uniform bucket permissions for helm repo, so we need to stop attempting to set an ACL because it now triggers an error.
> Do not set ACLs since we now use uniform bucket perms.

- charts/alertmanager/templates/alertmanager-configmap.yaml
fixing a dumb typo mistake in the alert manager config.
> Corrected typo in severity label

- charts/astronomer/templates/commander/commander-networkpolicy.yaml
- charts/astronomer/templates/prisma/prisma-networkpolicy.yaml
- charts/astronomer/templates/registry/registry-networkpolicy.yaml
Prevously this allowed things with component label houston. Needs to allow component label houston-worker as well.
> Allowing houston-workers through network policies.

- charts/nats/templates/service.yaml
- charts/prometheus/templates/prometheus-config-configmap.yaml
- charts/stan/templates/service.yaml
Updates the nat server scrape config to be more specificity and added the Stan server scrape config.
nats and Stan services needed prometheus annotations to be found by service discovery. Previously it only existed at the pod level.
> Improve Nats Metrics Gathering

- Makefile
- bin/release-helm-chart
This sets the max-age of the index.yaml to 5 minutes, which allows us a shorter window until we get consistent results after releasing a new helm chart.
> Set max-age of index.yaml files to 5 minutes.

- bin/migration-scripts/upgrade-to-lts.sh
There is a situation with some users who have upgraded a few times where a historically present config is carrying through upgrades such that it is causing a collision in a yaml merge of two lists. This is solved by deleting elasticsearch statefulset but not the persistent volumes behind.
> Improve Astronomer 0.16 upgrade script

- charts/astronomer/templates/houston/api/houston-deployment.yaml
Adding wait for NATS so Houston will correctly connect to NATS and avoid reconnect failures.
Related https://github.com/astronomer/issues/issues/1534
> Wait for nats

- Makefile
Using `.ONESHELL` changes the behavior of every target in the entire Makefile. Looking at how how it was being used, I found that we didn't really need it, and removing it would make our Makefile a bit simpler, more compatible and more in line with common Makefile behaviors.
One consideration here is that some of the logic I added requires GNU find, so it will not work on vanilla macOS. I assume this isn't a problem though since the Makefile is meant to be run on linux.
> Remove .ONESHELL, rework logic to enable this.

- charts/astronomer/templates/houston/worker/houston-worker-pod-disruption-budget.yaml
- charts/nats/templates/pod-disruption-budget.yaml
- charts/nats/templates/service.yaml
- charts/nats/templates/statefulset.yaml
- charts/stan/templates/pod-disruption-budget.yaml
- charts/stan/templates/service.yaml
- charts/stan/templates/statefulset.yaml
**Context**
Astro CLI is occasionally reporting `Error: connection closed` on `create` and `delete` deployment commands.  This most likely affects Astro UI as well, but errors there haven't been reported yet. 
**Propsed Solution**
Currently NATS and STAN can be down for a short amount of time and our system will continue to report that it's healthy.  We need NATS and STAN to have `maxUnavailable: 1` to function similarly to Commander.
> Add Pod Disruption Budget for NATS and STAN

- charts/nginx/templates/nginx-headers-configmap.yaml
From [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/vr):
> The WebVR API has been replaced with the WebXR Device API and is currently being removed from the web platform. Use the feature identifier xr-spatial-tracking for WebXR Device API instead.
This is why this error is being shown in Chrome:
> Update NGINX policy

- Makefile
* Remove GNU-find specific syntax and replace it with busybox shell compatible syntax
* Improve cp -R syntax
I have verified this on my workstation inside of busybox, and inside of the astronomerinc/ap-e2e-test container.
> Remove GNU-find specific syntax

- charts/astronomer/templates/houston/cronjobs/houston-check-updates-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-expire-deployments-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-upgrade-deployments-job.yaml
- charts/astronomer/tests/houston_pdb_test.yaml
closes: https://github.com/astronomer/issues/issues/1229
houston PDB is accidentally patching the labels on the these jobs, this makes the houston rollout get 'stuck' for users with low replica count. For example if PDB says maxUnavailable: 1, then it will remain stuck as long as any of these jobs are in a non-ready state, including "completed"
I'm going to leave this in draft, I want to see if I can use the new unit testing framework to capture the logic 'no pods match these labels except the ones we want'
This is optionally in 0.18 and ought to be backported to 0.16, since it is a bug fix.
> Fix Houston API pod disruption budget to not match Houston cron jobs

- charts/prometheus/templates/prometheus-config-configmap.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/tests/prometheus-config-configmap_test.yaml
Found another issue related to conflating namespace and release name.
Closes: https://github.com/astronomer/issues/issues/1680
> Fix scrape configuration for blackbox exporter

- charts/astronomer/templates/houston/worker/houston-worker-deployment.yaml
In support of fully enabling both create and and delete deployment workers to publish to commander.
Resolves astronomer/issues#1619
See Houston API Pull Request for all of the testing steps: https://github.com/astronomer/houston-api/pull/417
> Enable Commander for Houston API Workers

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/houston/api/houston-deployment.yaml
- charts/astronomer/templates/houston/worker/houston-worker-deployment.yaml
Remove wait for NATS from charts and add it to the init container instead.
Resolves https://github.com/astronomer/issues/issues/1683
> Add NATS_URL to entrypoint. Remove extra NATS wait

- charts/astronomer/values.yaml
`astronomerinc/ap-astro-ui:0.19.0`
Commits: 
> 98702fa Build(deps-dev): Bump eslint from 7.6.0 to 7.7.0 (https://github.com/astronomer/astro-ui/pull/751)
> bafae21 Build(deps): Bump lodash from 4.17.19 to 4.17.20 (https://github.com/astronomer/astro-ui/pull/750)
> 5e8ad7b Build(deps): Bump logrocket from 1.0.10 to 1.0.11 (https://github.com/astronomer/astro-ui/pull/747)
> 6b5f3e1 Build(deps-dev): Bump jest from 26.3.0 to 26.4.0 (https://github.com/astronomer/astro-ui/pull/749)
> 90d3fe3 Delete deployment error messaging (https://github.com/astronomer/astro-ui/pull/745)
> b86b0eb Build(deps): Bump @testing-library/jest-dom from 5.11.2 to 5.11.3 (https://github.com/astronomer/astro-ui/pull/744)
> f35f85c Displays toast message after successful deployment deletion …
> UI package updates, variable RBAC updates, deployment removal enhancements

- .circleci/config.yml
- .github/pull_request_template.md
- .gitignore
- Makefile
- bin/functional-tests/requirements.txt
- bin/functional-tests/test_astronomer.py
- bin/test-ap
- charts/prometheus/templates/prometheus-config-configmap.yaml
- Add a scrape configuration to prometheus to monitor kube-dns
- Add to PR template
- Add a place to do system testing
Closes: https://github.com/astronomer/issues/issues/1717
I added a very simple, functional testing set up.
This is what it looks like when the cluster is using kube dns:
This is what is looks like when the cluster is not using kube dns, e.g. core dns:
> Add Prometheus monitoring for kube-dns

- Makefile
- charts/prometheus/templates/prometheus-alerts-configmap.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/tests/prometheus-alerts-configmap_test.yaml
- charts/prometheus/values.yaml
This allows for a user to pass custom alerts into prometheus alerts configmap via values in top-level `config.yaml`.
Allow for user-supplied values in prometheus alerts configmap
Resolves astronomer/issues#1684
`/charts/prometheus/tests/prometheus-alerts-configmap_test.yaml`
- User supplied values in `config.yaml`
- We can see the user supplied airflow alert passed through to `/charts/prometheus/templates/prometheus-alerts-configmap.yaml`
- We can see the user supplied platform alert passed through to `/charts/prometheus/templates/prometheus-alerts-configmap.yaml`
> Allow for user-supplied values in prometheus alerts configmap

- bin/install-platform
- charts/astronomer/templates/commander/commander-networkpolicy.yaml
- charts/astronomer/templates/prisma/prisma-networkpolicy.yaml
- charts/astronomer/templates/registry/registry-networkpolicy.yaml
The houston upgrader pod needs network policy to allow connection. This bug is caused by my other PR that adjusted the labels on the houston upgrader pod to not match the houston pod disruption budget.
hot fix before release, no associated issue
I turned this part on by default in CI runs.
> Fix network policy to allow houston upgrader to connect to DB

- charts/astronomer/values.yaml
Resolve dependency issues in the minified version of `astro-ui` in `0.19.1` (https://github.com/astronomer/astro-ui/commit/95bff83ec735519023abe8c1e2bccb113259256b)
This issue is only occurring on the minified, production ran version. Was not reproducible in the `localhost` environment where the code is not compiled and minified.
No ticket created. Issue was found during `0.19` internal testing by @shmanu017 
Should resolve: 
This error was seen across the app on different pages such as workspace user, billing, and service account. 
The easiest way to test would be to:
1) Makes sure trials are turned on and login
2) Create a new workspace
3) Add workspace billing 
If the page does not flash to replicate the screenshot above, then issue is resolved.
> Astro UI revert build dependencies to previous versions

- charts/astronomer/values.yaml
Continued effort to fix https://github.com/astronomer/astronomer/pull/822.
Reoccuring hooks error on the Workspace billing page after submitting billing info.
No ticket created. Issue was found during 0.19 internal testing by @shmanu017
1. Makes sure trials are turned on and login
2. Create a new workspace
3. Add workspace billing and submit form
4. Expect page to reload then show billing info and edit button.
> Astro UI fix Oops! on workspace billing page

- charts/astronomer/values.yaml
Resolves astronomer/issues#XXXX
> Please add helm unit …
> Airflow chart fix for secret synchronization

- .gitignore
- bin/functional-tests/test_astronomer.py
- charts/prometheus/templates/prometheus-config-configmap.yaml
- values.yaml
Collect metrics from Houston's metrics endpoint
Closes: https://github.com/astronomer/issues/issues/1727
Prometheus misconfiguration is the biggest risk. Adding to the functional testing to check that the metrics are collected as intended.
> Collect metrics from Houston

- bin/reset-local-dev
- charts/astronomer/templates/houston/api/houston-deployment.yaml
- charts/astronomer/tests/houston_api_houston-deployment_test.yaml
Currently Houston performs database migrations as part of the API container startup. These happen before the serving portion of the application has started. If those migrations take a long time, it will cause the container to fail its liveness probe and will get restarted. This change moves that work to an init container to be performed before the start up of the primary container. This takes the migration time out of the application startup time as far as the liveness and readiness probes are concerned. 
There are two minor changes that fix bugs in the kind startup script for local dev that I fixed as well. 
Resolves https://github.com/astronomer/issues/issues/1658
Related PR to houston https://github.com/astronomer/houston-api/pull/442
If the init container didn't run or migrations …
> Improve Houston API Startup by Performing Houston migrations via Init Container

- charts/astronomer/values.yaml
Increment the Airflow chart version. This change is to optimize DNS queries with regard to pgbouncer lookups. This is PR'ed into the 0.16 release branch because it is only intended for the LTS version.
> Please make the PR title informative to the user experience. For example when adding a feature, say "Add metrics tab for Deployments" instead of "Bump Astro-UI to version X.Y.Z". Bugs are sometimes harder to make customer-facing because they are very detailed, but do what you can. Instead of "Fix metrics cardinality bug" (user does not know what 'cardinality' means and does not matter to them), say "Fix bug slowing down the metrics tab". The PR title will be used for the commit message when it's merged, and these commit messages are used to …
> Optimize DNS query volume with regard to pgbouncer lookups

- charts/grafana/dashboards/kube-dns.json
- charts/prometheus/templates/prometheus-config-configmap.yaml
Add a grafana dashboard for kube dns, also fix a bug in the scrape configuration
Closes: https://github.com/astronomer/issues/issues/1696
The main risk is that grafana won't start (mitigated by smoke tests) or that the scrape config is still broken. The issue is that kind does not use kube-dns, so the scrape config can only be functionally validated in GKE.
> Kube-DNS metrics dashboard

- .pre-commit-config.yaml
- charts/alertmanager/templates/alertmanager-statefulset.yaml
- charts/astronomer/templates/registry/registry-statefulset.yaml
- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- charts/postgresql/templates/statefulset-slaves.yaml
- charts/postgresql/templates/statefulset.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- templates/_apivers.tpl
Remove helm template for apiVersion.StatefulSet which sometimes selected `apps/v1beta2` when `apps/v1` was available. This template was also only one of three places that should have had such a mechanic if it were useful (daemonset, statefulset, deployment).
This will be a no-op to the user, it merely takes out an unneeded conditional.
Remove apiVersion.StatefulSet, always use apps/v1
Resolves astronomer/astronomer/pull/838 discussion points, and supersedes that PR.
There should be no risks associated with this change. the `apps/v1` endpoint has existed since way before any currently supported version.
> Remove apiVersion.StatefulSet, always use apps/v1

- .circleci/config.yml
- .circleci/config.yml.j2
Disallow publishing of future releases to public helm repository, github tag, and github release.
Resolves astronomer/issues#1771
AFAIK it's not possible to test this without committing to at least two release branch (eg: release-0.16 and release-0.19). It's possible the regular expressions do not match due to the regex dialect used by CircleCI, but I have made an effort to reference other people's regex examples and think that this is correct.
> Disallow publishing of future releases to public helm repository

- .circleci/config.yml
- .circleci/config.yml.j2
This is a quick follow up to #843 which left out a trailing slash at the end of the regex. I also found a way to test this, by pushing it as a future release branch. This was done so [here](https://app.circleci.com/pipelines/github/astronomer/astronomer?branch=release-0.999). The failing tests are due to me deleting the branch before they could run. The important details is that there are "approve-internal-release" and "release-to-internal" steps.
> 1771 add missing slash

- bin/functional-tests/conftest.py
- bin/functional-tests/test_config.py
- bin/functional-tests/test_network_security.py
- bin/test-ap
- charts/nginx/templates/nginx-default-backend-networkpolicy.yaml
Fix a test that is failing in CI and also fix network access from nginx ingress to default backend
no issue associated, part of release 0.20 fixes
this change only adjusts tests or includes a functional test for the network policy change.
> Fix access to default backend for 404 pages

- charts/astronomer/values.yaml
Fix a DateTime bug related to incorrect string conversion in Houston API.
> If there is only one commit in the PR, when clicking the merge button, be sure to copy the PR title into the PR squash and merge …
> Fix Houston API DateTime Bug

- charts/astronomer/templates/houston/houston-configmap.yaml
astronomer/ap-airflow@74fd8a6
1.10.10-5 Tag: https://github.com/astronomer/airflow/releases/tag/v1.10.10%2Bastro.5
> Add AC 1.10.10-5 to supported images

- bin/install-ci-tools
- bin/migration-scripts/README.md
- bin/migration-scripts/upgrade-to-lts.sh
[Helm 3.3.2](https://github.com/helm/helm/releases/tag/v3.3.2) was a security patch.
> Helm v3.3.2 is a security (patch) release. Users are strongly recommended to update to this release. It fixes a variety of minor security issues, as well as four notable security issues for which we have opened security advisories. More information on the security advisory can be found [on the security advisory page](https://github.com/helm/helm/security/advisories).
[Helm 2.16.11](https://github.com/helm/helm/releases/tag/v2.16.11) was also a security patch.
> Helm v2.16.11 is a security (patch) release. Users are strongly recommended to update to this release. It fixes four notable security issues for which we have opened security advisories. More information on the security advisory can be found [on …
> Bump helm to newest versions (security)

- charts/astronomer/templates/commander/commander-networkpolicy.yaml
- charts/astronomer/templates/registry/registry-networkpolicy.yaml
add ingress rules to commander and registry from houston job pods
no issue associated
we detected this issue during 0.20 release process. For other network policies, I usually add a function test. But these are jobs, so the pods aren't around all the time, so they aren't available for the functional test. I will add some helm chart unit tests.
> Add network policy rules

- .circleci/config.yml
- .circleci/config.yml.j2
CI changes only. Use ubuntu 20.04 as machine image.
These changes are all related to CI, so the customer impact is zero as long as tests are passing.
- <https://discuss.circleci.com/t/early-preview-new-ubuntu-20-04-linux-machine-executor-image/37140>
> Use ubuntu 20.04 machine image

- charts/stan/templates/statefulset.yaml
- charts/stan/tests/statefulset_test.yaml
The nats Stan component did not previously have liveness or readiness probes. These are being added here. 
Resolves https://github.com/astronomer/issues/issues/1672
If the probe was misconfigured it could either never pass the probe checks or would pass incorrectly, false positive. 
helm-unittest tests have been added to check for the existence of livenessProbe and readinessProbe
and that the path/port are correct
> livenessProbe and readinessProbe added to Stan server.

- bin/functional-tests/README.md
- bin/functional-tests/test_config.py
- bin/test-ap
- charts/prometheus/templates/_helpers.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/tests/prometheus-statefulset_test.yaml
- charts/prometheus/values.yaml
This PR adds a sidecar to prometheus to allow reloading the config of prometheus when the configmap for the configuration or alert rules is modified. 
Resolves https://github.com/astronomer/issues/issues/1832
There is risk of the configmap-reloader not triggering, or not communicating correctly with prometheus. A unit test has been added to test for the presence of the sidecar. A functional test has been added that modifies the configmap and looks for those changes to be reflected in the container.
> Adding configmap-reloader sidecar to prometheus

- charts/astronomer/templates/houston/houston-configmap.yaml
- https://github.com/astronomer/ap-airflow/pull/135
- https://hub.docker.com/r/astronomerinc/ap-airflow/tags?page=1&ordering=last_updated&name=1.10.7-15
> Add AC 1.10.7-15 to supported images

- bin/migration-scripts/prisma1_to_prisma2.sql
Add missing step to migrate `Deployment_alertEmails` to prevent during prisma1 -> to prisma2 rollout.
And prevent interactive message:
```
⚠️  There will be data loss:
• You are about to drop the `Deployment_alertEmails` table, which is not empty (1 rows).
```
practically tested using release-016/ and than main.
> add missing step to migrate alertEmails

- charts/astronomer/values.yaml
Bump airflowChartVersion from 0.17.0 to 0.17.1
Optimize FQDN DNS lookups.
This patch has been live in many environments running Airflow 0.15.
> airflowChartVersion from 0.17.0 to 0.17.1

- charts/nginx/templates/nginx-deployment.yaml
- charts/nginx/values.yaml
The nginx ingress controller has deprecated the --force-namespace-isolation flag, which apparently was not even doing anything.
- Removal of feature from ingress-nginx: https://github.com/kubernetes/ingress-nginx/pull/3887
- Where this feature shows up in our chart:
- https://github.com/astronomer/astronomer/blob/master/charts/nginx/templates/nginx-deployment.yaml#L55-L57
- https://github.com/astronomer/astronomer/blob/master/charts/nginx/values.yaml#L19
Remove deprecated nginx ingress flag `--force-namespace-isolation`
Resolves https://github.com/astronomer/issues/issues/1911
- Verified that this fix works in kind
- Reviewed upstream code to verify that the flag removal was in fact not doing anything
> Remove --force-namespace-isolation

- charts/astronomer/values.yaml
Fix the migration script for Houston API.  Prevent the `workspaceId` null error database constraint error from throwing errors during our migration.
Resolves astronomer/issues#1926
The migrations should successfully run when there are `InviteToken.workspaceId` null values in the database (you'll need to seed your DB with invites and then make the workspaceIds null manually).
> Fix Houston Knex Migration Error

- charts/astronomer/values.yaml
Fix the createToken Houston API Bug
Fix a bug with the `trialEndsAt` date being in an invalid format
Resolves astronomer/issues#1933
Resolves astronomer/issues#1935
1. Log in as an admin
2. Invite a user your-email+{SOME_INT}@astronomer.io
3. Check your email and accept the invite (make sure you use a different browser or are logged out of your admin account)
4. Use the basic auth option to login with the new invite
5. After signing in, log out
6. Log in again with the newly created account (at this point you should be able to get back in without any errors)
> Fix createToken Houston API Bug

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/generate_circleci_config.py
Automatically test only the latest k8s version on each run. Testing all runs is now a manual step that must be run before releasing to internal.
Update kind versions to latest available in https://hub.docker.com/r/kindest/node/tags
Added a final newline to the rendering. Ran `black` on generate_circleci_config.py via pre-commit hooks.
This should be cherry-picked to all branches.
CI changes only. No-op for all installations.
Related to astronomer/issues#1932
[Iterated on several configs](https://app.circleci.com/pipelines/github/astronomer/astronomer?branch=1932-reduce-ci-resource-usage) before arriving at the final config. "Test all platforms" is a manual step that can be approved immediately at the start of the run, essentially giving pre-approval to test all versions without needing to …
> Only auto test latest k8s version.

- charts/astronomer/values.yaml
Fix the Astro UI billing details bug.
Resolves astronomer/issues#1900
1. Log into Astro UI
2. Go to the billing page as a `WORKSPACE_ADMIN` **not** a `SYS_ADMIN` and try to view the billing details
3. You should be able to see the billing details and the update the billing information
https://github.com/astronomer/astro-ui/pull/855
> Fix Astro UI Billing Permissions Bug

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
Add airflow tier specific alert for CPU Throttling. This alert includes all the metadata required for houston to receive the alerts. 
Modified platform tier CPU Throttling alert that was incorrectly ignoring namespaces with a regex
Resolves https://github.com/astronomer/issues/issues/1844
prom tool to validate alerts syntax. Needs to be deployed on a real cluster to truly confirm.
> Improve CPUThrottlingHigh prometheus alerts

- bin/functional-tests/README.md
- bin/functional-tests/test_versioning.py
- bin/release-helm-chart
Move the check for an already published helm chart farther down the line so chart version mismatches don't block code testing.
Manually tested the release process on my laptop with an already published version.
> Move helm-chart-released-already check into release script.

- charts/alertmanager/templates/alertmanager-configmap.yaml
- charts/alertmanager/values.yaml
This PR adds the ability to augment alert manager routing rules with custom routes. Currently we only have predefined routes that we can enable or disable. This change opens up at the ability for us, or a customer to inject whatever extra routing rules they with to implement. 
does not resolve the following issue. But is in support of completing that issue
https://github.com/astronomer/issues/issues/1934
Tested with `amtool` with a goal to black hole a specific set of alerts
```
amtool config routes test --config.file test_routing.yaml tier=platform namespace=test-ns-2 --tree
Matching routes:
.
└── default-route
└── {namespace=~"^(?:^(test-ns.*))$",tier=~"^(?:platform)$"}  receiver: blackhole-receiver
blackhole-receiver
```
> Add support for adding additional custom routes to alertmanager

- charts/astronomer/templates/commander/commander-networkpolicy.yaml
- charts/astronomer/templates/registry/registry-networkpolicy.yaml
> hotfix: add correct network policy for registry to allow airflow update check

- templates/trust-private-ca-on-all-nodes/daemonset.yaml
- templates/trust-private-ca-on-all-nodes/psp-clusterrole.yaml
- templates/trust-private-ca-on-all-nodes/psp-rolebinding.yaml
- templates/trust-private-ca-on-all-nodes/psp.yaml
- templates/trust-private-ca-on-all-nodes/serviceaccount.yaml
- tests/private-ca-ds.yaml
- values.yaml
Private certificate authorities are used by enterprises to authenticate services and for TLS encryption in their networks. In addition, maintaining control of a root certificate authority trusted by all clients in an enterprise network allows enterprises to decrypt and inspect TLS traffic.
In most cases, enterprises will install this certificate into all their nodes. However, in other cases they may use default images for their kubernetes nodes. In this case, the Docker (or containerd) daemon must be configured to accept this certificate, such that image pulls from the Astronomer registry will work.
I have tested manually on AKS to make sure image pull works after "astro deploy" with a private cert. Complete manual steps are documented here: …
> Optionally copy a private certificate to all nodes

- values.yaml
This is the only value that works in this configuration, so let's make it default
> Add default configuration value for global.tlsSecret

- .circleci/config.yml
- .circleci/config.yml.j2
- Chart.yaml
- bin/functional-tests/test_config.py
The build in CI was being performed with Helm 2, and that broke the Helm 3 conditional subchart logic. Instead, all subcharts were unconditionally enabled.
I added a functional test to protect against regression
> Fix conditionally disabling subcharts

- charts/nginx/templates/nginx-configmap.yaml
This enables outputting nginx logs as json structured data rather than plain text to make parsing and querying easier for things such as GCP Stackdriver. For example we can query on status codes, or request ids or IPs etc. With the current textPayload that is unsctructured we do not have this capability with Stackdriver.
Example of capabilities we get in stack driver with json logging from nginx
> Enable json logging for nginx ingress

- bin/install-ci-tools
Switch out deprecated helm repo for new stable repo.
- <https://www.cncf.io/blog/2020/11/05/helm-chart-repository-deprecation-update/>
- <https://helm.sh/docs/faq/#i-am-getting-a-warning-about-unable-to-get-an-update-from-the-stable-chart-repository>
> Update to new helm stable repo

- charts/astronomer/templates/commander/commander-role.yaml
- This allows commander to create / delete persistent volumes for airflow deployments
- Necessary for PR https://github.com/astronomer/airflow-chart/pull/127
- Related to issue https://github.com/astronomer/issues/issues/1954
> Allow commander to create and delete volumes

- charts/fluentd/templates/fluentd-configmap.yaml
I found that Airflow, when logging not in json mode, logs timestamps in a different format than is specified in our config file. We would not notice this error because most users (including our clouds) use json logging format for Airflow logs.
I think this pattern is not in the version of airflow I am using, 1.10.7:
```
%Y-%m-%dT%H:%M:%S.%NZ
```
This pattern is working:
```
%Y-%m-%dT%H:%M:%S.%N+%z
```
Example log line, copied from fluentd pod filesystem
```
2020-11-11T19:22:45.526814634+00:00 stdout F 10.130.4.1 - - [11/Nov/2020:19:22:45 +0000] "GET /meteoroidal-kiloparsec-2912/airflow/health HTTP/1.1" 200 187 "-" "kube-probe/1.17+"
```
Not related to any particular issue, but discovered during openshift work
This change adds an additional pattern match for fluentd parsing of logs, …
> More compatibility for Astronomer logging

- charts/fluentd/templates/fluentd-configmap.yaml
I should not have included the plus sign in the recent change
```
2020-11-12T03:15:23.657380000++0530 Asia/Kolkata
2020-11-11T23:45:23.661661000++0200 Europe/Kiev
2020-11-11T21:45:23.666075000++0000 Europe/London
2020-11-11T16:45:23.670673000+-0500 US/Eastern
2020-11-11T15:45:23.675109000+-0600 US/Central
2020-11-11T13:45:23.678963000+-0800 US/Pacific
```
> Parse timestamps from non UTC times

- configs/dev.yaml
Update ap-astro-ui tag with one that exists. I found this broken reference while validating changes for release-0.16. The `dev` tag does not exist in docker hub or quay.
> Fix this reference that does not exist

- .circleci/config.yml
- .circleci/config.yml.j2
- Chart.yaml
- README.md
- UPDATING.md
- bin/migration-scripts/README.md
- bin/migration-scripts/upgrade.sh
- charts/alertmanager/values.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/keda/values.yaml
- charts/kibana/values.yaml
- charts/kube-state/values.yaml
- charts/kubed/values.yaml
- charts/nginx/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/prometheus/values.yaml
- configs/dev.yaml
- configs/master.yaml
Switch all docker image references to point to quay.io in release-0.16 branch.
These changes should only be merged to 0.16 and not cherry-picked back to master because they are irrelevant. master already has these changes, but the diff was so large I couldn't just cherry-pick.
Related to astronomer/issues#1355
Closes astronomer/issues#2181
I manually checked that all updated images exist via:
```sh
git diff --staged  |
grep -E 'repository.*quay|tag' |
awk '{print $NF}' |
sed 's/"//g' |
paste -s -d ':\n' - |
xargs -n1 docker manifest inspect > /dev/null
```
All images that did not exist were migrated via:
```sh
pull_tag_push() {
for image in "$@" ; do
new_image="${image}"
new_image="${new_image/astronomerinc/quay.io\/astronomer}";
new_image="${new_image/astronomerio/quay.io\/astronomer}"; …
```
> Switch all docker images to point to quay in release-0.16

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
We currently already have a 4 hour high alert, and a 5% remaining critical. The 24 hour warning to slack creates too much noise.
Resolves https://github.com/astronomer/issues/issues/2215
> Removed 24 hour storage space filling up warning.

- charts/astronomer/values.yaml
Bump airflow chart to 0.18.3 which contains a hotfix for istio sidecar misbehavior.
> Bump airflow chart version to 0.18.4

- .circleci/config.yml
Only LTS release branches are able to be approved for public release. This adds release-0.23 to that list.
> Add release-0.23 to publicly releasable branches

- charts/astronomer/values.yaml
Adding logs into Houston Workers NATS messages
Resolves astronomer/issues#2267
View the Houston Worker logs and notice the full messages for deployments being logged.
> Add logs for Houston Worker messages

- charts/astronomer/values.yaml
The Houston Worker queries have a bug where the query and application code does not filter out deletedAt deployments from the NATS Message.  Normally this isn't a problem, but there is a race condition that we found while doing automated and rapid testing where we quickly create and delete deployments.  The NATS message can get into a bad state in this case and continue to resend messages that are unacknowledged.
Resolves astronomer/issues#2267
Confirm that the volume of messages for NATS on dev decreases.
> Fix the Houston Worker Queries

- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
Push out airflow-chart 0.18.5, which solves an issue where alpine deploys would run under incorrect permissions.
- See astronomer/airflow-chart#165 referenced airflow-chart fix
> Bump astro version to 0.23.3, airflowChartVersion to 0.18.5

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
increasing the ephemeral storage alert to "5gb for 10 minutes"
this isn't a perfect threshold, but it's better than the legacy values we have currently. i'll be working to find a way to alert based on percentage rather than a hardcoded value.
> update prometheus ephemeral storage alert threshold

- bin/functional-tests/conftest.py
- bin/functional-tests/test_config.py
This PR is into @andriisoldatenko 's branch where he is working on this issue: https://github.com/astronomer/issues/issues/2251
These commits include a test that reproduces an error under the following conditions:
- helm upgrade such that no houston pods are restarted (by using --no-hooks). This will clear out the connection secret with the current issue with helm upgrade clearing the 'connection' key in the release_name-houston-backend secret.
- delete houston container so that it restarts, it will start crashlooping because the connection secret is missing.
This test fails with error 'container not found' because the pod is crashlooping due to the secret missing. So, this test is reproducing the issue.
This test shows that using the init container for initializing the secret is not …
> Test disappearing secret

- charts/astronomer/templates/houston/houston-configmap.yaml
This PR adds 1.10.12-2 support to 0.16 of the platform
https://github.com/astronomer/updates.astronomer.io/pull/29
Changelog:
https://github.com/astronomer/ap-airflow/blob/master/1.10.12/CHANGELOG.md#astronomer-certified-11012-2-2020-12-04
> Add AC 1.10.12-2 to list of supported images

- charts/astronomer/values.yaml
resolves:
- Airflow2.0rc2: Astro Deploy does not load the DAGS defined by the user. and related issues:
https://github.com/astronomer/issues/issues/2380 
https://github.com/astronomer/issues/issues/2375 
https://github.com/astronomer/issues/issues/2379
and
Hofix: Deployment XYZ.resources defensive checks https://github.com/astronomer/astro-ui/pull/948
> bump houston-api and astro-ui

- charts/astronomer/templates/houston/houston-configmap.yaml
- https://github.com/astronomer/updates.astronomer.io/pull/30
- https://github.com/astronomer/ap-airflow/pull/178
Resolves https://github.com/astronomer/issues/issues/2394
> Add AC 1.10.7-16 & 1.10.10-6 to list of supported images

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/install-ci-tools
Modernize some CI aspects that need to be updated, but are not in sync with master. **This change should not be cherry-picked or merged to any other branch.**
- Use latest ap-build
- Do not install packages during CI runs (packages already existed in base image, plus this is a bad behavior)
- Replace deprecated and delete helm stable repo with merely deprecated one
- `set -x`
> Modernize 16 ci

- charts/astronomer/values.yaml
Airflow chart 0.15.7 changes docker image source from docker hub to quay.io. Airflow chart 0.15 is what users of Astronomer 0.16 use, so this change should only be applied to the release-0.16 branch.
Related to astronomer/issues#1355
> Bump airflow chart to 0.15.7

- bin/migration-scripts/lts-to-lts/0.16-to-0.23/README.md
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
This checks for Airflow updates after LTS 0.16 to LTS 0.23 upgrade
Resolves astronomer/issues#2428
The LTS upgrade automation has a smoke test where it ensures that the upgrader and rollback works. That protects against errors in the automation. To make sure that the automation does the expected thing, I captured these logs in my development environment:
```
k logs -f airflow-update-check-first-run-n6hfj
Running update-ca-certificates
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
WARNING: ca-cert-registry.pem does not contain exactly one certificate or CRL: skipping
Waiting for host: astro-commander 50051
Received response from: astro-commander 50051
Waiting for host: astro-registry 5000
Received response from: astro-registry 5000
Waiting for host: …
```
> Update supported Airflow list after LTS upgrade

- .circleci/config.yml
- .circleci/config.yml.j2
This small change allows you to approve the internal release without waiting for tests to pass, but the release still depends on the tests passing.
> Change approval in CI

- charts/astronomer/templates/houston/houston-configmap.yaml
- values.yaml
- Add flag `.Values.global.azure.enabled` for toggling any values that may be unique to Azure.
- This is being implemented for webserver livenessProbe values required when using Azure and PostgreSQL Flexible Server.
- Set the following values in houston config when enabled:
```
deployments:
helm:
webserver:
livenessProbe:
failureThreshold: 25
periodSeconds: 10
```
- This flag can be used for any other unique values that may be required in the future.
- Related to https://github.com/astronomer/issues/issues/2417
Confirmed the values are passed through to the webserver deployment when enabled:
```
k get deployment -n astronomer-optical-cluster-6838 optical-cluster-6838-webserver -o yaml
...
livenessProbe:
failureThreshold: 25
httpGet:
path: /optical-cluster-6838/airflow/health
port: 8080 …
```
> Add flag to enable values unique to Azure 

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
further reducing unnecessary noise. the default ephemeral storage limit is 10gb. setting this alert threshold to 8.5gb.
> update prometheus-alerts-configmap.yaml ephemeral storage alert threshold

- bin/functional-tests/test_versioning.py
Comment out the downgrade/upgrade test that is failing on missing migration files. These files are not present, but are also not needed because nobody will be downgrading to a prior patch release of this unreleased version.
We will reinstate this test after enhancing it perform the database downgrade, which is required for it to be a valid test. see astronomer/issues#2486 for more details.
Most of the changes in this PR are caused by `black` reformatting the file. The only actual changes are:
- Remove unused `json` import
- Skip `test_downgrade_then_upgrade()` (Line 31)
> 2486 db downgrade ci

- .circleci/config.yml
- .circleci/config.yml.j2
- Bump CI image to recommendation from https://circleci.com/docs/2.0/executor-intro/
- Make lts-upgrade-0-23-test require release-to-internal, since it does.
> Bump CI image to recommendation from CircleCI

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
Even though the intention was to, we are currently not running the airflow-update-check job during the LTS-to-LTS upgrade. This fix will hopefully take care of that.
Resolves astronomer/issues#2487
> Run the airflow updates check job instead of platform update check one

- .circleci/config.yml
- .circleci/config.yml.j2
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
We need to check for new airflow versions before performing the Airflow chart upgrades.
No issue for the re ordering of checking Airflow upgrades, but also
Closes: https://github.com/astronomer/issues/issues/2534
The upgrader smoke testing will make sure the upgrader pod runs in success
> LTS to LTS upgrade: update airflow versions

- charts/prometheus/templates/prometheus-config-configmap.yaml
we are scraping the service endpoint for nginx, resulting in only scraping one pod at a time randomly.  we are not getting accurate alerts and our dashboard isn't reflecting the real world.
i have not tested this yet in dev, but i believe jim already tested this somewhere.  we can easily deploy this to dev before this gets merged if we want to...
> change scrape from service to endpoints

- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
Add connection limit flag db_bootstrapper image
Resolves astronomer/issues#2476
Test that the `PRISMA_CONNECTION_LIMIT` is set and Houston API & Workers are taking less idle connections.
We need to check this in dev, staging and finally prod and monitor this update.
> Add connection limit for db bootstrapper

- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/Dockerfile
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/rollback.yaml
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
Resolves astronomer/issues#2618
1. EKS cluster with helm release ice-ice in astronomer namespace upgrade and downgrade from 0.16 -> 0.23 -> 0.16 - PASS
2. EKS cluster with helm release ice in astronomer namespace upgrade and downgrade from 0.16 -> 0.23 -> 0.16 - PASS
> Update lts script to allow - names in helm releases to work

- charts/alertmanager/templates/alertmanager-statefulset.yaml
- charts/alertmanager/values.yaml
Adds an option to disable Alertmanagers clustering for internal networks
Adds option to disable Alertmanager clustering for private networks where the gossip protocol causes failures
Resolves astronomer/issues#2592
> Add disableClustering as an alertmanager option

- .circleci/config.yml
- .circleci/config.yml.j2
This allows lts-upgrad-test to run without having a release-to-internal, which is needed when we want to fix bugs in the upgrader without having to release a new version of the astronomer helm chart.
> Do not require release-to-internal for lts-upgrade-0-23-test

- values.yaml
Resolves #1009
This is a documentation PR for the values.yaml file with all content commented out
```
```
> Add a note about storageClass at the global level in values.yaml

- charts/fluentd/templates/_helpers.tpl
This Issue is regarding to the 2 new params added in fluentd chart having concatenation Issue.
Note: - Earlier created PR - Unable to merge due to branch conflict - Now created a flunentd_issue branch and this can be merged with master - So please check and approve this.
fluentd 2 params string concatenation fix.
New parameters added for the fluentd Configuration has concatenation issue - which is basically implemented in Astronomer platform 0.23.11
Fix is to remove the "-" underscore syntax at the end of the if loop and end loop.
Tested and working as expected in local env.
Please find the below screenshots and reference links for ref
https://astronomer.zendesk.com/agent/tickets/3700
> fluentd_concatenation issue_github_issue_1030

- charts/elasticsearch/templates/nginx/nginx-es-networkpolicy.yaml
correct the selectors on the network policy so webservers can talk to the elasticsearch-nginx pod
Resolves astronomer/issues#2598
> update nginx-es-networkpolicy.yaml to allow comms from webservers to elasticsearch-nginx pod

- charts/nginx/templates/nginx-service.yaml
- Use Network Load Balancer (NLB) as default AWS LB instead of Classic Load Balancer (default)
- AWS recommends migrating to the newer generation of load balancers
Resolves https://github.com/astronomer/issues/issues/1546
> Please add helm unit testing, if applicable. The docs are regretfully sparse for helm unit testing, [here](https://github.com/astronomer/helm-unittest/blob/main/DOCUMENT.md) is what we have to work with. In general, these kind of tests can be used for specific assertions like 'when these values are set, the resource ends up looking like XYZ' but not for generalized assertions like 'for all resources, make sure the namespace is not set to the release name'.
> …
> Use NLB as default AWS load balancer

- charts/nginx/templates/nginx-service.yaml
- charts/nginx/tests/nginx-service_test.yaml
- charts/nginx/values.yaml
- values.yaml
Related to <https://github.com/astronomer/issues/issues/2640>, which talks about GCP Global Access, and offers a solution of allowing arbitrary ingress annotations.
* Add default null string for loadBalancerIP
* Add default null dict for loadBalancerSourceRanges
* Fix yaml anchor syntax for platformTolerations
* Whitespace
* Add test for these changes and other existing behaviors of the NGINX Service
* Auto-formatting applied by vscode `prettier` that removed some whitespace, re-aligned some braces.
> Add ingressAnnotations. Improve other syntaxes.

- charts/fluentd/templates/_helpers.tpl
This Issue is regarding to the 2 new params added in fluentd chart having concatenation Issue.
fluentd 2 params string concatenation fix.
New parameters added for the fluentd Configuration has concatenation issue - which is basically implemented in Astronomer platform 0.23.11
Fix is to remove the "-" underscore syntax at the end of the if loop and end loop. 
Tested and working as expected in local env.
Please find the below screenshots and reference links for ref
https://astronomer.zendesk.com/agent/tickets/3700
> fluentd 2 params string concatenation fix

- charts/elasticsearch/values.yaml
The root of this change is to fix an error about missing urllib3 in the latest published version of curator. This was done by adding urllib3, and py3-requests. This change also bumps the base image to a newer version of alpine.
See:
- https://github.com/astronomer/issues/issues/2773
- https://github.com/astronomer/ap-vendor/pull/77
- https://github.com/astronomer/ap-vendor/pull/78
> Fix missing urllib3, requests

- Makefile
There is a bunch of old (circa 2018) cruft in the `Makefile` related to releasing a helm charts outside of CI. This code isn't used these days, and is potentially dangerous.
* Remove old helm build and release code from Makefile
* Rename `TEMP` to `TEMPDIR`
I'm not sure if the `lint-prom` step should be deleted too. We are not using it, and haven't ever used it since I started here ~8 months ago. I feel like if we are going to use it, we should redo it.
> Remove Makefile cruft

- .pre-commit-config.yaml
- bin/functional-tests/conftest.py
- bin/functional-tests/test_config.py
- bin/functional-tests/test_network_security.py
- bin/install-ci-tools
- bin/lts-0-23-upgrade-tests/conftest.py
- bin/lts-0-23-upgrade-tests/test_lts_upgrade.py
- bin/migration-scripts/README.md
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/README.md
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/manifests/rollback-0.16-to-0.23.yaml
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/manifests/upgrade-0.16-to-0.23.yaml
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/Dockerfile
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/rollback.yaml
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
- bin/migration-scripts/upgrade-to-lts.sh
- bin/validate-helm-unittest-templates.py
Almost everything in here was flagged by pre-commit. This should all be functionally identical. The reverted `CIRCLECI=true` commits are because I began this work on a different branch, then branched off that because I wanted to keep those changes separate from these housekeeping changes.
- apply `black` to our python scripts (pre-commit)
- fix some flake8 complaints related to unnecessary f-strings, unused imports (pre-commit)
- Tweak pre-commit
- Apply `flynt` to one file.
> Blacken python

- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/rollback.yaml
Match both `postgres://` and `postgresql://` db connection strings in the LTS upgrader. Use named capture groups.
Related to https://github.com/astronomer/issues/issues/2537
- Manually validated this logic here: <https://github.com/danielhoherd/ansible-playground/tree/master/regex-groups>
- Validated the regex at <https://regex101.com/r/kZ2w3t/1> using:
- `postgres://user:pw@host.com:234`
- `postgresql://user:pw@host.com:234`
- `postgres://user:pw@host.com:5678/something`
- `postgresql://user:pw@host.com:5678/something`
- `postgres://user@host.com:234`
- `postgresql://user@host.com:234`
- `postgres://host.com:5678/something`
- `postgresql://host.com/something`
> Match both postres and postgresql protocol strings.

- .circleci/config.yml
- .circleci/config.yml.j2
These are CI changes only.
Break release-upgrader into its own workflow. See astronomer/issues#2789 for further reasoning.
EG: <https://app.circleci.com/pipelines/github/astronomer/astronomer/2266/workflows/ff4a5c91-c621-467e-a9cb-5cb23cbc649c>
EG:
- <https://app.circleci.com/pipelines/github/astronomer/astronomer/2268/workflows/11732fac-a012-4f47-8bd0-02aef4990bfb>
- <https://app.circleci.com/pipelines/github/astronomer/astronomer/2268/workflows/7d2f63ff-f61d-49c3-a137-f2b0245d9d78>
> Break LTS upgrader into its own workflow. 'prettier' cleanup.

- bin/lts-0-23-upgrade-tests/requirements.txt
- bin/lts-0-23-upgrade-tests/test_lts_upgrade.py
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/Dockerfile
- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
Only use internal-helm repo when testing the LTS upgrader, use the public helm repo at any other time. This is done in order to prevent customers from picking up pre-release versions of the chart.
This is done through a new variable `USE_INTERNAL_HELM_REPO` which tells ansible (the component that performs the LTS upgrade) to use the internal helm repo instead of the public helm repo. This var is passed from [the test script into k8s](https://github.com/astronomer/astronomer/blob/e6ef341f/bin/lts-0-23-upgrade-tests/test_lts_upgrade.py#L60-L80) [into Docker into Ansible](https://github.com/astronomer/astronomer/blob/e6ef341f/bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/Dockerfile#L27).
Related to astronomer/issues#2596
Normal testing env shows:
```
/lts-upgrade # …
```
> LTS Upgrader: use private helm repo only when testing

- charts/elasticsearch/templates/exporter/es-exporter-deployment.yaml
Maybe we meant `readinessProbe` ?
> Duplicate key `livenessProbe` in `elasticsearch-exporter`

- charts/astronomer/templates/houston/cronjobs/houston-check-airflow-version-updates-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-check-updates-cronjob.yaml
- charts/astronomer/templates/houston/cronjobs/houston-cleanup-deployments-cronjob.yaml
Interfering with `kustomize` parsing of our helm chart - non-ascii quote characters snuck in
> Fix Non-Ascii Quotes 😡

- .circleci/config.yml
- .circleci/config.yml.j2
Tune up some LTS CI configs. I thought this would be bigger when I opened the original ticket.
Now that all releases will be public, we can reduce this logic back to a simple regex instead of matching against specific version numbers that were approved for public release.
Related to https://github.com/astronomer/issues/issues/2828
> Add LTS 25, remove pre 16 versions from CI rules.

- charts/astronomer/templates/houston/houston-configmap.yaml
Updated houston-configmap local airflow settings to allow kubernetes pod operator pods to be labeled properly
Resolves astronomer/issues#2822
Tested with this change on my local cluster to verify that pods launched by the Kubernetes Pod Operator pods are tagged
> Update Houston config map to properly label pods launched by the Kubernetes Pod Operator

- Chart.yaml
- charts/astronomer/Chart.yaml
Bump astronomer to 0.23.14
Changes:
- Allow release of all `release-0.NN` branches as public (#1064)
- LTS Upgrader: use private helm repo only when testing (#1056)
- Update Houston config map to properly label pods launched by the Kubernetes Pod Operator (#1059)
- bump docker registry to support IRSA (#1065)
- fix quotes (comments only) (#1062)
- Fix liveness probe bug: Duplicate key `livenessProbe` (#1061)
> Bump astronomer to 0.23.14

- .circleci/config.yml
- .circleci/config.yml.j2
- charts/astronomer/tests/deployment_test.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nginx/values.yaml
- charts/prometheus-postgres-exporter/values.yaml
- charts/stan/values.yaml
This bumps a bunch of docker images for the 0.25.0 release. There are a LOT of changes in here and I have done no testing of any of these images.
Releated to https://github.com/astronomer/issues/issues/2749
> Bump docker images for 0.25.0

- charts/astronomer/values.yaml
Bump houston-api:
- https://github.com/astronomer/houston-api/commit/5978253784d68e85a117dbd440ae0450031b6eb6
- https://github.com/astronomer/houston-api/pull/677
- https://github.com/astronomer/houston-api/pull/675
> bump houston-api to 0.25.1

- charts/astronomer/values.yaml
Summary:
- Prevent creation of airflow prior 2.0.0 and type = volume and “nfsLocation”: “test:/test”, using GraphQL.https://github.com/astronomer/issues/issues/2909
- based on https://app.circleci.com/pipelines/github/astronomer/houston-api/3108/workflows/7aeb8e3d-2c39-4ed0-b721-27d874205433/jobs/10789
> bump houston-api to 0.25.2

- charts/astronomer/values.yaml
Changing deployment from NFS to Image type should remove reference to the mount #2931 https://github.com/astronomer/issues/issues/2931
> bump houston-api to 0.25.3

- charts/astronomer/values.yaml
- return empty extras during switching back to image type https://github.com/astronomer/houston-api/pull/680
> bump houston api to 0.25.4

- charts/grafana/templates/grafana-deployment.yaml
- charts/grafana/tests/grafana-deployment_test.yaml
- values.yaml
resolves https://github.com/astronomer/issues/issues/2870
> Fix: title: Default sslmode 'prefer' unsupported by Grafana

- charts/elasticsearch/values.yaml
Resolves the crypto library problem in astronomer/issues#2952 verified by @pgvishnuram in dev
I have also verified on my laptop that the crypto error does not occur anymore.
```
$ docker run quay.io/astronomer/ap-curator:5.8.4 --help
Traceback (most recent call last):
File "/usr/bin/curator", line 6, in <module>
import urllib3.contrib.pyopenssl
File "/usr/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
import OpenSSL.SSL
File "/usr/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import crypto, SSL
File "/usr/lib/python3.8/site-packages/OpenSSL/crypto.py", line 14, in <module>
from cryptography import utils, x509
ModuleNotFoundError: No module named 'cryptography'
```
```
$ docker run quay.io/astronomer/ap-curator:5.8.4-1 …
```
> Bump ap-curator astronomer/issues#2952

- .circleci/config.yml
- .circleci/config.yml.j2
Release-to-public step failed because of a missing security credential. This is fallout from astronomer/issues#2841
> Add circleci context 'github-repo' to release step

- bin/migration-scripts/lts-to-lts/0.16-to-0.23/README.md
Two manifest URLs in the LTS 16-to23 flow point to master, which is wrong. These need to point to the branch of the release that they are upgrading to, which is release 23.
Until this is merged, customers will be unable to upgrade from 16 to 23 using our instructions because the old URLs are 404.
- <https://raw.githubusercontent.com/astronomer/astronomer/master/bin/migration-scripts/lts-to-lts/0.16-to-0.23/manifests/upgrade-0.16-to-0.23.yaml>
- <https://raw.githubusercontent.com/astronomer/astronomer/master/bin/migration-scripts/lts-to-lts/0.16-to-0.23/manifests/rollback-0.16-to-0.23.yaml>
- <https://raw.githubusercontent.com/astronomer/astronomer/release-0.23/bin/migration-scripts/lts-to-lts/0.16-to-0.23/manifests/upgrade-0.16-to-0.23.yaml>
- …
> Point LTS 23 upgrade manifest URLs to the release-0.23 branch

- migrations/scripts/lts-to-lts/0.23-to-0.25/playbooks/tasks/upgrade.yaml
- Quit using `helm_devel` mechanic in favor of appending `-0` to version
- Upgrade to airflow chart 0.19
This change fixes an issue where `helm upgrade --version --devel` ignored the `--devel` option, meaning we were not testing pre-release charts. This is a desired behavior of helm. We instead append a `-0` to the end of the chart version, which tells helm to also include pre-release versions. This syntax does work as expected.
Taken from <https://app.circleci.com/pipelines/github/astronomer/astronomer/2479/workflows/94b467f3-f679-4236-a710-094c3aaee4f4/jobs/17936/parallel-runs/0/steps/0-104>
```
Helm history: (pre-upgrade)
REVISION	UPDATED                 	STATUS  	CHART             	APP VERSION	DESCRIPTION     
1       	Mon May 17 03:15:42 2021	deployed	astronomer-0.23.14	0.23.14 …
```
> Quit using helm_devel mechanic in favor of appending -0 to version.

- charts/fluentd/templates/fluentd-configmap.yaml
Relates to astronomer/issues#2975
Steps to apply the fix:
1. Added `suppress_type_name true` to fluentd configmap. 
2. Restart fluentd pods.
> Setting suppress_type_name true in fluentd configmap

- charts/astronomer/templates/commander/commander-role.yaml
- charts/astronomer/templates/commander/commander-rolebinding.yaml
- charts/astronomer/templates/commander/commander-serviceaccount.yaml
- charts/astronomer/templates/houston/api/houston-bootstrap-rolebinding.yaml
- charts/astronomer/templates/houston/api/houston-bootstrap-serviceaccount.yaml
- charts/astronomer/tests/commander_commander-role_test.yaml
- charts/astronomer/tests/commander_commander-rolebinding_test.yaml
- charts/astronomer/tests/commander_commander-service_test.yaml
- charts/astronomer/tests/houston_api_houston-bootstrap-role_test.yaml
- charts/astronomer/tests/houston_api_houston-bootstrap-serviceaccount_test.yaml
- values.yaml
resolves https://github.com/astronomer/issues/issues/2960
based in slack conversation with @rbankston:
Add:
```
metadata:
annotations:
argocd.argoproj.io/sync-wave: "-1"
```
to  ServiceAccounts, ClusterRoles, RoleBindings, ClusterRoleBindings
@rbankston do i need to add annotations also to elasticsearch, kubed etc?
> Support Argo Sync-waves for Helm chart for a better Argo installation experience#2960

- charts/fluentd/templates/fluentd-configmap.yaml
Docker breaks logs that are bigger than 16kb and fluentd currently doesn't merge those logs back together. Customers expect long logs to continue being found as a single entry in elastic. This adds the configuration so that long logs get merged back together.
Resolves astronomer/issues#3029
1. create a DAG that prints out really long messages over (16kb)
2. execute DAG 
3. look for log in kabana and make sure that the whole log shows up instead of a part of the log
Example since screen shot wouldnt really show much:  [here](https://kibana.dev.astrodev.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-28T14:30:00.000Z',to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'2697b5d0-2437-11eb-9842-2d41c29d …
> Concat Long logs that are split up by Dockers 16kb limit with fluentd plugin

- charts/alertmanager/templates/alertmanager-statefulset.yaml
- charts/alertmanager/values.yaml
- tests/alertmanager-statefulset_test.yaml
Some enterprises use private networks outside of RFC 1918, for example Class E networks. These are necessary for enterprises that have exhausted or otherwise allocated all RFC 1918 address space. When this is done Alertmanager  crash loops because it is not able to use these address spaces. 
https://github.com/prometheus/alertmanager/issues/2438
This PR adds the ability to `enableNonRFC` address range usage by adding the related `env` and `args` to the helm chart. 
🎟 Issue(s)
Resolves astronomer/issues#3028
- This has been tested in a sandbox on GKE as a helm chart, by both enabling and disabling the flag.
- Also has been tested with a customer deployment by editing the STS with the same values directly.
- Risks are that the values are not created properly thus non-RFC address spaces are …
> Enable non-RFC address space for Alertmanager

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/templates/registry/registry-statefulset.yaml
- charts/astronomer/values.yaml
- values.yaml
resolves 3rd part of https://github.com/astronomer/issues/issues/3007
>Our chart uses Helm's random number generator in certain areas. This random number generator changes each time Argo evaluates those sections and marks the application as not in sync. It would be useful if there was an option to specify the variable instead of only having the Random Data generate those values. This is used in 6 places in our current repository but the houston-backend-secret and registry-statefulset appear to be the only places that a production grade Astronomer deployment would use.
> add ability to use options for random data

- charts/fluentd/templates/_helpers.tpl
- charts/fluentd/templates/fluentd-daemonset.yaml
- charts/fluentd/tests/fluentd-daemonset_test.yaml
- charts/fluentd/tests/fluentd-psp-rolebinding_test.yaml
- tests/fluentd-clusterrolebinding_test.yaml
- tests/fluentd-daemonset_test.yaml
- tests/fluentd-psp-clusterrole_test.yaml
- tests/fluentd-psp-rolebinding_test.yaml
- tests/fluentd-psp_test.yaml
Added the private ca cert file to the fluentd pod for external usage
Resolves astronomer/issues#3063
Verified that the private root ca volumes and volumemounts existed properly following the change. Added fluentd daemonset testing to this pull request as well which pass.
```
volumeMounts:
- name: private-root-ca
mountPath: /usr/local/share/ca-certificates/private-root-ca.pem
subPath: cert.pem
- name: varlog
mountPath: /var/log
- name: varlibdockercontainers
mountPath: /var/lib/docker/containers
readOnly: true
- name: libsystemddir
mountPath: /host/lib
readOnly: true
- name: config-volume-astronomer-fluentd
mountPath: /etc/fluent/config.d
resources:
{}
ports:
- name: monitor-agent
containerPort: 24231
terminationGracePeriodSeconds: 30
volumes:
- name: private-root-ca
secret:
secretName: …
```
> Add Cacert file to fluentd if enabled

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
AirflowDeploymentUnhealthy on the description is missing the value for deployments but the release label  is available so changing it for that
Related astronomer/issues#3037
Can only test in QA (need to test)
screen shot above you can see broken link and missing string inbetween 
this should be fixed with this pr and https://github.com/astronomer/houston-api/pull/711#issuecomment-857839998
> Update Prometheus Alerts Config to fix missing field on emails

- charts/astronomer/values.yaml
Bumps the version of the astro ui to `0.25.1`
Among the most important fixes:
* Workspace admins will be able to have god-mode in their workspace they are admins of. Previously due to an implementation error, admins could not see deployments created by service accounts.
* Deployment counts regardless of user now show correctly in the workspace nav
* Side bar now correctly shows the deployments any given user has access to
* Historical deployment logs are finally working.
* Improvements to live logs
> bumping ap-astro-ui version

- charts/astronomer/values.yaml
- fix links to the deployment in the email is not working (Missing Workspace details)
- workspace_admin's now have access to all deployments under that workspace and can create,read,update,delete
- open shift support
- fix so only workspace admins and system admins should have privileges to invite users to a workspace.
- mixmatch email wording rework
- log search better-querying support
- add by pass email invite option for sso users
- fix CVE-2021-23369, CVE-2021-23337, CVE-2021-23358
> houston release 0.25.6

- charts/alertmanager/templates/alertmanager-auth-sidecar-configmap.yaml
- charts/alertmanager/templates/alertmanager-networkpolicy.yaml
- charts/alertmanager/templates/alertmanager-service.yaml
- charts/alertmanager/templates/alertmanager-statefulset.yaml
- charts/alertmanager/templates/ingress.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/grafana/templates/grafana-auth-sidecar-configmap.yaml
- charts/grafana/templates/grafana-deployment.yaml
- charts/grafana/templates/grafana-networkpolicy.yaml
- charts/grafana/templates/grafana-service.yaml
- charts/grafana/templates/ingress.yaml
- charts/kibana/templates/ingress.yaml
- charts/kibana/templates/kibana-auth-sidecar-configmap.yaml
- charts/kibana/templates/kibana-deployment.yaml
- charts/kibana/templates/kibana-networkpolicy.yaml
- charts/kibana/templates/kibana-service.yaml
- charts/prometheus/templates/ingress.yaml
- charts/prometheus/templates/prometheus-auth-sidecar-configmap.yaml
- charts/prometheus/templates/prometheus-networkpolicy.yaml
- charts/prometheus/templates/prometheus-service.yaml
- charts/prometheus/templates/prometheus-statefulset.yaml
- values.yaml
This PR created for enhancement of sidecar configs
**Auth Sidecar Enhancements**
🎟 Issue(s)
health check was missing for all sidecar services
houston configmap didnt had updated sidecar values 
sidecar port configuration found hardcoded
resource naming are  inappropriate
> Auth Sidecar Enhancements

- charts/astronomer/values.yaml
Bumps the version of the astro ui to 0.25.2
Among the most important fixes:
- fix deployment access list as a deployment viewer gets stuck in loading.
> bumping ap-astro-ui version 

- bin/release-helm-chart
As a follow up to #1133, we should allow internal helm to have a shorter HTTP cache TTL, since we will be using it for more feature branch testing, not just release testing.
> Different max-age for internal helm

- charts/prometheus/templates/ingress.yaml
- tests/test_prometheus_ingress.py
When using a newer k8s version the prometheus ingress port name isn't correct causing a 503 error because of the port name.
Part of astronomer/issues#3126
Verified that my clusters prometheus page now works without manually changing the port name 
Broken:
```
spec:
rules:
- host: prometheus.airflow.ralphbankston.com
http:
paths:
- backend:
service:
name: uat-prometheus
port:
name: prometheus
path: /
pathType: Prefix
```
Fixed:
```
spec:
rules:
- host: prometheus.airflow.ralphbankston.com
http:
paths:
- backend:
service:
name: uat-prometheus
port:
name: prometheus-data
path: /
pathType: Prefix
```
> Added the port-name of prometheus-data instead of prometheus in Prometheus Ingress

- charts/fluentd/templates/fluentd-configmap.yaml
This reverts commit 1743b9b9aaf61f65508d8d15e2a881f7b6cd763e.
Revert concat filter that was introduced to solve an edge case with long log lines. This change caused problems in all versions of kubernetes, which differed depending on whether the cluster was >=1.20 or <1.20. Removal of this change does leave the original problem, but that problem is an edge case which should be dealt with by writing large data directly to files and not stdout. Due to the multi-stream nature of our dag workers, it is technologically infeasible for us to fix the long-line problem in our application stack. Instead, that problem should be better handled by the CRI.
There is a long discussion about this with lots of debugging info and learning in a private thread: https://github.com/astronomer/issues/issues/3113
> Revert "add concat long logs (#1114)"

- charts/prometheus/templates/prometheus-alerts-configmap.yaml
- tests/test_prometheus_alerts_configmap.py
- https://github.com/astronomer/issues/issues/2531
- https://github.com/astronomer/issues/issues/2532
- https://github.com/astronomer/issues/issues/2874
- Add an absolute value threshold to the NginxIngressHigh[45]XXRage alerts.
- Correct some wording and make both rule wordings match.
- Add tests for alerts configmap and its embedded yaml document
The below script was inspiration for the tests I added. The tests could've been done with `promtool` too, but testing this way was easier in context.
```
$ cat /Users/danielh/temp/2021-06-28/parse.py
#!/usr/bin/env python3
import yaml
with open('/dev/stdin') as f:
outer = yaml.safe_load(f)
inner = outer["data"]["alerts"]
parsed = yaml.load(inner, Loader=yaml.SafeLoader)
print(yaml.dump(parsed))
$ helm template . --show-only …
```
> Add absolute value threshold to NginxIngressHigh[45]XXRate

- charts/nginx/values.yaml
Upgrade nginx to latest version to fix CVE issues
> bump nginx to .47 to fix CVE issues

- charts/astronomer/values.yaml
upgrade houston to 0.25.7
includes: 
- fix for workspace service accounts not being able to CRUD
- fix CVE issues
> upgrade houston-api 0.25.7

- .circleci/config.yml
- .circleci/config.yml.j2
- .pre-commit-config.yaml
- bin/install-platform
- bin/lts-23-to-25-test
- bin/prep-k8s
- bin/reset-local-dev
- bin/run-ci
- bin/setup-kind
- bin/test-ap
- bin/waitfor-platform
There are a bunch of places in this repo where we assign `GIT_ROOT` from the output of `git rev-parse --show-toplevel`, but this command is issued from the PWD of the shell that is issuing the command, which may not always be within the same repo as where the command resides, particularly if we are debugging and running these scripts manually. This change set specifies the repo to always be that of the script where `git rev-parse` is run from by issuing `-C <path>    Run as if git was started in <path> instead of the current working directory` from the directory of the script itself, determined by stripping `/*` from script name via `"${0%/*}"`.
Also bump some CI things.
> Execute git-rev-parse from the script dir, not PWD. Bump some CI things.

- bin/install-platform
- bin/lts-23-to-25-test
- bin/prep-k8s
- bin/reset-local-dev
- bin/run-ci
- bin/setup-kind
- bin/test-ap
- bin/waitfor-platform
The [recently added syntax](https://github.com/astronomer/astronomer/pull/1149) to always execute `git rev-parse` from the astronomer repo was invalid. [This was in fact caught by CI](https://app.circleci.com/pipelines/github/astronomer/astronomer/2795/workflows/2d28cd30-07fe-4d10-b246-f8c21d08f7e3/jobs/19710), but somehow I missed this and merged it. This change set fixes that syntax to work as expected. Shout out to @aliotta for catching this!
FWIW during testing I tested this on prehistoric bash `3.2.57(1)-release (x86_64-apple-darwin20)` which is still the default on MacOS 11, and modern bash `5.1.8(1)-release (x86_64-apple-darwin20.3.0)`
> Correct git -C syntax

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nats/values.yaml
- charts/stan/values.yaml
Bump vendored images:
- `quay.io/astronomer/ap-cli-install:0.25.1`
- `quay.io/astronomer/ap-registry:3.13.7-1`
- `quay.io/astronomer/ap-nats-server:2.3.2`
- `quay.io/astronomer/ap-nats-streaming:0.22.0`
- `quay.io/astronomer/ap-nats-exporter:0.6.2-1`
- `quay.io/astronomer/ap-elasticsearch:7.10.2-3`
> bump: ap-cli-install to 0.25.0 and other ap-vendor images to fix container running as root user problem

- charts/nginx/templates/nginx-service.yaml
- charts/nginx/values.yaml
- tests/test_nginx_service.py
Allows the NGINX ServiceType to be configurable within our chart. Default is left at LoadBalancer so only folks that need it would go looking for it.
Also adds ability to add an external ip to the NGINX service.
Resolves astronomer/issues#3136
Resolves astronomer/issues#3204
Created tests for the nginx service for LoadBalancer, NodePort, and ClusterIP. Most people wouldn't notice this change unless it is needed for a customized on-prem configuration
Also added tests for adding an externalip
LoadBalancer:
sessionAffinity: None
type: LoadBalancer
ClusterIP:
sessionAffinity: None
type: ClusterIP
NodePort:
sessionAffinity: None
type: NodePort
> Add ServiceType of NGINX to be configurable and externalIPs

- charts/astronomer/templates/registry/registry-statefulset.yaml
https://github.com/astronomer/issues/issues/3252
some trouble shooting why it's working in qa cluster (google env) and don't work in AWS:
```
{{- if and .Values.registry.gcs.enabled .Values.registry.gcs.useKeyfile }}
{{- include "registry.gcsVolumeMount" . | indent 12 }}
{{- end }}
11:25
helm get values astronomer | rg registry -C5
cpu: 1000m
memory: 1Gi
requests:
cpu: 500m
memory: 512Mi
registry:
gcs:
bucket: qa-astronomer-qa-registry
enabled: true
podLabels:
spotinst.io/node-lifecycle: od
replicas: 2
elasticsearch:
```
```
/ $ ps
PID   USER     TIME  COMMAND
1 registry 16:40 registry serve /etc/docker/registry/config.yml
33 registry  0:00 sh
39 registry  0:00 ps
11:27
/ $ cat /etc/docker/registry/config.yml
version: 0.1
log:
fields:
service: registry
storage:
cache:
blobdescriptor: …
```
> registry: add securityContext to registry container

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- bin/setup-kind
- tests/__init__.py
This PR adds testing for kubernetes 1.21. All tests are passing, likely because of some work that was done for 1.19 and 1.20.
Related to <https://github.com/astronomer/issues/issues/3126>
> Support k8s 1.21

- charts/fluentd/values.yaml
Bump ap-fluentd to 1.13.3-1 to solve a few CVEs. This change also includes the new plugin [fluent-plugin-cloudwatch-logs](https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs)
Solves https://github.com/astronomer/issues/issues/3325
> Bump fluentd to 1.13.3-1

- charts/fluentd/values.yaml
Use ap-fluentd:1.13.3 which solves some CVEs but does not include some newer packages that are breaking the image.
Related to https://github.com/astronomer/issues/issues/3326
> Use ap-fluentd:1.13.3

- charts/elasticsearch/values.yaml
Updating ap-elasticsearch-exporter
Resolves astronomer/issues#2937
> Update packages that have 'don't run as root' fixes

- charts/astronomer/templates/houston/worker/houston-worker-deployment.yaml
Just did debug with client  (and with @pgagnon )and they are using custom ca certificates, so houston-worker can have this error:
```
/houston $ node --experimental-repl-await
Welcome to Node.js v14.17.1.
Type ".help" for more information.
> const config = require('config');
undefined
> const { allowRootAccess, enabled, connection } = config.get(
... "deployments.database"
... );
undefined
> const { ssl } = config.get("database");
undefined
> const knex = require('knex');
undefined
> const conn = knex({ client: "postgres", connection: connection });
undefined
> await conn.raw('CREATE DATABASE test9');
Uncaught Error: unable to get issuer certificate
at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
at TLSSocket.emit (events.js:375:28)
at TLSSocket.emit (domain.js:532:15)
at …
```
> fix: missing custom ca volume mount for houston-worker

- CODEOWNERS
- templates/trust-private-ca-on-all-nodes/daemonset.yaml
- tests/helm_template_generator.py
- tests/test_privateca.py
- values.yaml
First crack at allowing customization of cert-copy image. I'm not sure everything here is in the right place, so feedback is welcome.
This change also alters the way that pytest reports failures, attempting to be more helpful. Here is an example exception:
```
ERROR: subprocess.CalledProcessError:
helm command: helm template --kube-version 1.20.0 RELEASE-NAME /Users/danielh/a/astronomer --set global.baseDomain=example.com --values /var/folders/9p/kbxv3fnn447706mqhnf7bncm0000z8/T/tmpmovq26rc --show-only templates/trust-private-ca-on-all-nodes/daemonset.yaml
Values file contents:
---------------------
global:
privateCaCerts:
- private-ca-cert-foo
- private-ca-cert-bar
privateCaCertsAddToHost:
enabled: false
---------------------
error.output=b''
error.stderr=b'Error: could not find template …
```
> Allow customization of cert-copy image

- charts/prometheus-blackbox-exporter/values.yaml
Bump ap-blackbox-exporter to 0.19.0-2, which drops root user and updates alpine base image.
Related to <https://github.com/astronomer/issues/issues/3338>
> Bump ap-blackbox-exporter to 0.19.0-2

- charts/fluentd/values.yaml
update ap-fluentd to allow export to Cloudwatch logs and elasticSearch
> update ap-fluentd to allow export to Cloudwatch logs and elasticSearch

- .pre-commit-config.yaml
- bin/create-initial-user
- bin/generate_ssl_keys
- bin/reset-local-dev
- bin/run-ci
- bin/setup-hosts
- configs/local-dev-ha.yaml
- configs/local-dev.yaml
The DNS zone *.astronomer-development.com was deleted recently during a scheduled spin-down of an old developer account. This updates references to it with a globally resolvable domain name that points itself and all subdomains to 127.0.0.1, which fixes the local dev workflow.
This change also replaces the shellcheck pre-commit hook with one that installs shellcheck into the env.
- `gsed -i 's/local.astronomer-development.com/localtest.me/' ...files...`
- `gsed -E -i 's#https://github.com/detailyang/pre-commit-shell#https://github.com/shellcheck-py/shellcheck-py#'` and stuff
- `pre-commit auto-update`
- `rm -f bin/setup-hosts` and delete the reference from `bin/run-ci`
I manually ran the `bin/reset-local-dev` flow a few times and tested in a few browsers to make sure it works.
> Fix local dev

- charts/fluentd/values.yaml
Update to pull image version `1.13.3-4` which includes new-relic plugin gem introduced in https://github.com/astronomer/ap-vendor/pull/137
https://github.com/astronomer/issues/issues/3359
1. pulled new image to EKS cluster with chart version `0.25.4`
2. verified pods ran 
3. edited configmap to include new-relic specific details
4. redeployed pods, verified logs streaming to both es/kibana and new-relic
> Fluentd:updates image to 1.13.3-4

- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/rollback.yaml
Adding Deletion of Scheduler deployment box in current Rollback script from 0.23.14 to 0.16.15.
Ref: Zendesk [5619](https://astronomer.zendesk.com/agent/tickets/5619)
> Rollback 0.23 to 0.16 fix

- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/tests/deployment_test.yaml
- charts/astronomer/values.yaml
Bump astronomer to 0.23.15-rc1 with upgraded components for that release. LTS upgrade tests will likely fail, but we will fix those in parallel to rc1 testing.
> Bump to 0.23.15-rc1

- bin/functional-tests/requirements.txt
- bin/functional-tests/test_config.py
A flaky prometheus test was fixed in release-0.25, but was not backported to release-0.23. We are now experiencing that flaky test, so this backports the workaround by using the version of test_config.py that is currently found in master. Also bump some library versions and add the required pytest rerunfailures module.
> Fix flaky test by merging master version of test_config.py

- charts/elasticsearch/templates/curator/es-curator-cronjob.yaml
Isitio proxy connect fails to send quit signal after curator job completion 
fix for isitio proxy connect error 
https://github.com/astronomer/issues/issues/2775
> fix for curator quitquitquit error

- tests/test_astronomer_commander.py
Only check that the image name matches, not the version tag. This gives us at least a test that we're using the right image, while not requiring us to update this test every time we bump the version tag for the image.
> Only check image name, not tag version

- bin/migration-scripts/lts-to-lts/0.16-to-0.23/playbooks/tasks/upgrade.yaml
Enhances the 0.23 upgrade script
Resolves astronomer/issues#2637
Have used removing the upgrade deployments section twice with @shmanu017 on a cluster that had previously failed. Also tested the flags so that the behavior described works as intended.
> Enhance 0.16 -> 0.23 Script

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
- charts/stan/values.yaml
```
$ helm template . --set global.baseDomain=foo.com -f /Users/danielh/a/google-environments/prod/cloud/app/config.yaml 2>/dev/null |
> awk '/image: / {match($2, /(([^"]*):[^"]*)/, a) ; printf "https://%s %s\n", a[2], a[1] ;}' |
> sort -u |
> column -t
2021-09-27T18:16:50-0700
https://quay.io/astronomer/ap-alertmanager            quay.io/astronomer/ap-alertmanager:0.23.0
https://quay.io/astronomer/ap-astro-ui                quay.io/astronomer/ap-astro-ui:0.25.4
https://quay.io/astronomer/ap-base                    quay.io/astronomer/ap-base:3.14.2
https://quay.io/astronomer/ap-cli-install             quay.io/astronomer/ap-cli-install:0.25.2
https://quay.io/astronomer/ap-commander               quay.io/astronomer/ap-commander:0.25.3
https://quay.io/astronomer/ap-configmap-reloader …
```
> Bump docker images to the latest builds

- charts/astronomer/values.yaml
This new version bumps pgbouncer from version 1.8.1 to 1.16.0
> bump airflow chart version to 1.0.0-rc1-build11945

- Makefile
- charts/prometheus/values.yaml
* Bump ap-configmap-reloader to 0.5.0-1
* Add make target: show-docker-images
```
$ make show-docker-images
helm template . --set global.baseDomain=foo.com 2>/dev/null | awk '/image: / {match($2, /(([^"]*):[^"]*)/, a) ; printf "https://%s %s\n", a[2], a[1] ;}' | sort -u | column -t
https://quay.io/astronomer/ap-alertmanager            quay.io/astronomer/ap-alertmanager:0.23.0
https://quay.io/astronomer/ap-astro-ui                quay.io/astronomer/ap-astro-ui:0.25.4
https://quay.io/astronomer/ap-base                    quay.io/astronomer/ap-base:3.14.2
https://quay.io/astronomer/ap-cli-install             quay.io/astronomer/ap-cli-install:0.25.2
https://quay.io/astronomer/ap-commander               quay.io/astronomer/ap-commander:0.25.3
https://quay.io/astronomer/ap-configmap-reloader …
```
> Bump ap-configmap-reloader to 0.5.0-1

- charts/postgresql/values.yaml
Current postgres image sourced from bitnami is now vendored from ap-vendor .
default max_connections is set to 200
runs as non-root by default
updated vendored postgresql image
https://github.com/astronomer/issues/issues/792
https://github.com/astronomer/issues/issues/3614
> updated vendored postgresql image

- charts/fluentd/templates/fluentd-daemonset.yaml
setting  K8S_NODE_NAME can reduce the number of API calls against kubernetes API server 
https://github.com/astronomer/issues/issues/3724
> define K8S_NODE_NAME in fluentd daemonset

- charts/astronomer/templates/houston/houston-configmap.yaml
- values.schema.json
Currently the OSS chart only allows you to specify an sslmode on the resultBackendConnection and metadataConnection if you define the whole object. We need this param to allow our users to overide just this field and use what we specify for the other values.
> add new field for settign sslmode

- charts/astronomer/values.yaml
- charts/grafana/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/stan/values.yaml
* db bootstrapper image version 0.26.0 -> 0.26.1
* ap-default-backend image version 0.25.3 -> 0.25.4
* ap-nats-exporter image version 0.8.0-1 -> 0.9.0
Resolves https://github.com/astronomer/issues/issues/3765
> bump platform images

- charts/astronomer/templates/commander/commander-role.yaml
A forthcoming version of commander will patch namespace objects to update the list of labels and annotations - this adds the PATCH verb to the commander-role.
https://github.com/astronomer/issues/issues/3674
https://github.com/astronomer/commander/pull/72
> Allow commander-role to PATCH namespaces

- charts/nginx/values.yaml
Solve https://github.com/astronomer/issues/issues/3402 in release-0.25 branch by bumping to known fixed ap-default-backend image.
> bump ap-default-backend

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/fluentd/values.yaml
- charts/prometheus-node-exporter/values.yaml
- charts/stan/values.yaml
Bump versions of:
- quay.io/astronomer/ap-commander
- quay.io/astronomer/ap-registry
- quay.io/astronomer/ap-cli-install
- quay.io/astronomer/ap-base
- quay.io/astronomer/ap-fluentd
- quay.io/prometheus/node-exporter
Also FWIW I opened an issue to vendor node-exporter, so for now don't worry about that being third party.
> Bump a bunch of ap docker image versions

- Makefile
- charts/elasticsearch/values.yaml
- charts/fluentd/values.yaml
- charts/kibana/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
This bumps all images that include elastic.co components to versions that are post 2020 license change.
Also add line breaks in `make show-docker-images` to be easier to modify.
> Bump elastic.co related versions

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- tests/__init__.py
k8s 1.17 is not supported by any public clouds as of January 2022. This change set drops testing for 1.17. There are no other 1.17 specific changes that are needed.
<https://github.com/astronomer/issues/issues/3863>
> Drop k8s 1.17

- charts/fluentd/values.yaml
Use an ap-fluentd docker image that has the pre-license-change ES components so fluentd can connect into all ES clusters.
> Use image with old fluentd es components

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/test_external_elasticsearch.py
Disable kibana dashboard when  customLogging is enabled
https://github.com/astronomer/issues/issues/3680
> Disable kibana dashboard when  customLogging is enabled

- charts/astronomer/values.yaml
- fixes issue in astro-ui that stil shows kibana on drop down even when user has customLogging turned on
Related astronomer/issues#3680
> Bump ap-houston to 0.27.7 and ui to 0.27.5 to fix Astro-ui bug that still shows kabana on dropdown when customLogging enabled

- .github/pull_request_template.md
Because people rarely fill out any details in the PR template, often just leaving the boilerplate in place which just adds noise to the PR, I thought we could try vastly simplifying it. The changes here include text that indicates the PR should not be merged, leading people who want their code to be merged to actually replace that text. I'm not sure if this is too passive aggressive or if it will work. What do you all think?
> Vastly simplify the gh issue template [ci skip]

- charts/astronomer/values.yaml
Fix issue in houston where when running upgrade script it will set labels to empty causing deployment to not work and update commander version in Houston
astronomer/issues#3878 
andrii did testing locally in his kind cluster with these changes
> bump ap-houston 0.27.8

- charts/elasticsearch/templates/client/es-client-deployment.yaml
- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- tests/test_cves.py
Remediate CVE-2021-44228 by setting `ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true` by default for all containers.
- https://github.com/astronomer/issues/issues/3880
- https://github.com/astronomer/issues/issues/3881
This includes unit tests. Manual testing has been done to show that the configs do work in run time. Better tests would have an integration test that probes the running process to check if the remediation is in place.
> Remediate CVE-2021-44228 at runtime through env configs

- bin/functional-tests/conftest.py
- bin/functional-tests/test_config.py
As a follow up to #1310 which included unit tests, this PR includes functional tests that probe the running ES processes to verify they are configured with the right flags.
These changes should be merged into 0.23, 0.25, 0.26, 0.27, and possibly 0.16.
- https://github.com/astronomer/issues/issues/3880
- https://github.com/astronomer/issues/issues/3881
- https://github.com/astronomer/astronomer/pull/1310
- create functional test for cve-2021-44228 that probe the running processes in the container for correct config
- create pytest fixtures for es_client, es_data, es_master
- rework the kube_client ptest fixture to be simpler
- create get_pod_by_label_selector helper function
- DRY up some code
I ran it locally
I ran it in CI
I ran it with code duplicated
And I ran it DRY 🎤
> Add functional tests for cve-2021-44228

- .gitignore
- charts/grafana/templates/grafana-deployment.yaml
- charts/grafana/values.yaml
- tests/test_grafana.py
- values.yaml
Add extra environment variables to the `grafana-deployment` resource in order to set configuration settings in Grafana.
- [#1308](https://github.com/astronomer/astronomer/issues/1308)
Verified that extra environment variables are rendered when provided as a list to the `grafana` section of helm values, and no side effect occurs when not provided.
> 1308-templating-grafana-extra-env-vars

- charts/astronomer/values.yaml
bump airflow chart to 1.1.1 to add 1.3.1 of the oss chart
https://github.com/astronomer/airflow-chart/pull/277
https://github.com/astronomer/issues/issues/3923
@ernest-kr how was this tested?
Tested in a air gap environment where external access is completely cut down.
> bump airflow chart to 1.1.1 to add 1.3.1 of the oss chart

- charts/astronomer/values.yaml
bump airflow chart in commander to 1.1.1 to add 1.3.1 of the oss chart
astronomer/airflow-chart#277
astronomer/issues#3923
Tested in a air gap environment where external access is completely cut down.
> bump commander to 0.27.2 to include airflow chart 1.1.1 that includes 1.3.1 of the oss chart

- charts/astronomer/values.yaml
bump airflow chart in commander to 1.1.1 to add 1.3.1 of the oss chart
actually contains files
astronomer/airflow-chart#277
astronomer/issues#3923
Tested in a air gap environment where external access is completely cut down.
> bump commander to 0.27.3 to include airflow chart 1.1.1 that includes 1.3.1 of the oss chart #1321

- charts/nats/templates/_helpers.tpl
- charts/nats/templates/statefulset.yaml
- charts/nats/values.yaml
- charts/prometheus-node-exporter/templates/_helpers.tpl
- charts/prometheus-node-exporter/templates/daemonset.yaml
- charts/prometheus-node-exporter/values.yaml
- charts/prometheus/templates/_helpers.yaml
- charts/stan/templates/_helpers.tpl
- charts/stan/templates/statefulset.yaml
- charts/stan/values.yaml
- tests/test_private_registry.py
NATS, STAN, and Prometheus have wrong image names when `privateRegistry` is enabled. Normally, customers using private registry will mirror our public names. Having different names for only few of the images causes confusion and should be fixed. Should also be merged to 0.26, 0.25 and 0.23 releases.
https://github.com/astronomer/issues/issues/3893
Manual testing has been done to show that the configs do work in run time. It uses the same image names as the public images, should not need additional testing.
> Fix nats, stan, and prometheus image names for private registry

- charts/prometheus/values.yaml
Includes CVE fixes and enhancements for prometheus service
Issue Link: https://github.com/astronomer/issues/issues/3946
No testing done, but this should be tested as part of QA before the next release.
> bump prometheus image to 2.32.1

- bin/functional-tests/test_config.py
- charts/elasticsearch/values.yaml
- charts/kibana/values.yaml
- charts/kubed/values.yaml
- charts/prometheus-node-exporter/templates/_helpers.tpl
- charts/prometheus-node-exporter/values.yaml
* elasticsearch version update to 7.16.2
* kibana version update to 7.16.2
* kubed version update to 0.13.0
* node exporter move to astronomer quay
Also
* Improve cve_2021_44228 test cases by string matching in python instead of grep
https://github.com/astronomer/issues/issues/3945
https://github.com/astronomer/issues/issues/3942
https://github.com/astronomer/issues/issues/3833
NA
> bump various image

- charts/astronomer/templates/houston/ingress.yaml
Due to payload size exceeds the default value end up in 502 error, this change fixes that issue by increasing 16k
https://github.com/astronomer/issues/issues/3974
NA
> setting proxy buffer size to 16k to avoid payload issues

- charts/prometheus-postgres-exporter/values.yaml
Enhancement for postgres exporter 
for descriptive changelog ref https://github.com/prometheus-community/postgres_exporter/releases/tag/v0.10.1 
NA
NA
> bump postgres exporter to 0.10.1

- charts/astronomer/values.yaml
Bump up the commander image to latest 0.27.4 release
Changes present in the new release: https://github.com/astronomer/commander/pull/77
Have tested locally and on circle-ci that the commander while building was able to pick up the latest airflow chart version
> Bump commander to 0.27.4

- charts/postgresql/values.yaml
- tests/test_postgres.py
we no longer need to run init container with root privileges for in cluster postgres , we have already migrated our postgres image to run as non root. we can disable this in astronomer/astronomer postgres chart helm values
https://github.com/astronomer/issues/issues/4087
NA
> disable postgres init container

- charts/astronomer/templates/add-labels-to-namespace.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/postgresql/templates/networkpolicy.yaml
- tests/test_network_ns_labels.py
- values.yaml
This PR allows to set platform label to be used along with network policies , additionally locks down communication which is not  part of astronomer platform 
Related astronomer/issues#3278 
Yet to be added
> enable namespace labels to platform

- charts/astronomer/values.yaml
we want to include most recent airflow OSS chart so, we need to bump astronomer airflow-chart to 1.2.0
release notes https://github.com/apache/airflow/releases/tag/helm-chart%2F1.4.0 
https://github.com/apache/airflow/pull/20266/files
> bump airflow-chart to 1.2.0

- .circleci/config.yml
- .circleci/generate_circleci_config.py
- README.md
- bin/reset-local-dev
- tests/__init__.py
- tests/helm_template_generator.py
Stop testing and suggesting k8s 1.18. k8s 1.18 will be deprecated by all cloud providers within 2 months. We will not be writing any new features for it and will not support it going forward.
We can hold off to merge this until we're ready to deprecate it, or just merge early since we're not going to support 1.18 long anyway and all our feature development is targeting 1.21 and soon 1.22.
https://github.com/astronomer/issues/issues/3890
Nothing beyond CI. We're removing features and defaulting to 1.21, so there's not much to test. 1.21 already works, so using it as a default is not a huge change.
> Deprecate 1.18. Use 1.21 as default in chart tests and comments.

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
fixes critical security introduced by libexpat 
https://github.com/astronomer/issues/issues/4089
can be verified by running trivy image -s CRITICAL,HIGH <image-name>
> images contains fix for libexpat

- charts/nginx/values.yaml
Bump to [ap-default-backend 0.28.0](https://github.com/astronomer/default-backend/releases/tag/v0.28.0) to solve several issues. This version also [moves from Redhat ubi8 to nginx](https://github.com/astronomer/default-backend/commit/e9ca08d09b01512ae7b2a690c2cd91266b40629f).
https://github.com/astronomer/issues/issues/3953
N/A
> Bump ap-default-backend to 0.28.0

- charts/astronomer/values.yaml
- charts/elasticsearch/templates/client/es-client-deployment.yaml
- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- charts/elasticsearch/values.yaml
- charts/kibana/values.yaml
- charts/nginx/values.yaml
- charts/stan/values.yaml
- tests/test_cves.py
* kibana 7.10.2-2 -> 7.16.3
* elasticsearch 7.10.2-2 -> 7.16.3
* curator 5.8.4-7 -> 5.8.4-8
* db-bootstrapper 0.26.1 -> 0.26.2 
* nginx ingress 0.49.0-1 -> 0.50.0
* stan ap-base 3.15.0 -> 3.15.0-1
https://github.com/astronomer/issues/issues/4123
> Add missing security fixes release 0 25

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
bump vendor images to fix critical cve
https://github.com/astronomer/issues/issues/4089
trivy image -s CRITICAL,HIGH quay.io/astronomer/ap-curator:5.8.4-9
trivy image -s CRITICAL,HIGH quay.io/astronomer/ap-db-bootstrapper:0.26.3
> bump vendor images

- charts/nats/values.yaml
- charts/stan/values.yaml
Bump image versions in nats and stan. This is partly to solve CVEs, and partly to stay up on the latest updates.
These changes should be merged into all supported branches.
https://github.com/astronomer/issues/issues/4202
Normal testing should cover these changes AFAIK.
> Bump image versions in nats and stan

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
bump vendor images to fix critical cve
https://github.com/astronomer/issues/issues/4089
trivy image -s CRITICAL,HIGH quay.io/astronomer/ap-curator:5.8.4-9
trivy image -s CRITICAL,HIGH quay.io/astronomer/ap-db-bootstrapper:0.26.3
> bump vendor images (#1360)

- requirements/chart-tests.txt
- requirements/functional-tests.txt
Bump requirements, which include bump to [pytest 7](https://docs.pytest.org/en/stable/changelog.html#pytest-7-0-0-2022-02-03).
No issue, just regular dev-flow maintenance.
If tests pass then that's testing enough.
> Update requirements, including pytest 7

- charts/nginx/values.yaml
update default backend for nginx
NA
NA
> update default backend nginx to 0.28.0

- charts/fluentd/templates/fluentd-serviceaccount.yaml
- charts/nats/templates/statefulset.yaml
- charts/nats/values.yaml
- charts/stan/templates/statefulset.yaml
- charts/stan/values.yaml
- tests/helm_template_generator.py
- tests/test_nats_sts.py
- tests/test_stan_sts.py
- values.yaml
Allow the ability to configure nodeSelector, affinity, and tolerations for Nats and Stan in order to restrict the Kubernetes nodes the Pods are scheduled on.
https://github.com/astronomer/issues/issues/4137
- Added `test_nats_sts.py` to validate generation of the statefulset yaml and nodeSelector, affinity, and tolerations are configured correctly
- Added test in `test_stan_sts.py` to validate nodeSelector, affinity, and tolerations are configured correctly
> Allow nodeSelector, affinity, and tolerations configuration for Stan and Nats

- charts/grafana/values.yaml
* update grafana image 7.5.10 -> 7.5.12
* grafana db-bootstrapper 0.25.1 -> 0.26.3
Issue Link : https://github.com/astronomer/issues/issues/4123
trivy image -s CRITICAL,HIGH quay.io/astronomer/ap-grafana:7.5.12
trivy image -s CRITICAL,HIGH quay.io/astronomer/ap-db-bootstrapper:0.26.3
> bump grafana chart security fixes

- charts/astronomer/values.yaml
* ap-commander 0.25.3 -> 0.25.4
* ap-registry 3.14.2-2 -> 3.15.0
Qa team should able to deploy platform without any issues , and able to deploy airflow.
> bump platform image for various security fixes

- charts/nats/templates/statefulset.yaml
- charts/nginx/templates/nginx-deployment.yaml
- charts/stan/templates/statefulset.yaml
- tests/test_default_chart.py
- tests/test_stan_sts.py
release-0.27 did not have tests for stan, and we ran into some problems with some release-0.28 in airgapped environments. This adds tests to make sure release-0.27 image customization works. The boilerplate tests were taken from release-0.28, but `test_stan_statefulset_with_custom_images` is not in release-0.28 and should be ported and updated for those changes.
Part of the problem here included imagePullPolicy being absent from a pod manager manifest. To check for this everywhere I wrote a test that checks all pod managers for imagePullPolicy. This test found 3 other places where it was missing, along with at least one other place where it would be missing if a feature that appears to be broken (but apparently quite unused) was enabled. I have fixed those three instances so those changes …
> Add tests for stan

- Makefile
- charts/nats/templates/statefulset.yaml
- charts/nginx/templates/nginx-deployment.yaml
- charts/postgresql/templates/_helpers.tpl
- charts/prometheus-blackbox-exporter/templates/_helpers.tpl
- charts/prometheus-blackbox-exporter/templates/deployment.yaml
- charts/stan/templates/statefulset.yaml
- tests/__init__.py
- tests/test_authsidecar.py
- tests/test_default_chart.py
- tests/test_kube_state_deployment.py
- tests/test_kubed_clusterrolebinding.py
- tests/test_nats_sts.py
- tests/test_postgres.py
- tests/test_prometheus_node_exporter.py
- tests/test_prometheus_statefulset.py
- tests/test_stan_sts.py
Lots of our images were not using the privateRegistry when it was enabled. Most of these do not appear to be supported production things, but some of them are.
The only images I have found that do not support privateRegistry are:
- quay.io/astronomer/ap-keda:1.3.0
- quay.io/astronomer/ap-keda-metrics-adapter:1.3.0
- quay.io/astronomer/ap-postgres-exporter:0.10.1
- Add make target: `show-docker-images-with-private-registry`.
- Fix or add missing imagePullPolicy on several images.
- Templatize some postgres stuff to be modern and support privateRegstry.
- Add test function `get_containers_by_name` and use it wherever `c_by_name` was done long-form.
- Slight refactor in test_authsidecar: remove print, move definition closer to use.
- Add `test_all_charts_with_private_registry` that tests …
> Fix lots of privateRegistry images

- charts/astronomer/values.yaml
> bump houston-api yarn migrate hotfix

- charts/astronomer/values.yaml
Update astronomer's helm chart to use latest commander docker image.
We found a few security vulnerabilities in the previous base docker image (which we extend in commander). In order to fix these vulnerabilities, I updated the base image to a newer version.
- https://github.com/astronomer/issues/issues/4215
- https://github.com/astronomer/commander/pull/80 the PR containing the fix.
> bump platform image for docker image security fixes

- charts/astronomer/values.yaml
update airflow chart version to 0.20.2
release link: https://github.com/astronomer/airflow-chart/releases/tag/v0.20.2
Issue Link: https://github.com/astronomer/issues/issues/4123
QA team should be able to deploy airflow without any issues
> update airflow chart version to 0.20.2

- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- tests/test_cves.py
* ap-elasticsearch 7.16.2 -> 7.16.3
* ap-kibana 7.16.2 -> 7.16.3
* ap-db-bootstrapper  0.26.1 ->  0.26.3
* ap-base 3.15.0 -> 3.15.0-2
**remove unneeded env vars for elasticsearch**
* formatMsgNoLookups - added as default since 7.16.1 , so not needed to be explicitly defined in newer versions
* skipping log4j tests thats covered by functional tests
Issue Link: https://github.com/astronomer/issues/issues/4267
> update vendor images to latest

- charts/astronomer/values.yaml
- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/nginx/values.yaml
- charts/prometheus/values.yaml
- tests/test_cves.py
**security fixes to platform images release-0.27**
* ap-db-bootstrapper 0.26.1 -> 0.26.3
* ap-elasticsearch 7.16.2 -> 7.16.3
* ap-kibana 7.16.2 -> 7.16.3
* ap-nginx 0.49.3 -> 0.50.0
* ap-default-backend 0.25.4 -> 0.28.0
* ap-prometheus 2.30.3 -> 2.32.1
**remove unneeded env vars for elasticsearch**
* formatMsgNoLookups - added as default since 7.16.1 , so not needed to be explicitly defined in newer versions
* skipping log4j tests thats covered by functional tests
https://github.com/astronomer/issues/issues/4179
QA team should be able to deploy airflow without any issues
> backport ap-vendor security fixes to release-0.27

- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/stan/values.yaml
* ap-commander 0.26.6 -> 0.26.7
* ap-db-bootstrapper 0.26.3 -> 0.26.4
* ap-base 3.15.0-2 -> 3.15.0-3
* ap-curator 5.8.4-9 -> 5.8.4-10
Issue Link: https://github.com/astronomer/issues/issues/4318
> updated images includes libexpat fixes

- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
Rebrand the logo in astro ui and allow ability to change app name in config 
astronomer/issues#4265
Tested in dev and have pr ready for prod changes in google env https://github.com/astronomer/google-environments/pull/674
> 0.27 branding refactor bump astro-ui 0.27.16 to and houston 0.27.18 and bump platform version 0.27.4-rc3

- .circleci/config.yml
- .circleci/config.yml.j2
- charts/prometheus/templates/prometheus-config-configmap.yaml
- charts/prometheus/values.yaml
- tests/test_prometheus_config_configmap.py
Add the ability to specify helm values to be passed into the prometheus config file's remote_write and global.external_labels sections.
- Add .Values.external_labels and .Values.remote_write sections to prometheus config file template
- Add tests for Values.external_labels, and .Values.remote_write
- Add commented out sections in charts/prometheus/values.yaml which indicate these available options, and links to prometheus documentation on how to use them
- Refactor adjacent config test test_prometheus_config_configmap_with_different_name_and_ns to not use regex, and instead do string comparisons against loaded prometheus config. This was mainly done for consistency.
- https://github.com/astronomer/issues/issues/4186
I have written unit tests that capture my understanding of the original …
> Add Prometheus config file global.external_labels, remote_write

- charts/fluentd/templates/fluentd-configmap.yaml
Force fluentd to flush buffers at shutdown. This [defaults to false on file backed buffers](https://docs.fluentd.org/configuration/buffer-section#flushing-parameters) which is likely the wrong configuration for our environment.
https://github.com/astronomer/astronomer/issues/1349
This one would be a bit difficult to test to confirm that the function is working, though that is a bit beyond the scope of what we should be testing. Making sure fluentd continues to function should be enough, so as long as logs are coming in we should be good.
> Add fluentd config buffer flush_at_shutdown true

- tests/test_prometheus_alerts_configmap.py
- tests/test_prometheus_config_configmap.py
Lowercase some test data that is breaking on helm 3.8. This is part 2 of <https://github.com/astronomer/astronomer/pull/1362>
https://github.com/astronomer/issues/issues/4124
Chart unit tests are passing with helm 3.8 on my machine now when previously they were not.
> lowercase some test data for helm 3.8 compatibility.

- charts/nginx/templates/nginx-role.yaml
- charts/nginx/values.yaml
*  We are in progress in supporting k8s >= 1.22, this PR upgrades the current ingress controller to latest version      (0.50.0 -> 1.1.2) includes enhancements and security fixes. 
* current role is not sufficient to run ingress controller , we have updated necessary privileges to run the service.
https://github.com/astronomer/issues/issues/3889
QA should able to deploy and run astronomer platform without any issues due to ingress controller.
> update ingress controller

- charts/elasticsearch/templates/client/es-client-deployment.yaml
- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- charts/elasticsearch/values.yaml
- tests/test_elasticsearch.py
* this change enables customer to enable|disable sysctl config option (defaults to true)
* applicable for master,data and client services
Issue Link: https://github.com/astronomer/issues/issues/4226
QA team can set elasticsearch.sysctlInitContainer.enabled=false to see if sysctl containers are not applied anymore.
> make sysctl config configurable for elasticsearch

- configs/local-dev.yaml
Issue: https://app.zenhub.com/workspaces/team-platform-apps-61d5f7ef8de56e0014840a75/issues/astronomer/issues/4395
Description: these were added by accident and should not be set. having them set won't cause any issues atm its just not our desired default state.
> removeAccidentallyAddedFeatureFlagDefaults

- charts/astronomer/values.yaml
Recently incorrect airflow chart versions are shipped inside commander image due to an issue observed in ci pipeline, which affected airgapped installs.  
This PR fixes those issues and ships with correct airflow chart version
GH Issue: https://github.com/astronomer/issues/issues/4396
QA can run below command to verify the chart version 
docker run -it --rm --entrypoint=/bin/sh quay.io/astronomer/ap-commander:release-0.27.6 -c 'ls -l astronomer-ee'
output
```
docker run -it --rm --entrypoint=/bin/sh quay.io/astronomer/ap-commander:release-0.27 -c 'ls -l astronomer-ee'
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
total 136
-rw-r--r-- 1 commander commander 135766 Mar 21 11:34 …
```
> Fix airflow chart version in commander

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
update  ap-base  3.15.0-3 ->  3.15.1
update ap-curator 5.8.4-10 -> 5.8.4-11
update ap-nginx-es 1.21.4 -> 1.21.6
update ap-cli-install 0.26.1 -> 0.26.2
update ap-registry  3.15.0 -> 3.15.1
update nats-exporter 0.9.1 -> 0.9.1-1
update  ap-blackbox-exporter 0.19.0-5 -> 0.19.0-6
update ap-awsesproxy  1.3-1 -> 1.3-3 
update ap-default-backend 0.28.0 -> 0.28.1
Not Yet Created 
Yet to update
> update platform  images for security fixes

- tests/README.md
- tests/helm_template_generator.py
- tests/test_alertmanager.py
- tests/test_astro_ui_deployment.py
- tests/test_astronomer_commander.py
- tests/test_authsidecar.py
- tests/test_external_elasticsearch.py
- tests/test_fluentd.py
- tests/test_houston_configmap.py
- tests/test_houston_ingress.py
- tests/test_ingress.py
- tests/test_kubed_clusterrolebinding.py
- tests/test_nginx_service.py
- tests/test_privateca.py
- tests/test_prometheus_alerts_configmap.py
- tests/test_prometheus_config_configmap.py
- tests/test_prometheus_ingress.py
- tests/test_prometheus_statefulset.py
- tests/test_psp.py
- tests/test_registry_statefulset.py
- tests/test_stan_sts.py
Fix helm 3.8 compatibility in release-0.27 tests.
<https://github.com/astronomer/issues/issues/4124>
CI tests passing is enough since only test files were modified.
Also I tested on helm 3.8 locally and tests passed.
> Fix helm 3.8 compatibility in release 0.27 tests

- CODEOWNERS
- tests/README.md
- tests/helm_template_generator.py
- tests/test_alertmanager.py
- tests/test_astro_ui_deployment.py
- tests/test_astronomer_commander.py
- tests/test_fluentd.py
- tests/test_houston_configmap.py
- tests/test_houston_ingress.py
- tests/test_ingress.py
- tests/test_kubed_clusterrolebinding.py
- tests/test_nginx_service.py
- tests/test_privateca.py
- tests/test_prometheus_alerts_configmap.py
- tests/test_prometheus_config_configmap.py
- tests/test_prometheus_ingress.py
- tests/test_prometheus_statefulset.py
- tests/test_psp.py
- tests/test_registry_statefulset.py
Fix helm 3.8 compatibility in release-0.26 tests.
<https://github.com/astronomer/issues/issues/4124>
CI tests passing is enough since only test files were modified.
Also I tested on helm 3.8 locally and tests passed.
> Fix helm 3.8 compatibility in release 0.26 tests

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/fluentd/values.yaml
- charts/kubed/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
* update ap-base 3.15.0-3 -> 3.15.1
* update ap-curator 5.8.4-10 -> 5.8.4-11
* update ap-nginx-es 1.21.4 -> 1.21.6
* update ap-cli-install 0.26.1 -> 0.26.2
* update ap-registry 3.15.0 -> 3.15.1
* update nats-exporter 0.9.1 -> 0.9.1-1
* update ap-blackbox-exporter 0.19.0-5 -> 0.19.0-6
* update ap-awsesproxy 1.3-1 -> 1.3-3
* update ap-default-backend 0.28.0 -> 0.28.1
* update ap-openresty 1.19.9 1.19.9-1
* update ap-fluentd 1.14.3-1 1.14.5
* update ap-kubed 0.13.0 -> 0.13.2
QA should be able to install platform without any issues
> update vendor images for security fixes and enhancements

- charts/fluentd/templates/fluentd-configmap.yaml
- tests/test_astronomer_namespace_pools.py
- tests/test_fluentd.py
When using the Namespace Pools feature, we want to optimize fluentd to only retrieve Airflow logs from the namespaces provided in the pool, since Airflow deployments will ONLY be deployed in these namespaces.
I have also added tests to look for this configuration under the different scenarios.
https://github.com/astronomer/issues/issues/4322
To test this PR, we want to render the helm chart and check that the fluentd configuration is set properly according to our global values.
We want to make sure that fluentd is still working as expected, we are going to create a helm release with namespace pool enabled, and provide a list of namespaces to use and to create, and then we will need to make sure that fluentd does collect the logs from our Airflow deployments created in these namespaces:
- …
> Namespace Pools: Optimize fluentd's configuration

- charts/fluentd/values.yaml
- charts/prometheus/values.yaml
fluentd kubernetes meta plugin had a vulnerable kube_client plugin that has been updated in the new version of fluentd image 
minor enhancements to prometheus image 
Image update details below:
update ap-fluentd 1.14.5 -> 1.14.5-1
update ap-prometheus  2.32.1 -> 2.34.0
QA should able to deploy / upgrade platform without any issues
> enhanced security fixes

- charts/nginx/values.yaml
* bump default-backend 0.28.1 -> 0.28.2
https://github.com/astronomer/issues/issues/4428
Qa should able to deploy and see proper error pages
> update ap-default backend

- charts/astronomer/templates/commander/commander-role.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/test_astronomer_commander.py
- tests/test_astronomer_namespace_pools.py
- tests/test_scc.py
This PR contains:
- Reduce permissions for Commander
- Fix a bug, when using the new global.features.namespacePools value, the rendered configmap for Houston to use these preCreatedNamespaces was not formatted properly: I rendered a list of string, instead of a list of object with the form {"name": "namespace-name"}.
At the moment, users do not like the permissions we give to Commander:
- `*` values in permissions can be risky
- Permissions to manage ClusterRoles and ClusterRoleBindings is too dangerous, if someones steals commander's Service Account, he can just create an admin ClusterRole + binding and gain access to the whole cluster.
The only scenario in which we want to give Commander the permissions to manage Cluster* RBAC resources is if the user uses the Airflow multinamespace …
> Reduce Commander Permissions and fix namespace pools Houston config

- charts/astronomer/values.yaml
Bump airflowChartVersion to 1.4.0.
airflow-chart 1.4.0 added k8s 1.22 and 1.23 support. It also does not work with k8s 1.18 or lower.
<https://github.com/astronomer/issues/issues/4377>
Manual testing has been done. There are no automated tests that can verify this change because it requires doing an `astro deploy` and we still don't have the ability to do such a thing in an automated way.
> Bump airflowChartVersion

- charts/astronomer/values.yaml
fix cve issues in astro ui
HIGH severity CVE CVE-2022-23308
https://github.com/astronomer/issues/issues/4426
ci is passing
> bump astro ui from 0.28.7 to 0.28.8

- charts/astronomer/values.yaml
fix astro ui zlib CVE
related: https://github.com/astronomer/astro-ui/pull/1400
passes CI
> bump astro ui to 0.28.9 from 0.28.8 fix zlib CVE

- charts/elasticsearch/values.yaml
- charts/kibana/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
Shipping all vendor images with least cve's to ensure customers are getting latest updates in patch releases
* update ap-base 3.15.0-3 -> 3.15.3
* update ap-prometheus 2.32.1 -> 2.34.0
* update ap-nats-server 2.7.2 -> 2.7.2-1
* update ap-kibana 7.16.3 -> 7.17.1
* update ap-elasticsearch 7.16.3 -> 7.17.1
* update ap-default-backend 0.28.2 -> 0.28.3
QA team should able deploy platform without any issues and upgrading from existing version should not cause any issue.
> update vendor images

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/nats/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
* update ap-registry 3.15.1 -> 3.15.3
* update ap-curator 5.8.4-11 -> 5.8.4-12
* update ap-nginx-es 1.12.6 -> 1.21.6-1
* update ap-nats-server 2.7.2-1 -> 2.7.2-2
* update ap-nats-exporter 0.9.1-1 -> 0.9.1-2
* update ap-blackbox-exporter 0.19.0-6 -> 0.19.0-7
* update ap-nats-streaming  0.24.1 ->  0.24.1-1
NA
> vendor images includes fix for zlib

- charts/astronomer/values.yaml
release 0.28.4 components for astro ui
- https://github.com/astronomer/issues/issues/4167
- https://github.com/astronomer/issues/issues/4168
- https://github.com/astronomer/issues/issues/4348
- https://github.com/astronomer/issues/issues/4021
- https://github.com/astronomer/issues/issues/4398
tested in dev
> bump astro ui to 0.28.10 from 0.28.9

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
- charts/kubed/values.yaml
- charts/nats/values.yaml
- charts/nginx/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
This PR cherry-picks the commits from master to sync platform and vendor images which includes cve fixes
NA
QA should able to perform upgrade from existing installation and new installation of platform should not cause issues
**Overview of changes for QA view**
quay.io/astronomer/ap-registry:3.15.3
quay.io/astronomer/ap-cli-install:0.26.2
quay.io/astronomer/ap-elasticsearch:7.17.1
quay.io/astronomer/ap-kibana:7.17.1
quay.io/astronomer/ap-base:3.15.3
quay.io/astronomer/ap-curator:5.8.4-12
quay.io/astronomer/ap-nginx-es:1.21.6-1
quay.io/astronomer/ap-openresty:1.19.9-1
quay.io/astronomer/ap-awsesproxy:1.3-3
quay.io/astronomer/ap-fluentd:1.14.5-1 
quay.io/astronomer/ap-grafana:8.3.7
quay.io/astronomer/ap-kubed:0.13.2
quay.io/astronomer/ap-nats-server:2.7.2-2 …
> Sync release28 branch

- charts/astronomer/values.yaml
Fixes zlib vulnerability
bump ap-cli-install 0.26.2 -> 0.26.3
> bump ap-cli-install

- charts/astronomer/values.yaml
bump houston to add a missing issue for 0.28.4 release
https://github.com/astronomer/houston-api/pull/989
tested in dev
> bump houston to 0.28.14 from 0.28.13

- charts/nats/values.yaml
- charts/stan/values.yaml
* bump ap-nats-exporter 0.9.1 -> 0.9.2
* bump ap-nats-exporter 0.9.1-2 -> 0.9.2
Fixes  CVE-2022-24450 vulnerability
> update nats exporter service

- charts/astronomer/values.yaml
fix cert issues for aws in houston-api
no issue is created for issue
vishnu tested 
release-0.28
> fix cert issues with bumping houston-api to 0.28.17

- charts/nats/values.yaml
- charts/stan/values.yaml
resolves CVE-2022-24450 cve
* bump ap-nats-exporter 0.9.1 -> 0.9.2
* bump ap-nats-exporter 0.9.1-2 -> 0.9.2
cherry-pick commit id dfece8556f555535c095a17304ab2c0b160aa6dd to release-28 branch
> update nats exporter service (#1453)

- charts/astronomer/values.yaml
bump versions for houston 0.28.18 and astro-ui 0.28.12
ui:
Relates https://github.com/astronomer/issues/issues/4457
Relates https://github.com/astronomer/issues/issues/4409
Relates https://github.com/astronomer/issues/issues/4146
houston:
Related https://github.com/astronomer/issues/issues/4457
related https://github.com/astronomer/issues/issues/4488
tested by dev
release-0.28 - 0.28.4
> Bump versions for houston 0.28.18 and astro-ui 0.28.12

- Makefile
Adds the image used by global.authSidecar.repository to the list of images listed by make show-docker-images
https://github.com/astronomer/issues/issues/4502
Ran make show-docker-images and now it shows up as expected. Note that this image is currently named nginxinc/nginx-unprivileged:stable but is anticipated to be renamed shortly.
Please cherry-pick into all currently supported release branches as we may wish to use these values in automated image scanning in the future.
> add the image used by global.authSidecar.repository to make show-docker-images

- charts/astronomer/templates/registry/registry-configmap.yaml
- charts/astronomer/values.yaml
- tests/test_astronomer_registry_configmap.py
Changes:
- Added redirect section under storage in registry config map (Default value for `redirectDisabled` is set to False, same as what docker registry treats it in case it is not passed)
Currently, the astronomer registry will use redirection whenever the backend of the registry supports it. This PR is to allow users to disable registry redirection and pass all the data through the registry, this use case is useful in a couple of scenarios, one of them is when the backend storage for instance does not allow any other connection to push objects except the registry IP.
Reference: https://docs.docker.com/registry/configuration/#redirect
https://github.com/astronomer/issues/issues/4183
In order to test whether this change fixes the mentioned issue, one has to bring up an Astronomer …
> Add redirect section in registry configmap

- Makefile
- tests/enable_all_features.yaml
We have two images not showing up on make show-docker-images. This sets the options needed for ap-awsesproxy and ap-openresty to show.
https://github.com/astronomer/issues/issues/4508
Ran make show-docker-images before and after, here's the diff of the results before and after this change.
```
rob@Robs-MacBook-Pro astronomer % diff -u /tmp/old /tmp/new
--- /tmp/old	2022-04-12 08:48:55.000000000 -0400
+++ /tmp/new	2022-04-12 08:52:34.000000000 -0400
@@ -1,6 +1,7 @@
https://nginxinc/nginx-unprivileged                   nginxinc/nginx-unprivileged:stable
https://quay.io/astronomer/ap-alertmanager            quay.io/astronomer/ap-alertmanager:0.23.0
https://quay.io/astronomer/ap-astro-ui                quay.io/astronomer/ap-astro-ui:0.28.12
+https://quay.io/astronomer/ap-awsesproxy …
```
> add ap-awsesproxy and ap-openresty to make show-docker-images output

- charts/nginx/values.yaml
Update values typo introduced in pull #1160
closes https://github.com/astronomer/issues/issues/4522
Verified that  loadBalancerIP was used in the code but incorrectly identified in the values file
> fix loadBalancerIPs to loadBalancerIP

- .circleci/config.yml
- .circleci/config.yml.j2
- Makefile
- bin/validate_commander_airflow_version
We want to check the Airflow Chart version used in Commander when making changes to astronomer/astronomer (see the issue for more details).
In this PR, I added the job in CI that inspects commander's image to retrieve the airflow chart version used, and compare it with the default version set in astronomer/astronomer.
This will allow us to get notified when there's a mismatch of Airflow Chart Version between Commander and astronomer/astronomer before shipping a release.
https://github.com/astronomer/issues/issues/4369
> CI: check commander's airflow chart version matches astronomer/astronomer's

- charts/astronomer/templates/houston/api/houston-deployment.yaml
- charts/astronomer/templates/houston/worker/houston-worker-deployment.yaml
Log grpc requests logs
Related https://github.com/astronomer/issues/issues/4329
related pr: https://github.com/astronomer/houston-api/pull/1055
locally test in kind
when i set to debug level at the astro/astro level logs look like:
```
astronomer-houston-worker-8487b64497-jlnvr houston D 2022-04-20T20:15:17.178Z | index | Loading @grpc/grpc-js version 1.4.2
astronomer-houston-worker-8487b64497-jlnvr houston {"level":"DEBUG","message":"2022-04-20T20:15:17.606Z | resolving_load_balancer | dns:astronomer-commander:50051 IDLE -> IDLE","timestamp":"2022-04-20T20:15:17.610"}
astronomer-houston-worker-8487b64497-jlnvr houston {"level":"DEBUG","message":"2022-04-20T20:15:17.616Z | connectivity_state | (1) dns:astronomer-commander:50051 IDLE -> IDLE","timestamp":"2022-04-20T20:15:17.616"} …
```
> turn on GRPC logs for houston

- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/nats/values.yaml
- charts/stan/values.yaml
fixes CVE-2022-28391
* bump ap-registry 3.15.3 -> 3.15.4
* bump ap-db-bootstraper 0.26.5 -> 0.26.6
* bump  ap-base 3.15.3 -> 3.15.4
* bump ap-curator 5.8.4-12 -> 5.8.4-13
* bump nginx-es 1.21.6-1 1.21.6-2
* bump ap-awsesproxy 1.3-3 -> 1.3-4
* bump ap-nats-exporter 0.9.2 -> 0.9.2-1
* bump ap-nats-streaming 0.24.1-1 0.24.1-2
* bump ap-nats-exporter 0.9.2 -> 0.9.2-1
* bump ap-nats-server 2.7.2-2 -> 2.7.2-3
https://github.com/astronomer/issues/issues/4538
NA
should go in release-29 and release-28
> fixes CVE-2022-28391

- charts/nginx/values.yaml
* bump 0.28.3 -> 0.28.4
QA team should able to see the 404, 503, 403 error pages properly
merge to release-29 and release-28
> update nginx default backend

- charts/nginx/values.yaml
* cherry-pick release-29 branch
* fixes kubernetes/ingress-nginx#8503
NA
cherry-pick to release-29 branch
> nginx chart uses quay.io/astronomer/ap-nginx:1.2.0

- charts/astronomer/values.yaml
> bump quay.io/astronomer/ap-houston-api version to 0.29.3

- charts/fluentd/values.yaml
ap-fluentd 1.14.6-1 which solves some CVEs
https://github.com/astronomer/issues/issues/4521
This only changes the base image build version, no pinned version changes. Testing on this can be light.
This is only for 0.29
> ap-fluentd 1.14.6-1

- charts/elasticsearch/values.yaml
- charts/kibana/values.yaml
- charts/postgresql/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
security improvements and package updates
* bump ap-elasticsearch 7.17.1 -> 7.17.3
* bump ap-kibana 7.17.1 -> 7.17.3
* ap-postgresql 11.13.0 -> 11.15.0
* ap-blackbox-exporter  0.19.0-7 -> 0.20.0
NA
NA
merge to 0.29 release branch
> update vendor packages

- charts/kubed/templates/kubed-deployment.yaml
- tests/test_kubed.py
Use a configuration flag on KubeD Deployment to scope it to Astronomer release namespace. Should fix performance issues and latency before synchronizing secrets.
https://github.com/astronomer/issues/issues/4546
> fix kubed performance in large clusters: scope to release ns

- .pre-commit-config.yaml
- bin/validate_commander_airflow_version
Skip check when airflowChartVersion is an rc, which breaks us out of a hard dependency loop that and eases testing of rc airflow releases in astronomer release branches.
CI was failing on release-0.29 branch version 0.29.0-rc5 where airflowChartVersion was set to 1.5.0-rc1 because commander did not match the same version. AFAIK this match is not necessary except in airgapped situations, so it should definitely be checked on release branches, but not when we're in an airflow-chart rc phase.
N/A
I manually tested this by changing the `airflowChartVersion` in `charts/astronomer/values.yaml`. The grep syntax works with both bsd and gnu grep.
This should be merged to any branches that this check exists in.
> Skip check when airflowChartVersion is an rc

- bin/build-helm-chart.sh
[git.io is shutting down on Friday](https://github.blog/changelog/2022-04-25-git-io-deprecation/). This change removes the short URL and just uses the long URL. 
https://github.com/astronomer/issues/issues/4564
This is a very small change that is only related to CI. No testing is needed if CI passes.
This change should be merged to every branch we support.
> Use the long URL since git.io is shutting down.

- charts/astronomer/values.yaml
update astro ui with fixes for runtime ui for migrate button to be consitent
Related https://github.com/astronomer/issues/issues/4475
tested in dev
0.39
> bump astro ui to 0.29.3 from 0.29.2- runtime ui bug fixes

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
- Add houston loggingSidecar flag overrides
- Fix curl call to kill container by adding missing http post method
- Improve logging sidecar tests
- https://github.com/astronomer/issues/issues/4577
- https://github.com/astronomer/issues/issues/4576
Verified in an AWS test cluster that these changes solve the original issue.
This should only go to 0.29
> adding sidecar houston config overrides

- charts/elasticsearch/templates/data/es-data-statefulset.yaml
- charts/elasticsearch/templates/master/es-master-statefulset.yaml
- charts/elasticsearch/values.yaml
- tests/chart_tests/test_elasticsearch.py
Dropping all capabilities from elasticsearch, this will allow enterprise customer to install elasticsearch with no extra privileges 
https://github.com/astronomer/issues/issues/4226
Yet to update
> drop all capabilities from elastic service

- charts/astronomer/values.yaml
fix astro ui runtime triggerer and scheduler slider not showing up problem
https://github.com/astronomer/issues/issues/4574
tested locally and in dev
0.29
> bump astro ui to 0.29.4 from 0.29.3

- charts/astronomer/values.yaml
various runtime issues for release 0.29 
Related https://github.com/astronomer/issues/issues/4574
Related https://github.com/astronomer/issues/issues/4566
https://github.com/astronomer/issues/issues/4584
Related https://github.com/astronomer/issues/issues/4557
https://github.com/astronomer/issues/issues/4557
in dev and locally
0.29
> bump houston to 0.29.6 from 0.29.5

- charts/grafana/values.yaml
grafana 8.4.5-1
https://github.com/astronomer/issues/issues/4452
I have manually tested this version in prod.
This should be merged to anywhere that we are using grafana 8. Definitely into 0.29, but probably also 0.28.
> grafana 8.4.5-1

- charts/astronomer/values.yaml
resolves https://github.com/astronomer/issues/issues/4584
release:
0.29
> bump houston-api to hotfix default runtime images

- charts/elasticsearch/values.yaml
- charts/grafana/values.yaml
- charts/kibana/values.yaml
Updating docker image for below services. This change update the docker container to run as non-root user. This PR is to check the backward support.
- ap-grafana
- ap-kibana
- ap-elasticsearch
- PR to `master`: https://github.com/astronomer/astronomer/pull/1503
- Change PR: https://github.com/astronomer/ap-vendor/pull/294
https://github.com/astronomer/issues/issues/4510
https://github.com/astronomer/issues/issues/4511
https://github.com/astronomer/issues/issues/4512
Non-root check was tested in change PR.
> Feature/AP-4510 Updating images with non root users

- charts/astronomer/templates/commander/commander-role.yaml
- charts/astronomer/templates/commander/commander-rolebinding.yaml
- tests/chart_tests/test_astronomer_commander.py
With recent re-work on the namespace pools feature, we have removed the use of ClusterRoles and ClusterRoleBindings for `commander`.
On Openshift, commander needs permissions to manage `securitycontextconstraints` resources, set at the **CLUSTER** Level (through ClusterRole and ClusterRoleBinding).
So in this PR, I simply added a Cluster and ClusterRoleBinding if `namespacePools` is enabled, and `sccEnabled` is true, to only create Cluster-RBAC permissions in this scenario.
https://github.com/astronomer/issues/issues/4613
> Fix openshift RBAC permissions with namespace pools

- charts/astronomer/templates/houston/helm-hooks/houston-upgrade-deployments-job.yaml
We had an issue where the job houston-upgrade-deployment (triggered when Helm release is upgraded for Astronomer Platform) failed due to insufficient K8s permissions.
The `initContainer` houston-bootstrapper tried to read and create/patch a k8s secret. This k8s job was configured with `default` service account, with 0 permissions, so it failed.
To fix this, I simply made the houston-upgrade-deployment job use an already-created houston-bootstrapper SA which seems to be used for this very specific purpose.
https://github.com/astronomer/issues/issues/4618
> Use houston-bootstrapper SA in upgrade-deployment hook job

- charts/astronomer/templates/namespaces.yaml
Fix a bug where existing deployments in namespaces from namespace pools get deleted when a user redeploys a new version of the Astronomer Platform with Namespace Pools feature disabled.
bug was that Helm deletes Namespace Resources since they are not part of the release anymore. When k8s deletes namespaces, it also deletes all resources inside it. In this case, the Airflow deployments.
https://github.com/astronomer/issues/issues/4621
> Fix bug deployments get deleted when namespace pools is disabled

- charts/astronomer/values.yaml
bump Houston to 0.29.13
Related https://github.com/astronomer/issues/issues/4586
Tested google direct sign in in kind cluster
release-0.29
> bump houston to 0.29.13

- charts/astronomer/values.yaml
bump houston to 0.29.14 from 0.29.13
https://github.com/astronomer/issues/issues/4619
https://github.com/astronomer/issues/issues/4578
https://github.com/astronomer/issues/issues/4623
https://github.com/astronomer/issues/issues/4552
dev
0.29
> bump houston to 0.29.14 from 0.29.13

- charts/nginx/templates/nginx-metrics-networkpolicy.yaml
Disable all the network policies from global configuration.Fixed this in regression testing cc @pgvishnuram 
https://github.com/astronomer/issues/issues/4386
> Added astronomer-nginx-metrics-policy global flag

- charts/astronomer/values.yaml
hotfix: upgrade deployments when airflow version is null #1096
https://github.com/astronomer/issues/issues/4578
via unit tests and practical tests
0.29.0
> bump houston-api: hotfix upgrade-deployments hook

- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/templates/nginx/nginx-es-configmap.yaml
- charts/elasticsearch/templates/nginx/nginx-es-ingress-networkpolicy.yaml
- charts/external-es-proxy/templates/external-es-proxy-networkpolicy.yaml
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_external_elasticsearch.py
- tests/chart_tests/test_houston_configmap.py
- values.yaml
**Move loggingsidecar config to globals**
This change moves logging sidecar values to global , so that additional conditions can be implemented if needed for other components
updates to nginx es client to allow vector indexes to be allowed for search if logging sidecar is enabled
Allow multiple airflow components to communicate nginx es when sidecar is enabled
Yet to be updated
QA team will see below changes
**- when sidecar logging is disabled** 
* only webserver network policies are activated in elasticsearch nginx 
* only webserver network policies are activated in external es proxy 
* index will be pointing to fluent.*
**- when sidecar logging is enabled**
* all airlfow components( triggerer, worker, scheduler, webserver)  will be activated in elasticsearch nginx network policies
* …
> change logging sidecar values to global

- .circleci/config.yml
- charts/astronomer/values.yaml
bump houston to 0.29.19
Related https://github.com/astronomer/issues/issues/4622
On dev
0.29
> bump houston to 0.29.19

- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/astronomer/values.yaml
- charts/elasticsearch/templates/nginx/nginx-es-configmap.yaml
- charts/elasticsearch/templates/nginx/nginx-es-ingress-networkpolicy.yaml
- charts/external-es-proxy/templates/external-es-proxy-networkpolicy.yaml
- charts/nginx/templates/nginx-metrics-networkpolicy.yaml
- tests/chart_tests/test_elasticsearch.py
- tests/chart_tests/test_external_elasticsearch.py
- tests/chart_tests/test_houston_configmap.py
- tests/test_global_network_policy_flag.py
- values.yaml
Backport sidecar logging feature changes from master
sideLogging feature now moved to global values 
QA team can set sidecarLogging from global params instead of houston params
> Sync sidecar changes rel 029

- charts/astronomer/values.yaml
Run cronjob/astronomer-houston-update-airflow-check more frequently by default from 24hrs to hourly at the 57 min mark in every hour as suggested by @danielhoherd 
https://github.com/astronomer/issues/issues/4633
Can be cherry-picked into any releases. Not mandatory, not high priority.
> increase-cronjob-frequency for airflow check

- .circleci/config.yml
- .circleci/config.yml.j2
- .pre-commit-config.yaml
- requirements/chart-tests.txt
- requirements/functional-tests.txt
- Update requirements for release-0.28
- Bump CI image versions
- Bump pre-commit versions
N/A, just regular maintenance
If tests pass then that should be enough.
This PR is only meant for release-0.28 branch.
> Update requirements for release-0.28

- .circleci/config.yml
- charts/astronomer/values.yaml
bump houston to 0.29.21
implemented https://app.zenhub.com/workspaces/team-platform-apps-61d5f7ef8de56e0014840a75/issues/astronomer/issues/4645
On dev
0.29.0
> bump houston to 0.29.21

- .circleci/config.yml
- charts/astronomer/values.yaml
ignore race condition during create same AC/rutime version concurrently (#1114) #1550
fix ui bugs
- logs tab for ac not showing up triggerer tab
- runtime not being able to show NFS on ui
https://github.com/astronomer/issues/issues/4606
https://github.com/astronomer/issues/issues/4668
https://github.com/astronomer/issues/issues/4669
0.29.0
> ignore race condition during create same AC/rutime version concurrently (#1114)

- charts/external-es-proxy/templates/external-es-proxy-configmap.yaml
- tests/chart_tests/test_external_elasticsearch.py
Allow vector index pattern search from airflow when  external elasicsearch  service is configured.
NA
QA should able to see logs in airflow UI. 
merge to release-0.29
> allow vector index search for external elasic service

- .circleci/config.yml
- .circleci/config.yml.j2
- .circleci/slack_message_templates/security_scan_fail.json
This PR adds the scan notifications to Slack (#team-software-infra-bot) on fail. It will only report the fail scan (that found vulnerabilities).
<https://github.com/astronomer/issues/issues/4620>
This change is adding CI capability.
> Adding Slack notifications for Image Scan

- .circleci/config.yml
- .pre-commit-config.yaml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
- Bump commander and airflow chart to the release 1.6.0 version
- Fix pre-commit circle-config-yaml bug by regenerating when values.yaml files change
- Chart version to 0.29.0
N/A, part of iterating on the 0.29 release.
tested in qa
0.29
> Bump commander and airflow chart

- .circleci/config.yml
- charts/astronomer/values.yaml
Updated the CLI install version to the latest one, i.e. `0.29`
The bash script present in `astro-cli` repo, used by the install CLI pod, now supports not mentioning the patch number, in which case it will pull the latest patch of that minor version
Ex:
This will help us not to update the chart value for each patch release
> updated the CLI version in chart values

- .circleci/config.yml
- charts/astronomer/values.yaml
updating houston for 0.29 with hotfix for graphql issue and ad azure filter 
https://github.com/astronomer/houston-api/issues/1104
https://github.com/astronomer/issues/issues/4675
Related https://github.com/astronomer/issues/issues/4693
dev and customer cluster for display name filter
0.29.1
> bump houston to 0.29.26 from 0.29.24

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
Refactoring ES config params upon migrating to the new elasticsearch client in houston, required to fix an ansi-regex snyk vulnerability
Related https://github.com/astronomer/issues/issues/4624
astronomer/issues#4660
https://github.com/astronomer/houston-api/pull/1134
Tested on kind cluster
0.29.2
> CVE fix new es client

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/grafana/values.yaml
* fixes critical CVE found by trivy
* bump db-boostrapper 0.26.6 -> 0.26.7
https://github.com/astronomer/issues/issues/4663
NA
> update db bootstrapper: fix CVEs

- CODEOWNERS
Now that @cmarteepants is a product manager on Software, I'm much more in tune with what's happening on `astronomer/astronomer` for a given release. Without context, the PRs alone don't provide enough information to warrant a writer being a reviewer on every one. I'll still keep us on `.md` in case there's any internal documentation that needs review.
> Remove docs from YAML review

- charts/fluentd/templates/fluentd-configmap.yaml
- tests/chart_tests/test_fluentd.py
With the new Namespace Pool update, we updated the Fluentd Configuration to only retrieve logs from namespaces in the Pool.
The problem is that if a user then disables the NS pool feature, logs from the namespaces in the pool are not collected anymore.
In this PR, I updated FluentD's configuration to collect logs for all namespaces containing the label `platform` (automatically added to all namespaces running Airflow deployments by the Control Plane). This allows us to still capture logs from deployments inside namespace in NS pool even if disabled.
https://github.com/astronomer/issues/issues/4646
See Issue for detailed steps on how to test this update.
> FIX FluentD retrieve logs from namespaces in ns pool even if disabled

- .circleci/config.yml
- .circleci/config.yml.j2
- charts/astronomer/templates/astro-ui/astro-ui-deployment.yaml
- charts/astronomer/templates/commander/commander-deployment.yaml
- charts/astronomer/templates/extra-objects.yaml
- charts/astronomer/templates/houston/api/houston-deployment.yaml
- charts/astronomer/templates/houston/worker/houston-worker-deployment.yaml
- tests/chart_tests/test_astronomer_houston_sidecar.py
- tests/chart_tests/test_extra_objects.py
- tests/functional_tests/test_container_no_root.py
- values.yaml
- Adding capability to add any Kubernetes Object from values.
- Adding capability to add extra containers and volumes for `astro-ui` service.
- Improving CircleCI `unittest` execution time by using the larger machine to test.
[#4472 ](https://github.com/astronomer/issues/issues/4472)
- Added test case to test the extra-object input.
N/A
> Feature/4472 Adding Extra Object Capability

- charts/elasticsearch/values.yaml
- tests/chart_tests/test_elasticsearch.py
- tests/functional_tests/test_container_no_root.py
The `elasticsearch-exporter` has security-context set on it, making it run as a root group. Disabling setting security-context that will run it as default user `65534`. 
https://github.com/astronomer/issues/issues/3892
The test is already in place. Fixing it to test in case of the default value. 
N/A
> Feature-3892 Disabling Security Context from Elasticsearch Exporter

- .circleci/config.yml
- charts/astronomer/values.yaml
* set airflowchartversion to 1.6.1
* include commander image that has airflowchart 1.6.1
https://github.com/astronomer/issues/issues/4819
QA should see 1.6.1 airflowchart 
merge to release-0.29
> update airflow chart version

- .circleci/config.yml
- charts/astronomer/values.yaml
bump astro ui to 0.29.11 from 0.29.10
https://github.com/astronomer/issues/issues/4808
https://github.com/astronomer/issues/issues/4816
dev
0.29.2
> bump astro ui to 0.29.11 from 0.29.10

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
Node url check for https is causing external logging with es to fail
https://github.com/astronomer/issues/issues/4825
0.29.2
> updated node url to http

- bin/install-ci-tools
Just keeping `bin/reset-local-dev` up to date with the latest component versions.
N/A, but slack discussion is here: <https://astronomer.slack.com/archives/C02J8JT58CC/p1657653587089449>
As long as CI is passing we're good.
This should be merged into every supported branch: 0.29, 0.28, 0.25
> Bump several components in bin/reset-local-dev

- charts/astronomer/templates/_helpers.yaml
- tests/chart_tests/test_houston_api_deployment.py
Previously our chart was ignoring if someone set the deployment db connection via helm because the env var set here overwrit the connection. By blocking the env var when the user sets the deployment db connection we enable them to use a seperate db for the airflow deployments than the db used by houston.
astronomer/issues#4738
Tested this change in aws and kind
0.30.0
> allowAirflowDbToBeSeperateFromHoustonDb

- charts/astronomer/templates/houston/houston-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
Passes down the feature flags controlling whether update airflow and update runtime features are enabled.
Related PR https://github.com/astronomer/houston-api/pull/1176 in which these flags are used by houston.
Related https://github.com/astronomer/issues/issues/4831
Related https://github.com/astronomer/issues/issues/4830
unit tested
0.30.0
> Add update check confs to houston conf

- .circleci/config.yml
- charts/nginx/templates/nginx-config-role.yaml
- charts/nginx/values.yaml
* CVE fixes and upstream enhancements
**release_notes:** 
* https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.3.0
**Points to note:**
* This release removes support for Kubernetes v1.19.0
* permissions on the coordination.k8s.io/leases resource for leaderelection lock added 
Yet to create
Yet to add
> update nginx ingress controller image

- .circleci/config.yml
- charts/elasticsearch/values.yaml
Fix urllib3 CVE.
- https://github.com/astronomer/issues/issues/4427
- https://github.com/elastic/curator/issues/1622
This version of ap-curator is a rebuild of the prior version, just with a new version of urllib3. Testing isn't necessary for this.
This can be merged into all supported branches.
> ap-curator 5.8.4-17

- charts/kube-state/templates/kube-state-deployment.yaml
- charts/kube-state/values.yaml
- tests/chart_tests/test_kube_state_deployment.py
* current kube state config does not allow us to provide extra args to allow additional flags, this change allow that option
* post 2.0.x kube-state version not all metrics are exposed by default to reduce load , this allow us to define args needed for platform to work
- https://github.com/astronomer/issues/issues/4828
- https://github.com/astronomer/issues/issues/4754
Yet to update
> kubestate metrics adding extra args

- charts/astronomer/templates/_helpers.yaml
- charts/astronomer/values.yaml
- tests/chart_tests/test_registry_configmap_with_s3Enabled.py
PR change request to include new parameter `regionendpoint` under s3 registry backend configuration to support IBM COS bucket integration via S3 api.
https://github.com/astronomer/issues/issues/4853
> Included new parameter regionendpoint under s3 registry backend configuration

- .circleci/config.yml
- .circleci/trivyignore
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/fluentd/values.yaml
- charts/grafana/values.yaml
- charts/kube-state/templates/kube-state-deployment.yaml
- charts/kube-state/values.yaml
- charts/nats/values.yaml
- charts/nginx/templates/nginx-config-role.yaml
- charts/nginx/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
- tests/chart_tests/helm_template_generator.py
- tests/chart_tests/test_houston_configmap.py
- tests/chart_tests/test_kube_state_deployment.py
- values.yaml
**Update Vendor packages for CVE fixes and enhacements** 
-- | -- | --
ap-registry|3.15.4-1|3.16.1
ap-db-bootstrapper | 0.26.7 | 0.26.8
ap-cli-install | 0.26.6 | 0.26.7
ap-base | 3.16.0 | 3.16.1
ap-curator| 5.8.4-15 |  5.8.4-17 
ap-nginx-es | 1.23.0 | 1.23.1
ap-openresty | 1.21.4 |  1.21.4-1
ap-awsesproxy  | 1.3-5 |  1.3-6
ap-fluentd|1.14.6-1|1.15.0
ap-kube-state| 1.9.7 | 2.5.0
ap-nats-server| 2.8.1 | 2.8.1-1
ap-nats-exporter | 0.9.3 | 0.9.3-1
ap-nats-streaming| 0.24.5 | 0.24.5-1
ap-nginx| 1.2.1 | 1.3.0
ap-default-backend | 0.28.7 | 0.28.8
ap-blackbox-exporter | 0.21.1 | 0.21.1-1
ap-auth-sidecar | 1.23.0 |  1.23.1 
ap-vector|0.22.3|0.23.0
https://github.com/astronomer/issues/issues/4876
Do not merge this PR until this text is replaced with details about how these changes …
> Back port CVE fixes for release-0.29

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/postgresql/values.yaml
-- | -- | --
ap-postgresql |11.15.0 | 11.15.0-1
ap-commander | 0.29.5 | 0.29.6
set airflowChartVersion 1.6.1 ->  1.6.2
https://github.com/astronomer/issues/issues/4876
> update vendor and platform images

- charts/astronomer/values.yaml
- charts/prometheus/templates/prometheus-alerts-configmap.yaml
- values.yaml
Code cleanup: remove prisma related PORT and update comments, since we don't rely on prisma seperatly. It's backed into houston currently. 
release-0.30
> fix: remove prisma obsolete code

- .circleci/config.yml
- Chart.yaml
- charts/astronomer/Chart.yaml
- charts/astronomer/values.yaml
- charts/postgresql/values.yaml
- charts/prometheus/templates/prometheus-alerts-configmap.yaml
- values.yaml
This PR is to sync master branch to release 0.30 
* includes update airflowChartVersion 1.7.0-rc1 -> 1.7.0-rc2
* Code cleanup: remove prisma related PORT and update comments, since we don't rely on prisma seperatly. It's backed into houston currently.
This is a sync PR from master again re-linking issues not needed
NA
git merge master to release-0.30
> sync master to release 0.30

- .circleci/config.yml
- charts/fluentd/values.yaml
fluentd version 1.15.1 (which uses ubuntu 22.04 as base image instead of 20.04)
https://github.com/astronomer/issues/issues/4908
None so far. Normal fluentd tests should be fine: just making sure logs are shipping, no unexpected output it seen in the fluentd logs.
> fluentd 1.15.1

- .circleci/config.yml
- charts/grafana/values.yaml
* bump 8.5.5 -> 8.5.10
* release notes: https://github.com/grafana/grafana/releases/tag/v8.5.10
https://github.com/astronomer/issues/issues/4914
NA
cherry-pick into 0.28,0.29,0.30
> update grafana image

- .circleci/config.yml
- charts/astronomer/values.yaml
fix being able to push images to houston 
reverted this issue that was accidently added: https://github.com/astronomer/houston-api/pull/1193
and the fix for it that was added after 
dev
0.30
> bump houston to 0.30.12 from 0.30.11

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/nats/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/stan/values.yaml
Update all components affected by CVE-2022-37434
https://github.com/astronomer/issues/issues/4928
The only changes here are the base image, so minimal testing will suffice.
This is only meant for the release-0.30 branch. Changes could be cherry-picked to master too if needed for future releases.
> Update components for CVE-2022-37434 fix

- charts/fluentd/templates/fluentd-configmap.yaml
- tests/chart_tests/test_fluentd.py
Add customization for fluentd log stores.
[Issue 4863](https://github.com/astronomer/issues/issues/4863)
Add the following configuration in the `fluentd` section of the astronomer helm values:
```
fluentd:
extraLogStores: |
<store>
@type newrelic
@log_level info
base_uri https://log-api.newrelic.com/log/v1
license_key <LICENSE_KEY>
<buffer>
@type memory
flush_interval 5s
</buffer>
</store>
```
This is just an example of an extra store, but you could also configure this with an S3 store outside of using the built-in chart configuration to test if logs show up.
> add extraLogStores config to fluentd configmap

- .circleci/config.yml
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/nginx/values.yaml
- charts/stan/values.yaml
- values.yaml
List of images being updated in this PR 
-- | -- | --
ap-base            | 3.16.1     | 3.16.2
ap-nginx           | 1.3.0 |  1.3.0-1
ap-db-bootstrapper |  0.26.8 |  0.26.9
ap-nginx-es |  1.23.1 |  1.23.1-1
ap-auth-sidecar |  1.23.1 |  1.23.1-1
ap-openresty |  1.21.4-1 |  1.21.4-2 
ap-cli-install  |  0.26.7    | 0.26.8
https://github.com/astronomer/issues/issues/4987
cherry-pick release-0.29, 0.30
> master: update vendor image in astronomer/astronomer

- .circleci/config.yml
- charts/elasticsearch/values.yaml
* update es exporter 1.3.0 -> 1.5.0
* fix CVE-2022-21698
https://github.com/astronomer/issues/issues/5003
cherry-pick to release-0.28,0.29,0.30
> update elasticsearch exporter package

- .circleci/config.yml
- charts/elasticsearch/values.yaml
* bump ap-elasticsearch-exporter 1.3.0 -> 1.5.0
https://github.com/astronomer/issues/issues/5003
NA
cherry-pick to release-0.28
> release 0.28 security fixes for elasticsearch exporter

- charts/prometheus/templates/prometheus-config-configmap.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_prometheus_config_configmap.py
Revert https://github.com/astronomer/astronomer/pull/1578 due to the implementation breaking other things. Will revisit this later.
https://github.com/astronomer/issues/issues/4782
The changes in the original PR had a test case added that referenced the feature, so I have fixed that test and opened this PR rather than doing a direct revert, which caused conflicts. Tests are passing now. QA has already validated that unsetting these parameters fixes the problem, but it's worth validating once more.
Merge to 0.30 and 0.29
> Revert prometheus scrape inverval configuration feature additions.

- charts/fluentd/templates/fluentd-daemonset.yaml
- charts/fluentd/values.yaml
- tests/chart_tests/test_fluentd.py
Adds a configurable securityContextConstraint for fluentd
[Github issue #4989](https://github.com/astronomer/issues/issues/4989)
Added new unit tests
Tested against a real prod cluster pre-and-post and made sure, when set, the securityContext in pod and container was set appropriately. 
Please cherry-pick to main and 0.30.x
> add support for configuring securityContexts on fluentd

- charts/nats/templates/configmap.yaml
- charts/nats/values.yaml
- tests/chart_tests/test_nats_sts.py
Nats server on every restart/upgrades picks a dynamic cluster name which increases the delay in startup, this changes fixes that issue and adds a cluster name based on release name
Related Issue: https://github.com/astronomer/issues/issues/4978
QA should see result similar to below screen shot
Not yet confirmed
> add nats cluster name

- .circleci/config.yml
- charts/nginx/values.yaml
fixes all CVE's
bump 1.3.0-1 -> 1.3.1
https://github.com/astronomer/issues/issues/5010
https://github.com/astronomer/issues/issues/4938
Ingress controller should come up without any issues 
merge to release-0.28
> release 0.28 update nginx ingress controller image to 1.3.1

- .circleci/config.yml
- tests/enable_all_features.yaml
add loggingSidecar to enable_all_features so it shows on image list
https://github.com/astronomer/issues/issues/5036
make show-docker-images now includes this image
Please cherry-pick to release-0.29 release-0.30 as well as to v0.30.1 v0.29.3 and v0.29.4.
> add loggingSidecar to enable_all_features so it shows on image list

- charts/alertmanager/templates/alertmanager-configmap.yaml
- charts/alertmanager/values.yaml
- tests/chart_tests/test_alertmanager.py
Option to configure multiple receivers in addition to defaults.
This Allows customers to bring in multiple  custom receivers and allows them to define their own rules , based on their needs instead of depending on astronomer platform configured ones.
Issue Link: https://github.com/astronomer/issues/issues/3114
QA should able to define multiple  custom receivers and able to get alerts though the custome ones.
release-0.29,0.30
> add support for multiple receivers in alertmanager

- charts/elasticsearch/templates/es-psp-clusterrole.yaml
- charts/elasticsearch/templates/es-psp-rolebinding.yaml
- charts/elasticsearch/templates/es-psp.yaml
- charts/fluentd/templates/fluentd-psp-clusterrole.yaml
- charts/fluentd/templates/fluentd-psp-rolebinding.yaml
- charts/fluentd/templates/fluentd-psp.yaml
- charts/nginx/templates/nginx-psp-clusterrole.yaml
- charts/nginx/templates/nginx-psp-rolebinding.yaml
- charts/nginx/templates/nginx-psp.yaml
- charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
- charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
- charts/prometheus-node-exporter/templates/psp.yaml
- templates/psp/permissive-clusterrole.yaml
- templates/psp/permissive-clusterrolebinding.yaml
- templates/psp/permissive-psp.yaml
- templates/psp/restrictive-cluserrolebinding.yaml
- templates/psp/restrictive-clusterrole.yaml
- templates/psp/restrictive-psp.yaml
- tests/test_psp.py
Many helm templates were missing headers and that caused errors in rendering. Adding headers to those templates.
Master PR: https://github.com/astronomer/astronomer/pull/1644
https://github.com/astronomer/issues/issues/4230
The test was present and updated.
- 0.25: https://github.com/astronomer/astronomer/pull/1663
- 0.29: https://github.com/astronomer/astronomer/pull/1664
- 0.30: Already updated
> Adding header for Helm templates - 0.28

- charts/elasticsearch/templates/es-psp-clusterrole.yaml
- charts/elasticsearch/templates/es-psp-rolebinding.yaml
- charts/elasticsearch/templates/es-psp.yaml
- charts/fluentd/templates/fluentd-psp-clusterrole.yaml
- charts/fluentd/templates/fluentd-psp-rolebinding.yaml
- charts/fluentd/templates/fluentd-psp.yaml
- charts/nginx/templates/nginx-psp-clusterrole.yaml
- charts/nginx/templates/nginx-psp-rolebinding.yaml
- charts/nginx/templates/nginx-psp.yaml
- charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
- charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
- charts/prometheus-node-exporter/templates/psp.yaml
- templates/psp/permissive-clusterrole.yaml
- templates/psp/permissive-clusterrolebinding.yaml
- templates/psp/permissive-psp.yaml
- templates/psp/restrictive-cluserrolebinding.yaml
- templates/psp/restrictive-clusterrole.yaml
- templates/psp/restrictive-psp.yaml
- tests/chart_tests/test_psp.py
Many helm templates were missing headers and that caused errors in rendering. Adding headers to those templates.
Master PR: https://github.com/astronomer/astronomer/pull/1644
https://github.com/astronomer/issues/issues/4230
The test was present and updated.
- 0.25: https://github.com/astronomer/astronomer/pull/1663
- 0.28: https://github.com/astronomer/astronomer/pull/1665
- 0.30: Already updated
> Adding header for Helm templates - 0.29

- charts/elasticsearch/templates/es-psp-clusterrole.yaml
- charts/elasticsearch/templates/es-psp-rolebinding.yaml
- charts/elasticsearch/templates/es-psp.yaml
- charts/fluentd/templates/fluentd-psp-clusterrole.yaml
- charts/fluentd/templates/fluentd-psp-rolebinding.yaml
- charts/fluentd/templates/fluentd-psp.yaml
- charts/nginx/templates/nginx-psp-clusterrole.yaml
- charts/nginx/templates/nginx-psp-rolebinding.yaml
- charts/nginx/templates/nginx-psp.yaml
- charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
- charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
- charts/prometheus-node-exporter/templates/psp.yaml
- templates/psp/permissive-clusterrole.yaml
- templates/psp/permissive-clusterrolebinding.yaml
- templates/psp/permissive-psp.yaml
- templates/psp/restrictive-cluserrolebinding.yaml
- templates/psp/restrictive-clusterrole.yaml
- templates/psp/restrictive-psp.yaml
- tests/test_psp.py
Many helm templates were missing headers and that caused errors in rendering. Adding headers to those templates.
Master PR: https://github.com/astronomer/astronomer/pull/1644
https://github.com/astronomer/issues/issues/4230
The test was present and updated.
- 0.28: https://github.com/astronomer/astronomer/pull/1665
- 0.29: https://github.com/astronomer/astronomer/pull/1664
- 0.30: Already updated
> Adding header for Helm templates - 0.25

- .circleci/config.yml
- charts/elasticsearch/values.yaml
- charts/kibana/values.yaml
updates elastic package to 7.17.6
ES  release notes https://www.elastic.co/guide/en/elasticsearch/reference/7.17/release-notes-7.17.6.html
KB  release notes https://www.elastic.co/guide/en/kibana/7.17/release-notes-7.17.6.html
https://github.com/astronomer/issues/issues/5061
QA should able to make elasticsearch and kibana deployments without any issues
merge to release-0.25,0.28,0.29,0.30
> update elastic package 7.17.5 -> 7.17.6

- .circleci/config.yml
- charts/nats/values.yaml
- charts/stan/values.yaml
* bump 0.9.3-2 -> 0.10.0
* Fixes
CVE-2022-21698
CVE-2022-40674 
https://github.com/astronomer/issues/issues/5020
NA
Yet to verify which we have not updated the nats images
> update nats exporter 0.9.3-2 -> 0.10.0

- charts/prometheus/templates/prometheus-statefulset.yaml
- charts/prometheus/values.yaml
- tests/chart_tests/test_prometheus_statefulset.py
Make livenessProbe and readinessProbe configurable
https://github.com/astronomer/issues/issues/5050
Unit-tested + manual diff of helm template pre and post, no organic testing.
n.b. 3 is the default kubernetes failureThreshold and is thus a no-op from the status-quo
``` 
spec:
nodeSelector:
{}
@@ -7662,12 +7662,14 @@
port: 9090
initialDelaySeconds: 10
periodSeconds: 5
+            failureThreshold: 3
readinessProbe:
httpGet:
path: /-/ready
port: 9090
initialDelaySeconds: 10
periodSeconds: 5
+            failureThreshold: 3
```
Please cherry-pick to 0.29.x and 0.30.x
> make prometheus livenessProbe and readinessProbe configurable

- charts/astronomer/templates/houston/houston-configmap.yaml
- charts/prometheus/templates/prometheus-alerts-configmap.yaml
- charts/prometheus/templates/prometheus-config-configmap.yaml
- tests/chart_tests/test_houston_configmap.py
- tests/chart_tests/test_prometheus_config_configmap.py
- values.yaml
- makes namespaceFreeFormEntry a global helm value
- when enabled it fixes the prometheus regex for release name
- fixes some prometheus alerts that were missing triggerer
Related https://github.com/astronomer/issues/issues/5039
tested in my aws
0.31.0
> fixPrometheusForNamespaceFreeForm

- .circleci/config.yml
- .circleci/trivyignore
- charts/astronomer/values.yaml
- charts/elasticsearch/values.yaml
- charts/external-es-proxy/values.yaml
- charts/grafana/values.yaml
- charts/kube-state/values.yaml
- charts/nats/values.yaml
- charts/pgbouncer/values.yaml
- charts/prometheus-blackbox-exporter/values.yaml
- charts/prometheus-node-exporter/values.yaml
- charts/prometheus/values.yaml
- charts/stan/values.yaml
- values.yaml
--    | --  | --
ap-base | 3.16.2  | 3.16.2-1
ap-db-bootstrapper | 0.26.9 |  0.26.11
ap-nats-server | 2.8.1-2 | 2.8.1-3
ap-nats-exporter | 0.10.0 | 0.10.0-1
ap-pgbouncer-krb | 1.17.0-1 | 1.17.0-3
ap-blackbox-exporter | 0.21.1-2 | 0.22.0 
ap-node-exporter  | 1.3.1 | 1.4.0
ap-prometheus | 2.37.0 | 2.37.1
ap-nats-streaming | 0.24.5-2 | 0.24.5-3
ap-vector | 0.23.0 | 0.23.3-1
ap-kube-state | 2.5.0 | 2.6.0
ap-registry |  3.16.2 | 3.16.2-1
ap-awsesproxy | 1.3-7 | 1.3-8
related to https://github.com/astronomer/issues/issues/5065
QA should see all updated services should function normally without causing any new issues 
> update vendor packages for astronomer/astronomer
